// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package coolify

import (
	"context"
	"reflect"

	"errors"
	"github.com/mheers/pulumi-provider-coolify/sdk/go/coolify/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Attaches an additional standalone Docker destination to an application. Do not use this for the primary destination (<span pulumi-lang-nodejs="`destinationUuid`" pulumi-lang-dotnet="`DestinationUuid`" pulumi-lang-go="`destinationUuid`" pulumi-lang-python="`destination_uuid`" pulumi-lang-yaml="`destinationUuid`" pulumi-lang-java="`destinationUuid`" pulumi-lang-hcl="`destination_uuid`">`destinationUuid`</span> on the application resource). Requires Coolify >= v4.2.0.
//
// ## Example Usage
//
// <!--Start PulumiCodeChooser -->
// ```go
// package main
//
// import (
//
//	"github.com/mheers/pulumi-provider-coolify/sdk/go/coolify"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := coolify.NewApplicationDestination(ctx, "extra", &coolify.ApplicationDestinationArgs{
//				ApplicationUuid: pulumi.Any(example.Uuid),
//				DestinationUuid: pulumi.Any(extraCoolifyDestination.Uuid),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
// <!--End PulumiCodeChooser -->
//
// ## Import
//
// The `pulumi import` command can be used, for example:
//
// ```sh
// $ pulumi import coolify:index/applicationDestination:ApplicationDestination extra <application-uuid>:<destination-uuid>
// ```
type ApplicationDestination struct {
	pulumi.CustomResourceState

	ApplicationUuid pulumi.StringOutput `pulumi:"applicationUuid"`
	DestinationUuid pulumi.StringOutput `pulumi:"destinationUuid"`
}

// NewApplicationDestination registers a new resource with the given unique name, arguments, and options.
func NewApplicationDestination(ctx *pulumi.Context,
	name string, args *ApplicationDestinationArgs, opts ...pulumi.ResourceOption) (*ApplicationDestination, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ApplicationUuid == nil {
		return nil, errors.New("invalid value for required argument 'ApplicationUuid'")
	}
	if args.DestinationUuid == nil {
		return nil, errors.New("invalid value for required argument 'DestinationUuid'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ApplicationDestination
	err := ctx.RegisterResource("coolify:index/applicationDestination:ApplicationDestination", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetApplicationDestination gets an existing ApplicationDestination resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetApplicationDestination(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ApplicationDestinationState, opts ...pulumi.ResourceOption) (*ApplicationDestination, error) {
	var resource ApplicationDestination
	err := ctx.ReadResource("coolify:index/applicationDestination:ApplicationDestination", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ApplicationDestination resources.
type applicationDestinationState struct {
	ApplicationUuid *string `pulumi:"applicationUuid"`
	DestinationUuid *string `pulumi:"destinationUuid"`
}

type ApplicationDestinationState struct {
	ApplicationUuid pulumi.StringPtrInput
	DestinationUuid pulumi.StringPtrInput
}

func (ApplicationDestinationState) ElementType() reflect.Type {
	return reflect.TypeOf((*applicationDestinationState)(nil)).Elem()
}

type applicationDestinationArgs struct {
	ApplicationUuid string `pulumi:"applicationUuid"`
	DestinationUuid string `pulumi:"destinationUuid"`
}

// The set of arguments for constructing a ApplicationDestination resource.
type ApplicationDestinationArgs struct {
	ApplicationUuid pulumi.StringInput
	DestinationUuid pulumi.StringInput
}

func (ApplicationDestinationArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*applicationDestinationArgs)(nil)).Elem()
}

type ApplicationDestinationInput interface {
	pulumi.Input

	ToApplicationDestinationOutput() ApplicationDestinationOutput
	ToApplicationDestinationOutputWithContext(ctx context.Context) ApplicationDestinationOutput
}

func (*ApplicationDestination) ElementType() reflect.Type {
	return reflect.TypeOf((**ApplicationDestination)(nil)).Elem()
}

func (i *ApplicationDestination) ToApplicationDestinationOutput() ApplicationDestinationOutput {
	return i.ToApplicationDestinationOutputWithContext(context.Background())
}

func (i *ApplicationDestination) ToApplicationDestinationOutputWithContext(ctx context.Context) ApplicationDestinationOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ApplicationDestinationOutput)
}

// ApplicationDestinationArrayInput is an input type that accepts ApplicationDestinationArray and ApplicationDestinationArrayOutput values.
// You can construct a concrete instance of `ApplicationDestinationArrayInput` via:
//
//	ApplicationDestinationArray{ ApplicationDestinationArgs{...} }
type ApplicationDestinationArrayInput interface {
	pulumi.Input

	ToApplicationDestinationArrayOutput() ApplicationDestinationArrayOutput
	ToApplicationDestinationArrayOutputWithContext(context.Context) ApplicationDestinationArrayOutput
}

type ApplicationDestinationArray []ApplicationDestinationInput

func (ApplicationDestinationArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ApplicationDestination)(nil)).Elem()
}

func (i ApplicationDestinationArray) ToApplicationDestinationArrayOutput() ApplicationDestinationArrayOutput {
	return i.ToApplicationDestinationArrayOutputWithContext(context.Background())
}

func (i ApplicationDestinationArray) ToApplicationDestinationArrayOutputWithContext(ctx context.Context) ApplicationDestinationArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ApplicationDestinationArrayOutput)
}

// ApplicationDestinationMapInput is an input type that accepts ApplicationDestinationMap and ApplicationDestinationMapOutput values.
// You can construct a concrete instance of `ApplicationDestinationMapInput` via:
//
//	ApplicationDestinationMap{ "key": ApplicationDestinationArgs{...} }
type ApplicationDestinationMapInput interface {
	pulumi.Input

	ToApplicationDestinationMapOutput() ApplicationDestinationMapOutput
	ToApplicationDestinationMapOutputWithContext(context.Context) ApplicationDestinationMapOutput
}

type ApplicationDestinationMap map[string]ApplicationDestinationInput

func (ApplicationDestinationMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ApplicationDestination)(nil)).Elem()
}

func (i ApplicationDestinationMap) ToApplicationDestinationMapOutput() ApplicationDestinationMapOutput {
	return i.ToApplicationDestinationMapOutputWithContext(context.Background())
}

func (i ApplicationDestinationMap) ToApplicationDestinationMapOutputWithContext(ctx context.Context) ApplicationDestinationMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ApplicationDestinationMapOutput)
}

type ApplicationDestinationOutput struct{ *pulumi.OutputState }

func (ApplicationDestinationOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ApplicationDestination)(nil)).Elem()
}

func (o ApplicationDestinationOutput) ToApplicationDestinationOutput() ApplicationDestinationOutput {
	return o
}

func (o ApplicationDestinationOutput) ToApplicationDestinationOutputWithContext(ctx context.Context) ApplicationDestinationOutput {
	return o
}

func (o ApplicationDestinationOutput) ApplicationUuid() pulumi.StringOutput {
	return o.ApplyT(func(v *ApplicationDestination) pulumi.StringOutput { return v.ApplicationUuid }).(pulumi.StringOutput)
}

func (o ApplicationDestinationOutput) DestinationUuid() pulumi.StringOutput {
	return o.ApplyT(func(v *ApplicationDestination) pulumi.StringOutput { return v.DestinationUuid }).(pulumi.StringOutput)
}

type ApplicationDestinationArrayOutput struct{ *pulumi.OutputState }

func (ApplicationDestinationArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ApplicationDestination)(nil)).Elem()
}

func (o ApplicationDestinationArrayOutput) ToApplicationDestinationArrayOutput() ApplicationDestinationArrayOutput {
	return o
}

func (o ApplicationDestinationArrayOutput) ToApplicationDestinationArrayOutputWithContext(ctx context.Context) ApplicationDestinationArrayOutput {
	return o
}

func (o ApplicationDestinationArrayOutput) Index(i pulumi.IntInput) ApplicationDestinationOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ApplicationDestination {
		return vs[0].([]*ApplicationDestination)[vs[1].(int)]
	}).(ApplicationDestinationOutput)
}

type ApplicationDestinationMapOutput struct{ *pulumi.OutputState }

func (ApplicationDestinationMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ApplicationDestination)(nil)).Elem()
}

func (o ApplicationDestinationMapOutput) ToApplicationDestinationMapOutput() ApplicationDestinationMapOutput {
	return o
}

func (o ApplicationDestinationMapOutput) ToApplicationDestinationMapOutputWithContext(ctx context.Context) ApplicationDestinationMapOutput {
	return o
}

func (o ApplicationDestinationMapOutput) MapIndex(k pulumi.StringInput) ApplicationDestinationOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ApplicationDestination {
		return vs[0].(map[string]*ApplicationDestination)[vs[1].(string)]
	}).(ApplicationDestinationOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ApplicationDestinationInput)(nil)).Elem(), &ApplicationDestination{})
	pulumi.RegisterInputType(reflect.TypeOf((*ApplicationDestinationArrayInput)(nil)).Elem(), ApplicationDestinationArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ApplicationDestinationMapInput)(nil)).Elem(), ApplicationDestinationMap{})
	pulumi.RegisterOutputType(ApplicationDestinationOutput{})
	pulumi.RegisterOutputType(ApplicationDestinationArrayOutput{})
	pulumi.RegisterOutputType(ApplicationDestinationMapOutput{})
}
