// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package coolify

import (
	"context"
	"reflect"

	"errors"
	"github.com/mheers/pulumi-provider-coolify/sdk/go/coolify/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Manages a Dragonfly database resource on Coolify.
//
// ## Example Usage
//
// <!--Start PulumiCodeChooser -->
// ```go
// package main
//
// import (
//
//	"github.com/mheers/pulumi-provider-coolify/sdk/go/coolify"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := coolify.NewDatabaseDragonfly(ctx, "example", &coolify.DatabaseDragonflyArgs{
//				Name:        pulumi.String("my-dragonfly"),
//				ProjectUuid: pulumi.Any(exampleCoolifyProject.Uuid),
//				ServerUuid:  pulumi.Any(exampleCoolifyServer.Uuid),
//				Image:       pulumi.String("docker.dragonflydb.io/dragonflydb/dragonfly:v1.25"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
// <!--End PulumiCodeChooser -->
//
// ## Import
//
// The `pulumi import` command can be used, for example:
//
// Simple import (project_uuid, server_uuid,<span pulumi-lang-nodejs=" environmentName " pulumi-lang-dotnet=" EnvironmentName " pulumi-lang-go=" environmentName " pulumi-lang-python=" environment_name " pulumi-lang-yaml=" environmentName " pulumi-lang-java=" environmentName " pulumi-lang-hcl=" environment_name "> environmentName </span>must be added to config manually):
//
// ```sh
// $ pulumi import coolify:index/databaseDragonfly:DatabaseDragonfly example <database-uuid>
// ```
//
// Compound import (recommended, populates all required fields):
//
// ```sh
// $ pulumi import coolify:index/databaseDragonfly:DatabaseDragonfly example <project-uuid>:<server-uuid>:<environment-name>:<database-uuid>
// ```
type DatabaseDragonfly struct {
	pulumi.CustomResourceState

	// Custom Docker run options passed to the container.
	CustomDockerRunOptions pulumi.StringPtrOutput `pulumi:"customDockerRunOptions"`
	// A description of the database.
	Description pulumi.StringOutput `pulumi:"description"`
	// UUID of the Coolify destination (Docker network) on the server. Create-only; changing forces a new resource. Coolify requires this when the server has multiple destinations and ignores a mismatched value when only one destination exists. Supported on database create for all Coolify versions this provider supports (v4.1.0+). When omitted on a multi-destination server, the client may auto-resolve after Coolify returns the multi-destination error (prefers network <span pulumi-lang-nodejs="`coolify`" pulumi-lang-dotnet="`Coolify`" pulumi-lang-go="`coolify`" pulumi-lang-python="`coolify`" pulumi-lang-yaml="`coolify`" pulumi-lang-java="`coolify`" pulumi-lang-hcl="`coolify`">`coolify`</span>). Manage destinations with <span pulumi-lang-nodejs="`coolify.Destination`" pulumi-lang-dotnet="`coolify.Destination`" pulumi-lang-go="`Destination`" pulumi-lang-python="`Destination`" pulumi-lang-yaml="`coolify.Destination`" pulumi-lang-java="`coolify.Destination`" pulumi-lang-hcl="`coolify_destination`">`coolify.Destination`</span>. Import cannot recover this value (GET does not return destination UUID); re-adding it after import forces replacement unless you set it in state or omit the attribute.
	DestinationUuid pulumi.StringPtrOutput `pulumi:"destinationUuid"`
	// The Dragonfly password. If omitted, Coolify auto-generates a value readable from state after creation.
	DragonflyPassword pulumi.StringOutput `pulumi:"dragonflyPassword"`
	// When <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>, enables SSL/TLS encryption for database connections. Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
	EnableSsl pulumi.BoolOutput `pulumi:"enableSsl"`
	// The name of the environment within the project to deploy into. Coolify auto-creates a <span pulumi-lang-nodejs="`production`" pulumi-lang-dotnet="`Production`" pulumi-lang-go="`production`" pulumi-lang-python="`production`" pulumi-lang-yaml="`production`" pulumi-lang-java="`production`" pulumi-lang-hcl="`production`">`production`</span> environment per project; for other environments, create one first with <span pulumi-lang-nodejs="`coolify.Environment`" pulumi-lang-dotnet="`coolify.Environment`" pulumi-lang-go="`Environment`" pulumi-lang-python="`Environment`" pulumi-lang-yaml="`coolify.Environment`" pulumi-lang-java="`coolify.Environment`" pulumi-lang-hcl="`coolify_environment`">`coolify.Environment`</span>. Defaults to <span pulumi-lang-nodejs="`production`" pulumi-lang-dotnet="`Production`" pulumi-lang-go="`production`" pulumi-lang-python="`production`" pulumi-lang-yaml="`production`" pulumi-lang-java="`production`" pulumi-lang-hcl="`production`">`production`</span>. Changing this forces a new resource.
	EnvironmentName pulumi.StringOutput `pulumi:"environmentName"`
	// When <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>, enables the Docker health check probe for this database container. Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
	HealthCheckEnabled pulumi.BoolOutput `pulumi:"healthCheckEnabled"`
	// Health check interval in seconds. Minimum <span pulumi-lang-nodejs="`1`" pulumi-lang-dotnet="`1`" pulumi-lang-go="`1`" pulumi-lang-python="`1`" pulumi-lang-yaml="`1`" pulumi-lang-java="`1`" pulumi-lang-hcl="`1`">`1`</span>. Defaults to <span pulumi-lang-nodejs="`15`" pulumi-lang-dotnet="`15`" pulumi-lang-go="`15`" pulumi-lang-python="`15`" pulumi-lang-yaml="`15`" pulumi-lang-java="`15`" pulumi-lang-hcl="`15`">`15`</span>.
	HealthCheckInterval pulumi.IntOutput `pulumi:"healthCheckInterval"`
	// Number of consecutive health check failures before the container is considered unhealthy. Minimum <span pulumi-lang-nodejs="`1`" pulumi-lang-dotnet="`1`" pulumi-lang-go="`1`" pulumi-lang-python="`1`" pulumi-lang-yaml="`1`" pulumi-lang-java="`1`" pulumi-lang-hcl="`1`">`1`</span>. Defaults to <span pulumi-lang-nodejs="`5`" pulumi-lang-dotnet="`5`" pulumi-lang-go="`5`" pulumi-lang-python="`5`" pulumi-lang-yaml="`5`" pulumi-lang-java="`5`" pulumi-lang-hcl="`5`">`5`</span>.
	HealthCheckRetries pulumi.IntOutput `pulumi:"healthCheckRetries"`
	// Grace period in seconds before health checks start counting failures after container start. Minimum <span pulumi-lang-nodejs="`0`" pulumi-lang-dotnet="`0`" pulumi-lang-go="`0`" pulumi-lang-python="`0`" pulumi-lang-yaml="`0`" pulumi-lang-java="`0`" pulumi-lang-hcl="`0`">`0`</span>. Defaults to <span pulumi-lang-nodejs="`5`" pulumi-lang-dotnet="`5`" pulumi-lang-go="`5`" pulumi-lang-python="`5`" pulumi-lang-yaml="`5`" pulumi-lang-java="`5`" pulumi-lang-hcl="`5`">`5`</span>.
	HealthCheckStartPeriod pulumi.IntOutput `pulumi:"healthCheckStartPeriod"`
	// Health check timeout in seconds. Minimum <span pulumi-lang-nodejs="`1`" pulumi-lang-dotnet="`1`" pulumi-lang-go="`1`" pulumi-lang-python="`1`" pulumi-lang-yaml="`1`" pulumi-lang-java="`1`" pulumi-lang-hcl="`1`">`1`</span>. Defaults to <span pulumi-lang-nodejs="`5`" pulumi-lang-dotnet="`5`" pulumi-lang-go="`5`" pulumi-lang-python="`5`" pulumi-lang-yaml="`5`" pulumi-lang-java="`5`" pulumi-lang-hcl="`5`">`5`</span>.
	HealthCheckTimeout pulumi.IntOutput `pulumi:"healthCheckTimeout"`
	// The Docker image to use.
	Image pulumi.StringOutput `pulumi:"image"`
	// Whether to immediately deploy the database after creation. When <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>, Coolify starts the database container right away. When <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span> (default), the database is created but not started.
	InstantDeploy pulumi.BoolOutput `pulumi:"instantDeploy"`
	// Internal connection URL for the database, accessible from other containers on the same server. Contains credentials; requires an API token with sensitive-data read permission.
	InternalDbUrl pulumi.StringOutput `pulumi:"internalDbUrl"`
	// When <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>, includes timestamps in container log output. Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
	IsIncludeTimestamps pulumi.BoolOutput `pulumi:"isIncludeTimestamps"`
	// When <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>, sends container logs to the configured log drain. Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
	IsLogDrainEnabled pulumi.BoolOutput `pulumi:"isLogDrainEnabled"`
	// When <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>, exposes the database on a port accessible via the server's IP address. When <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span> (default), the database is only reachable from other containers on the same Docker network. Set <span pulumi-lang-nodejs="`publicPort`" pulumi-lang-dotnet="`PublicPort`" pulumi-lang-go="`publicPort`" pulumi-lang-python="`public_port`" pulumi-lang-yaml="`publicPort`" pulumi-lang-java="`publicPort`" pulumi-lang-hcl="`public_port`">`publicPort`</span> to choose a specific port.
	IsPublic pulumi.BoolOutput `pulumi:"isPublic"`
	// CPU shares (relative weight).
	LimitsCpuShares pulumi.IntOutput `pulumi:"limitsCpuShares"`
	// CPU limit (e.g., `0.5`, <span pulumi-lang-nodejs="`2`" pulumi-lang-dotnet="`2`" pulumi-lang-go="`2`" pulumi-lang-python="`2`" pulumi-lang-yaml="`2`" pulumi-lang-java="`2`" pulumi-lang-hcl="`2`">`2`</span>).
	LimitsCpus pulumi.StringOutput `pulumi:"limitsCpus"`
	// CPU set restriction (e.g., `0-3`, `0,2`).
	LimitsCpuset pulumi.StringOutput `pulumi:"limitsCpuset"`
	// Memory limit (e.g., <span pulumi-lang-nodejs="`512m`" pulumi-lang-dotnet="`512m`" pulumi-lang-go="`512m`" pulumi-lang-python="`512m`" pulumi-lang-yaml="`512m`" pulumi-lang-java="`512m`" pulumi-lang-hcl="`512m`">`512m`</span>, <span pulumi-lang-nodejs="`2g`" pulumi-lang-dotnet="`2g`" pulumi-lang-go="`2g`" pulumi-lang-python="`2g`" pulumi-lang-yaml="`2g`" pulumi-lang-java="`2g`" pulumi-lang-hcl="`2g`">`2g`</span>).
	LimitsMemory pulumi.StringOutput `pulumi:"limitsMemory"`
	// Memory reservation (e.g., <span pulumi-lang-nodejs="`256m`" pulumi-lang-dotnet="`256m`" pulumi-lang-go="`256m`" pulumi-lang-python="`256m`" pulumi-lang-yaml="`256m`" pulumi-lang-java="`256m`" pulumi-lang-hcl="`256m`">`256m`</span>).
	LimitsMemoryReservation pulumi.StringOutput `pulumi:"limitsMemoryReservation"`
	// Memory swap limit (e.g., <span pulumi-lang-nodejs="`1g`" pulumi-lang-dotnet="`1g`" pulumi-lang-go="`1g`" pulumi-lang-python="`1g`" pulumi-lang-yaml="`1g`" pulumi-lang-java="`1g`" pulumi-lang-hcl="`1g`">`1g`</span>).
	LimitsMemorySwap pulumi.StringOutput `pulumi:"limitsMemorySwap"`
	// Memory swappiness (0-100).
	LimitsMemorySwappiness pulumi.IntOutput `pulumi:"limitsMemorySwappiness"`
	// The name of the database resource. Also used as the Docker container name and internal DNS hostname for inter-container communication.
	Name pulumi.StringOutput `pulumi:"name"`
	// Port mappings in `host:container` format, comma-separated (e.g., `8080:5432`).
	PortsMappings pulumi.StringPtrOutput `pulumi:"portsMappings"`
	// The UUID of the project this database belongs to. Changing this forces a new resource.
	ProjectUuid pulumi.StringOutput `pulumi:"projectUuid"`
	// The host port to expose the database on when <span pulumi-lang-nodejs="`isPublic`" pulumi-lang-dotnet="`IsPublic`" pulumi-lang-go="`isPublic`" pulumi-lang-python="`is_public`" pulumi-lang-yaml="`isPublic`" pulumi-lang-java="`isPublic`" pulumi-lang-hcl="`is_public`">`isPublic`</span> is <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>. If omitted, Coolify auto-assigns an available port. Ignored when <span pulumi-lang-nodejs="`isPublic`" pulumi-lang-dotnet="`IsPublic`" pulumi-lang-go="`isPublic`" pulumi-lang-python="`is_public`" pulumi-lang-yaml="`isPublic`" pulumi-lang-java="`isPublic`" pulumi-lang-hcl="`is_public`">`isPublic`</span> is <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
	PublicPort pulumi.IntOutput `pulumi:"publicPort"`
	// Timeout in seconds for public port allocation.
	PublicPortTimeout pulumi.IntPtrOutput `pulumi:"publicPortTimeout"`
	// The UUID of the server to deploy the database on. Changing this forces a new resource.
	ServerUuid pulumi.StringOutput `pulumi:"serverUuid"`
	// The current status of the database (e.g., <span pulumi-lang-nodejs="`running`" pulumi-lang-dotnet="`Running`" pulumi-lang-go="`running`" pulumi-lang-python="`running`" pulumi-lang-yaml="`running`" pulumi-lang-java="`running`" pulumi-lang-hcl="`running`">`running`</span>, <span pulumi-lang-nodejs="`exited`" pulumi-lang-dotnet="`Exited`" pulumi-lang-go="`exited`" pulumi-lang-python="`exited`" pulumi-lang-yaml="`exited`" pulumi-lang-java="`exited`" pulumi-lang-hcl="`exited`">`exited`</span>).
	Status   pulumi.StringOutput                `pulumi:"status"`
	Timeouts DatabaseDragonflyTimeoutsPtrOutput `pulumi:"timeouts"`
	// The UUID of the database.
	Uuid pulumi.StringOutput `pulumi:"uuid"`
}

// NewDatabaseDragonfly registers a new resource with the given unique name, arguments, and options.
func NewDatabaseDragonfly(ctx *pulumi.Context,
	name string, args *DatabaseDragonflyArgs, opts ...pulumi.ResourceOption) (*DatabaseDragonfly, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ProjectUuid == nil {
		return nil, errors.New("invalid value for required argument 'ProjectUuid'")
	}
	if args.ServerUuid == nil {
		return nil, errors.New("invalid value for required argument 'ServerUuid'")
	}
	if args.DragonflyPassword != nil {
		args.DragonflyPassword = pulumi.ToSecret(args.DragonflyPassword).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"dragonflyPassword",
		"internalDbUrl",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource DatabaseDragonfly
	err := ctx.RegisterResource("coolify:index/databaseDragonfly:DatabaseDragonfly", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDatabaseDragonfly gets an existing DatabaseDragonfly resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDatabaseDragonfly(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DatabaseDragonflyState, opts ...pulumi.ResourceOption) (*DatabaseDragonfly, error) {
	var resource DatabaseDragonfly
	err := ctx.ReadResource("coolify:index/databaseDragonfly:DatabaseDragonfly", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering DatabaseDragonfly resources.
type databaseDragonflyState struct {
	// Custom Docker run options passed to the container.
	CustomDockerRunOptions *string `pulumi:"customDockerRunOptions"`
	// A description of the database.
	Description *string `pulumi:"description"`
	// UUID of the Coolify destination (Docker network) on the server. Create-only; changing forces a new resource. Coolify requires this when the server has multiple destinations and ignores a mismatched value when only one destination exists. Supported on database create for all Coolify versions this provider supports (v4.1.0+). When omitted on a multi-destination server, the client may auto-resolve after Coolify returns the multi-destination error (prefers network <span pulumi-lang-nodejs="`coolify`" pulumi-lang-dotnet="`Coolify`" pulumi-lang-go="`coolify`" pulumi-lang-python="`coolify`" pulumi-lang-yaml="`coolify`" pulumi-lang-java="`coolify`" pulumi-lang-hcl="`coolify`">`coolify`</span>). Manage destinations with <span pulumi-lang-nodejs="`coolify.Destination`" pulumi-lang-dotnet="`coolify.Destination`" pulumi-lang-go="`Destination`" pulumi-lang-python="`Destination`" pulumi-lang-yaml="`coolify.Destination`" pulumi-lang-java="`coolify.Destination`" pulumi-lang-hcl="`coolify_destination`">`coolify.Destination`</span>. Import cannot recover this value (GET does not return destination UUID); re-adding it after import forces replacement unless you set it in state or omit the attribute.
	DestinationUuid *string `pulumi:"destinationUuid"`
	// The Dragonfly password. If omitted, Coolify auto-generates a value readable from state after creation.
	DragonflyPassword *string `pulumi:"dragonflyPassword"`
	// When <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>, enables SSL/TLS encryption for database connections. Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
	EnableSsl *bool `pulumi:"enableSsl"`
	// The name of the environment within the project to deploy into. Coolify auto-creates a <span pulumi-lang-nodejs="`production`" pulumi-lang-dotnet="`Production`" pulumi-lang-go="`production`" pulumi-lang-python="`production`" pulumi-lang-yaml="`production`" pulumi-lang-java="`production`" pulumi-lang-hcl="`production`">`production`</span> environment per project; for other environments, create one first with <span pulumi-lang-nodejs="`coolify.Environment`" pulumi-lang-dotnet="`coolify.Environment`" pulumi-lang-go="`Environment`" pulumi-lang-python="`Environment`" pulumi-lang-yaml="`coolify.Environment`" pulumi-lang-java="`coolify.Environment`" pulumi-lang-hcl="`coolify_environment`">`coolify.Environment`</span>. Defaults to <span pulumi-lang-nodejs="`production`" pulumi-lang-dotnet="`Production`" pulumi-lang-go="`production`" pulumi-lang-python="`production`" pulumi-lang-yaml="`production`" pulumi-lang-java="`production`" pulumi-lang-hcl="`production`">`production`</span>. Changing this forces a new resource.
	EnvironmentName *string `pulumi:"environmentName"`
	// When <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>, enables the Docker health check probe for this database container. Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
	HealthCheckEnabled *bool `pulumi:"healthCheckEnabled"`
	// Health check interval in seconds. Minimum <span pulumi-lang-nodejs="`1`" pulumi-lang-dotnet="`1`" pulumi-lang-go="`1`" pulumi-lang-python="`1`" pulumi-lang-yaml="`1`" pulumi-lang-java="`1`" pulumi-lang-hcl="`1`">`1`</span>. Defaults to <span pulumi-lang-nodejs="`15`" pulumi-lang-dotnet="`15`" pulumi-lang-go="`15`" pulumi-lang-python="`15`" pulumi-lang-yaml="`15`" pulumi-lang-java="`15`" pulumi-lang-hcl="`15`">`15`</span>.
	HealthCheckInterval *int `pulumi:"healthCheckInterval"`
	// Number of consecutive health check failures before the container is considered unhealthy. Minimum <span pulumi-lang-nodejs="`1`" pulumi-lang-dotnet="`1`" pulumi-lang-go="`1`" pulumi-lang-python="`1`" pulumi-lang-yaml="`1`" pulumi-lang-java="`1`" pulumi-lang-hcl="`1`">`1`</span>. Defaults to <span pulumi-lang-nodejs="`5`" pulumi-lang-dotnet="`5`" pulumi-lang-go="`5`" pulumi-lang-python="`5`" pulumi-lang-yaml="`5`" pulumi-lang-java="`5`" pulumi-lang-hcl="`5`">`5`</span>.
	HealthCheckRetries *int `pulumi:"healthCheckRetries"`
	// Grace period in seconds before health checks start counting failures after container start. Minimum <span pulumi-lang-nodejs="`0`" pulumi-lang-dotnet="`0`" pulumi-lang-go="`0`" pulumi-lang-python="`0`" pulumi-lang-yaml="`0`" pulumi-lang-java="`0`" pulumi-lang-hcl="`0`">`0`</span>. Defaults to <span pulumi-lang-nodejs="`5`" pulumi-lang-dotnet="`5`" pulumi-lang-go="`5`" pulumi-lang-python="`5`" pulumi-lang-yaml="`5`" pulumi-lang-java="`5`" pulumi-lang-hcl="`5`">`5`</span>.
	HealthCheckStartPeriod *int `pulumi:"healthCheckStartPeriod"`
	// Health check timeout in seconds. Minimum <span pulumi-lang-nodejs="`1`" pulumi-lang-dotnet="`1`" pulumi-lang-go="`1`" pulumi-lang-python="`1`" pulumi-lang-yaml="`1`" pulumi-lang-java="`1`" pulumi-lang-hcl="`1`">`1`</span>. Defaults to <span pulumi-lang-nodejs="`5`" pulumi-lang-dotnet="`5`" pulumi-lang-go="`5`" pulumi-lang-python="`5`" pulumi-lang-yaml="`5`" pulumi-lang-java="`5`" pulumi-lang-hcl="`5`">`5`</span>.
	HealthCheckTimeout *int `pulumi:"healthCheckTimeout"`
	// The Docker image to use.
	Image *string `pulumi:"image"`
	// Whether to immediately deploy the database after creation. When <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>, Coolify starts the database container right away. When <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span> (default), the database is created but not started.
	InstantDeploy *bool `pulumi:"instantDeploy"`
	// Internal connection URL for the database, accessible from other containers on the same server. Contains credentials; requires an API token with sensitive-data read permission.
	InternalDbUrl *string `pulumi:"internalDbUrl"`
	// When <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>, includes timestamps in container log output. Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
	IsIncludeTimestamps *bool `pulumi:"isIncludeTimestamps"`
	// When <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>, sends container logs to the configured log drain. Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
	IsLogDrainEnabled *bool `pulumi:"isLogDrainEnabled"`
	// When <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>, exposes the database on a port accessible via the server's IP address. When <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span> (default), the database is only reachable from other containers on the same Docker network. Set <span pulumi-lang-nodejs="`publicPort`" pulumi-lang-dotnet="`PublicPort`" pulumi-lang-go="`publicPort`" pulumi-lang-python="`public_port`" pulumi-lang-yaml="`publicPort`" pulumi-lang-java="`publicPort`" pulumi-lang-hcl="`public_port`">`publicPort`</span> to choose a specific port.
	IsPublic *bool `pulumi:"isPublic"`
	// CPU shares (relative weight).
	LimitsCpuShares *int `pulumi:"limitsCpuShares"`
	// CPU limit (e.g., `0.5`, <span pulumi-lang-nodejs="`2`" pulumi-lang-dotnet="`2`" pulumi-lang-go="`2`" pulumi-lang-python="`2`" pulumi-lang-yaml="`2`" pulumi-lang-java="`2`" pulumi-lang-hcl="`2`">`2`</span>).
	LimitsCpus *string `pulumi:"limitsCpus"`
	// CPU set restriction (e.g., `0-3`, `0,2`).
	LimitsCpuset *string `pulumi:"limitsCpuset"`
	// Memory limit (e.g., <span pulumi-lang-nodejs="`512m`" pulumi-lang-dotnet="`512m`" pulumi-lang-go="`512m`" pulumi-lang-python="`512m`" pulumi-lang-yaml="`512m`" pulumi-lang-java="`512m`" pulumi-lang-hcl="`512m`">`512m`</span>, <span pulumi-lang-nodejs="`2g`" pulumi-lang-dotnet="`2g`" pulumi-lang-go="`2g`" pulumi-lang-python="`2g`" pulumi-lang-yaml="`2g`" pulumi-lang-java="`2g`" pulumi-lang-hcl="`2g`">`2g`</span>).
	LimitsMemory *string `pulumi:"limitsMemory"`
	// Memory reservation (e.g., <span pulumi-lang-nodejs="`256m`" pulumi-lang-dotnet="`256m`" pulumi-lang-go="`256m`" pulumi-lang-python="`256m`" pulumi-lang-yaml="`256m`" pulumi-lang-java="`256m`" pulumi-lang-hcl="`256m`">`256m`</span>).
	LimitsMemoryReservation *string `pulumi:"limitsMemoryReservation"`
	// Memory swap limit (e.g., <span pulumi-lang-nodejs="`1g`" pulumi-lang-dotnet="`1g`" pulumi-lang-go="`1g`" pulumi-lang-python="`1g`" pulumi-lang-yaml="`1g`" pulumi-lang-java="`1g`" pulumi-lang-hcl="`1g`">`1g`</span>).
	LimitsMemorySwap *string `pulumi:"limitsMemorySwap"`
	// Memory swappiness (0-100).
	LimitsMemorySwappiness *int `pulumi:"limitsMemorySwappiness"`
	// The name of the database resource. Also used as the Docker container name and internal DNS hostname for inter-container communication.
	Name *string `pulumi:"name"`
	// Port mappings in `host:container` format, comma-separated (e.g., `8080:5432`).
	PortsMappings *string `pulumi:"portsMappings"`
	// The UUID of the project this database belongs to. Changing this forces a new resource.
	ProjectUuid *string `pulumi:"projectUuid"`
	// The host port to expose the database on when <span pulumi-lang-nodejs="`isPublic`" pulumi-lang-dotnet="`IsPublic`" pulumi-lang-go="`isPublic`" pulumi-lang-python="`is_public`" pulumi-lang-yaml="`isPublic`" pulumi-lang-java="`isPublic`" pulumi-lang-hcl="`is_public`">`isPublic`</span> is <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>. If omitted, Coolify auto-assigns an available port. Ignored when <span pulumi-lang-nodejs="`isPublic`" pulumi-lang-dotnet="`IsPublic`" pulumi-lang-go="`isPublic`" pulumi-lang-python="`is_public`" pulumi-lang-yaml="`isPublic`" pulumi-lang-java="`isPublic`" pulumi-lang-hcl="`is_public`">`isPublic`</span> is <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
	PublicPort *int `pulumi:"publicPort"`
	// Timeout in seconds for public port allocation.
	PublicPortTimeout *int `pulumi:"publicPortTimeout"`
	// The UUID of the server to deploy the database on. Changing this forces a new resource.
	ServerUuid *string `pulumi:"serverUuid"`
	// The current status of the database (e.g., <span pulumi-lang-nodejs="`running`" pulumi-lang-dotnet="`Running`" pulumi-lang-go="`running`" pulumi-lang-python="`running`" pulumi-lang-yaml="`running`" pulumi-lang-java="`running`" pulumi-lang-hcl="`running`">`running`</span>, <span pulumi-lang-nodejs="`exited`" pulumi-lang-dotnet="`Exited`" pulumi-lang-go="`exited`" pulumi-lang-python="`exited`" pulumi-lang-yaml="`exited`" pulumi-lang-java="`exited`" pulumi-lang-hcl="`exited`">`exited`</span>).
	Status   *string                    `pulumi:"status"`
	Timeouts *DatabaseDragonflyTimeouts `pulumi:"timeouts"`
	// The UUID of the database.
	Uuid *string `pulumi:"uuid"`
}

type DatabaseDragonflyState struct {
	// Custom Docker run options passed to the container.
	CustomDockerRunOptions pulumi.StringPtrInput
	// A description of the database.
	Description pulumi.StringPtrInput
	// UUID of the Coolify destination (Docker network) on the server. Create-only; changing forces a new resource. Coolify requires this when the server has multiple destinations and ignores a mismatched value when only one destination exists. Supported on database create for all Coolify versions this provider supports (v4.1.0+). When omitted on a multi-destination server, the client may auto-resolve after Coolify returns the multi-destination error (prefers network <span pulumi-lang-nodejs="`coolify`" pulumi-lang-dotnet="`Coolify`" pulumi-lang-go="`coolify`" pulumi-lang-python="`coolify`" pulumi-lang-yaml="`coolify`" pulumi-lang-java="`coolify`" pulumi-lang-hcl="`coolify`">`coolify`</span>). Manage destinations with <span pulumi-lang-nodejs="`coolify.Destination`" pulumi-lang-dotnet="`coolify.Destination`" pulumi-lang-go="`Destination`" pulumi-lang-python="`Destination`" pulumi-lang-yaml="`coolify.Destination`" pulumi-lang-java="`coolify.Destination`" pulumi-lang-hcl="`coolify_destination`">`coolify.Destination`</span>. Import cannot recover this value (GET does not return destination UUID); re-adding it after import forces replacement unless you set it in state or omit the attribute.
	DestinationUuid pulumi.StringPtrInput
	// The Dragonfly password. If omitted, Coolify auto-generates a value readable from state after creation.
	DragonflyPassword pulumi.StringPtrInput
	// When <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>, enables SSL/TLS encryption for database connections. Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
	EnableSsl pulumi.BoolPtrInput
	// The name of the environment within the project to deploy into. Coolify auto-creates a <span pulumi-lang-nodejs="`production`" pulumi-lang-dotnet="`Production`" pulumi-lang-go="`production`" pulumi-lang-python="`production`" pulumi-lang-yaml="`production`" pulumi-lang-java="`production`" pulumi-lang-hcl="`production`">`production`</span> environment per project; for other environments, create one first with <span pulumi-lang-nodejs="`coolify.Environment`" pulumi-lang-dotnet="`coolify.Environment`" pulumi-lang-go="`Environment`" pulumi-lang-python="`Environment`" pulumi-lang-yaml="`coolify.Environment`" pulumi-lang-java="`coolify.Environment`" pulumi-lang-hcl="`coolify_environment`">`coolify.Environment`</span>. Defaults to <span pulumi-lang-nodejs="`production`" pulumi-lang-dotnet="`Production`" pulumi-lang-go="`production`" pulumi-lang-python="`production`" pulumi-lang-yaml="`production`" pulumi-lang-java="`production`" pulumi-lang-hcl="`production`">`production`</span>. Changing this forces a new resource.
	EnvironmentName pulumi.StringPtrInput
	// When <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>, enables the Docker health check probe for this database container. Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
	HealthCheckEnabled pulumi.BoolPtrInput
	// Health check interval in seconds. Minimum <span pulumi-lang-nodejs="`1`" pulumi-lang-dotnet="`1`" pulumi-lang-go="`1`" pulumi-lang-python="`1`" pulumi-lang-yaml="`1`" pulumi-lang-java="`1`" pulumi-lang-hcl="`1`">`1`</span>. Defaults to <span pulumi-lang-nodejs="`15`" pulumi-lang-dotnet="`15`" pulumi-lang-go="`15`" pulumi-lang-python="`15`" pulumi-lang-yaml="`15`" pulumi-lang-java="`15`" pulumi-lang-hcl="`15`">`15`</span>.
	HealthCheckInterval pulumi.IntPtrInput
	// Number of consecutive health check failures before the container is considered unhealthy. Minimum <span pulumi-lang-nodejs="`1`" pulumi-lang-dotnet="`1`" pulumi-lang-go="`1`" pulumi-lang-python="`1`" pulumi-lang-yaml="`1`" pulumi-lang-java="`1`" pulumi-lang-hcl="`1`">`1`</span>. Defaults to <span pulumi-lang-nodejs="`5`" pulumi-lang-dotnet="`5`" pulumi-lang-go="`5`" pulumi-lang-python="`5`" pulumi-lang-yaml="`5`" pulumi-lang-java="`5`" pulumi-lang-hcl="`5`">`5`</span>.
	HealthCheckRetries pulumi.IntPtrInput
	// Grace period in seconds before health checks start counting failures after container start. Minimum <span pulumi-lang-nodejs="`0`" pulumi-lang-dotnet="`0`" pulumi-lang-go="`0`" pulumi-lang-python="`0`" pulumi-lang-yaml="`0`" pulumi-lang-java="`0`" pulumi-lang-hcl="`0`">`0`</span>. Defaults to <span pulumi-lang-nodejs="`5`" pulumi-lang-dotnet="`5`" pulumi-lang-go="`5`" pulumi-lang-python="`5`" pulumi-lang-yaml="`5`" pulumi-lang-java="`5`" pulumi-lang-hcl="`5`">`5`</span>.
	HealthCheckStartPeriod pulumi.IntPtrInput
	// Health check timeout in seconds. Minimum <span pulumi-lang-nodejs="`1`" pulumi-lang-dotnet="`1`" pulumi-lang-go="`1`" pulumi-lang-python="`1`" pulumi-lang-yaml="`1`" pulumi-lang-java="`1`" pulumi-lang-hcl="`1`">`1`</span>. Defaults to <span pulumi-lang-nodejs="`5`" pulumi-lang-dotnet="`5`" pulumi-lang-go="`5`" pulumi-lang-python="`5`" pulumi-lang-yaml="`5`" pulumi-lang-java="`5`" pulumi-lang-hcl="`5`">`5`</span>.
	HealthCheckTimeout pulumi.IntPtrInput
	// The Docker image to use.
	Image pulumi.StringPtrInput
	// Whether to immediately deploy the database after creation. When <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>, Coolify starts the database container right away. When <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span> (default), the database is created but not started.
	InstantDeploy pulumi.BoolPtrInput
	// Internal connection URL for the database, accessible from other containers on the same server. Contains credentials; requires an API token with sensitive-data read permission.
	InternalDbUrl pulumi.StringPtrInput
	// When <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>, includes timestamps in container log output. Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
	IsIncludeTimestamps pulumi.BoolPtrInput
	// When <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>, sends container logs to the configured log drain. Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
	IsLogDrainEnabled pulumi.BoolPtrInput
	// When <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>, exposes the database on a port accessible via the server's IP address. When <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span> (default), the database is only reachable from other containers on the same Docker network. Set <span pulumi-lang-nodejs="`publicPort`" pulumi-lang-dotnet="`PublicPort`" pulumi-lang-go="`publicPort`" pulumi-lang-python="`public_port`" pulumi-lang-yaml="`publicPort`" pulumi-lang-java="`publicPort`" pulumi-lang-hcl="`public_port`">`publicPort`</span> to choose a specific port.
	IsPublic pulumi.BoolPtrInput
	// CPU shares (relative weight).
	LimitsCpuShares pulumi.IntPtrInput
	// CPU limit (e.g., `0.5`, <span pulumi-lang-nodejs="`2`" pulumi-lang-dotnet="`2`" pulumi-lang-go="`2`" pulumi-lang-python="`2`" pulumi-lang-yaml="`2`" pulumi-lang-java="`2`" pulumi-lang-hcl="`2`">`2`</span>).
	LimitsCpus pulumi.StringPtrInput
	// CPU set restriction (e.g., `0-3`, `0,2`).
	LimitsCpuset pulumi.StringPtrInput
	// Memory limit (e.g., <span pulumi-lang-nodejs="`512m`" pulumi-lang-dotnet="`512m`" pulumi-lang-go="`512m`" pulumi-lang-python="`512m`" pulumi-lang-yaml="`512m`" pulumi-lang-java="`512m`" pulumi-lang-hcl="`512m`">`512m`</span>, <span pulumi-lang-nodejs="`2g`" pulumi-lang-dotnet="`2g`" pulumi-lang-go="`2g`" pulumi-lang-python="`2g`" pulumi-lang-yaml="`2g`" pulumi-lang-java="`2g`" pulumi-lang-hcl="`2g`">`2g`</span>).
	LimitsMemory pulumi.StringPtrInput
	// Memory reservation (e.g., <span pulumi-lang-nodejs="`256m`" pulumi-lang-dotnet="`256m`" pulumi-lang-go="`256m`" pulumi-lang-python="`256m`" pulumi-lang-yaml="`256m`" pulumi-lang-java="`256m`" pulumi-lang-hcl="`256m`">`256m`</span>).
	LimitsMemoryReservation pulumi.StringPtrInput
	// Memory swap limit (e.g., <span pulumi-lang-nodejs="`1g`" pulumi-lang-dotnet="`1g`" pulumi-lang-go="`1g`" pulumi-lang-python="`1g`" pulumi-lang-yaml="`1g`" pulumi-lang-java="`1g`" pulumi-lang-hcl="`1g`">`1g`</span>).
	LimitsMemorySwap pulumi.StringPtrInput
	// Memory swappiness (0-100).
	LimitsMemorySwappiness pulumi.IntPtrInput
	// The name of the database resource. Also used as the Docker container name and internal DNS hostname for inter-container communication.
	Name pulumi.StringPtrInput
	// Port mappings in `host:container` format, comma-separated (e.g., `8080:5432`).
	PortsMappings pulumi.StringPtrInput
	// The UUID of the project this database belongs to. Changing this forces a new resource.
	ProjectUuid pulumi.StringPtrInput
	// The host port to expose the database on when <span pulumi-lang-nodejs="`isPublic`" pulumi-lang-dotnet="`IsPublic`" pulumi-lang-go="`isPublic`" pulumi-lang-python="`is_public`" pulumi-lang-yaml="`isPublic`" pulumi-lang-java="`isPublic`" pulumi-lang-hcl="`is_public`">`isPublic`</span> is <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>. If omitted, Coolify auto-assigns an available port. Ignored when <span pulumi-lang-nodejs="`isPublic`" pulumi-lang-dotnet="`IsPublic`" pulumi-lang-go="`isPublic`" pulumi-lang-python="`is_public`" pulumi-lang-yaml="`isPublic`" pulumi-lang-java="`isPublic`" pulumi-lang-hcl="`is_public`">`isPublic`</span> is <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
	PublicPort pulumi.IntPtrInput
	// Timeout in seconds for public port allocation.
	PublicPortTimeout pulumi.IntPtrInput
	// The UUID of the server to deploy the database on. Changing this forces a new resource.
	ServerUuid pulumi.StringPtrInput
	// The current status of the database (e.g., <span pulumi-lang-nodejs="`running`" pulumi-lang-dotnet="`Running`" pulumi-lang-go="`running`" pulumi-lang-python="`running`" pulumi-lang-yaml="`running`" pulumi-lang-java="`running`" pulumi-lang-hcl="`running`">`running`</span>, <span pulumi-lang-nodejs="`exited`" pulumi-lang-dotnet="`Exited`" pulumi-lang-go="`exited`" pulumi-lang-python="`exited`" pulumi-lang-yaml="`exited`" pulumi-lang-java="`exited`" pulumi-lang-hcl="`exited`">`exited`</span>).
	Status   pulumi.StringPtrInput
	Timeouts DatabaseDragonflyTimeoutsPtrInput
	// The UUID of the database.
	Uuid pulumi.StringPtrInput
}

func (DatabaseDragonflyState) ElementType() reflect.Type {
	return reflect.TypeOf((*databaseDragonflyState)(nil)).Elem()
}

type databaseDragonflyArgs struct {
	// Custom Docker run options passed to the container.
	CustomDockerRunOptions *string `pulumi:"customDockerRunOptions"`
	// A description of the database.
	Description *string `pulumi:"description"`
	// UUID of the Coolify destination (Docker network) on the server. Create-only; changing forces a new resource. Coolify requires this when the server has multiple destinations and ignores a mismatched value when only one destination exists. Supported on database create for all Coolify versions this provider supports (v4.1.0+). When omitted on a multi-destination server, the client may auto-resolve after Coolify returns the multi-destination error (prefers network <span pulumi-lang-nodejs="`coolify`" pulumi-lang-dotnet="`Coolify`" pulumi-lang-go="`coolify`" pulumi-lang-python="`coolify`" pulumi-lang-yaml="`coolify`" pulumi-lang-java="`coolify`" pulumi-lang-hcl="`coolify`">`coolify`</span>). Manage destinations with <span pulumi-lang-nodejs="`coolify.Destination`" pulumi-lang-dotnet="`coolify.Destination`" pulumi-lang-go="`Destination`" pulumi-lang-python="`Destination`" pulumi-lang-yaml="`coolify.Destination`" pulumi-lang-java="`coolify.Destination`" pulumi-lang-hcl="`coolify_destination`">`coolify.Destination`</span>. Import cannot recover this value (GET does not return destination UUID); re-adding it after import forces replacement unless you set it in state or omit the attribute.
	DestinationUuid *string `pulumi:"destinationUuid"`
	// The Dragonfly password. If omitted, Coolify auto-generates a value readable from state after creation.
	DragonflyPassword *string `pulumi:"dragonflyPassword"`
	// When <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>, enables SSL/TLS encryption for database connections. Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
	EnableSsl *bool `pulumi:"enableSsl"`
	// The name of the environment within the project to deploy into. Coolify auto-creates a <span pulumi-lang-nodejs="`production`" pulumi-lang-dotnet="`Production`" pulumi-lang-go="`production`" pulumi-lang-python="`production`" pulumi-lang-yaml="`production`" pulumi-lang-java="`production`" pulumi-lang-hcl="`production`">`production`</span> environment per project; for other environments, create one first with <span pulumi-lang-nodejs="`coolify.Environment`" pulumi-lang-dotnet="`coolify.Environment`" pulumi-lang-go="`Environment`" pulumi-lang-python="`Environment`" pulumi-lang-yaml="`coolify.Environment`" pulumi-lang-java="`coolify.Environment`" pulumi-lang-hcl="`coolify_environment`">`coolify.Environment`</span>. Defaults to <span pulumi-lang-nodejs="`production`" pulumi-lang-dotnet="`Production`" pulumi-lang-go="`production`" pulumi-lang-python="`production`" pulumi-lang-yaml="`production`" pulumi-lang-java="`production`" pulumi-lang-hcl="`production`">`production`</span>. Changing this forces a new resource.
	EnvironmentName *string `pulumi:"environmentName"`
	// When <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>, enables the Docker health check probe for this database container. Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
	HealthCheckEnabled *bool `pulumi:"healthCheckEnabled"`
	// Health check interval in seconds. Minimum <span pulumi-lang-nodejs="`1`" pulumi-lang-dotnet="`1`" pulumi-lang-go="`1`" pulumi-lang-python="`1`" pulumi-lang-yaml="`1`" pulumi-lang-java="`1`" pulumi-lang-hcl="`1`">`1`</span>. Defaults to <span pulumi-lang-nodejs="`15`" pulumi-lang-dotnet="`15`" pulumi-lang-go="`15`" pulumi-lang-python="`15`" pulumi-lang-yaml="`15`" pulumi-lang-java="`15`" pulumi-lang-hcl="`15`">`15`</span>.
	HealthCheckInterval *int `pulumi:"healthCheckInterval"`
	// Number of consecutive health check failures before the container is considered unhealthy. Minimum <span pulumi-lang-nodejs="`1`" pulumi-lang-dotnet="`1`" pulumi-lang-go="`1`" pulumi-lang-python="`1`" pulumi-lang-yaml="`1`" pulumi-lang-java="`1`" pulumi-lang-hcl="`1`">`1`</span>. Defaults to <span pulumi-lang-nodejs="`5`" pulumi-lang-dotnet="`5`" pulumi-lang-go="`5`" pulumi-lang-python="`5`" pulumi-lang-yaml="`5`" pulumi-lang-java="`5`" pulumi-lang-hcl="`5`">`5`</span>.
	HealthCheckRetries *int `pulumi:"healthCheckRetries"`
	// Grace period in seconds before health checks start counting failures after container start. Minimum <span pulumi-lang-nodejs="`0`" pulumi-lang-dotnet="`0`" pulumi-lang-go="`0`" pulumi-lang-python="`0`" pulumi-lang-yaml="`0`" pulumi-lang-java="`0`" pulumi-lang-hcl="`0`">`0`</span>. Defaults to <span pulumi-lang-nodejs="`5`" pulumi-lang-dotnet="`5`" pulumi-lang-go="`5`" pulumi-lang-python="`5`" pulumi-lang-yaml="`5`" pulumi-lang-java="`5`" pulumi-lang-hcl="`5`">`5`</span>.
	HealthCheckStartPeriod *int `pulumi:"healthCheckStartPeriod"`
	// Health check timeout in seconds. Minimum <span pulumi-lang-nodejs="`1`" pulumi-lang-dotnet="`1`" pulumi-lang-go="`1`" pulumi-lang-python="`1`" pulumi-lang-yaml="`1`" pulumi-lang-java="`1`" pulumi-lang-hcl="`1`">`1`</span>. Defaults to <span pulumi-lang-nodejs="`5`" pulumi-lang-dotnet="`5`" pulumi-lang-go="`5`" pulumi-lang-python="`5`" pulumi-lang-yaml="`5`" pulumi-lang-java="`5`" pulumi-lang-hcl="`5`">`5`</span>.
	HealthCheckTimeout *int `pulumi:"healthCheckTimeout"`
	// The Docker image to use.
	Image *string `pulumi:"image"`
	// Whether to immediately deploy the database after creation. When <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>, Coolify starts the database container right away. When <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span> (default), the database is created but not started.
	InstantDeploy *bool `pulumi:"instantDeploy"`
	// When <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>, includes timestamps in container log output. Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
	IsIncludeTimestamps *bool `pulumi:"isIncludeTimestamps"`
	// When <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>, sends container logs to the configured log drain. Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
	IsLogDrainEnabled *bool `pulumi:"isLogDrainEnabled"`
	// When <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>, exposes the database on a port accessible via the server's IP address. When <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span> (default), the database is only reachable from other containers on the same Docker network. Set <span pulumi-lang-nodejs="`publicPort`" pulumi-lang-dotnet="`PublicPort`" pulumi-lang-go="`publicPort`" pulumi-lang-python="`public_port`" pulumi-lang-yaml="`publicPort`" pulumi-lang-java="`publicPort`" pulumi-lang-hcl="`public_port`">`publicPort`</span> to choose a specific port.
	IsPublic *bool `pulumi:"isPublic"`
	// CPU shares (relative weight).
	LimitsCpuShares *int `pulumi:"limitsCpuShares"`
	// CPU limit (e.g., `0.5`, <span pulumi-lang-nodejs="`2`" pulumi-lang-dotnet="`2`" pulumi-lang-go="`2`" pulumi-lang-python="`2`" pulumi-lang-yaml="`2`" pulumi-lang-java="`2`" pulumi-lang-hcl="`2`">`2`</span>).
	LimitsCpus *string `pulumi:"limitsCpus"`
	// CPU set restriction (e.g., `0-3`, `0,2`).
	LimitsCpuset *string `pulumi:"limitsCpuset"`
	// Memory limit (e.g., <span pulumi-lang-nodejs="`512m`" pulumi-lang-dotnet="`512m`" pulumi-lang-go="`512m`" pulumi-lang-python="`512m`" pulumi-lang-yaml="`512m`" pulumi-lang-java="`512m`" pulumi-lang-hcl="`512m`">`512m`</span>, <span pulumi-lang-nodejs="`2g`" pulumi-lang-dotnet="`2g`" pulumi-lang-go="`2g`" pulumi-lang-python="`2g`" pulumi-lang-yaml="`2g`" pulumi-lang-java="`2g`" pulumi-lang-hcl="`2g`">`2g`</span>).
	LimitsMemory *string `pulumi:"limitsMemory"`
	// Memory reservation (e.g., <span pulumi-lang-nodejs="`256m`" pulumi-lang-dotnet="`256m`" pulumi-lang-go="`256m`" pulumi-lang-python="`256m`" pulumi-lang-yaml="`256m`" pulumi-lang-java="`256m`" pulumi-lang-hcl="`256m`">`256m`</span>).
	LimitsMemoryReservation *string `pulumi:"limitsMemoryReservation"`
	// Memory swap limit (e.g., <span pulumi-lang-nodejs="`1g`" pulumi-lang-dotnet="`1g`" pulumi-lang-go="`1g`" pulumi-lang-python="`1g`" pulumi-lang-yaml="`1g`" pulumi-lang-java="`1g`" pulumi-lang-hcl="`1g`">`1g`</span>).
	LimitsMemorySwap *string `pulumi:"limitsMemorySwap"`
	// Memory swappiness (0-100).
	LimitsMemorySwappiness *int `pulumi:"limitsMemorySwappiness"`
	// The name of the database resource. Also used as the Docker container name and internal DNS hostname for inter-container communication.
	Name *string `pulumi:"name"`
	// Port mappings in `host:container` format, comma-separated (e.g., `8080:5432`).
	PortsMappings *string `pulumi:"portsMappings"`
	// The UUID of the project this database belongs to. Changing this forces a new resource.
	ProjectUuid string `pulumi:"projectUuid"`
	// The host port to expose the database on when <span pulumi-lang-nodejs="`isPublic`" pulumi-lang-dotnet="`IsPublic`" pulumi-lang-go="`isPublic`" pulumi-lang-python="`is_public`" pulumi-lang-yaml="`isPublic`" pulumi-lang-java="`isPublic`" pulumi-lang-hcl="`is_public`">`isPublic`</span> is <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>. If omitted, Coolify auto-assigns an available port. Ignored when <span pulumi-lang-nodejs="`isPublic`" pulumi-lang-dotnet="`IsPublic`" pulumi-lang-go="`isPublic`" pulumi-lang-python="`is_public`" pulumi-lang-yaml="`isPublic`" pulumi-lang-java="`isPublic`" pulumi-lang-hcl="`is_public`">`isPublic`</span> is <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
	PublicPort *int `pulumi:"publicPort"`
	// Timeout in seconds for public port allocation.
	PublicPortTimeout *int `pulumi:"publicPortTimeout"`
	// The UUID of the server to deploy the database on. Changing this forces a new resource.
	ServerUuid string                     `pulumi:"serverUuid"`
	Timeouts   *DatabaseDragonflyTimeouts `pulumi:"timeouts"`
}

// The set of arguments for constructing a DatabaseDragonfly resource.
type DatabaseDragonflyArgs struct {
	// Custom Docker run options passed to the container.
	CustomDockerRunOptions pulumi.StringPtrInput
	// A description of the database.
	Description pulumi.StringPtrInput
	// UUID of the Coolify destination (Docker network) on the server. Create-only; changing forces a new resource. Coolify requires this when the server has multiple destinations and ignores a mismatched value when only one destination exists. Supported on database create for all Coolify versions this provider supports (v4.1.0+). When omitted on a multi-destination server, the client may auto-resolve after Coolify returns the multi-destination error (prefers network <span pulumi-lang-nodejs="`coolify`" pulumi-lang-dotnet="`Coolify`" pulumi-lang-go="`coolify`" pulumi-lang-python="`coolify`" pulumi-lang-yaml="`coolify`" pulumi-lang-java="`coolify`" pulumi-lang-hcl="`coolify`">`coolify`</span>). Manage destinations with <span pulumi-lang-nodejs="`coolify.Destination`" pulumi-lang-dotnet="`coolify.Destination`" pulumi-lang-go="`Destination`" pulumi-lang-python="`Destination`" pulumi-lang-yaml="`coolify.Destination`" pulumi-lang-java="`coolify.Destination`" pulumi-lang-hcl="`coolify_destination`">`coolify.Destination`</span>. Import cannot recover this value (GET does not return destination UUID); re-adding it after import forces replacement unless you set it in state or omit the attribute.
	DestinationUuid pulumi.StringPtrInput
	// The Dragonfly password. If omitted, Coolify auto-generates a value readable from state after creation.
	DragonflyPassword pulumi.StringPtrInput
	// When <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>, enables SSL/TLS encryption for database connections. Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
	EnableSsl pulumi.BoolPtrInput
	// The name of the environment within the project to deploy into. Coolify auto-creates a <span pulumi-lang-nodejs="`production`" pulumi-lang-dotnet="`Production`" pulumi-lang-go="`production`" pulumi-lang-python="`production`" pulumi-lang-yaml="`production`" pulumi-lang-java="`production`" pulumi-lang-hcl="`production`">`production`</span> environment per project; for other environments, create one first with <span pulumi-lang-nodejs="`coolify.Environment`" pulumi-lang-dotnet="`coolify.Environment`" pulumi-lang-go="`Environment`" pulumi-lang-python="`Environment`" pulumi-lang-yaml="`coolify.Environment`" pulumi-lang-java="`coolify.Environment`" pulumi-lang-hcl="`coolify_environment`">`coolify.Environment`</span>. Defaults to <span pulumi-lang-nodejs="`production`" pulumi-lang-dotnet="`Production`" pulumi-lang-go="`production`" pulumi-lang-python="`production`" pulumi-lang-yaml="`production`" pulumi-lang-java="`production`" pulumi-lang-hcl="`production`">`production`</span>. Changing this forces a new resource.
	EnvironmentName pulumi.StringPtrInput
	// When <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>, enables the Docker health check probe for this database container. Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
	HealthCheckEnabled pulumi.BoolPtrInput
	// Health check interval in seconds. Minimum <span pulumi-lang-nodejs="`1`" pulumi-lang-dotnet="`1`" pulumi-lang-go="`1`" pulumi-lang-python="`1`" pulumi-lang-yaml="`1`" pulumi-lang-java="`1`" pulumi-lang-hcl="`1`">`1`</span>. Defaults to <span pulumi-lang-nodejs="`15`" pulumi-lang-dotnet="`15`" pulumi-lang-go="`15`" pulumi-lang-python="`15`" pulumi-lang-yaml="`15`" pulumi-lang-java="`15`" pulumi-lang-hcl="`15`">`15`</span>.
	HealthCheckInterval pulumi.IntPtrInput
	// Number of consecutive health check failures before the container is considered unhealthy. Minimum <span pulumi-lang-nodejs="`1`" pulumi-lang-dotnet="`1`" pulumi-lang-go="`1`" pulumi-lang-python="`1`" pulumi-lang-yaml="`1`" pulumi-lang-java="`1`" pulumi-lang-hcl="`1`">`1`</span>. Defaults to <span pulumi-lang-nodejs="`5`" pulumi-lang-dotnet="`5`" pulumi-lang-go="`5`" pulumi-lang-python="`5`" pulumi-lang-yaml="`5`" pulumi-lang-java="`5`" pulumi-lang-hcl="`5`">`5`</span>.
	HealthCheckRetries pulumi.IntPtrInput
	// Grace period in seconds before health checks start counting failures after container start. Minimum <span pulumi-lang-nodejs="`0`" pulumi-lang-dotnet="`0`" pulumi-lang-go="`0`" pulumi-lang-python="`0`" pulumi-lang-yaml="`0`" pulumi-lang-java="`0`" pulumi-lang-hcl="`0`">`0`</span>. Defaults to <span pulumi-lang-nodejs="`5`" pulumi-lang-dotnet="`5`" pulumi-lang-go="`5`" pulumi-lang-python="`5`" pulumi-lang-yaml="`5`" pulumi-lang-java="`5`" pulumi-lang-hcl="`5`">`5`</span>.
	HealthCheckStartPeriod pulumi.IntPtrInput
	// Health check timeout in seconds. Minimum <span pulumi-lang-nodejs="`1`" pulumi-lang-dotnet="`1`" pulumi-lang-go="`1`" pulumi-lang-python="`1`" pulumi-lang-yaml="`1`" pulumi-lang-java="`1`" pulumi-lang-hcl="`1`">`1`</span>. Defaults to <span pulumi-lang-nodejs="`5`" pulumi-lang-dotnet="`5`" pulumi-lang-go="`5`" pulumi-lang-python="`5`" pulumi-lang-yaml="`5`" pulumi-lang-java="`5`" pulumi-lang-hcl="`5`">`5`</span>.
	HealthCheckTimeout pulumi.IntPtrInput
	// The Docker image to use.
	Image pulumi.StringPtrInput
	// Whether to immediately deploy the database after creation. When <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>, Coolify starts the database container right away. When <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span> (default), the database is created but not started.
	InstantDeploy pulumi.BoolPtrInput
	// When <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>, includes timestamps in container log output. Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
	IsIncludeTimestamps pulumi.BoolPtrInput
	// When <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>, sends container logs to the configured log drain. Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
	IsLogDrainEnabled pulumi.BoolPtrInput
	// When <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>, exposes the database on a port accessible via the server's IP address. When <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span> (default), the database is only reachable from other containers on the same Docker network. Set <span pulumi-lang-nodejs="`publicPort`" pulumi-lang-dotnet="`PublicPort`" pulumi-lang-go="`publicPort`" pulumi-lang-python="`public_port`" pulumi-lang-yaml="`publicPort`" pulumi-lang-java="`publicPort`" pulumi-lang-hcl="`public_port`">`publicPort`</span> to choose a specific port.
	IsPublic pulumi.BoolPtrInput
	// CPU shares (relative weight).
	LimitsCpuShares pulumi.IntPtrInput
	// CPU limit (e.g., `0.5`, <span pulumi-lang-nodejs="`2`" pulumi-lang-dotnet="`2`" pulumi-lang-go="`2`" pulumi-lang-python="`2`" pulumi-lang-yaml="`2`" pulumi-lang-java="`2`" pulumi-lang-hcl="`2`">`2`</span>).
	LimitsCpus pulumi.StringPtrInput
	// CPU set restriction (e.g., `0-3`, `0,2`).
	LimitsCpuset pulumi.StringPtrInput
	// Memory limit (e.g., <span pulumi-lang-nodejs="`512m`" pulumi-lang-dotnet="`512m`" pulumi-lang-go="`512m`" pulumi-lang-python="`512m`" pulumi-lang-yaml="`512m`" pulumi-lang-java="`512m`" pulumi-lang-hcl="`512m`">`512m`</span>, <span pulumi-lang-nodejs="`2g`" pulumi-lang-dotnet="`2g`" pulumi-lang-go="`2g`" pulumi-lang-python="`2g`" pulumi-lang-yaml="`2g`" pulumi-lang-java="`2g`" pulumi-lang-hcl="`2g`">`2g`</span>).
	LimitsMemory pulumi.StringPtrInput
	// Memory reservation (e.g., <span pulumi-lang-nodejs="`256m`" pulumi-lang-dotnet="`256m`" pulumi-lang-go="`256m`" pulumi-lang-python="`256m`" pulumi-lang-yaml="`256m`" pulumi-lang-java="`256m`" pulumi-lang-hcl="`256m`">`256m`</span>).
	LimitsMemoryReservation pulumi.StringPtrInput
	// Memory swap limit (e.g., <span pulumi-lang-nodejs="`1g`" pulumi-lang-dotnet="`1g`" pulumi-lang-go="`1g`" pulumi-lang-python="`1g`" pulumi-lang-yaml="`1g`" pulumi-lang-java="`1g`" pulumi-lang-hcl="`1g`">`1g`</span>).
	LimitsMemorySwap pulumi.StringPtrInput
	// Memory swappiness (0-100).
	LimitsMemorySwappiness pulumi.IntPtrInput
	// The name of the database resource. Also used as the Docker container name and internal DNS hostname for inter-container communication.
	Name pulumi.StringPtrInput
	// Port mappings in `host:container` format, comma-separated (e.g., `8080:5432`).
	PortsMappings pulumi.StringPtrInput
	// The UUID of the project this database belongs to. Changing this forces a new resource.
	ProjectUuid pulumi.StringInput
	// The host port to expose the database on when <span pulumi-lang-nodejs="`isPublic`" pulumi-lang-dotnet="`IsPublic`" pulumi-lang-go="`isPublic`" pulumi-lang-python="`is_public`" pulumi-lang-yaml="`isPublic`" pulumi-lang-java="`isPublic`" pulumi-lang-hcl="`is_public`">`isPublic`</span> is <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>. If omitted, Coolify auto-assigns an available port. Ignored when <span pulumi-lang-nodejs="`isPublic`" pulumi-lang-dotnet="`IsPublic`" pulumi-lang-go="`isPublic`" pulumi-lang-python="`is_public`" pulumi-lang-yaml="`isPublic`" pulumi-lang-java="`isPublic`" pulumi-lang-hcl="`is_public`">`isPublic`</span> is <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
	PublicPort pulumi.IntPtrInput
	// Timeout in seconds for public port allocation.
	PublicPortTimeout pulumi.IntPtrInput
	// The UUID of the server to deploy the database on. Changing this forces a new resource.
	ServerUuid pulumi.StringInput
	Timeouts   DatabaseDragonflyTimeoutsPtrInput
}

func (DatabaseDragonflyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*databaseDragonflyArgs)(nil)).Elem()
}

type DatabaseDragonflyInput interface {
	pulumi.Input

	ToDatabaseDragonflyOutput() DatabaseDragonflyOutput
	ToDatabaseDragonflyOutputWithContext(ctx context.Context) DatabaseDragonflyOutput
}

func (*DatabaseDragonfly) ElementType() reflect.Type {
	return reflect.TypeOf((**DatabaseDragonfly)(nil)).Elem()
}

func (i *DatabaseDragonfly) ToDatabaseDragonflyOutput() DatabaseDragonflyOutput {
	return i.ToDatabaseDragonflyOutputWithContext(context.Background())
}

func (i *DatabaseDragonfly) ToDatabaseDragonflyOutputWithContext(ctx context.Context) DatabaseDragonflyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DatabaseDragonflyOutput)
}

// DatabaseDragonflyArrayInput is an input type that accepts DatabaseDragonflyArray and DatabaseDragonflyArrayOutput values.
// You can construct a concrete instance of `DatabaseDragonflyArrayInput` via:
//
//	DatabaseDragonflyArray{ DatabaseDragonflyArgs{...} }
type DatabaseDragonflyArrayInput interface {
	pulumi.Input

	ToDatabaseDragonflyArrayOutput() DatabaseDragonflyArrayOutput
	ToDatabaseDragonflyArrayOutputWithContext(context.Context) DatabaseDragonflyArrayOutput
}

type DatabaseDragonflyArray []DatabaseDragonflyInput

func (DatabaseDragonflyArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*DatabaseDragonfly)(nil)).Elem()
}

func (i DatabaseDragonflyArray) ToDatabaseDragonflyArrayOutput() DatabaseDragonflyArrayOutput {
	return i.ToDatabaseDragonflyArrayOutputWithContext(context.Background())
}

func (i DatabaseDragonflyArray) ToDatabaseDragonflyArrayOutputWithContext(ctx context.Context) DatabaseDragonflyArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DatabaseDragonflyArrayOutput)
}

// DatabaseDragonflyMapInput is an input type that accepts DatabaseDragonflyMap and DatabaseDragonflyMapOutput values.
// You can construct a concrete instance of `DatabaseDragonflyMapInput` via:
//
//	DatabaseDragonflyMap{ "key": DatabaseDragonflyArgs{...} }
type DatabaseDragonflyMapInput interface {
	pulumi.Input

	ToDatabaseDragonflyMapOutput() DatabaseDragonflyMapOutput
	ToDatabaseDragonflyMapOutputWithContext(context.Context) DatabaseDragonflyMapOutput
}

type DatabaseDragonflyMap map[string]DatabaseDragonflyInput

func (DatabaseDragonflyMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*DatabaseDragonfly)(nil)).Elem()
}

func (i DatabaseDragonflyMap) ToDatabaseDragonflyMapOutput() DatabaseDragonflyMapOutput {
	return i.ToDatabaseDragonflyMapOutputWithContext(context.Background())
}

func (i DatabaseDragonflyMap) ToDatabaseDragonflyMapOutputWithContext(ctx context.Context) DatabaseDragonflyMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DatabaseDragonflyMapOutput)
}

type DatabaseDragonflyOutput struct{ *pulumi.OutputState }

func (DatabaseDragonflyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DatabaseDragonfly)(nil)).Elem()
}

func (o DatabaseDragonflyOutput) ToDatabaseDragonflyOutput() DatabaseDragonflyOutput {
	return o
}

func (o DatabaseDragonflyOutput) ToDatabaseDragonflyOutputWithContext(ctx context.Context) DatabaseDragonflyOutput {
	return o
}

// Custom Docker run options passed to the container.
func (o DatabaseDragonflyOutput) CustomDockerRunOptions() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DatabaseDragonfly) pulumi.StringPtrOutput { return v.CustomDockerRunOptions }).(pulumi.StringPtrOutput)
}

// A description of the database.
func (o DatabaseDragonflyOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v *DatabaseDragonfly) pulumi.StringOutput { return v.Description }).(pulumi.StringOutput)
}

// UUID of the Coolify destination (Docker network) on the server. Create-only; changing forces a new resource. Coolify requires this when the server has multiple destinations and ignores a mismatched value when only one destination exists. Supported on database create for all Coolify versions this provider supports (v4.1.0+). When omitted on a multi-destination server, the client may auto-resolve after Coolify returns the multi-destination error (prefers network <span pulumi-lang-nodejs="`coolify`" pulumi-lang-dotnet="`Coolify`" pulumi-lang-go="`coolify`" pulumi-lang-python="`coolify`" pulumi-lang-yaml="`coolify`" pulumi-lang-java="`coolify`" pulumi-lang-hcl="`coolify`">`coolify`</span>). Manage destinations with <span pulumi-lang-nodejs="`coolify.Destination`" pulumi-lang-dotnet="`coolify.Destination`" pulumi-lang-go="`Destination`" pulumi-lang-python="`Destination`" pulumi-lang-yaml="`coolify.Destination`" pulumi-lang-java="`coolify.Destination`" pulumi-lang-hcl="`coolify_destination`">`coolify.Destination`</span>. Import cannot recover this value (GET does not return destination UUID); re-adding it after import forces replacement unless you set it in state or omit the attribute.
func (o DatabaseDragonflyOutput) DestinationUuid() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DatabaseDragonfly) pulumi.StringPtrOutput { return v.DestinationUuid }).(pulumi.StringPtrOutput)
}

// The Dragonfly password. If omitted, Coolify auto-generates a value readable from state after creation.
func (o DatabaseDragonflyOutput) DragonflyPassword() pulumi.StringOutput {
	return o.ApplyT(func(v *DatabaseDragonfly) pulumi.StringOutput { return v.DragonflyPassword }).(pulumi.StringOutput)
}

// When <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>, enables SSL/TLS encryption for database connections. Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
func (o DatabaseDragonflyOutput) EnableSsl() pulumi.BoolOutput {
	return o.ApplyT(func(v *DatabaseDragonfly) pulumi.BoolOutput { return v.EnableSsl }).(pulumi.BoolOutput)
}

// The name of the environment within the project to deploy into. Coolify auto-creates a <span pulumi-lang-nodejs="`production`" pulumi-lang-dotnet="`Production`" pulumi-lang-go="`production`" pulumi-lang-python="`production`" pulumi-lang-yaml="`production`" pulumi-lang-java="`production`" pulumi-lang-hcl="`production`">`production`</span> environment per project; for other environments, create one first with <span pulumi-lang-nodejs="`coolify.Environment`" pulumi-lang-dotnet="`coolify.Environment`" pulumi-lang-go="`Environment`" pulumi-lang-python="`Environment`" pulumi-lang-yaml="`coolify.Environment`" pulumi-lang-java="`coolify.Environment`" pulumi-lang-hcl="`coolify_environment`">`coolify.Environment`</span>. Defaults to <span pulumi-lang-nodejs="`production`" pulumi-lang-dotnet="`Production`" pulumi-lang-go="`production`" pulumi-lang-python="`production`" pulumi-lang-yaml="`production`" pulumi-lang-java="`production`" pulumi-lang-hcl="`production`">`production`</span>. Changing this forces a new resource.
func (o DatabaseDragonflyOutput) EnvironmentName() pulumi.StringOutput {
	return o.ApplyT(func(v *DatabaseDragonfly) pulumi.StringOutput { return v.EnvironmentName }).(pulumi.StringOutput)
}

// When <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>, enables the Docker health check probe for this database container. Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
func (o DatabaseDragonflyOutput) HealthCheckEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *DatabaseDragonfly) pulumi.BoolOutput { return v.HealthCheckEnabled }).(pulumi.BoolOutput)
}

// Health check interval in seconds. Minimum <span pulumi-lang-nodejs="`1`" pulumi-lang-dotnet="`1`" pulumi-lang-go="`1`" pulumi-lang-python="`1`" pulumi-lang-yaml="`1`" pulumi-lang-java="`1`" pulumi-lang-hcl="`1`">`1`</span>. Defaults to <span pulumi-lang-nodejs="`15`" pulumi-lang-dotnet="`15`" pulumi-lang-go="`15`" pulumi-lang-python="`15`" pulumi-lang-yaml="`15`" pulumi-lang-java="`15`" pulumi-lang-hcl="`15`">`15`</span>.
func (o DatabaseDragonflyOutput) HealthCheckInterval() pulumi.IntOutput {
	return o.ApplyT(func(v *DatabaseDragonfly) pulumi.IntOutput { return v.HealthCheckInterval }).(pulumi.IntOutput)
}

// Number of consecutive health check failures before the container is considered unhealthy. Minimum <span pulumi-lang-nodejs="`1`" pulumi-lang-dotnet="`1`" pulumi-lang-go="`1`" pulumi-lang-python="`1`" pulumi-lang-yaml="`1`" pulumi-lang-java="`1`" pulumi-lang-hcl="`1`">`1`</span>. Defaults to <span pulumi-lang-nodejs="`5`" pulumi-lang-dotnet="`5`" pulumi-lang-go="`5`" pulumi-lang-python="`5`" pulumi-lang-yaml="`5`" pulumi-lang-java="`5`" pulumi-lang-hcl="`5`">`5`</span>.
func (o DatabaseDragonflyOutput) HealthCheckRetries() pulumi.IntOutput {
	return o.ApplyT(func(v *DatabaseDragonfly) pulumi.IntOutput { return v.HealthCheckRetries }).(pulumi.IntOutput)
}

// Grace period in seconds before health checks start counting failures after container start. Minimum <span pulumi-lang-nodejs="`0`" pulumi-lang-dotnet="`0`" pulumi-lang-go="`0`" pulumi-lang-python="`0`" pulumi-lang-yaml="`0`" pulumi-lang-java="`0`" pulumi-lang-hcl="`0`">`0`</span>. Defaults to <span pulumi-lang-nodejs="`5`" pulumi-lang-dotnet="`5`" pulumi-lang-go="`5`" pulumi-lang-python="`5`" pulumi-lang-yaml="`5`" pulumi-lang-java="`5`" pulumi-lang-hcl="`5`">`5`</span>.
func (o DatabaseDragonflyOutput) HealthCheckStartPeriod() pulumi.IntOutput {
	return o.ApplyT(func(v *DatabaseDragonfly) pulumi.IntOutput { return v.HealthCheckStartPeriod }).(pulumi.IntOutput)
}

// Health check timeout in seconds. Minimum <span pulumi-lang-nodejs="`1`" pulumi-lang-dotnet="`1`" pulumi-lang-go="`1`" pulumi-lang-python="`1`" pulumi-lang-yaml="`1`" pulumi-lang-java="`1`" pulumi-lang-hcl="`1`">`1`</span>. Defaults to <span pulumi-lang-nodejs="`5`" pulumi-lang-dotnet="`5`" pulumi-lang-go="`5`" pulumi-lang-python="`5`" pulumi-lang-yaml="`5`" pulumi-lang-java="`5`" pulumi-lang-hcl="`5`">`5`</span>.
func (o DatabaseDragonflyOutput) HealthCheckTimeout() pulumi.IntOutput {
	return o.ApplyT(func(v *DatabaseDragonfly) pulumi.IntOutput { return v.HealthCheckTimeout }).(pulumi.IntOutput)
}

// The Docker image to use.
func (o DatabaseDragonflyOutput) Image() pulumi.StringOutput {
	return o.ApplyT(func(v *DatabaseDragonfly) pulumi.StringOutput { return v.Image }).(pulumi.StringOutput)
}

// Whether to immediately deploy the database after creation. When <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>, Coolify starts the database container right away. When <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span> (default), the database is created but not started.
func (o DatabaseDragonflyOutput) InstantDeploy() pulumi.BoolOutput {
	return o.ApplyT(func(v *DatabaseDragonfly) pulumi.BoolOutput { return v.InstantDeploy }).(pulumi.BoolOutput)
}

// Internal connection URL for the database, accessible from other containers on the same server. Contains credentials; requires an API token with sensitive-data read permission.
func (o DatabaseDragonflyOutput) InternalDbUrl() pulumi.StringOutput {
	return o.ApplyT(func(v *DatabaseDragonfly) pulumi.StringOutput { return v.InternalDbUrl }).(pulumi.StringOutput)
}

// When <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>, includes timestamps in container log output. Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
func (o DatabaseDragonflyOutput) IsIncludeTimestamps() pulumi.BoolOutput {
	return o.ApplyT(func(v *DatabaseDragonfly) pulumi.BoolOutput { return v.IsIncludeTimestamps }).(pulumi.BoolOutput)
}

// When <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>, sends container logs to the configured log drain. Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
func (o DatabaseDragonflyOutput) IsLogDrainEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *DatabaseDragonfly) pulumi.BoolOutput { return v.IsLogDrainEnabled }).(pulumi.BoolOutput)
}

// When <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>, exposes the database on a port accessible via the server's IP address. When <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span> (default), the database is only reachable from other containers on the same Docker network. Set <span pulumi-lang-nodejs="`publicPort`" pulumi-lang-dotnet="`PublicPort`" pulumi-lang-go="`publicPort`" pulumi-lang-python="`public_port`" pulumi-lang-yaml="`publicPort`" pulumi-lang-java="`publicPort`" pulumi-lang-hcl="`public_port`">`publicPort`</span> to choose a specific port.
func (o DatabaseDragonflyOutput) IsPublic() pulumi.BoolOutput {
	return o.ApplyT(func(v *DatabaseDragonfly) pulumi.BoolOutput { return v.IsPublic }).(pulumi.BoolOutput)
}

// CPU shares (relative weight).
func (o DatabaseDragonflyOutput) LimitsCpuShares() pulumi.IntOutput {
	return o.ApplyT(func(v *DatabaseDragonfly) pulumi.IntOutput { return v.LimitsCpuShares }).(pulumi.IntOutput)
}

// CPU limit (e.g., `0.5`, <span pulumi-lang-nodejs="`2`" pulumi-lang-dotnet="`2`" pulumi-lang-go="`2`" pulumi-lang-python="`2`" pulumi-lang-yaml="`2`" pulumi-lang-java="`2`" pulumi-lang-hcl="`2`">`2`</span>).
func (o DatabaseDragonflyOutput) LimitsCpus() pulumi.StringOutput {
	return o.ApplyT(func(v *DatabaseDragonfly) pulumi.StringOutput { return v.LimitsCpus }).(pulumi.StringOutput)
}

// CPU set restriction (e.g., `0-3`, `0,2`).
func (o DatabaseDragonflyOutput) LimitsCpuset() pulumi.StringOutput {
	return o.ApplyT(func(v *DatabaseDragonfly) pulumi.StringOutput { return v.LimitsCpuset }).(pulumi.StringOutput)
}

// Memory limit (e.g., <span pulumi-lang-nodejs="`512m`" pulumi-lang-dotnet="`512m`" pulumi-lang-go="`512m`" pulumi-lang-python="`512m`" pulumi-lang-yaml="`512m`" pulumi-lang-java="`512m`" pulumi-lang-hcl="`512m`">`512m`</span>, <span pulumi-lang-nodejs="`2g`" pulumi-lang-dotnet="`2g`" pulumi-lang-go="`2g`" pulumi-lang-python="`2g`" pulumi-lang-yaml="`2g`" pulumi-lang-java="`2g`" pulumi-lang-hcl="`2g`">`2g`</span>).
func (o DatabaseDragonflyOutput) LimitsMemory() pulumi.StringOutput {
	return o.ApplyT(func(v *DatabaseDragonfly) pulumi.StringOutput { return v.LimitsMemory }).(pulumi.StringOutput)
}

// Memory reservation (e.g., <span pulumi-lang-nodejs="`256m`" pulumi-lang-dotnet="`256m`" pulumi-lang-go="`256m`" pulumi-lang-python="`256m`" pulumi-lang-yaml="`256m`" pulumi-lang-java="`256m`" pulumi-lang-hcl="`256m`">`256m`</span>).
func (o DatabaseDragonflyOutput) LimitsMemoryReservation() pulumi.StringOutput {
	return o.ApplyT(func(v *DatabaseDragonfly) pulumi.StringOutput { return v.LimitsMemoryReservation }).(pulumi.StringOutput)
}

// Memory swap limit (e.g., <span pulumi-lang-nodejs="`1g`" pulumi-lang-dotnet="`1g`" pulumi-lang-go="`1g`" pulumi-lang-python="`1g`" pulumi-lang-yaml="`1g`" pulumi-lang-java="`1g`" pulumi-lang-hcl="`1g`">`1g`</span>).
func (o DatabaseDragonflyOutput) LimitsMemorySwap() pulumi.StringOutput {
	return o.ApplyT(func(v *DatabaseDragonfly) pulumi.StringOutput { return v.LimitsMemorySwap }).(pulumi.StringOutput)
}

// Memory swappiness (0-100).
func (o DatabaseDragonflyOutput) LimitsMemorySwappiness() pulumi.IntOutput {
	return o.ApplyT(func(v *DatabaseDragonfly) pulumi.IntOutput { return v.LimitsMemorySwappiness }).(pulumi.IntOutput)
}

// The name of the database resource. Also used as the Docker container name and internal DNS hostname for inter-container communication.
func (o DatabaseDragonflyOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *DatabaseDragonfly) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Port mappings in `host:container` format, comma-separated (e.g., `8080:5432`).
func (o DatabaseDragonflyOutput) PortsMappings() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DatabaseDragonfly) pulumi.StringPtrOutput { return v.PortsMappings }).(pulumi.StringPtrOutput)
}

// The UUID of the project this database belongs to. Changing this forces a new resource.
func (o DatabaseDragonflyOutput) ProjectUuid() pulumi.StringOutput {
	return o.ApplyT(func(v *DatabaseDragonfly) pulumi.StringOutput { return v.ProjectUuid }).(pulumi.StringOutput)
}

// The host port to expose the database on when <span pulumi-lang-nodejs="`isPublic`" pulumi-lang-dotnet="`IsPublic`" pulumi-lang-go="`isPublic`" pulumi-lang-python="`is_public`" pulumi-lang-yaml="`isPublic`" pulumi-lang-java="`isPublic`" pulumi-lang-hcl="`is_public`">`isPublic`</span> is <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>. If omitted, Coolify auto-assigns an available port. Ignored when <span pulumi-lang-nodejs="`isPublic`" pulumi-lang-dotnet="`IsPublic`" pulumi-lang-go="`isPublic`" pulumi-lang-python="`is_public`" pulumi-lang-yaml="`isPublic`" pulumi-lang-java="`isPublic`" pulumi-lang-hcl="`is_public`">`isPublic`</span> is <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
func (o DatabaseDragonflyOutput) PublicPort() pulumi.IntOutput {
	return o.ApplyT(func(v *DatabaseDragonfly) pulumi.IntOutput { return v.PublicPort }).(pulumi.IntOutput)
}

// Timeout in seconds for public port allocation.
func (o DatabaseDragonflyOutput) PublicPortTimeout() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *DatabaseDragonfly) pulumi.IntPtrOutput { return v.PublicPortTimeout }).(pulumi.IntPtrOutput)
}

// The UUID of the server to deploy the database on. Changing this forces a new resource.
func (o DatabaseDragonflyOutput) ServerUuid() pulumi.StringOutput {
	return o.ApplyT(func(v *DatabaseDragonfly) pulumi.StringOutput { return v.ServerUuid }).(pulumi.StringOutput)
}

// The current status of the database (e.g., <span pulumi-lang-nodejs="`running`" pulumi-lang-dotnet="`Running`" pulumi-lang-go="`running`" pulumi-lang-python="`running`" pulumi-lang-yaml="`running`" pulumi-lang-java="`running`" pulumi-lang-hcl="`running`">`running`</span>, <span pulumi-lang-nodejs="`exited`" pulumi-lang-dotnet="`Exited`" pulumi-lang-go="`exited`" pulumi-lang-python="`exited`" pulumi-lang-yaml="`exited`" pulumi-lang-java="`exited`" pulumi-lang-hcl="`exited`">`exited`</span>).
func (o DatabaseDragonflyOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *DatabaseDragonfly) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

func (o DatabaseDragonflyOutput) Timeouts() DatabaseDragonflyTimeoutsPtrOutput {
	return o.ApplyT(func(v *DatabaseDragonfly) DatabaseDragonflyTimeoutsPtrOutput { return v.Timeouts }).(DatabaseDragonflyTimeoutsPtrOutput)
}

// The UUID of the database.
func (o DatabaseDragonflyOutput) Uuid() pulumi.StringOutput {
	return o.ApplyT(func(v *DatabaseDragonfly) pulumi.StringOutput { return v.Uuid }).(pulumi.StringOutput)
}

type DatabaseDragonflyArrayOutput struct{ *pulumi.OutputState }

func (DatabaseDragonflyArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*DatabaseDragonfly)(nil)).Elem()
}

func (o DatabaseDragonflyArrayOutput) ToDatabaseDragonflyArrayOutput() DatabaseDragonflyArrayOutput {
	return o
}

func (o DatabaseDragonflyArrayOutput) ToDatabaseDragonflyArrayOutputWithContext(ctx context.Context) DatabaseDragonflyArrayOutput {
	return o
}

func (o DatabaseDragonflyArrayOutput) Index(i pulumi.IntInput) DatabaseDragonflyOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *DatabaseDragonfly {
		return vs[0].([]*DatabaseDragonfly)[vs[1].(int)]
	}).(DatabaseDragonflyOutput)
}

type DatabaseDragonflyMapOutput struct{ *pulumi.OutputState }

func (DatabaseDragonflyMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*DatabaseDragonfly)(nil)).Elem()
}

func (o DatabaseDragonflyMapOutput) ToDatabaseDragonflyMapOutput() DatabaseDragonflyMapOutput {
	return o
}

func (o DatabaseDragonflyMapOutput) ToDatabaseDragonflyMapOutputWithContext(ctx context.Context) DatabaseDragonflyMapOutput {
	return o
}

func (o DatabaseDragonflyMapOutput) MapIndex(k pulumi.StringInput) DatabaseDragonflyOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *DatabaseDragonfly {
		return vs[0].(map[string]*DatabaseDragonfly)[vs[1].(string)]
	}).(DatabaseDragonflyOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DatabaseDragonflyInput)(nil)).Elem(), &DatabaseDragonfly{})
	pulumi.RegisterInputType(reflect.TypeOf((*DatabaseDragonflyArrayInput)(nil)).Elem(), DatabaseDragonflyArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*DatabaseDragonflyMapInput)(nil)).Elem(), DatabaseDragonflyMap{})
	pulumi.RegisterOutputType(DatabaseDragonflyOutput{})
	pulumi.RegisterOutputType(DatabaseDragonflyArrayOutput{})
	pulumi.RegisterOutputType(DatabaseDragonflyMapOutput{})
}
