// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package coolify

import (
	"context"
	"reflect"

	"github.com/mheers/pulumi-provider-coolify/sdk/go/coolify/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Use this data source to retrieve information about a Coolify application by UUID.
//
// ## Example Usage
//
// <!--Start PulumiCodeChooser -->
// ```go
// package main
//
// import (
//
//	"github.com/mheers/pulumi-provider-coolify/sdk/go/coolify"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := coolify.GetApplication(ctx, &coolify.LookupApplicationArgs{
//				Uuid: "550e8400-e29b-41d4-a716-446655440000",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
// <!--End PulumiCodeChooser -->
func LookupApplication(ctx *pulumi.Context, args *LookupApplicationArgs, opts ...pulumi.InvokeOption) (*LookupApplicationResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupApplicationResult
	err := ctx.Invoke("coolify:index/getApplication:getApplication", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getApplication.
type LookupApplicationArgs struct {
	// The UUID of the application to look up.
	Uuid string `pulumi:"uuid"`
}

// A collection of values returned by getApplication.
type LookupApplicationResult struct {
	// The build command.
	BuildCommand string `pulumi:"buildCommand"`
	// The build pack type used by the application.
	BuildPack string `pulumi:"buildPack"`
	// The description of the application.
	Description string `pulumi:"description"`
	// The raw Docker Compose content.
	DockerComposeRaw string `pulumi:"dockerComposeRaw"`
	// The Docker registry image name.
	DockerRegistryImageName string `pulumi:"dockerRegistryImageName"`
	// For Git-backed applications, the path to the Dockerfile relative to the repository root. For <span pulumi-lang-nodejs="`coolify.ApplicationDockerfile`" pulumi-lang-dotnet="`coolify.ApplicationDockerfile`" pulumi-lang-go="`ApplicationDockerfile`" pulumi-lang-python="`ApplicationDockerfile`" pulumi-lang-yaml="`coolify.ApplicationDockerfile`" pulumi-lang-java="`coolify.ApplicationDockerfile`" pulumi-lang-hcl="`coolify_application_dockerfile`">`coolify.ApplicationDockerfile`</span> resources, this contains the Dockerfile content (base64-encoded).
	DockerfileLocation string `pulumi:"dockerfileLocation"`
	// The fully qualified domain name of the application.
	Domains string `pulumi:"domains"`
	// The environment name of the application.
	EnvironmentName string `pulumi:"environmentName"`
	// The Git branch used by the application.
	GitBranch string `pulumi:"gitBranch"`
	// The Git repository URL of the application.
	GitRepository string `pulumi:"gitRepository"`
	// The install command.
	InstallCommand string `pulumi:"installCommand"`
	// Whether Coolify uses a consistent container name for this application. Coolify default is <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>. Set to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span> for apps that keep an exclusive file lock on a persistent volume (SQLite, DuckDB, LMDB, BoltDB). A fixed name makes Docker refuse a second container on the same mounts, so Coolify falls back to stop-then-start instead of a rolling update that would leave the new container unable to open the store while still reporting a successful deploy. Requires Coolify >= v4.3.0.
	IsConsistentContainerNameEnabled bool `pulumi:"isConsistentContainerNameEnabled"`
	// The maximum number of container restarts before Coolify stops the application.
	MaxRestartCount int `pulumi:"maxRestartCount"`
	// The name of the application.
	Name string `pulumi:"name"`
	// The exposed ports.
	PortsExposes string `pulumi:"portsExposes"`
	// The UUID of the project the application belongs to.
	ProjectUuid string `pulumi:"projectUuid"`
	// The UUID of the server the application is deployed on.
	ServerUuid string `pulumi:"serverUuid"`
	// The start command.
	StartCommand string `pulumi:"startCommand"`
	// The current status of the application (e.g., running, stopped, exited).
	Status string `pulumi:"status"`
	// The UUID of the application to look up.
	Uuid string `pulumi:"uuid"`
}

func LookupApplicationOutput(ctx *pulumi.Context, args LookupApplicationOutputArgs, opts ...pulumi.InvokeOption) LookupApplicationResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupApplicationResultOutput, error) {
			args := v.(LookupApplicationArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("coolify:index/getApplication:getApplication", args, LookupApplicationResultOutput{}, options).(LookupApplicationResultOutput), nil
		}).(LookupApplicationResultOutput)
}

// A collection of arguments for invoking getApplication.
type LookupApplicationOutputArgs struct {
	// The UUID of the application to look up.
	Uuid pulumi.StringInput `pulumi:"uuid"`
}

func (LookupApplicationOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupApplicationArgs)(nil)).Elem()
}

// A collection of values returned by getApplication.
type LookupApplicationResultOutput struct{ *pulumi.OutputState }

func (LookupApplicationResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupApplicationResult)(nil)).Elem()
}

func (o LookupApplicationResultOutput) ToLookupApplicationResultOutput() LookupApplicationResultOutput {
	return o
}

func (o LookupApplicationResultOutput) ToLookupApplicationResultOutputWithContext(ctx context.Context) LookupApplicationResultOutput {
	return o
}

// The build command.
func (o LookupApplicationResultOutput) BuildCommand() pulumi.StringOutput {
	return o.ApplyT(func(v LookupApplicationResult) string { return v.BuildCommand }).(pulumi.StringOutput)
}

// The build pack type used by the application.
func (o LookupApplicationResultOutput) BuildPack() pulumi.StringOutput {
	return o.ApplyT(func(v LookupApplicationResult) string { return v.BuildPack }).(pulumi.StringOutput)
}

// The description of the application.
func (o LookupApplicationResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupApplicationResult) string { return v.Description }).(pulumi.StringOutput)
}

// The raw Docker Compose content.
func (o LookupApplicationResultOutput) DockerComposeRaw() pulumi.StringOutput {
	return o.ApplyT(func(v LookupApplicationResult) string { return v.DockerComposeRaw }).(pulumi.StringOutput)
}

// The Docker registry image name.
func (o LookupApplicationResultOutput) DockerRegistryImageName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupApplicationResult) string { return v.DockerRegistryImageName }).(pulumi.StringOutput)
}

// For Git-backed applications, the path to the Dockerfile relative to the repository root. For <span pulumi-lang-nodejs="`coolify.ApplicationDockerfile`" pulumi-lang-dotnet="`coolify.ApplicationDockerfile`" pulumi-lang-go="`ApplicationDockerfile`" pulumi-lang-python="`ApplicationDockerfile`" pulumi-lang-yaml="`coolify.ApplicationDockerfile`" pulumi-lang-java="`coolify.ApplicationDockerfile`" pulumi-lang-hcl="`coolify_application_dockerfile`">`coolify.ApplicationDockerfile`</span> resources, this contains the Dockerfile content (base64-encoded).
func (o LookupApplicationResultOutput) DockerfileLocation() pulumi.StringOutput {
	return o.ApplyT(func(v LookupApplicationResult) string { return v.DockerfileLocation }).(pulumi.StringOutput)
}

// The fully qualified domain name of the application.
func (o LookupApplicationResultOutput) Domains() pulumi.StringOutput {
	return o.ApplyT(func(v LookupApplicationResult) string { return v.Domains }).(pulumi.StringOutput)
}

// The environment name of the application.
func (o LookupApplicationResultOutput) EnvironmentName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupApplicationResult) string { return v.EnvironmentName }).(pulumi.StringOutput)
}

// The Git branch used by the application.
func (o LookupApplicationResultOutput) GitBranch() pulumi.StringOutput {
	return o.ApplyT(func(v LookupApplicationResult) string { return v.GitBranch }).(pulumi.StringOutput)
}

// The Git repository URL of the application.
func (o LookupApplicationResultOutput) GitRepository() pulumi.StringOutput {
	return o.ApplyT(func(v LookupApplicationResult) string { return v.GitRepository }).(pulumi.StringOutput)
}

// The install command.
func (o LookupApplicationResultOutput) InstallCommand() pulumi.StringOutput {
	return o.ApplyT(func(v LookupApplicationResult) string { return v.InstallCommand }).(pulumi.StringOutput)
}

// Whether Coolify uses a consistent container name for this application. Coolify default is <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>. Set to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span> for apps that keep an exclusive file lock on a persistent volume (SQLite, DuckDB, LMDB, BoltDB). A fixed name makes Docker refuse a second container on the same mounts, so Coolify falls back to stop-then-start instead of a rolling update that would leave the new container unable to open the store while still reporting a successful deploy. Requires Coolify >= v4.3.0.
func (o LookupApplicationResultOutput) IsConsistentContainerNameEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupApplicationResult) bool { return v.IsConsistentContainerNameEnabled }).(pulumi.BoolOutput)
}

// The maximum number of container restarts before Coolify stops the application.
func (o LookupApplicationResultOutput) MaxRestartCount() pulumi.IntOutput {
	return o.ApplyT(func(v LookupApplicationResult) int { return v.MaxRestartCount }).(pulumi.IntOutput)
}

// The name of the application.
func (o LookupApplicationResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupApplicationResult) string { return v.Name }).(pulumi.StringOutput)
}

// The exposed ports.
func (o LookupApplicationResultOutput) PortsExposes() pulumi.StringOutput {
	return o.ApplyT(func(v LookupApplicationResult) string { return v.PortsExposes }).(pulumi.StringOutput)
}

// The UUID of the project the application belongs to.
func (o LookupApplicationResultOutput) ProjectUuid() pulumi.StringOutput {
	return o.ApplyT(func(v LookupApplicationResult) string { return v.ProjectUuid }).(pulumi.StringOutput)
}

// The UUID of the server the application is deployed on.
func (o LookupApplicationResultOutput) ServerUuid() pulumi.StringOutput {
	return o.ApplyT(func(v LookupApplicationResult) string { return v.ServerUuid }).(pulumi.StringOutput)
}

// The start command.
func (o LookupApplicationResultOutput) StartCommand() pulumi.StringOutput {
	return o.ApplyT(func(v LookupApplicationResult) string { return v.StartCommand }).(pulumi.StringOutput)
}

// The current status of the application (e.g., running, stopped, exited).
func (o LookupApplicationResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v LookupApplicationResult) string { return v.Status }).(pulumi.StringOutput)
}

// The UUID of the application to look up.
func (o LookupApplicationResultOutput) Uuid() pulumi.StringOutput {
	return o.ApplyT(func(v LookupApplicationResult) string { return v.Uuid }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupApplicationResultOutput{})
}
