// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package coolify

import (
	"context"
	"reflect"

	"github.com/mheers/pulumi-provider-coolify/sdk/go/coolify/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Use this data source to retrieve information about a Coolify database by UUID.
//
// ## Example Usage
//
// <!--Start PulumiCodeChooser -->
// ```go
// package main
//
// import (
//
//	"github.com/mheers/pulumi-provider-coolify/sdk/go/coolify"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := coolify.GetDatabase(ctx, &coolify.GetDatabaseArgs{
//				Uuid: "550e8400-e29b-41d4-a716-446655440001",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
// <!--End PulumiCodeChooser -->
func GetDatabase(ctx *pulumi.Context, args *GetDatabaseArgs, opts ...pulumi.InvokeOption) (*GetDatabaseResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetDatabaseResult
	err := ctx.Invoke("coolify:index/getDatabase:getDatabase", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getDatabase.
type GetDatabaseArgs struct {
	// The unique identifier of the database.
	Uuid string `pulumi:"uuid"`
}

// A collection of values returned by getDatabase.
type GetDatabaseResult struct {
	// A description of the database.
	Description string `pulumi:"description"`
	// Whether SSL/TLS is enabled for database connections.
	EnableSsl bool `pulumi:"enableSsl"`
	// The environment name.
	EnvironmentName string `pulumi:"environmentName"`
	// Whether the Docker health check probe is enabled.
	HealthCheckEnabled bool `pulumi:"healthCheckEnabled"`
	// Health check interval in seconds.
	HealthCheckInterval int `pulumi:"healthCheckInterval"`
	// Number of consecutive failures before unhealthy.
	HealthCheckRetries int `pulumi:"healthCheckRetries"`
	// Grace period in seconds before health checks count.
	HealthCheckStartPeriod int `pulumi:"healthCheckStartPeriod"`
	// Health check timeout in seconds.
	HealthCheckTimeout int `pulumi:"healthCheckTimeout"`
	// The Docker image used by the database.
	Image string `pulumi:"image"`
	// Internal connection URL for the database, accessible from other containers on the same server. Contains credentials; requires an API token with sensitive-data read permission.
	InternalDbUrl string `pulumi:"internalDbUrl"`
	// Whether timestamps are included in log output.
	IsIncludeTimestamps bool `pulumi:"isIncludeTimestamps"`
	// Whether log drain is enabled for this database.
	IsLogDrainEnabled bool `pulumi:"isLogDrainEnabled"`
	// Whether the database is publicly accessible.
	IsPublic bool `pulumi:"isPublic"`
	// The name of the database.
	Name string `pulumi:"name"`
	// The UUID of the project this database belongs to.
	ProjectUuid string `pulumi:"projectUuid"`
	// The public port for the database, if publicly accessible.
	PublicPort int `pulumi:"publicPort"`
	// The UUID of the server the database is deployed on.
	ServerUuid string `pulumi:"serverUuid"`
	// The SSL connection mode (e.g., <span pulumi-lang-nodejs="`require`" pulumi-lang-dotnet="`Require`" pulumi-lang-go="`require`" pulumi-lang-python="`require`" pulumi-lang-yaml="`require`" pulumi-lang-java="`require`" pulumi-lang-hcl="`require`">`require`</span>, `verify-full`). Empty when SSL is not enabled or not supported by the database type.
	SslMode string `pulumi:"sslMode"`
	// The current status of the database (e.g., running, exited).
	Status string `pulumi:"status"`
	// The type of the database (e.g., postgresql, mysql, redis).
	Type string `pulumi:"type"`
	// The unique identifier of the database.
	Uuid string `pulumi:"uuid"`
}

func GetDatabaseOutput(ctx *pulumi.Context, args GetDatabaseOutputArgs, opts ...pulumi.InvokeOption) GetDatabaseResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetDatabaseResultOutput, error) {
			args := v.(GetDatabaseArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("coolify:index/getDatabase:getDatabase", args, GetDatabaseResultOutput{}, options).(GetDatabaseResultOutput), nil
		}).(GetDatabaseResultOutput)
}

// A collection of arguments for invoking getDatabase.
type GetDatabaseOutputArgs struct {
	// The unique identifier of the database.
	Uuid pulumi.StringInput `pulumi:"uuid"`
}

func (GetDatabaseOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDatabaseArgs)(nil)).Elem()
}

// A collection of values returned by getDatabase.
type GetDatabaseResultOutput struct{ *pulumi.OutputState }

func (GetDatabaseResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDatabaseResult)(nil)).Elem()
}

func (o GetDatabaseResultOutput) ToGetDatabaseResultOutput() GetDatabaseResultOutput {
	return o
}

func (o GetDatabaseResultOutput) ToGetDatabaseResultOutputWithContext(ctx context.Context) GetDatabaseResultOutput {
	return o
}

// A description of the database.
func (o GetDatabaseResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v GetDatabaseResult) string { return v.Description }).(pulumi.StringOutput)
}

// Whether SSL/TLS is enabled for database connections.
func (o GetDatabaseResultOutput) EnableSsl() pulumi.BoolOutput {
	return o.ApplyT(func(v GetDatabaseResult) bool { return v.EnableSsl }).(pulumi.BoolOutput)
}

// The environment name.
func (o GetDatabaseResultOutput) EnvironmentName() pulumi.StringOutput {
	return o.ApplyT(func(v GetDatabaseResult) string { return v.EnvironmentName }).(pulumi.StringOutput)
}

// Whether the Docker health check probe is enabled.
func (o GetDatabaseResultOutput) HealthCheckEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v GetDatabaseResult) bool { return v.HealthCheckEnabled }).(pulumi.BoolOutput)
}

// Health check interval in seconds.
func (o GetDatabaseResultOutput) HealthCheckInterval() pulumi.IntOutput {
	return o.ApplyT(func(v GetDatabaseResult) int { return v.HealthCheckInterval }).(pulumi.IntOutput)
}

// Number of consecutive failures before unhealthy.
func (o GetDatabaseResultOutput) HealthCheckRetries() pulumi.IntOutput {
	return o.ApplyT(func(v GetDatabaseResult) int { return v.HealthCheckRetries }).(pulumi.IntOutput)
}

// Grace period in seconds before health checks count.
func (o GetDatabaseResultOutput) HealthCheckStartPeriod() pulumi.IntOutput {
	return o.ApplyT(func(v GetDatabaseResult) int { return v.HealthCheckStartPeriod }).(pulumi.IntOutput)
}

// Health check timeout in seconds.
func (o GetDatabaseResultOutput) HealthCheckTimeout() pulumi.IntOutput {
	return o.ApplyT(func(v GetDatabaseResult) int { return v.HealthCheckTimeout }).(pulumi.IntOutput)
}

// The Docker image used by the database.
func (o GetDatabaseResultOutput) Image() pulumi.StringOutput {
	return o.ApplyT(func(v GetDatabaseResult) string { return v.Image }).(pulumi.StringOutput)
}

// Internal connection URL for the database, accessible from other containers on the same server. Contains credentials; requires an API token with sensitive-data read permission.
func (o GetDatabaseResultOutput) InternalDbUrl() pulumi.StringOutput {
	return o.ApplyT(func(v GetDatabaseResult) string { return v.InternalDbUrl }).(pulumi.StringOutput)
}

// Whether timestamps are included in log output.
func (o GetDatabaseResultOutput) IsIncludeTimestamps() pulumi.BoolOutput {
	return o.ApplyT(func(v GetDatabaseResult) bool { return v.IsIncludeTimestamps }).(pulumi.BoolOutput)
}

// Whether log drain is enabled for this database.
func (o GetDatabaseResultOutput) IsLogDrainEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v GetDatabaseResult) bool { return v.IsLogDrainEnabled }).(pulumi.BoolOutput)
}

// Whether the database is publicly accessible.
func (o GetDatabaseResultOutput) IsPublic() pulumi.BoolOutput {
	return o.ApplyT(func(v GetDatabaseResult) bool { return v.IsPublic }).(pulumi.BoolOutput)
}

// The name of the database.
func (o GetDatabaseResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetDatabaseResult) string { return v.Name }).(pulumi.StringOutput)
}

// The UUID of the project this database belongs to.
func (o GetDatabaseResultOutput) ProjectUuid() pulumi.StringOutput {
	return o.ApplyT(func(v GetDatabaseResult) string { return v.ProjectUuid }).(pulumi.StringOutput)
}

// The public port for the database, if publicly accessible.
func (o GetDatabaseResultOutput) PublicPort() pulumi.IntOutput {
	return o.ApplyT(func(v GetDatabaseResult) int { return v.PublicPort }).(pulumi.IntOutput)
}

// The UUID of the server the database is deployed on.
func (o GetDatabaseResultOutput) ServerUuid() pulumi.StringOutput {
	return o.ApplyT(func(v GetDatabaseResult) string { return v.ServerUuid }).(pulumi.StringOutput)
}

// The SSL connection mode (e.g., <span pulumi-lang-nodejs="`require`" pulumi-lang-dotnet="`Require`" pulumi-lang-go="`require`" pulumi-lang-python="`require`" pulumi-lang-yaml="`require`" pulumi-lang-java="`require`" pulumi-lang-hcl="`require`">`require`</span>, `verify-full`). Empty when SSL is not enabled or not supported by the database type.
func (o GetDatabaseResultOutput) SslMode() pulumi.StringOutput {
	return o.ApplyT(func(v GetDatabaseResult) string { return v.SslMode }).(pulumi.StringOutput)
}

// The current status of the database (e.g., running, exited).
func (o GetDatabaseResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v GetDatabaseResult) string { return v.Status }).(pulumi.StringOutput)
}

// The type of the database (e.g., postgresql, mysql, redis).
func (o GetDatabaseResultOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v GetDatabaseResult) string { return v.Type }).(pulumi.StringOutput)
}

// The unique identifier of the database.
func (o GetDatabaseResultOutput) Uuid() pulumi.StringOutput {
	return o.ApplyT(func(v GetDatabaseResult) string { return v.Uuid }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetDatabaseResultOutput{})
}
