// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package coolify

import (
	"context"
	"reflect"

	"github.com/mheers/pulumi-provider-coolify/sdk/go/coolify/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Lists DigitalOcean droplet sizes for a cloud provider token. Requires Coolify >= v4.2.0.
//
// ## Example Usage
//
// <!--Start PulumiCodeChooser -->
// <!--End PulumiCodeChooser -->
func GetDigitaloceanSizes(ctx *pulumi.Context, args *GetDigitaloceanSizesArgs, opts ...pulumi.InvokeOption) (*GetDigitaloceanSizesResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetDigitaloceanSizesResult
	err := ctx.Invoke("coolify:index/getDigitaloceanSizes:getDigitaloceanSizes", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getDigitaloceanSizes.
type GetDigitaloceanSizesArgs struct {
	// The UUID of the DigitalOcean cloud provider token to use for listing sizes. Requires Coolify >= v4.2.0.
	CloudProviderTokenUuid string `pulumi:"cloudProviderTokenUuid"`
	// Filter results by field values. Multiple filters are ANDed together. Multiple values within a filter are ORed.
	Filters []GetDigitaloceanSizesFilter `pulumi:"filters"`
}

// A collection of values returned by getDigitaloceanSizes.
type GetDigitaloceanSizesResult struct {
	// The UUID of the DigitalOcean cloud provider token to use for listing sizes. Requires Coolify >= v4.2.0.
	CloudProviderTokenUuid string `pulumi:"cloudProviderTokenUuid"`
	// Filter results by field values. Multiple filters are ANDed together. Multiple values within a filter are ORed.
	Filters []GetDigitaloceanSizesFilter `pulumi:"filters"`
	// The list of DigitalOcean sizes.
	Sizes []GetDigitaloceanSizesSize `pulumi:"sizes"`
}

func GetDigitaloceanSizesOutput(ctx *pulumi.Context, args GetDigitaloceanSizesOutputArgs, opts ...pulumi.InvokeOption) GetDigitaloceanSizesResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetDigitaloceanSizesResultOutput, error) {
			args := v.(GetDigitaloceanSizesArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("coolify:index/getDigitaloceanSizes:getDigitaloceanSizes", args, GetDigitaloceanSizesResultOutput{}, options).(GetDigitaloceanSizesResultOutput), nil
		}).(GetDigitaloceanSizesResultOutput)
}

// A collection of arguments for invoking getDigitaloceanSizes.
type GetDigitaloceanSizesOutputArgs struct {
	// The UUID of the DigitalOcean cloud provider token to use for listing sizes. Requires Coolify >= v4.2.0.
	CloudProviderTokenUuid pulumi.StringInput `pulumi:"cloudProviderTokenUuid"`
	// Filter results by field values. Multiple filters are ANDed together. Multiple values within a filter are ORed.
	Filters GetDigitaloceanSizesFilterArrayInput `pulumi:"filters"`
}

func (GetDigitaloceanSizesOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDigitaloceanSizesArgs)(nil)).Elem()
}

// A collection of values returned by getDigitaloceanSizes.
type GetDigitaloceanSizesResultOutput struct{ *pulumi.OutputState }

func (GetDigitaloceanSizesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDigitaloceanSizesResult)(nil)).Elem()
}

func (o GetDigitaloceanSizesResultOutput) ToGetDigitaloceanSizesResultOutput() GetDigitaloceanSizesResultOutput {
	return o
}

func (o GetDigitaloceanSizesResultOutput) ToGetDigitaloceanSizesResultOutputWithContext(ctx context.Context) GetDigitaloceanSizesResultOutput {
	return o
}

// The UUID of the DigitalOcean cloud provider token to use for listing sizes. Requires Coolify >= v4.2.0.
func (o GetDigitaloceanSizesResultOutput) CloudProviderTokenUuid() pulumi.StringOutput {
	return o.ApplyT(func(v GetDigitaloceanSizesResult) string { return v.CloudProviderTokenUuid }).(pulumi.StringOutput)
}

// Filter results by field values. Multiple filters are ANDed together. Multiple values within a filter are ORed.
func (o GetDigitaloceanSizesResultOutput) Filters() GetDigitaloceanSizesFilterArrayOutput {
	return o.ApplyT(func(v GetDigitaloceanSizesResult) []GetDigitaloceanSizesFilter { return v.Filters }).(GetDigitaloceanSizesFilterArrayOutput)
}

// The list of DigitalOcean sizes.
func (o GetDigitaloceanSizesResultOutput) Sizes() GetDigitaloceanSizesSizeArrayOutput {
	return o.ApplyT(func(v GetDigitaloceanSizesResult) []GetDigitaloceanSizesSize { return v.Sizes }).(GetDigitaloceanSizesSizeArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetDigitaloceanSizesResultOutput{})
}
