// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package coolify

import (
	"context"
	"reflect"

	"github.com/mheers/pulumi-provider-coolify/sdk/go/coolify/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Use this data source to list all Coolify GitHub App integrations.
//
// ## Example Usage
//
// <!--Start PulumiCodeChooser -->
// <!--End PulumiCodeChooser -->
func GetGithubApps(ctx *pulumi.Context, args *GetGithubAppsArgs, opts ...pulumi.InvokeOption) (*GetGithubAppsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetGithubAppsResult
	err := ctx.Invoke("coolify:index/getGithubApps:getGithubApps", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getGithubApps.
type GetGithubAppsArgs struct {
	// Filter results by field values. Multiple filters are ANDed together. Multiple values within a filter are ORed.
	Filters []GetGithubAppsFilter `pulumi:"filters"`
}

// A collection of values returned by getGithubApps.
type GetGithubAppsResult struct {
	// Filter results by field values. Multiple filters are ANDed together. Multiple values within a filter are ORed.
	Filters []GetGithubAppsFilter `pulumi:"filters"`
	// The list of GitHub Apps.
	GithubApps []GetGithubAppsGithubApp `pulumi:"githubApps"`
}

func GetGithubAppsOutput(ctx *pulumi.Context, args GetGithubAppsOutputArgs, opts ...pulumi.InvokeOption) GetGithubAppsResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetGithubAppsResultOutput, error) {
			args := v.(GetGithubAppsArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("coolify:index/getGithubApps:getGithubApps", args, GetGithubAppsResultOutput{}, options).(GetGithubAppsResultOutput), nil
		}).(GetGithubAppsResultOutput)
}

// A collection of arguments for invoking getGithubApps.
type GetGithubAppsOutputArgs struct {
	// Filter results by field values. Multiple filters are ANDed together. Multiple values within a filter are ORed.
	Filters GetGithubAppsFilterArrayInput `pulumi:"filters"`
}

func (GetGithubAppsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetGithubAppsArgs)(nil)).Elem()
}

// A collection of values returned by getGithubApps.
type GetGithubAppsResultOutput struct{ *pulumi.OutputState }

func (GetGithubAppsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetGithubAppsResult)(nil)).Elem()
}

func (o GetGithubAppsResultOutput) ToGetGithubAppsResultOutput() GetGithubAppsResultOutput {
	return o
}

func (o GetGithubAppsResultOutput) ToGetGithubAppsResultOutputWithContext(ctx context.Context) GetGithubAppsResultOutput {
	return o
}

// Filter results by field values. Multiple filters are ANDed together. Multiple values within a filter are ORed.
func (o GetGithubAppsResultOutput) Filters() GetGithubAppsFilterArrayOutput {
	return o.ApplyT(func(v GetGithubAppsResult) []GetGithubAppsFilter { return v.Filters }).(GetGithubAppsFilterArrayOutput)
}

// The list of GitHub Apps.
func (o GetGithubAppsResultOutput) GithubApps() GetGithubAppsGithubAppArrayOutput {
	return o.ApplyT(func(v GetGithubAppsResult) []GetGithubAppsGithubApp { return v.GithubApps }).(GetGithubAppsGithubAppArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetGithubAppsResultOutput{})
}
