// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package coolify

import (
	"context"
	"reflect"

	"github.com/mheers/pulumi-provider-coolify/sdk/go/coolify/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Retrieves the health status of the connected Coolify instance.
//
// ## Example Usage
//
// <!--Start PulumiCodeChooser -->
// ```go
// package main
//
// import (
//
//	"github.com/mheers/pulumi-provider-coolify/sdk/go/coolify"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			current, err := coolify.GetHealth(ctx, map[string]interface{}{}, nil)
//			if err != nil {
//				return err
//			}
//			ctx.Export("coolifyHealthStatus", current.Status)
//			return nil
//		})
//	}
//
// ```
// <!--End PulumiCodeChooser -->
func GetHealth(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*GetHealthResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetHealthResult
	err := ctx.Invoke("coolify:index/getHealth:getHealth", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getHealth.
type GetHealthResult struct {
	// The health status of the Coolify instance.
	Status string `pulumi:"status"`
}

func GetHealthOutput(ctx *pulumi.Context, opts ...pulumi.InvokeOption) GetHealthResultOutput {
	return pulumi.ToOutput(0).ApplyT(func(int) (GetHealthResultOutput, error) {
		options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
		return ctx.InvokeOutput("coolify:index/getHealth:getHealth", nil, GetHealthResultOutput{}, options).(GetHealthResultOutput), nil
	}).(GetHealthResultOutput)
}

// A collection of values returned by getHealth.
type GetHealthResultOutput struct{ *pulumi.OutputState }

func (GetHealthResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetHealthResult)(nil)).Elem()
}

func (o GetHealthResultOutput) ToGetHealthResultOutput() GetHealthResultOutput {
	return o
}

func (o GetHealthResultOutput) ToGetHealthResultOutputWithContext(ctx context.Context) GetHealthResultOutput {
	return o
}

// The health status of the Coolify instance.
func (o GetHealthResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v GetHealthResult) string { return v.Status }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetHealthResultOutput{})
}
