// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package coolify

import (
	"context"
	"reflect"

	"github.com/mheers/pulumi-provider-coolify/sdk/go/coolify/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Reads the current team's Discord notification settings. This is a team-scoped singleton (selected by the API token). Requires Coolify >= v4.3.0.
//
// ## Example Usage
//
// <!--Start PulumiCodeChooser -->
// ```go
// package main
//
// import (
//
//	"github.com/mheers/pulumi-provider-coolify/sdk/go/coolify"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			current, err := coolify.GetNotificationDiscord(ctx, map[string]interface{}{}, nil)
//			if err != nil {
//				return err
//			}
//			ctx.Export("notifications", current.Enabled)
//			return nil
//		})
//	}
//
// ```
// <!--End PulumiCodeChooser -->
func LookupNotificationDiscord(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*LookupNotificationDiscordResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupNotificationDiscordResult
	err := ctx.Invoke("coolify:index/getNotificationDiscord:getNotificationDiscord", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getNotificationDiscord.
type LookupNotificationDiscordResult struct {
	// Whether Discord notifications are sent for backup failure events.
	BackupFailure bool `pulumi:"backupFailure"`
	// Whether Discord notifications are sent for backup success events.
	BackupSuccess bool `pulumi:"backupSuccess"`
	// Whether Discord notifications are sent for deployment failure events.
	DeploymentFailure bool `pulumi:"deploymentFailure"`
	// Whether Discord notifications are sent for deployment success events.
	DeploymentSuccess bool `pulumi:"deploymentSuccess"`
	// Whether Discord notifications are sent for Docker cleanup failure events.
	DockerCleanupFailure bool `pulumi:"dockerCleanupFailure"`
	// Whether Discord notifications are sent for Docker cleanup success events.
	DockerCleanupSuccess bool `pulumi:"dockerCleanupSuccess"`
	// Whether Discord notifications are enabled for the team.
	Enabled bool `pulumi:"enabled"`
	// Identifier. Always <span pulumi-lang-nodejs="`current`" pulumi-lang-dotnet="`Current`" pulumi-lang-go="`current`" pulumi-lang-python="`current`" pulumi-lang-yaml="`current`" pulumi-lang-java="`current`" pulumi-lang-hcl="`current`">`current`</span> (team is implied by the API token).
	Id string `pulumi:"id"`
	// Whether Discord @here / role pings are enabled.
	PingEnabled bool `pulumi:"pingEnabled"`
	// Whether Discord notifications are sent for scheduled task failure events.
	ScheduledTaskFailure bool `pulumi:"scheduledTaskFailure"`
	// Whether Discord notifications are sent for scheduled task success events.
	ScheduledTaskSuccess bool `pulumi:"scheduledTaskSuccess"`
	// Whether Discord notifications are sent for server disk usage events.
	ServerDiskUsage bool `pulumi:"serverDiskUsage"`
	// Whether Discord notifications are sent for server patch events.
	ServerPatch bool `pulumi:"serverPatch"`
	// Whether Discord notifications are sent for server reachable events.
	ServerReachable bool `pulumi:"serverReachable"`
	// Whether Discord notifications are sent for server unreachable events.
	ServerUnreachable bool `pulumi:"serverUnreachable"`
	// Whether Discord notifications are sent for status change events.
	StatusChange bool `pulumi:"statusChange"`
	// Whether Discord notifications are sent for Traefik outdated events.
	TraefikOutdated bool `pulumi:"traefikOutdated"`
	// Discord webhook URL. Coolify may omit this unless the API token can read sensitive fields (`read:sensitive` or root).
	WebhookUrl string `pulumi:"webhookUrl"`
}

func LookupNotificationDiscordOutput(ctx *pulumi.Context, opts ...pulumi.InvokeOption) LookupNotificationDiscordResultOutput {
	return pulumi.ToOutput(0).ApplyT(func(int) (LookupNotificationDiscordResultOutput, error) {
		options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
		return ctx.InvokeOutput("coolify:index/getNotificationDiscord:getNotificationDiscord", nil, LookupNotificationDiscordResultOutput{}, options).(LookupNotificationDiscordResultOutput), nil
	}).(LookupNotificationDiscordResultOutput)
}

// A collection of values returned by getNotificationDiscord.
type LookupNotificationDiscordResultOutput struct{ *pulumi.OutputState }

func (LookupNotificationDiscordResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNotificationDiscordResult)(nil)).Elem()
}

func (o LookupNotificationDiscordResultOutput) ToLookupNotificationDiscordResultOutput() LookupNotificationDiscordResultOutput {
	return o
}

func (o LookupNotificationDiscordResultOutput) ToLookupNotificationDiscordResultOutputWithContext(ctx context.Context) LookupNotificationDiscordResultOutput {
	return o
}

// Whether Discord notifications are sent for backup failure events.
func (o LookupNotificationDiscordResultOutput) BackupFailure() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupNotificationDiscordResult) bool { return v.BackupFailure }).(pulumi.BoolOutput)
}

// Whether Discord notifications are sent for backup success events.
func (o LookupNotificationDiscordResultOutput) BackupSuccess() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupNotificationDiscordResult) bool { return v.BackupSuccess }).(pulumi.BoolOutput)
}

// Whether Discord notifications are sent for deployment failure events.
func (o LookupNotificationDiscordResultOutput) DeploymentFailure() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupNotificationDiscordResult) bool { return v.DeploymentFailure }).(pulumi.BoolOutput)
}

// Whether Discord notifications are sent for deployment success events.
func (o LookupNotificationDiscordResultOutput) DeploymentSuccess() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupNotificationDiscordResult) bool { return v.DeploymentSuccess }).(pulumi.BoolOutput)
}

// Whether Discord notifications are sent for Docker cleanup failure events.
func (o LookupNotificationDiscordResultOutput) DockerCleanupFailure() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupNotificationDiscordResult) bool { return v.DockerCleanupFailure }).(pulumi.BoolOutput)
}

// Whether Discord notifications are sent for Docker cleanup success events.
func (o LookupNotificationDiscordResultOutput) DockerCleanupSuccess() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupNotificationDiscordResult) bool { return v.DockerCleanupSuccess }).(pulumi.BoolOutput)
}

// Whether Discord notifications are enabled for the team.
func (o LookupNotificationDiscordResultOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupNotificationDiscordResult) bool { return v.Enabled }).(pulumi.BoolOutput)
}

// Identifier. Always <span pulumi-lang-nodejs="`current`" pulumi-lang-dotnet="`Current`" pulumi-lang-go="`current`" pulumi-lang-python="`current`" pulumi-lang-yaml="`current`" pulumi-lang-java="`current`" pulumi-lang-hcl="`current`">`current`</span> (team is implied by the API token).
func (o LookupNotificationDiscordResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNotificationDiscordResult) string { return v.Id }).(pulumi.StringOutput)
}

// Whether Discord @here / role pings are enabled.
func (o LookupNotificationDiscordResultOutput) PingEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupNotificationDiscordResult) bool { return v.PingEnabled }).(pulumi.BoolOutput)
}

// Whether Discord notifications are sent for scheduled task failure events.
func (o LookupNotificationDiscordResultOutput) ScheduledTaskFailure() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupNotificationDiscordResult) bool { return v.ScheduledTaskFailure }).(pulumi.BoolOutput)
}

// Whether Discord notifications are sent for scheduled task success events.
func (o LookupNotificationDiscordResultOutput) ScheduledTaskSuccess() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupNotificationDiscordResult) bool { return v.ScheduledTaskSuccess }).(pulumi.BoolOutput)
}

// Whether Discord notifications are sent for server disk usage events.
func (o LookupNotificationDiscordResultOutput) ServerDiskUsage() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupNotificationDiscordResult) bool { return v.ServerDiskUsage }).(pulumi.BoolOutput)
}

// Whether Discord notifications are sent for server patch events.
func (o LookupNotificationDiscordResultOutput) ServerPatch() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupNotificationDiscordResult) bool { return v.ServerPatch }).(pulumi.BoolOutput)
}

// Whether Discord notifications are sent for server reachable events.
func (o LookupNotificationDiscordResultOutput) ServerReachable() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupNotificationDiscordResult) bool { return v.ServerReachable }).(pulumi.BoolOutput)
}

// Whether Discord notifications are sent for server unreachable events.
func (o LookupNotificationDiscordResultOutput) ServerUnreachable() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupNotificationDiscordResult) bool { return v.ServerUnreachable }).(pulumi.BoolOutput)
}

// Whether Discord notifications are sent for status change events.
func (o LookupNotificationDiscordResultOutput) StatusChange() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupNotificationDiscordResult) bool { return v.StatusChange }).(pulumi.BoolOutput)
}

// Whether Discord notifications are sent for Traefik outdated events.
func (o LookupNotificationDiscordResultOutput) TraefikOutdated() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupNotificationDiscordResult) bool { return v.TraefikOutdated }).(pulumi.BoolOutput)
}

// Discord webhook URL. Coolify may omit this unless the API token can read sensitive fields (`read:sensitive` or root).
func (o LookupNotificationDiscordResultOutput) WebhookUrl() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNotificationDiscordResult) string { return v.WebhookUrl }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupNotificationDiscordResultOutput{})
}
