// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package coolify

import (
	"context"
	"reflect"

	"github.com/mheers/pulumi-provider-coolify/sdk/go/coolify/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Use this data source to list all Coolify private keys.
//
// ## Example Usage
//
// <!--Start PulumiCodeChooser -->
// <!--End PulumiCodeChooser -->
func GetPrivateKeys(ctx *pulumi.Context, args *GetPrivateKeysArgs, opts ...pulumi.InvokeOption) (*GetPrivateKeysResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetPrivateKeysResult
	err := ctx.Invoke("coolify:index/getPrivateKeys:getPrivateKeys", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getPrivateKeys.
type GetPrivateKeysArgs struct {
	// Filter results by field values. Multiple filters are ANDed together. Multiple values within a filter are ORed.
	Filters []GetPrivateKeysFilter `pulumi:"filters"`
}

// A collection of values returned by getPrivateKeys.
type GetPrivateKeysResult struct {
	// Filter results by field values. Multiple filters are ANDed together. Multiple values within a filter are ORed.
	Filters []GetPrivateKeysFilter `pulumi:"filters"`
	// The list of private keys.
	PrivateKeys []GetPrivateKeysPrivateKey `pulumi:"privateKeys"`
}

func GetPrivateKeysOutput(ctx *pulumi.Context, args GetPrivateKeysOutputArgs, opts ...pulumi.InvokeOption) GetPrivateKeysResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetPrivateKeysResultOutput, error) {
			args := v.(GetPrivateKeysArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("coolify:index/getPrivateKeys:getPrivateKeys", args, GetPrivateKeysResultOutput{}, options).(GetPrivateKeysResultOutput), nil
		}).(GetPrivateKeysResultOutput)
}

// A collection of arguments for invoking getPrivateKeys.
type GetPrivateKeysOutputArgs struct {
	// Filter results by field values. Multiple filters are ANDed together. Multiple values within a filter are ORed.
	Filters GetPrivateKeysFilterArrayInput `pulumi:"filters"`
}

func (GetPrivateKeysOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPrivateKeysArgs)(nil)).Elem()
}

// A collection of values returned by getPrivateKeys.
type GetPrivateKeysResultOutput struct{ *pulumi.OutputState }

func (GetPrivateKeysResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPrivateKeysResult)(nil)).Elem()
}

func (o GetPrivateKeysResultOutput) ToGetPrivateKeysResultOutput() GetPrivateKeysResultOutput {
	return o
}

func (o GetPrivateKeysResultOutput) ToGetPrivateKeysResultOutputWithContext(ctx context.Context) GetPrivateKeysResultOutput {
	return o
}

// Filter results by field values. Multiple filters are ANDed together. Multiple values within a filter are ORed.
func (o GetPrivateKeysResultOutput) Filters() GetPrivateKeysFilterArrayOutput {
	return o.ApplyT(func(v GetPrivateKeysResult) []GetPrivateKeysFilter { return v.Filters }).(GetPrivateKeysFilterArrayOutput)
}

// The list of private keys.
func (o GetPrivateKeysResultOutput) PrivateKeys() GetPrivateKeysPrivateKeyArrayOutput {
	return o.ApplyT(func(v GetPrivateKeysResult) []GetPrivateKeysPrivateKey { return v.PrivateKeys }).(GetPrivateKeysPrivateKeyArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetPrivateKeysResultOutput{})
}
