// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package coolify

import (
	"context"
	"reflect"

	"github.com/mheers/pulumi-provider-coolify/sdk/go/coolify/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Retrieves information about a Coolify private key.
//
// ## Example Usage
//
// <!--Start PulumiCodeChooser -->
// ```go
// package main
//
// import (
//
//	"github.com/mheers/pulumi-provider-coolify/sdk/go/coolify"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			example, err := coolify.GetPrivateKey(ctx, &coolify.LookupPrivateKeyArgs{
//				Uuid: "550e8400-e29b-41d4-a716-446655440003",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			ctx.Export("privateKeyPublicKey", example.PublicKey)
//			ctx.Export("privateKeyFingerprint", example.Fingerprint)
//			return nil
//		})
//	}
//
// ```
// <!--End PulumiCodeChooser -->
func LookupPrivateKey(ctx *pulumi.Context, args *LookupPrivateKeyArgs, opts ...pulumi.InvokeOption) (*LookupPrivateKeyResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupPrivateKeyResult
	err := ctx.Invoke("coolify:index/getPrivateKey:getPrivateKey", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getPrivateKey.
type LookupPrivateKeyArgs struct {
	// The unique identifier of the private key.
	Uuid string `pulumi:"uuid"`
}

// A collection of values returned by getPrivateKey.
type LookupPrivateKeyResult struct {
	// A description of the private key.
	Description string `pulumi:"description"`
	// The fingerprint of the private key.
	Fingerprint string `pulumi:"fingerprint"`
	// Whether this key is used for Git operations.
	IsGitRelated bool `pulumi:"isGitRelated"`
	// The name of the private key.
	Name string `pulumi:"name"`
	// The PEM-encoded private key content. Requires an API token with <span pulumi-lang-nodejs="`root`" pulumi-lang-dotnet="`Root`" pulumi-lang-go="`root`" pulumi-lang-python="`root`" pulumi-lang-yaml="`root`" pulumi-lang-java="`root`" pulumi-lang-hcl="`root`">`root`</span> or `read:sensitive` permission; otherwise Coolify hides this value.
	PrivateKey string `pulumi:"privateKey"`
	// The public key derived from the private key.
	PublicKey string `pulumi:"publicKey"`
	// The unique identifier of the private key.
	Uuid string `pulumi:"uuid"`
}

func LookupPrivateKeyOutput(ctx *pulumi.Context, args LookupPrivateKeyOutputArgs, opts ...pulumi.InvokeOption) LookupPrivateKeyResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupPrivateKeyResultOutput, error) {
			args := v.(LookupPrivateKeyArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("coolify:index/getPrivateKey:getPrivateKey", args, LookupPrivateKeyResultOutput{}, options).(LookupPrivateKeyResultOutput), nil
		}).(LookupPrivateKeyResultOutput)
}

// A collection of arguments for invoking getPrivateKey.
type LookupPrivateKeyOutputArgs struct {
	// The unique identifier of the private key.
	Uuid pulumi.StringInput `pulumi:"uuid"`
}

func (LookupPrivateKeyOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupPrivateKeyArgs)(nil)).Elem()
}

// A collection of values returned by getPrivateKey.
type LookupPrivateKeyResultOutput struct{ *pulumi.OutputState }

func (LookupPrivateKeyResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupPrivateKeyResult)(nil)).Elem()
}

func (o LookupPrivateKeyResultOutput) ToLookupPrivateKeyResultOutput() LookupPrivateKeyResultOutput {
	return o
}

func (o LookupPrivateKeyResultOutput) ToLookupPrivateKeyResultOutputWithContext(ctx context.Context) LookupPrivateKeyResultOutput {
	return o
}

// A description of the private key.
func (o LookupPrivateKeyResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPrivateKeyResult) string { return v.Description }).(pulumi.StringOutput)
}

// The fingerprint of the private key.
func (o LookupPrivateKeyResultOutput) Fingerprint() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPrivateKeyResult) string { return v.Fingerprint }).(pulumi.StringOutput)
}

// Whether this key is used for Git operations.
func (o LookupPrivateKeyResultOutput) IsGitRelated() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupPrivateKeyResult) bool { return v.IsGitRelated }).(pulumi.BoolOutput)
}

// The name of the private key.
func (o LookupPrivateKeyResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPrivateKeyResult) string { return v.Name }).(pulumi.StringOutput)
}

// The PEM-encoded private key content. Requires an API token with <span pulumi-lang-nodejs="`root`" pulumi-lang-dotnet="`Root`" pulumi-lang-go="`root`" pulumi-lang-python="`root`" pulumi-lang-yaml="`root`" pulumi-lang-java="`root`" pulumi-lang-hcl="`root`">`root`</span> or `read:sensitive` permission; otherwise Coolify hides this value.
func (o LookupPrivateKeyResultOutput) PrivateKey() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPrivateKeyResult) string { return v.PrivateKey }).(pulumi.StringOutput)
}

// The public key derived from the private key.
func (o LookupPrivateKeyResultOutput) PublicKey() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPrivateKeyResult) string { return v.PublicKey }).(pulumi.StringOutput)
}

// The unique identifier of the private key.
func (o LookupPrivateKeyResultOutput) Uuid() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPrivateKeyResult) string { return v.Uuid }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupPrivateKeyResultOutput{})
}
