// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package coolify

import (
	"context"
	"reflect"

	"github.com/mheers/pulumi-provider-coolify/sdk/go/coolify/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Use this data source to list all Coolify resources.
//
// ## Example Usage
//
// <!--Start PulumiCodeChooser -->
// <!--End PulumiCodeChooser -->
func GetResources(ctx *pulumi.Context, args *GetResourcesArgs, opts ...pulumi.InvokeOption) (*GetResourcesResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetResourcesResult
	err := ctx.Invoke("coolify:index/getResources:getResources", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getResources.
type GetResourcesArgs struct {
	// Filter results by field values. Multiple filters are ANDed together. Multiple values within a filter are ORed.
	Filters []GetResourcesFilter `pulumi:"filters"`
}

// A collection of values returned by getResources.
type GetResourcesResult struct {
	// Filter results by field values. Multiple filters are ANDed together. Multiple values within a filter are ORed.
	Filters []GetResourcesFilter `pulumi:"filters"`
	// The list of resources.
	Resources []GetResourcesResource `pulumi:"resources"`
}

func GetResourcesOutput(ctx *pulumi.Context, args GetResourcesOutputArgs, opts ...pulumi.InvokeOption) GetResourcesResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetResourcesResultOutput, error) {
			args := v.(GetResourcesArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("coolify:index/getResources:getResources", args, GetResourcesResultOutput{}, options).(GetResourcesResultOutput), nil
		}).(GetResourcesResultOutput)
}

// A collection of arguments for invoking getResources.
type GetResourcesOutputArgs struct {
	// Filter results by field values. Multiple filters are ANDed together. Multiple values within a filter are ORed.
	Filters GetResourcesFilterArrayInput `pulumi:"filters"`
}

func (GetResourcesOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetResourcesArgs)(nil)).Elem()
}

// A collection of values returned by getResources.
type GetResourcesResultOutput struct{ *pulumi.OutputState }

func (GetResourcesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetResourcesResult)(nil)).Elem()
}

func (o GetResourcesResultOutput) ToGetResourcesResultOutput() GetResourcesResultOutput {
	return o
}

func (o GetResourcesResultOutput) ToGetResourcesResultOutputWithContext(ctx context.Context) GetResourcesResultOutput {
	return o
}

// Filter results by field values. Multiple filters are ANDed together. Multiple values within a filter are ORed.
func (o GetResourcesResultOutput) Filters() GetResourcesFilterArrayOutput {
	return o.ApplyT(func(v GetResourcesResult) []GetResourcesFilter { return v.Filters }).(GetResourcesFilterArrayOutput)
}

// The list of resources.
func (o GetResourcesResultOutput) Resources() GetResourcesResourceArrayOutput {
	return o.ApplyT(func(v GetResourcesResult) []GetResourcesResource { return v.Resources }).(GetResourcesResourceArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetResourcesResultOutput{})
}
