// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package coolify

import (
	"context"
	"reflect"

	"github.com/mheers/pulumi-provider-coolify/sdk/go/coolify/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Validates the connectivity of a Coolify server.
//
// ## Example Usage
//
// <!--Start PulumiCodeChooser -->
// ```go
// package main
//
// import (
//
//	"github.com/mheers/pulumi-provider-coolify/sdk/go/coolify"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			example, err := coolify.GetServerValidation(ctx, &coolify.GetServerValidationArgs{
//				Uuid: "550e8400-e29b-41d4-a716-446655440005",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			ctx.Export("serverValid", example.Valid)
//			ctx.Export("serverMessage", example.Message)
//			return nil
//		})
//	}
//
// ```
// <!--End PulumiCodeChooser -->
func GetServerValidation(ctx *pulumi.Context, args *GetServerValidationArgs, opts ...pulumi.InvokeOption) (*GetServerValidationResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetServerValidationResult
	err := ctx.Invoke("coolify:index/getServerValidation:getServerValidation", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getServerValidation.
type GetServerValidationArgs struct {
	// The UUID of the server to validate.
	Uuid string `pulumi:"uuid"`
}

// A collection of values returned by getServerValidation.
type GetServerValidationResult struct {
	// A message describing the validation result.
	Message string `pulumi:"message"`
	// The UUID of the server to validate.
	Uuid string `pulumi:"uuid"`
	// Whether the server connectivity check passed.
	Valid bool `pulumi:"valid"`
}

func GetServerValidationOutput(ctx *pulumi.Context, args GetServerValidationOutputArgs, opts ...pulumi.InvokeOption) GetServerValidationResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetServerValidationResultOutput, error) {
			args := v.(GetServerValidationArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("coolify:index/getServerValidation:getServerValidation", args, GetServerValidationResultOutput{}, options).(GetServerValidationResultOutput), nil
		}).(GetServerValidationResultOutput)
}

// A collection of arguments for invoking getServerValidation.
type GetServerValidationOutputArgs struct {
	// The UUID of the server to validate.
	Uuid pulumi.StringInput `pulumi:"uuid"`
}

func (GetServerValidationOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetServerValidationArgs)(nil)).Elem()
}

// A collection of values returned by getServerValidation.
type GetServerValidationResultOutput struct{ *pulumi.OutputState }

func (GetServerValidationResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetServerValidationResult)(nil)).Elem()
}

func (o GetServerValidationResultOutput) ToGetServerValidationResultOutput() GetServerValidationResultOutput {
	return o
}

func (o GetServerValidationResultOutput) ToGetServerValidationResultOutputWithContext(ctx context.Context) GetServerValidationResultOutput {
	return o
}

// A message describing the validation result.
func (o GetServerValidationResultOutput) Message() pulumi.StringOutput {
	return o.ApplyT(func(v GetServerValidationResult) string { return v.Message }).(pulumi.StringOutput)
}

// The UUID of the server to validate.
func (o GetServerValidationResultOutput) Uuid() pulumi.StringOutput {
	return o.ApplyT(func(v GetServerValidationResult) string { return v.Uuid }).(pulumi.StringOutput)
}

// Whether the server connectivity check passed.
func (o GetServerValidationResultOutput) Valid() pulumi.BoolOutput {
	return o.ApplyT(func(v GetServerValidationResult) bool { return v.Valid }).(pulumi.BoolOutput)
}

func init() {
	pulumi.RegisterOutputType(GetServerValidationResultOutput{})
}
