// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package coolify

import (
	"context"
	"reflect"

	"github.com/mheers/pulumi-provider-coolify/sdk/go/coolify/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Use this data source to retrieve information about a single Coolify S3 storage by its UUID. Requires Coolify >= v4.3.0.
//
// ## Example Usage
//
// <!--Start PulumiCodeChooser -->
// ```go
// package main
//
// import (
//
//	"github.com/mheers/pulumi-provider-coolify/sdk/go/coolify"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := coolify.GetS3Storage(ctx, &coolify.LookupS3StorageArgs{
//				Uuid: "550e8400-e29b-41d4-a716-446655440004",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
// <!--End PulumiCodeChooser -->
func LookupS3Storage(ctx *pulumi.Context, args *LookupS3StorageArgs, opts ...pulumi.InvokeOption) (*LookupS3StorageResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupS3StorageResult
	err := ctx.Invoke("coolify:index/getS3Storage:getS3Storage", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getS3Storage.
type LookupS3StorageArgs struct {
	// The unique identifier of the S3 storage to look up.
	Uuid string `pulumi:"uuid"`
}

// A collection of values returned by getS3Storage.
type LookupS3StorageResult struct {
	// S3 bucket name.
	Bucket string `pulumi:"bucket"`
	// Description of the S3 storage.
	Description string `pulumi:"description"`
	// S3-compatible endpoint URL.
	Endpoint string `pulumi:"endpoint"`
	// Whether Coolify marks this storage as usable.
	IsUsable bool `pulumi:"isUsable"`
	// A friendly name for the S3 storage.
	Name string `pulumi:"name"`
	// S3 region.
	Region string `pulumi:"region"`
	// The unique identifier of the S3 storage to look up.
	Uuid string `pulumi:"uuid"`
}

func LookupS3StorageOutput(ctx *pulumi.Context, args LookupS3StorageOutputArgs, opts ...pulumi.InvokeOption) LookupS3StorageResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupS3StorageResultOutput, error) {
			args := v.(LookupS3StorageArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("coolify:index/getS3Storage:getS3Storage", args, LookupS3StorageResultOutput{}, options).(LookupS3StorageResultOutput), nil
		}).(LookupS3StorageResultOutput)
}

// A collection of arguments for invoking getS3Storage.
type LookupS3StorageOutputArgs struct {
	// The unique identifier of the S3 storage to look up.
	Uuid pulumi.StringInput `pulumi:"uuid"`
}

func (LookupS3StorageOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupS3StorageArgs)(nil)).Elem()
}

// A collection of values returned by getS3Storage.
type LookupS3StorageResultOutput struct{ *pulumi.OutputState }

func (LookupS3StorageResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupS3StorageResult)(nil)).Elem()
}

func (o LookupS3StorageResultOutput) ToLookupS3StorageResultOutput() LookupS3StorageResultOutput {
	return o
}

func (o LookupS3StorageResultOutput) ToLookupS3StorageResultOutputWithContext(ctx context.Context) LookupS3StorageResultOutput {
	return o
}

// S3 bucket name.
func (o LookupS3StorageResultOutput) Bucket() pulumi.StringOutput {
	return o.ApplyT(func(v LookupS3StorageResult) string { return v.Bucket }).(pulumi.StringOutput)
}

// Description of the S3 storage.
func (o LookupS3StorageResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupS3StorageResult) string { return v.Description }).(pulumi.StringOutput)
}

// S3-compatible endpoint URL.
func (o LookupS3StorageResultOutput) Endpoint() pulumi.StringOutput {
	return o.ApplyT(func(v LookupS3StorageResult) string { return v.Endpoint }).(pulumi.StringOutput)
}

// Whether Coolify marks this storage as usable.
func (o LookupS3StorageResultOutput) IsUsable() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupS3StorageResult) bool { return v.IsUsable }).(pulumi.BoolOutput)
}

// A friendly name for the S3 storage.
func (o LookupS3StorageResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupS3StorageResult) string { return v.Name }).(pulumi.StringOutput)
}

// S3 region.
func (o LookupS3StorageResultOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v LookupS3StorageResult) string { return v.Region }).(pulumi.StringOutput)
}

// The unique identifier of the S3 storage to look up.
func (o LookupS3StorageResultOutput) Uuid() pulumi.StringOutput {
	return o.ApplyT(func(v LookupS3StorageResult) string { return v.Uuid }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupS3StorageResultOutput{})
}
