// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package coolify

import (
	"context"
	"reflect"

	"github.com/mheers/pulumi-provider-coolify/sdk/go/coolify/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Use this data source to list all Coolify services.
//
// ## Example Usage
//
// <!--Start PulumiCodeChooser -->
// <!--End PulumiCodeChooser -->
func GetServices(ctx *pulumi.Context, args *GetServicesArgs, opts ...pulumi.InvokeOption) (*GetServicesResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetServicesResult
	err := ctx.Invoke("coolify:index/getServices:getServices", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getServices.
type GetServicesArgs struct {
	// Filter results by field values. Multiple filters are ANDed together. Multiple values within a filter are ORed.
	Filters []GetServicesFilter `pulumi:"filters"`
}

// A collection of values returned by getServices.
type GetServicesResult struct {
	// Filter results by field values. Multiple filters are ANDed together. Multiple values within a filter are ORed.
	Filters []GetServicesFilter `pulumi:"filters"`
	// The list of services.
	Services []GetServicesService `pulumi:"services"`
}

func GetServicesOutput(ctx *pulumi.Context, args GetServicesOutputArgs, opts ...pulumi.InvokeOption) GetServicesResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetServicesResultOutput, error) {
			args := v.(GetServicesArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("coolify:index/getServices:getServices", args, GetServicesResultOutput{}, options).(GetServicesResultOutput), nil
		}).(GetServicesResultOutput)
}

// A collection of arguments for invoking getServices.
type GetServicesOutputArgs struct {
	// Filter results by field values. Multiple filters are ANDed together. Multiple values within a filter are ORed.
	Filters GetServicesFilterArrayInput `pulumi:"filters"`
}

func (GetServicesOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetServicesArgs)(nil)).Elem()
}

// A collection of values returned by getServices.
type GetServicesResultOutput struct{ *pulumi.OutputState }

func (GetServicesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetServicesResult)(nil)).Elem()
}

func (o GetServicesResultOutput) ToGetServicesResultOutput() GetServicesResultOutput {
	return o
}

func (o GetServicesResultOutput) ToGetServicesResultOutputWithContext(ctx context.Context) GetServicesResultOutput {
	return o
}

// Filter results by field values. Multiple filters are ANDed together. Multiple values within a filter are ORed.
func (o GetServicesResultOutput) Filters() GetServicesFilterArrayOutput {
	return o.ApplyT(func(v GetServicesResult) []GetServicesFilter { return v.Filters }).(GetServicesFilterArrayOutput)
}

// The list of services.
func (o GetServicesResultOutput) Services() GetServicesServiceArrayOutput {
	return o.ApplyT(func(v GetServicesResult) []GetServicesService { return v.Services }).(GetServicesServiceArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetServicesResultOutput{})
}
