// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package coolify

import (
	"context"
	"reflect"

	"github.com/mheers/pulumi-provider-coolify/sdk/go/coolify/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Use this data source to retrieve information about a Coolify service by UUID.
//
// ## Example Usage
//
// <!--Start PulumiCodeChooser -->
// ```go
// package main
//
// import (
//
//	"github.com/mheers/pulumi-provider-coolify/sdk/go/coolify"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := coolify.GetService(ctx, &coolify.LookupServiceArgs{
//				Uuid: "550e8400-e29b-41d4-a716-446655440002",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
// <!--End PulumiCodeChooser -->
func LookupService(ctx *pulumi.Context, args *LookupServiceArgs, opts ...pulumi.InvokeOption) (*LookupServiceResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupServiceResult
	err := ctx.Invoke("coolify:index/getService:getService", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getService.
type LookupServiceArgs struct {
	// The unique identifier of the service.
	Uuid string `pulumi:"uuid"`
}

// A collection of values returned by getService.
type LookupServiceResult struct {
	// A description of the service.
	Description string `pulumi:"description"`
	// The environment name.
	EnvironmentName string `pulumi:"environmentName"`
	// The name of the service.
	Name string `pulumi:"name"`
	// The UUID of the project this service belongs to.
	ProjectUuid string `pulumi:"projectUuid"`
	// The UUID of the server the service is deployed on.
	ServerUuid string `pulumi:"serverUuid"`
	// The current status of the service (e.g., <span pulumi-lang-nodejs="`running`" pulumi-lang-dotnet="`Running`" pulumi-lang-go="`running`" pulumi-lang-python="`running`" pulumi-lang-yaml="`running`" pulumi-lang-java="`running`" pulumi-lang-hcl="`running`">`running`</span>, <span pulumi-lang-nodejs="`stopped`" pulumi-lang-dotnet="`Stopped`" pulumi-lang-go="`stopped`" pulumi-lang-python="`stopped`" pulumi-lang-yaml="`stopped`" pulumi-lang-java="`stopped`" pulumi-lang-hcl="`stopped`">`stopped`</span>, <span pulumi-lang-nodejs="`exited`" pulumi-lang-dotnet="`Exited`" pulumi-lang-go="`exited`" pulumi-lang-python="`exited`" pulumi-lang-yaml="`exited`" pulumi-lang-java="`exited`" pulumi-lang-hcl="`exited`">`exited`</span>).
	Status string `pulumi:"status"`
	// The type of the service.
	Type string `pulumi:"type"`
	// The unique identifier of the service.
	Uuid string `pulumi:"uuid"`
}

func LookupServiceOutput(ctx *pulumi.Context, args LookupServiceOutputArgs, opts ...pulumi.InvokeOption) LookupServiceResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupServiceResultOutput, error) {
			args := v.(LookupServiceArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("coolify:index/getService:getService", args, LookupServiceResultOutput{}, options).(LookupServiceResultOutput), nil
		}).(LookupServiceResultOutput)
}

// A collection of arguments for invoking getService.
type LookupServiceOutputArgs struct {
	// The unique identifier of the service.
	Uuid pulumi.StringInput `pulumi:"uuid"`
}

func (LookupServiceOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupServiceArgs)(nil)).Elem()
}

// A collection of values returned by getService.
type LookupServiceResultOutput struct{ *pulumi.OutputState }

func (LookupServiceResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupServiceResult)(nil)).Elem()
}

func (o LookupServiceResultOutput) ToLookupServiceResultOutput() LookupServiceResultOutput {
	return o
}

func (o LookupServiceResultOutput) ToLookupServiceResultOutputWithContext(ctx context.Context) LookupServiceResultOutput {
	return o
}

// A description of the service.
func (o LookupServiceResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupServiceResult) string { return v.Description }).(pulumi.StringOutput)
}

// The environment name.
func (o LookupServiceResultOutput) EnvironmentName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupServiceResult) string { return v.EnvironmentName }).(pulumi.StringOutput)
}

// The name of the service.
func (o LookupServiceResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupServiceResult) string { return v.Name }).(pulumi.StringOutput)
}

// The UUID of the project this service belongs to.
func (o LookupServiceResultOutput) ProjectUuid() pulumi.StringOutput {
	return o.ApplyT(func(v LookupServiceResult) string { return v.ProjectUuid }).(pulumi.StringOutput)
}

// The UUID of the server the service is deployed on.
func (o LookupServiceResultOutput) ServerUuid() pulumi.StringOutput {
	return o.ApplyT(func(v LookupServiceResult) string { return v.ServerUuid }).(pulumi.StringOutput)
}

// The current status of the service (e.g., <span pulumi-lang-nodejs="`running`" pulumi-lang-dotnet="`Running`" pulumi-lang-go="`running`" pulumi-lang-python="`running`" pulumi-lang-yaml="`running`" pulumi-lang-java="`running`" pulumi-lang-hcl="`running`">`running`</span>, <span pulumi-lang-nodejs="`stopped`" pulumi-lang-dotnet="`Stopped`" pulumi-lang-go="`stopped`" pulumi-lang-python="`stopped`" pulumi-lang-yaml="`stopped`" pulumi-lang-java="`stopped`" pulumi-lang-hcl="`stopped`">`stopped`</span>, <span pulumi-lang-nodejs="`exited`" pulumi-lang-dotnet="`Exited`" pulumi-lang-go="`exited`" pulumi-lang-python="`exited`" pulumi-lang-yaml="`exited`" pulumi-lang-java="`exited`" pulumi-lang-hcl="`exited`">`exited`</span>).
func (o LookupServiceResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v LookupServiceResult) string { return v.Status }).(pulumi.StringOutput)
}

// The type of the service.
func (o LookupServiceResultOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v LookupServiceResult) string { return v.Type }).(pulumi.StringOutput)
}

// The unique identifier of the service.
func (o LookupServiceResultOutput) Uuid() pulumi.StringOutput {
	return o.ApplyT(func(v LookupServiceResult) string { return v.Uuid }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupServiceResultOutput{})
}
