// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package coolify

import (
	"context"
	"reflect"

	"github.com/mheers/pulumi-provider-coolify/sdk/go/coolify/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Lists all scheduled tasks for a Coolify application or service.
//
// ## Example Usage
//
// <!--Start PulumiCodeChooser -->
// <!--End PulumiCodeChooser -->
func GetScheduledTasks(ctx *pulumi.Context, args *GetScheduledTasksArgs, opts ...pulumi.InvokeOption) (*GetScheduledTasksResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetScheduledTasksResult
	err := ctx.Invoke("coolify:index/getScheduledTasks:getScheduledTasks", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getScheduledTasks.
type GetScheduledTasksArgs struct {
	// The UUID of the application. Exactly one of <span pulumi-lang-nodejs="`applicationUuid`" pulumi-lang-dotnet="`ApplicationUuid`" pulumi-lang-go="`applicationUuid`" pulumi-lang-python="`application_uuid`" pulumi-lang-yaml="`applicationUuid`" pulumi-lang-java="`applicationUuid`" pulumi-lang-hcl="`application_uuid`">`applicationUuid`</span> or <span pulumi-lang-nodejs="`serviceUuid`" pulumi-lang-dotnet="`ServiceUuid`" pulumi-lang-go="`serviceUuid`" pulumi-lang-python="`service_uuid`" pulumi-lang-yaml="`serviceUuid`" pulumi-lang-java="`serviceUuid`" pulumi-lang-hcl="`service_uuid`">`serviceUuid`</span> must be provided.
	ApplicationUuid *string `pulumi:"applicationUuid"`
	// Filter results by field values. Multiple filters are ANDed together. Multiple values within a filter are ORed.
	Filters []GetScheduledTasksFilter `pulumi:"filters"`
	// The UUID of the service. Exactly one of <span pulumi-lang-nodejs="`applicationUuid`" pulumi-lang-dotnet="`ApplicationUuid`" pulumi-lang-go="`applicationUuid`" pulumi-lang-python="`application_uuid`" pulumi-lang-yaml="`applicationUuid`" pulumi-lang-java="`applicationUuid`" pulumi-lang-hcl="`application_uuid`">`applicationUuid`</span> or <span pulumi-lang-nodejs="`serviceUuid`" pulumi-lang-dotnet="`ServiceUuid`" pulumi-lang-go="`serviceUuid`" pulumi-lang-python="`service_uuid`" pulumi-lang-yaml="`serviceUuid`" pulumi-lang-java="`serviceUuid`" pulumi-lang-hcl="`service_uuid`">`serviceUuid`</span> must be provided.
	ServiceUuid *string `pulumi:"serviceUuid"`
}

// A collection of values returned by getScheduledTasks.
type GetScheduledTasksResult struct {
	// The UUID of the application. Exactly one of <span pulumi-lang-nodejs="`applicationUuid`" pulumi-lang-dotnet="`ApplicationUuid`" pulumi-lang-go="`applicationUuid`" pulumi-lang-python="`application_uuid`" pulumi-lang-yaml="`applicationUuid`" pulumi-lang-java="`applicationUuid`" pulumi-lang-hcl="`application_uuid`">`applicationUuid`</span> or <span pulumi-lang-nodejs="`serviceUuid`" pulumi-lang-dotnet="`ServiceUuid`" pulumi-lang-go="`serviceUuid`" pulumi-lang-python="`service_uuid`" pulumi-lang-yaml="`serviceUuid`" pulumi-lang-java="`serviceUuid`" pulumi-lang-hcl="`service_uuid`">`serviceUuid`</span> must be provided.
	ApplicationUuid *string `pulumi:"applicationUuid"`
	// Filter results by field values. Multiple filters are ANDed together. Multiple values within a filter are ORed.
	Filters []GetScheduledTasksFilter `pulumi:"filters"`
	// The UUID of the service. Exactly one of <span pulumi-lang-nodejs="`applicationUuid`" pulumi-lang-dotnet="`ApplicationUuid`" pulumi-lang-go="`applicationUuid`" pulumi-lang-python="`application_uuid`" pulumi-lang-yaml="`applicationUuid`" pulumi-lang-java="`applicationUuid`" pulumi-lang-hcl="`application_uuid`">`applicationUuid`</span> or <span pulumi-lang-nodejs="`serviceUuid`" pulumi-lang-dotnet="`ServiceUuid`" pulumi-lang-go="`serviceUuid`" pulumi-lang-python="`service_uuid`" pulumi-lang-yaml="`serviceUuid`" pulumi-lang-java="`serviceUuid`" pulumi-lang-hcl="`service_uuid`">`serviceUuid`</span> must be provided.
	ServiceUuid *string `pulumi:"serviceUuid"`
	// The list of scheduled tasks.
	Tasks []GetScheduledTasksTask `pulumi:"tasks"`
}

func GetScheduledTasksOutput(ctx *pulumi.Context, args GetScheduledTasksOutputArgs, opts ...pulumi.InvokeOption) GetScheduledTasksResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetScheduledTasksResultOutput, error) {
			args := v.(GetScheduledTasksArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("coolify:index/getScheduledTasks:getScheduledTasks", args, GetScheduledTasksResultOutput{}, options).(GetScheduledTasksResultOutput), nil
		}).(GetScheduledTasksResultOutput)
}

// A collection of arguments for invoking getScheduledTasks.
type GetScheduledTasksOutputArgs struct {
	// The UUID of the application. Exactly one of <span pulumi-lang-nodejs="`applicationUuid`" pulumi-lang-dotnet="`ApplicationUuid`" pulumi-lang-go="`applicationUuid`" pulumi-lang-python="`application_uuid`" pulumi-lang-yaml="`applicationUuid`" pulumi-lang-java="`applicationUuid`" pulumi-lang-hcl="`application_uuid`">`applicationUuid`</span> or <span pulumi-lang-nodejs="`serviceUuid`" pulumi-lang-dotnet="`ServiceUuid`" pulumi-lang-go="`serviceUuid`" pulumi-lang-python="`service_uuid`" pulumi-lang-yaml="`serviceUuid`" pulumi-lang-java="`serviceUuid`" pulumi-lang-hcl="`service_uuid`">`serviceUuid`</span> must be provided.
	ApplicationUuid pulumi.StringPtrInput `pulumi:"applicationUuid"`
	// Filter results by field values. Multiple filters are ANDed together. Multiple values within a filter are ORed.
	Filters GetScheduledTasksFilterArrayInput `pulumi:"filters"`
	// The UUID of the service. Exactly one of <span pulumi-lang-nodejs="`applicationUuid`" pulumi-lang-dotnet="`ApplicationUuid`" pulumi-lang-go="`applicationUuid`" pulumi-lang-python="`application_uuid`" pulumi-lang-yaml="`applicationUuid`" pulumi-lang-java="`applicationUuid`" pulumi-lang-hcl="`application_uuid`">`applicationUuid`</span> or <span pulumi-lang-nodejs="`serviceUuid`" pulumi-lang-dotnet="`ServiceUuid`" pulumi-lang-go="`serviceUuid`" pulumi-lang-python="`service_uuid`" pulumi-lang-yaml="`serviceUuid`" pulumi-lang-java="`serviceUuid`" pulumi-lang-hcl="`service_uuid`">`serviceUuid`</span> must be provided.
	ServiceUuid pulumi.StringPtrInput `pulumi:"serviceUuid"`
}

func (GetScheduledTasksOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetScheduledTasksArgs)(nil)).Elem()
}

// A collection of values returned by getScheduledTasks.
type GetScheduledTasksResultOutput struct{ *pulumi.OutputState }

func (GetScheduledTasksResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetScheduledTasksResult)(nil)).Elem()
}

func (o GetScheduledTasksResultOutput) ToGetScheduledTasksResultOutput() GetScheduledTasksResultOutput {
	return o
}

func (o GetScheduledTasksResultOutput) ToGetScheduledTasksResultOutputWithContext(ctx context.Context) GetScheduledTasksResultOutput {
	return o
}

// The UUID of the application. Exactly one of <span pulumi-lang-nodejs="`applicationUuid`" pulumi-lang-dotnet="`ApplicationUuid`" pulumi-lang-go="`applicationUuid`" pulumi-lang-python="`application_uuid`" pulumi-lang-yaml="`applicationUuid`" pulumi-lang-java="`applicationUuid`" pulumi-lang-hcl="`application_uuid`">`applicationUuid`</span> or <span pulumi-lang-nodejs="`serviceUuid`" pulumi-lang-dotnet="`ServiceUuid`" pulumi-lang-go="`serviceUuid`" pulumi-lang-python="`service_uuid`" pulumi-lang-yaml="`serviceUuid`" pulumi-lang-java="`serviceUuid`" pulumi-lang-hcl="`service_uuid`">`serviceUuid`</span> must be provided.
func (o GetScheduledTasksResultOutput) ApplicationUuid() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetScheduledTasksResult) *string { return v.ApplicationUuid }).(pulumi.StringPtrOutput)
}

// Filter results by field values. Multiple filters are ANDed together. Multiple values within a filter are ORed.
func (o GetScheduledTasksResultOutput) Filters() GetScheduledTasksFilterArrayOutput {
	return o.ApplyT(func(v GetScheduledTasksResult) []GetScheduledTasksFilter { return v.Filters }).(GetScheduledTasksFilterArrayOutput)
}

// The UUID of the service. Exactly one of <span pulumi-lang-nodejs="`applicationUuid`" pulumi-lang-dotnet="`ApplicationUuid`" pulumi-lang-go="`applicationUuid`" pulumi-lang-python="`application_uuid`" pulumi-lang-yaml="`applicationUuid`" pulumi-lang-java="`applicationUuid`" pulumi-lang-hcl="`application_uuid`">`applicationUuid`</span> or <span pulumi-lang-nodejs="`serviceUuid`" pulumi-lang-dotnet="`ServiceUuid`" pulumi-lang-go="`serviceUuid`" pulumi-lang-python="`service_uuid`" pulumi-lang-yaml="`serviceUuid`" pulumi-lang-java="`serviceUuid`" pulumi-lang-hcl="`service_uuid`">`serviceUuid`</span> must be provided.
func (o GetScheduledTasksResultOutput) ServiceUuid() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetScheduledTasksResult) *string { return v.ServiceUuid }).(pulumi.StringPtrOutput)
}

// The list of scheduled tasks.
func (o GetScheduledTasksResultOutput) Tasks() GetScheduledTasksTaskArrayOutput {
	return o.ApplyT(func(v GetScheduledTasksResult) []GetScheduledTasksTask { return v.Tasks }).(GetScheduledTasksTaskArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetScheduledTasksResultOutput{})
}
