// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package coolify

import (
	"context"
	"reflect"

	"github.com/mheers/pulumi-provider-coolify/sdk/go/coolify/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Retrieves information about a Coolify server.
//
// ## Example Usage
//
// <!--Start PulumiCodeChooser -->
// ```go
// package main
//
// import (
//
//	"github.com/mheers/pulumi-provider-coolify/sdk/go/coolify"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := coolify.GetServer(ctx, &coolify.LookupServerArgs{
//				Uuid: "550e8400-e29b-41d4-a716-446655440005",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
// <!--End PulumiCodeChooser -->
func LookupServer(ctx *pulumi.Context, args *LookupServerArgs, opts ...pulumi.InvokeOption) (*LookupServerResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupServerResult
	err := ctx.Invoke("coolify:index/getServer:getServer", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getServer.
type LookupServerArgs struct {
	// The unique identifier of the server.
	Uuid string `pulumi:"uuid"`
}

// A collection of values returned by getServer.
type LookupServerResult struct {
	// How many deployments can run in parallel on this server.
	ConcurrentBuilds int `pulumi:"concurrentBuilds"`
	// SSH connection timeout in seconds.
	ConnectionTimeout int `pulumi:"connectionTimeout"`
	// Maximum number of queued deployments.
	DeploymentQueueLimit int `pulumi:"deploymentQueueLimit"`
	// A description of the server.
	Description string `pulumi:"description"`
	// Timeout in seconds for Docker operations (pull, build, health check) during deployment.
	DynamicTimeout int `pulumi:"dynamicTimeout"`
	// The IP address of the server.
	Ip string `pulumi:"ip"`
	// Whether this server is used for building applications.
	IsBuildServer bool `pulumi:"isBuildServer"`
	// Whether the server is currently reachable.
	IsReachable bool `pulumi:"isReachable"`
	// Whether the server is currently usable for deployments.
	IsUsable bool `pulumi:"isUsable"`
	// The name of the server.
	Name string `pulumi:"name"`
	// The SSH port of the server.
	Port int `pulumi:"port"`
	// Cron expression for how often disk usage is checked.
	ServerDiskUsageCheckFrequency string `pulumi:"serverDiskUsageCheckFrequency"`
	// Disk usage percentage at which a notification is sent.
	ServerDiskUsageNotificationThreshold int `pulumi:"serverDiskUsageNotificationThreshold"`
	// The SSH user for connecting to the server.
	User string `pulumi:"user"`
	// The unique identifier of the server.
	Uuid string `pulumi:"uuid"`
}

func LookupServerOutput(ctx *pulumi.Context, args LookupServerOutputArgs, opts ...pulumi.InvokeOption) LookupServerResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupServerResultOutput, error) {
			args := v.(LookupServerArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("coolify:index/getServer:getServer", args, LookupServerResultOutput{}, options).(LookupServerResultOutput), nil
		}).(LookupServerResultOutput)
}

// A collection of arguments for invoking getServer.
type LookupServerOutputArgs struct {
	// The unique identifier of the server.
	Uuid pulumi.StringInput `pulumi:"uuid"`
}

func (LookupServerOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupServerArgs)(nil)).Elem()
}

// A collection of values returned by getServer.
type LookupServerResultOutput struct{ *pulumi.OutputState }

func (LookupServerResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupServerResult)(nil)).Elem()
}

func (o LookupServerResultOutput) ToLookupServerResultOutput() LookupServerResultOutput {
	return o
}

func (o LookupServerResultOutput) ToLookupServerResultOutputWithContext(ctx context.Context) LookupServerResultOutput {
	return o
}

// How many deployments can run in parallel on this server.
func (o LookupServerResultOutput) ConcurrentBuilds() pulumi.IntOutput {
	return o.ApplyT(func(v LookupServerResult) int { return v.ConcurrentBuilds }).(pulumi.IntOutput)
}

// SSH connection timeout in seconds.
func (o LookupServerResultOutput) ConnectionTimeout() pulumi.IntOutput {
	return o.ApplyT(func(v LookupServerResult) int { return v.ConnectionTimeout }).(pulumi.IntOutput)
}

// Maximum number of queued deployments.
func (o LookupServerResultOutput) DeploymentQueueLimit() pulumi.IntOutput {
	return o.ApplyT(func(v LookupServerResult) int { return v.DeploymentQueueLimit }).(pulumi.IntOutput)
}

// A description of the server.
func (o LookupServerResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupServerResult) string { return v.Description }).(pulumi.StringOutput)
}

// Timeout in seconds for Docker operations (pull, build, health check) during deployment.
func (o LookupServerResultOutput) DynamicTimeout() pulumi.IntOutput {
	return o.ApplyT(func(v LookupServerResult) int { return v.DynamicTimeout }).(pulumi.IntOutput)
}

// The IP address of the server.
func (o LookupServerResultOutput) Ip() pulumi.StringOutput {
	return o.ApplyT(func(v LookupServerResult) string { return v.Ip }).(pulumi.StringOutput)
}

// Whether this server is used for building applications.
func (o LookupServerResultOutput) IsBuildServer() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupServerResult) bool { return v.IsBuildServer }).(pulumi.BoolOutput)
}

// Whether the server is currently reachable.
func (o LookupServerResultOutput) IsReachable() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupServerResult) bool { return v.IsReachable }).(pulumi.BoolOutput)
}

// Whether the server is currently usable for deployments.
func (o LookupServerResultOutput) IsUsable() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupServerResult) bool { return v.IsUsable }).(pulumi.BoolOutput)
}

// The name of the server.
func (o LookupServerResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupServerResult) string { return v.Name }).(pulumi.StringOutput)
}

// The SSH port of the server.
func (o LookupServerResultOutput) Port() pulumi.IntOutput {
	return o.ApplyT(func(v LookupServerResult) int { return v.Port }).(pulumi.IntOutput)
}

// Cron expression for how often disk usage is checked.
func (o LookupServerResultOutput) ServerDiskUsageCheckFrequency() pulumi.StringOutput {
	return o.ApplyT(func(v LookupServerResult) string { return v.ServerDiskUsageCheckFrequency }).(pulumi.StringOutput)
}

// Disk usage percentage at which a notification is sent.
func (o LookupServerResultOutput) ServerDiskUsageNotificationThreshold() pulumi.IntOutput {
	return o.ApplyT(func(v LookupServerResult) int { return v.ServerDiskUsageNotificationThreshold }).(pulumi.IntOutput)
}

// The SSH user for connecting to the server.
func (o LookupServerResultOutput) User() pulumi.StringOutput {
	return o.ApplyT(func(v LookupServerResult) string { return v.User }).(pulumi.StringOutput)
}

// The unique identifier of the server.
func (o LookupServerResultOutput) Uuid() pulumi.StringOutput {
	return o.ApplyT(func(v LookupServerResult) string { return v.Uuid }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupServerResultOutput{})
}
