// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package coolify

import (
	"context"
	"reflect"

	"github.com/mheers/pulumi-provider-coolify/sdk/go/coolify/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Lists Vultr operating systems for a cloud provider token. Requires Coolify >= v4.2.0.
//
// ## Example Usage
//
// <!--Start PulumiCodeChooser -->
// <!--End PulumiCodeChooser -->
func GetVultrOs(ctx *pulumi.Context, args *GetVultrOsArgs, opts ...pulumi.InvokeOption) (*GetVultrOsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetVultrOsResult
	err := ctx.Invoke("coolify:index/getVultrOs:getVultrOs", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getVultrOs.
type GetVultrOsArgs struct {
	// The UUID of the Vultr cloud provider token to use for listing operating systems. Requires Coolify >= v4.2.0.
	CloudProviderTokenUuid string `pulumi:"cloudProviderTokenUuid"`
	// Filter results by field values. Multiple filters are ANDed together. Multiple values within a filter are ORed.
	Filters []GetVultrOsFilter `pulumi:"filters"`
}

// A collection of values returned by getVultrOs.
type GetVultrOsResult struct {
	// The UUID of the Vultr cloud provider token to use for listing operating systems. Requires Coolify >= v4.2.0.
	CloudProviderTokenUuid string `pulumi:"cloudProviderTokenUuid"`
	// Filter results by field values. Multiple filters are ANDed together. Multiple values within a filter are ORed.
	Filters          []GetVultrOsFilter          `pulumi:"filters"`
	OperatingSystems []GetVultrOsOperatingSystem `pulumi:"operatingSystems"`
}

func GetVultrOsOutput(ctx *pulumi.Context, args GetVultrOsOutputArgs, opts ...pulumi.InvokeOption) GetVultrOsResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetVultrOsResultOutput, error) {
			args := v.(GetVultrOsArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("coolify:index/getVultrOs:getVultrOs", args, GetVultrOsResultOutput{}, options).(GetVultrOsResultOutput), nil
		}).(GetVultrOsResultOutput)
}

// A collection of arguments for invoking getVultrOs.
type GetVultrOsOutputArgs struct {
	// The UUID of the Vultr cloud provider token to use for listing operating systems. Requires Coolify >= v4.2.0.
	CloudProviderTokenUuid pulumi.StringInput `pulumi:"cloudProviderTokenUuid"`
	// Filter results by field values. Multiple filters are ANDed together. Multiple values within a filter are ORed.
	Filters GetVultrOsFilterArrayInput `pulumi:"filters"`
}

func (GetVultrOsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetVultrOsArgs)(nil)).Elem()
}

// A collection of values returned by getVultrOs.
type GetVultrOsResultOutput struct{ *pulumi.OutputState }

func (GetVultrOsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetVultrOsResult)(nil)).Elem()
}

func (o GetVultrOsResultOutput) ToGetVultrOsResultOutput() GetVultrOsResultOutput {
	return o
}

func (o GetVultrOsResultOutput) ToGetVultrOsResultOutputWithContext(ctx context.Context) GetVultrOsResultOutput {
	return o
}

// The UUID of the Vultr cloud provider token to use for listing operating systems. Requires Coolify >= v4.2.0.
func (o GetVultrOsResultOutput) CloudProviderTokenUuid() pulumi.StringOutput {
	return o.ApplyT(func(v GetVultrOsResult) string { return v.CloudProviderTokenUuid }).(pulumi.StringOutput)
}

// Filter results by field values. Multiple filters are ANDed together. Multiple values within a filter are ORed.
func (o GetVultrOsResultOutput) Filters() GetVultrOsFilterArrayOutput {
	return o.ApplyT(func(v GetVultrOsResult) []GetVultrOsFilter { return v.Filters }).(GetVultrOsFilterArrayOutput)
}

func (o GetVultrOsResultOutput) OperatingSystems() GetVultrOsOperatingSystemArrayOutput {
	return o.ApplyT(func(v GetVultrOsResult) []GetVultrOsOperatingSystem { return v.OperatingSystems }).(GetVultrOsOperatingSystemArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetVultrOsResultOutput{})
}
