// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package coolify

import (
	"context"
	"reflect"

	"errors"
	"github.com/mheers/pulumi-provider-coolify/sdk/go/coolify/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Manages a Coolify GitLab App source. Requires Coolify >= v4.3.0.
//
// ## Example Usage
//
// <!--Start PulumiCodeChooser -->
// ```go
// package main
//
// import (
//
//	"github.com/mheers/pulumi-provider-coolify/sdk/go/coolify"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			cfg := config.New(ctx, "")
//			gitlabAppClientSecret := cfg.Require("gitlabAppClientSecret")
//			_, err := coolify.NewGitlabApp(ctx, "example", &coolify.GitlabAppArgs{
//				Name:         pulumi.String("corp-gitlab"),
//				HtmlUrl:      pulumi.String("https://gitlab.example.com"),
//				ClientId:     pulumi.String("gitlab-app-id"),
//				ClientSecret: pulumi.String(gitlabAppClientSecret),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
// <!--End PulumiCodeChooser -->
//
// ## Import
//
// The `pulumi import` command can be used, for example:
//
// Import using the Coolify numeric GitLab App id, or the UUID when Coolify returns one.
//
// ```sh
// $ pulumi import coolify:index/gitlabApp:GitlabApp example 7
// ```
type GitlabApp struct {
	pulumi.CustomResourceState

	// GitLab API URL. Coolify derives it from<span pulumi-lang-nodejs=" htmlUrl " pulumi-lang-dotnet=" HtmlUrl " pulumi-lang-go=" htmlUrl " pulumi-lang-python=" html_url " pulumi-lang-yaml=" htmlUrl " pulumi-lang-java=" htmlUrl " pulumi-lang-hcl=" html_url "> htmlUrl </span>when omitted.
	ApiUrl pulumi.StringOutput `pulumi:"apiUrl"`
	// OAuth application id.
	ClientId pulumi.StringPtrOutput `pulumi:"clientId"`
	// OAuth application secret. Preserved when GET omits it.
	ClientSecret pulumi.StringPtrOutput `pulumi:"clientSecret"`
	// SSH port. Coolify defaults to 22.
	CustomPort pulumi.IntOutput `pulumi:"customPort"`
	// SSH user. Coolify defaults to git.
	CustomUser pulumi.StringOutput `pulumi:"customUser"`
	// Optional group filter.
	GroupName pulumi.StringPtrOutput `pulumi:"groupName"`
	// GitLab HTML URL (for example https://gitlab.example.com).
	HtmlUrl pulumi.StringOutput `pulumi:"htmlUrl"`
	// System-wide on self-hosted Coolify only.
	IsSystemWide pulumi.BoolOutput `pulumi:"isSystemWide"`
	// Display name.
	Name pulumi.StringOutput `pulumi:"name"`
	// OAuth redirect URI. May be a private URL.
	RedirectUri pulumi.StringPtrOutput `pulumi:"redirectUri"`
	// Coolify UUID when returned.
	Uuid pulumi.StringOutput `pulumi:"uuid"`
	// Webhook secret. Coolify generates one when omitted.
	WebhookToken pulumi.StringOutput `pulumi:"webhookToken"`
}

// NewGitlabApp registers a new resource with the given unique name, arguments, and options.
func NewGitlabApp(ctx *pulumi.Context,
	name string, args *GitlabAppArgs, opts ...pulumi.ResourceOption) (*GitlabApp, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.HtmlUrl == nil {
		return nil, errors.New("invalid value for required argument 'HtmlUrl'")
	}
	if args.ClientSecret != nil {
		args.ClientSecret = pulumi.ToSecret(args.ClientSecret).(pulumi.StringPtrInput)
	}
	if args.WebhookToken != nil {
		args.WebhookToken = pulumi.ToSecret(args.WebhookToken).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"clientSecret",
		"webhookToken",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource GitlabApp
	err := ctx.RegisterResource("coolify:index/gitlabApp:GitlabApp", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetGitlabApp gets an existing GitlabApp resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetGitlabApp(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *GitlabAppState, opts ...pulumi.ResourceOption) (*GitlabApp, error) {
	var resource GitlabApp
	err := ctx.ReadResource("coolify:index/gitlabApp:GitlabApp", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering GitlabApp resources.
type gitlabAppState struct {
	// GitLab API URL. Coolify derives it from<span pulumi-lang-nodejs=" htmlUrl " pulumi-lang-dotnet=" HtmlUrl " pulumi-lang-go=" htmlUrl " pulumi-lang-python=" html_url " pulumi-lang-yaml=" htmlUrl " pulumi-lang-java=" htmlUrl " pulumi-lang-hcl=" html_url "> htmlUrl </span>when omitted.
	ApiUrl *string `pulumi:"apiUrl"`
	// OAuth application id.
	ClientId *string `pulumi:"clientId"`
	// OAuth application secret. Preserved when GET omits it.
	ClientSecret *string `pulumi:"clientSecret"`
	// SSH port. Coolify defaults to 22.
	CustomPort *int `pulumi:"customPort"`
	// SSH user. Coolify defaults to git.
	CustomUser *string `pulumi:"customUser"`
	// Optional group filter.
	GroupName *string `pulumi:"groupName"`
	// GitLab HTML URL (for example https://gitlab.example.com).
	HtmlUrl *string `pulumi:"htmlUrl"`
	// System-wide on self-hosted Coolify only.
	IsSystemWide *bool `pulumi:"isSystemWide"`
	// Display name.
	Name *string `pulumi:"name"`
	// OAuth redirect URI. May be a private URL.
	RedirectUri *string `pulumi:"redirectUri"`
	// Coolify UUID when returned.
	Uuid *string `pulumi:"uuid"`
	// Webhook secret. Coolify generates one when omitted.
	WebhookToken *string `pulumi:"webhookToken"`
}

type GitlabAppState struct {
	// GitLab API URL. Coolify derives it from<span pulumi-lang-nodejs=" htmlUrl " pulumi-lang-dotnet=" HtmlUrl " pulumi-lang-go=" htmlUrl " pulumi-lang-python=" html_url " pulumi-lang-yaml=" htmlUrl " pulumi-lang-java=" htmlUrl " pulumi-lang-hcl=" html_url "> htmlUrl </span>when omitted.
	ApiUrl pulumi.StringPtrInput
	// OAuth application id.
	ClientId pulumi.StringPtrInput
	// OAuth application secret. Preserved when GET omits it.
	ClientSecret pulumi.StringPtrInput
	// SSH port. Coolify defaults to 22.
	CustomPort pulumi.IntPtrInput
	// SSH user. Coolify defaults to git.
	CustomUser pulumi.StringPtrInput
	// Optional group filter.
	GroupName pulumi.StringPtrInput
	// GitLab HTML URL (for example https://gitlab.example.com).
	HtmlUrl pulumi.StringPtrInput
	// System-wide on self-hosted Coolify only.
	IsSystemWide pulumi.BoolPtrInput
	// Display name.
	Name pulumi.StringPtrInput
	// OAuth redirect URI. May be a private URL.
	RedirectUri pulumi.StringPtrInput
	// Coolify UUID when returned.
	Uuid pulumi.StringPtrInput
	// Webhook secret. Coolify generates one when omitted.
	WebhookToken pulumi.StringPtrInput
}

func (GitlabAppState) ElementType() reflect.Type {
	return reflect.TypeOf((*gitlabAppState)(nil)).Elem()
}

type gitlabAppArgs struct {
	// GitLab API URL. Coolify derives it from<span pulumi-lang-nodejs=" htmlUrl " pulumi-lang-dotnet=" HtmlUrl " pulumi-lang-go=" htmlUrl " pulumi-lang-python=" html_url " pulumi-lang-yaml=" htmlUrl " pulumi-lang-java=" htmlUrl " pulumi-lang-hcl=" html_url "> htmlUrl </span>when omitted.
	ApiUrl *string `pulumi:"apiUrl"`
	// OAuth application id.
	ClientId *string `pulumi:"clientId"`
	// OAuth application secret. Preserved when GET omits it.
	ClientSecret *string `pulumi:"clientSecret"`
	// SSH port. Coolify defaults to 22.
	CustomPort *int `pulumi:"customPort"`
	// SSH user. Coolify defaults to git.
	CustomUser *string `pulumi:"customUser"`
	// Optional group filter.
	GroupName *string `pulumi:"groupName"`
	// GitLab HTML URL (for example https://gitlab.example.com).
	HtmlUrl string `pulumi:"htmlUrl"`
	// System-wide on self-hosted Coolify only.
	IsSystemWide *bool `pulumi:"isSystemWide"`
	// Display name.
	Name *string `pulumi:"name"`
	// OAuth redirect URI. May be a private URL.
	RedirectUri *string `pulumi:"redirectUri"`
	// Webhook secret. Coolify generates one when omitted.
	WebhookToken *string `pulumi:"webhookToken"`
}

// The set of arguments for constructing a GitlabApp resource.
type GitlabAppArgs struct {
	// GitLab API URL. Coolify derives it from<span pulumi-lang-nodejs=" htmlUrl " pulumi-lang-dotnet=" HtmlUrl " pulumi-lang-go=" htmlUrl " pulumi-lang-python=" html_url " pulumi-lang-yaml=" htmlUrl " pulumi-lang-java=" htmlUrl " pulumi-lang-hcl=" html_url "> htmlUrl </span>when omitted.
	ApiUrl pulumi.StringPtrInput
	// OAuth application id.
	ClientId pulumi.StringPtrInput
	// OAuth application secret. Preserved when GET omits it.
	ClientSecret pulumi.StringPtrInput
	// SSH port. Coolify defaults to 22.
	CustomPort pulumi.IntPtrInput
	// SSH user. Coolify defaults to git.
	CustomUser pulumi.StringPtrInput
	// Optional group filter.
	GroupName pulumi.StringPtrInput
	// GitLab HTML URL (for example https://gitlab.example.com).
	HtmlUrl pulumi.StringInput
	// System-wide on self-hosted Coolify only.
	IsSystemWide pulumi.BoolPtrInput
	// Display name.
	Name pulumi.StringPtrInput
	// OAuth redirect URI. May be a private URL.
	RedirectUri pulumi.StringPtrInput
	// Webhook secret. Coolify generates one when omitted.
	WebhookToken pulumi.StringPtrInput
}

func (GitlabAppArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*gitlabAppArgs)(nil)).Elem()
}

type GitlabAppInput interface {
	pulumi.Input

	ToGitlabAppOutput() GitlabAppOutput
	ToGitlabAppOutputWithContext(ctx context.Context) GitlabAppOutput
}

func (*GitlabApp) ElementType() reflect.Type {
	return reflect.TypeOf((**GitlabApp)(nil)).Elem()
}

func (i *GitlabApp) ToGitlabAppOutput() GitlabAppOutput {
	return i.ToGitlabAppOutputWithContext(context.Background())
}

func (i *GitlabApp) ToGitlabAppOutputWithContext(ctx context.Context) GitlabAppOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GitlabAppOutput)
}

// GitlabAppArrayInput is an input type that accepts GitlabAppArray and GitlabAppArrayOutput values.
// You can construct a concrete instance of `GitlabAppArrayInput` via:
//
//	GitlabAppArray{ GitlabAppArgs{...} }
type GitlabAppArrayInput interface {
	pulumi.Input

	ToGitlabAppArrayOutput() GitlabAppArrayOutput
	ToGitlabAppArrayOutputWithContext(context.Context) GitlabAppArrayOutput
}

type GitlabAppArray []GitlabAppInput

func (GitlabAppArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*GitlabApp)(nil)).Elem()
}

func (i GitlabAppArray) ToGitlabAppArrayOutput() GitlabAppArrayOutput {
	return i.ToGitlabAppArrayOutputWithContext(context.Background())
}

func (i GitlabAppArray) ToGitlabAppArrayOutputWithContext(ctx context.Context) GitlabAppArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GitlabAppArrayOutput)
}

// GitlabAppMapInput is an input type that accepts GitlabAppMap and GitlabAppMapOutput values.
// You can construct a concrete instance of `GitlabAppMapInput` via:
//
//	GitlabAppMap{ "key": GitlabAppArgs{...} }
type GitlabAppMapInput interface {
	pulumi.Input

	ToGitlabAppMapOutput() GitlabAppMapOutput
	ToGitlabAppMapOutputWithContext(context.Context) GitlabAppMapOutput
}

type GitlabAppMap map[string]GitlabAppInput

func (GitlabAppMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*GitlabApp)(nil)).Elem()
}

func (i GitlabAppMap) ToGitlabAppMapOutput() GitlabAppMapOutput {
	return i.ToGitlabAppMapOutputWithContext(context.Background())
}

func (i GitlabAppMap) ToGitlabAppMapOutputWithContext(ctx context.Context) GitlabAppMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GitlabAppMapOutput)
}

type GitlabAppOutput struct{ *pulumi.OutputState }

func (GitlabAppOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**GitlabApp)(nil)).Elem()
}

func (o GitlabAppOutput) ToGitlabAppOutput() GitlabAppOutput {
	return o
}

func (o GitlabAppOutput) ToGitlabAppOutputWithContext(ctx context.Context) GitlabAppOutput {
	return o
}

// GitLab API URL. Coolify derives it from<span pulumi-lang-nodejs=" htmlUrl " pulumi-lang-dotnet=" HtmlUrl " pulumi-lang-go=" htmlUrl " pulumi-lang-python=" html_url " pulumi-lang-yaml=" htmlUrl " pulumi-lang-java=" htmlUrl " pulumi-lang-hcl=" html_url "> htmlUrl </span>when omitted.
func (o GitlabAppOutput) ApiUrl() pulumi.StringOutput {
	return o.ApplyT(func(v *GitlabApp) pulumi.StringOutput { return v.ApiUrl }).(pulumi.StringOutput)
}

// OAuth application id.
func (o GitlabAppOutput) ClientId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *GitlabApp) pulumi.StringPtrOutput { return v.ClientId }).(pulumi.StringPtrOutput)
}

// OAuth application secret. Preserved when GET omits it.
func (o GitlabAppOutput) ClientSecret() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *GitlabApp) pulumi.StringPtrOutput { return v.ClientSecret }).(pulumi.StringPtrOutput)
}

// SSH port. Coolify defaults to 22.
func (o GitlabAppOutput) CustomPort() pulumi.IntOutput {
	return o.ApplyT(func(v *GitlabApp) pulumi.IntOutput { return v.CustomPort }).(pulumi.IntOutput)
}

// SSH user. Coolify defaults to git.
func (o GitlabAppOutput) CustomUser() pulumi.StringOutput {
	return o.ApplyT(func(v *GitlabApp) pulumi.StringOutput { return v.CustomUser }).(pulumi.StringOutput)
}

// Optional group filter.
func (o GitlabAppOutput) GroupName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *GitlabApp) pulumi.StringPtrOutput { return v.GroupName }).(pulumi.StringPtrOutput)
}

// GitLab HTML URL (for example https://gitlab.example.com).
func (o GitlabAppOutput) HtmlUrl() pulumi.StringOutput {
	return o.ApplyT(func(v *GitlabApp) pulumi.StringOutput { return v.HtmlUrl }).(pulumi.StringOutput)
}

// System-wide on self-hosted Coolify only.
func (o GitlabAppOutput) IsSystemWide() pulumi.BoolOutput {
	return o.ApplyT(func(v *GitlabApp) pulumi.BoolOutput { return v.IsSystemWide }).(pulumi.BoolOutput)
}

// Display name.
func (o GitlabAppOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *GitlabApp) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// OAuth redirect URI. May be a private URL.
func (o GitlabAppOutput) RedirectUri() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *GitlabApp) pulumi.StringPtrOutput { return v.RedirectUri }).(pulumi.StringPtrOutput)
}

// Coolify UUID when returned.
func (o GitlabAppOutput) Uuid() pulumi.StringOutput {
	return o.ApplyT(func(v *GitlabApp) pulumi.StringOutput { return v.Uuid }).(pulumi.StringOutput)
}

// Webhook secret. Coolify generates one when omitted.
func (o GitlabAppOutput) WebhookToken() pulumi.StringOutput {
	return o.ApplyT(func(v *GitlabApp) pulumi.StringOutput { return v.WebhookToken }).(pulumi.StringOutput)
}

type GitlabAppArrayOutput struct{ *pulumi.OutputState }

func (GitlabAppArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*GitlabApp)(nil)).Elem()
}

func (o GitlabAppArrayOutput) ToGitlabAppArrayOutput() GitlabAppArrayOutput {
	return o
}

func (o GitlabAppArrayOutput) ToGitlabAppArrayOutputWithContext(ctx context.Context) GitlabAppArrayOutput {
	return o
}

func (o GitlabAppArrayOutput) Index(i pulumi.IntInput) GitlabAppOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *GitlabApp {
		return vs[0].([]*GitlabApp)[vs[1].(int)]
	}).(GitlabAppOutput)
}

type GitlabAppMapOutput struct{ *pulumi.OutputState }

func (GitlabAppMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*GitlabApp)(nil)).Elem()
}

func (o GitlabAppMapOutput) ToGitlabAppMapOutput() GitlabAppMapOutput {
	return o
}

func (o GitlabAppMapOutput) ToGitlabAppMapOutputWithContext(ctx context.Context) GitlabAppMapOutput {
	return o
}

func (o GitlabAppMapOutput) MapIndex(k pulumi.StringInput) GitlabAppOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *GitlabApp {
		return vs[0].(map[string]*GitlabApp)[vs[1].(string)]
	}).(GitlabAppOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*GitlabAppInput)(nil)).Elem(), &GitlabApp{})
	pulumi.RegisterInputType(reflect.TypeOf((*GitlabAppArrayInput)(nil)).Elem(), GitlabAppArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GitlabAppMapInput)(nil)).Elem(), GitlabAppMap{})
	pulumi.RegisterOutputType(GitlabAppOutput{})
	pulumi.RegisterOutputType(GitlabAppArrayOutput{})
	pulumi.RegisterOutputType(GitlabAppMapOutput{})
}
