// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package coolify

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/mheers/pulumi-provider-coolify/sdk/go/coolify/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "coolify:index/apiSettings:ApiSettings":
		r = &ApiSettings{}
	case "coolify:index/application:Application":
		r = &Application{}
	case "coolify:index/applicationDestination:ApplicationDestination":
		r = &ApplicationDestination{}
	case "coolify:index/applicationDockerImage:ApplicationDockerImage":
		r = &ApplicationDockerImage{}
	case "coolify:index/applicationDockerfile:ApplicationDockerfile":
		r = &ApplicationDockerfile{}
	case "coolify:index/applicationGithubApp:ApplicationGithubApp":
		r = &ApplicationGithubApp{}
	case "coolify:index/applicationPreview:ApplicationPreview":
		r = &ApplicationPreview{}
	case "coolify:index/applicationPrivateGit:ApplicationPrivateGit":
		r = &ApplicationPrivateGit{}
	case "coolify:index/backupExecution:BackupExecution":
		r = &BackupExecution{}
	case "coolify:index/cloudInitScript:CloudInitScript":
		r = &CloudInitScript{}
	case "coolify:index/cloudToken:CloudToken":
		r = &CloudToken{}
	case "coolify:index/cloudTokenValidate:CloudTokenValidate":
		r = &CloudTokenValidate{}
	case "coolify:index/databaseBackup:DatabaseBackup":
		r = &DatabaseBackup{}
	case "coolify:index/databaseClickhouse:DatabaseClickhouse":
		r = &DatabaseClickhouse{}
	case "coolify:index/databaseDragonfly:DatabaseDragonfly":
		r = &DatabaseDragonfly{}
	case "coolify:index/databaseKeydb:DatabaseKeydb":
		r = &DatabaseKeydb{}
	case "coolify:index/databaseMariadb:DatabaseMariadb":
		r = &DatabaseMariadb{}
	case "coolify:index/databaseMongodb:DatabaseMongodb":
		r = &DatabaseMongodb{}
	case "coolify:index/databaseMysql:DatabaseMysql":
		r = &DatabaseMysql{}
	case "coolify:index/databasePostgresql:DatabasePostgresql":
		r = &DatabasePostgresql{}
	case "coolify:index/databaseRedis:DatabaseRedis":
		r = &DatabaseRedis{}
	case "coolify:index/deployment:Deployment":
		r = &Deployment{}
	case "coolify:index/destination:Destination":
		r = &Destination{}
	case "coolify:index/environment:Environment":
		r = &Environment{}
	case "coolify:index/environmentVariable:EnvironmentVariable":
		r = &EnvironmentVariable{}
	case "coolify:index/envsBulk:EnvsBulk":
		r = &EnvsBulk{}
	case "coolify:index/githubApp:GithubApp":
		r = &GithubApp{}
	case "coolify:index/gitlabApp:GitlabApp":
		r = &GitlabApp{}
	case "coolify:index/notificationDiscord:NotificationDiscord":
		r = &NotificationDiscord{}
	case "coolify:index/notificationEmail:NotificationEmail":
		r = &NotificationEmail{}
	case "coolify:index/notificationPushover:NotificationPushover":
		r = &NotificationPushover{}
	case "coolify:index/notificationSlack:NotificationSlack":
		r = &NotificationSlack{}
	case "coolify:index/notificationTelegram:NotificationTelegram":
		r = &NotificationTelegram{}
	case "coolify:index/notificationWebhook:NotificationWebhook":
		r = &NotificationWebhook{}
	case "coolify:index/privateKey:PrivateKey":
		r = &PrivateKey{}
	case "coolify:index/project:Project":
		r = &Project{}
	case "coolify:index/resourceAction:ResourceAction":
		r = &ResourceAction{}
	case "coolify:index/resourceTag:ResourceTag":
		r = &ResourceTag{}
	case "coolify:index/s3Storage:S3Storage":
		r = &S3Storage{}
	case "coolify:index/s3StorageValidate:S3StorageValidate":
		r = &S3StorageValidate{}
	case "coolify:index/scheduledTask:ScheduledTask":
		r = &ScheduledTask{}
	case "coolify:index/server:Server":
		r = &Server{}
	case "coolify:index/serverCloudflareTunnel:ServerCloudflareTunnel":
		r = &ServerCloudflareTunnel{}
	case "coolify:index/serverDigitalocean:ServerDigitalocean":
		r = &ServerDigitalocean{}
	case "coolify:index/serverDockerCleanup:ServerDockerCleanup":
		r = &ServerDockerCleanup{}
	case "coolify:index/serverHetzner:ServerHetzner":
		r = &ServerHetzner{}
	case "coolify:index/serverLogDrain:ServerLogDrain":
		r = &ServerLogDrain{}
	case "coolify:index/serverProxy:ServerProxy":
		r = &ServerProxy{}
	case "coolify:index/serverSentinel:ServerSentinel":
		r = &ServerSentinel{}
	case "coolify:index/serverValidate:ServerValidate":
		r = &ServerValidate{}
	case "coolify:index/serverVultr:ServerVultr":
		r = &ServerVultr{}
	case "coolify:index/service:Service":
		r = &Service{}
	case "coolify:index/sharedEnvironmentVariable:SharedEnvironmentVariable":
		r = &SharedEnvironmentVariable{}
	case "coolify:index/storage:Storage":
		r = &Storage{}
	case "coolify:index/storageBackup:StorageBackup":
		r = &StorageBackup{}
	case "coolify:index/tag:Tag":
		r = &Tag{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

type pkg struct {
	version semver.Version
}

func (p *pkg) Version() semver.Version {
	return p.version
}

func (p *pkg) ConstructProvider(ctx *pulumi.Context, name, typ, urn string) (pulumi.ProviderResource, error) {
	if typ != "pulumi:providers:coolify" {
		return nil, fmt.Errorf("unknown provider type: %s", typ)
	}

	r := &Provider{}
	err := ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return r, err
}

func init() {
	version, err := internal.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"coolify",
		"index/apiSettings",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coolify",
		"index/application",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coolify",
		"index/applicationDestination",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coolify",
		"index/applicationDockerImage",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coolify",
		"index/applicationDockerfile",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coolify",
		"index/applicationGithubApp",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coolify",
		"index/applicationPreview",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coolify",
		"index/applicationPrivateGit",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coolify",
		"index/backupExecution",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coolify",
		"index/cloudInitScript",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coolify",
		"index/cloudToken",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coolify",
		"index/cloudTokenValidate",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coolify",
		"index/databaseBackup",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coolify",
		"index/databaseClickhouse",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coolify",
		"index/databaseDragonfly",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coolify",
		"index/databaseKeydb",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coolify",
		"index/databaseMariadb",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coolify",
		"index/databaseMongodb",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coolify",
		"index/databaseMysql",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coolify",
		"index/databasePostgresql",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coolify",
		"index/databaseRedis",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coolify",
		"index/deployment",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coolify",
		"index/destination",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coolify",
		"index/environment",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coolify",
		"index/environmentVariable",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coolify",
		"index/envsBulk",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coolify",
		"index/githubApp",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coolify",
		"index/gitlabApp",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coolify",
		"index/notificationDiscord",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coolify",
		"index/notificationEmail",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coolify",
		"index/notificationPushover",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coolify",
		"index/notificationSlack",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coolify",
		"index/notificationTelegram",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coolify",
		"index/notificationWebhook",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coolify",
		"index/privateKey",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coolify",
		"index/project",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coolify",
		"index/resourceAction",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coolify",
		"index/resourceTag",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coolify",
		"index/s3Storage",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coolify",
		"index/s3StorageValidate",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coolify",
		"index/scheduledTask",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coolify",
		"index/server",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coolify",
		"index/serverCloudflareTunnel",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coolify",
		"index/serverDigitalocean",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coolify",
		"index/serverDockerCleanup",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coolify",
		"index/serverHetzner",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coolify",
		"index/serverLogDrain",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coolify",
		"index/serverProxy",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coolify",
		"index/serverSentinel",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coolify",
		"index/serverValidate",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coolify",
		"index/serverVultr",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coolify",
		"index/service",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coolify",
		"index/sharedEnvironmentVariable",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coolify",
		"index/storage",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coolify",
		"index/storageBackup",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coolify",
		"index/tag",
		&module{version},
	)
	pulumi.RegisterResourcePackage(
		"coolify",
		&pkg{version},
	)
}
