// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package coolify

import (
	"context"
	"reflect"

	"errors"
	"github.com/mheers/pulumi-provider-coolify/sdk/go/coolify/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Manages a Coolify private key used for SSH authentication.
//
// ## Example Usage
//
// <!--Start PulumiCodeChooser -->
// ```go
// package main
//
// import (
//
//	"github.com/mheers/pulumi-provider-coolify/sdk/go/coolify"
//	"github.com/pulumi/pulumi-std/sdk/v2/go/std"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			invokeFile, err := std.File(ctx, &std.FileArgs{
//				Input: "~/.ssh/id_ed25519",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			_, err = coolify.NewPrivateKey(ctx, "example", &coolify.PrivateKeyArgs{
//				Name:        pulumi.String("my-ssh-key"),
//				Description: pulumi.String("SSH key for server access"),
//				PrivateKey:  pulumi.String(invokeFile.Result),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
// <!--End PulumiCodeChooser -->
//
// ## Import
//
// The `pulumi import` command can be used, for example:
//
// ```sh
// $ pulumi import coolify:index/privateKey:PrivateKey example <private-key-uuid>
// ```
type PrivateKey struct {
	pulumi.CustomResourceState

	// A description of the private key.
	Description pulumi.StringOutput `pulumi:"description"`
	// The fingerprint of the private key. Read-only.
	Fingerprint pulumi.StringOutput `pulumi:"fingerprint"`
	// Whether this key is used for Git operations. Determined by the server.
	IsGitRelated pulumi.BoolOutput `pulumi:"isGitRelated"`
	// The name of the private key.
	Name pulumi.StringOutput `pulumi:"name"`
	// The PEM-encoded private key content.
	PrivateKey pulumi.StringOutput `pulumi:"privateKey"`
	// The public key derived from the private key. Read-only.
	PublicKey pulumi.StringOutput `pulumi:"publicKey"`
	// The unique identifier of the private key.
	Uuid pulumi.StringOutput `pulumi:"uuid"`
}

// NewPrivateKey registers a new resource with the given unique name, arguments, and options.
func NewPrivateKey(ctx *pulumi.Context,
	name string, args *PrivateKeyArgs, opts ...pulumi.ResourceOption) (*PrivateKey, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.PrivateKey == nil {
		return nil, errors.New("invalid value for required argument 'PrivateKey'")
	}
	if args.PrivateKey != nil {
		args.PrivateKey = pulumi.ToSecret(args.PrivateKey).(pulumi.StringInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"privateKey",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource PrivateKey
	err := ctx.RegisterResource("coolify:index/privateKey:PrivateKey", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetPrivateKey gets an existing PrivateKey resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetPrivateKey(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *PrivateKeyState, opts ...pulumi.ResourceOption) (*PrivateKey, error) {
	var resource PrivateKey
	err := ctx.ReadResource("coolify:index/privateKey:PrivateKey", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering PrivateKey resources.
type privateKeyState struct {
	// A description of the private key.
	Description *string `pulumi:"description"`
	// The fingerprint of the private key. Read-only.
	Fingerprint *string `pulumi:"fingerprint"`
	// Whether this key is used for Git operations. Determined by the server.
	IsGitRelated *bool `pulumi:"isGitRelated"`
	// The name of the private key.
	Name *string `pulumi:"name"`
	// The PEM-encoded private key content.
	PrivateKey *string `pulumi:"privateKey"`
	// The public key derived from the private key. Read-only.
	PublicKey *string `pulumi:"publicKey"`
	// The unique identifier of the private key.
	Uuid *string `pulumi:"uuid"`
}

type PrivateKeyState struct {
	// A description of the private key.
	Description pulumi.StringPtrInput
	// The fingerprint of the private key. Read-only.
	Fingerprint pulumi.StringPtrInput
	// Whether this key is used for Git operations. Determined by the server.
	IsGitRelated pulumi.BoolPtrInput
	// The name of the private key.
	Name pulumi.StringPtrInput
	// The PEM-encoded private key content.
	PrivateKey pulumi.StringPtrInput
	// The public key derived from the private key. Read-only.
	PublicKey pulumi.StringPtrInput
	// The unique identifier of the private key.
	Uuid pulumi.StringPtrInput
}

func (PrivateKeyState) ElementType() reflect.Type {
	return reflect.TypeOf((*privateKeyState)(nil)).Elem()
}

type privateKeyArgs struct {
	// A description of the private key.
	Description *string `pulumi:"description"`
	// The name of the private key.
	Name *string `pulumi:"name"`
	// The PEM-encoded private key content.
	PrivateKey string `pulumi:"privateKey"`
}

// The set of arguments for constructing a PrivateKey resource.
type PrivateKeyArgs struct {
	// A description of the private key.
	Description pulumi.StringPtrInput
	// The name of the private key.
	Name pulumi.StringPtrInput
	// The PEM-encoded private key content.
	PrivateKey pulumi.StringInput
}

func (PrivateKeyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*privateKeyArgs)(nil)).Elem()
}

type PrivateKeyInput interface {
	pulumi.Input

	ToPrivateKeyOutput() PrivateKeyOutput
	ToPrivateKeyOutputWithContext(ctx context.Context) PrivateKeyOutput
}

func (*PrivateKey) ElementType() reflect.Type {
	return reflect.TypeOf((**PrivateKey)(nil)).Elem()
}

func (i *PrivateKey) ToPrivateKeyOutput() PrivateKeyOutput {
	return i.ToPrivateKeyOutputWithContext(context.Background())
}

func (i *PrivateKey) ToPrivateKeyOutputWithContext(ctx context.Context) PrivateKeyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PrivateKeyOutput)
}

// PrivateKeyArrayInput is an input type that accepts PrivateKeyArray and PrivateKeyArrayOutput values.
// You can construct a concrete instance of `PrivateKeyArrayInput` via:
//
//	PrivateKeyArray{ PrivateKeyArgs{...} }
type PrivateKeyArrayInput interface {
	pulumi.Input

	ToPrivateKeyArrayOutput() PrivateKeyArrayOutput
	ToPrivateKeyArrayOutputWithContext(context.Context) PrivateKeyArrayOutput
}

type PrivateKeyArray []PrivateKeyInput

func (PrivateKeyArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*PrivateKey)(nil)).Elem()
}

func (i PrivateKeyArray) ToPrivateKeyArrayOutput() PrivateKeyArrayOutput {
	return i.ToPrivateKeyArrayOutputWithContext(context.Background())
}

func (i PrivateKeyArray) ToPrivateKeyArrayOutputWithContext(ctx context.Context) PrivateKeyArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PrivateKeyArrayOutput)
}

// PrivateKeyMapInput is an input type that accepts PrivateKeyMap and PrivateKeyMapOutput values.
// You can construct a concrete instance of `PrivateKeyMapInput` via:
//
//	PrivateKeyMap{ "key": PrivateKeyArgs{...} }
type PrivateKeyMapInput interface {
	pulumi.Input

	ToPrivateKeyMapOutput() PrivateKeyMapOutput
	ToPrivateKeyMapOutputWithContext(context.Context) PrivateKeyMapOutput
}

type PrivateKeyMap map[string]PrivateKeyInput

func (PrivateKeyMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*PrivateKey)(nil)).Elem()
}

func (i PrivateKeyMap) ToPrivateKeyMapOutput() PrivateKeyMapOutput {
	return i.ToPrivateKeyMapOutputWithContext(context.Background())
}

func (i PrivateKeyMap) ToPrivateKeyMapOutputWithContext(ctx context.Context) PrivateKeyMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PrivateKeyMapOutput)
}

type PrivateKeyOutput struct{ *pulumi.OutputState }

func (PrivateKeyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**PrivateKey)(nil)).Elem()
}

func (o PrivateKeyOutput) ToPrivateKeyOutput() PrivateKeyOutput {
	return o
}

func (o PrivateKeyOutput) ToPrivateKeyOutputWithContext(ctx context.Context) PrivateKeyOutput {
	return o
}

// A description of the private key.
func (o PrivateKeyOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v *PrivateKey) pulumi.StringOutput { return v.Description }).(pulumi.StringOutput)
}

// The fingerprint of the private key. Read-only.
func (o PrivateKeyOutput) Fingerprint() pulumi.StringOutput {
	return o.ApplyT(func(v *PrivateKey) pulumi.StringOutput { return v.Fingerprint }).(pulumi.StringOutput)
}

// Whether this key is used for Git operations. Determined by the server.
func (o PrivateKeyOutput) IsGitRelated() pulumi.BoolOutput {
	return o.ApplyT(func(v *PrivateKey) pulumi.BoolOutput { return v.IsGitRelated }).(pulumi.BoolOutput)
}

// The name of the private key.
func (o PrivateKeyOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *PrivateKey) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The PEM-encoded private key content.
func (o PrivateKeyOutput) PrivateKey() pulumi.StringOutput {
	return o.ApplyT(func(v *PrivateKey) pulumi.StringOutput { return v.PrivateKey }).(pulumi.StringOutput)
}

// The public key derived from the private key. Read-only.
func (o PrivateKeyOutput) PublicKey() pulumi.StringOutput {
	return o.ApplyT(func(v *PrivateKey) pulumi.StringOutput { return v.PublicKey }).(pulumi.StringOutput)
}

// The unique identifier of the private key.
func (o PrivateKeyOutput) Uuid() pulumi.StringOutput {
	return o.ApplyT(func(v *PrivateKey) pulumi.StringOutput { return v.Uuid }).(pulumi.StringOutput)
}

type PrivateKeyArrayOutput struct{ *pulumi.OutputState }

func (PrivateKeyArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*PrivateKey)(nil)).Elem()
}

func (o PrivateKeyArrayOutput) ToPrivateKeyArrayOutput() PrivateKeyArrayOutput {
	return o
}

func (o PrivateKeyArrayOutput) ToPrivateKeyArrayOutputWithContext(ctx context.Context) PrivateKeyArrayOutput {
	return o
}

func (o PrivateKeyArrayOutput) Index(i pulumi.IntInput) PrivateKeyOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *PrivateKey {
		return vs[0].([]*PrivateKey)[vs[1].(int)]
	}).(PrivateKeyOutput)
}

type PrivateKeyMapOutput struct{ *pulumi.OutputState }

func (PrivateKeyMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*PrivateKey)(nil)).Elem()
}

func (o PrivateKeyMapOutput) ToPrivateKeyMapOutput() PrivateKeyMapOutput {
	return o
}

func (o PrivateKeyMapOutput) ToPrivateKeyMapOutputWithContext(ctx context.Context) PrivateKeyMapOutput {
	return o
}

func (o PrivateKeyMapOutput) MapIndex(k pulumi.StringInput) PrivateKeyOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *PrivateKey {
		return vs[0].(map[string]*PrivateKey)[vs[1].(string)]
	}).(PrivateKeyOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*PrivateKeyInput)(nil)).Elem(), &PrivateKey{})
	pulumi.RegisterInputType(reflect.TypeOf((*PrivateKeyArrayInput)(nil)).Elem(), PrivateKeyArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*PrivateKeyMapInput)(nil)).Elem(), PrivateKeyMap{})
	pulumi.RegisterOutputType(PrivateKeyOutput{})
	pulumi.RegisterOutputType(PrivateKeyArrayOutput{})
	pulumi.RegisterOutputType(PrivateKeyMapOutput{})
}
