// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package coolify

import (
	"context"
	"reflect"

	"errors"
	"github.com/mheers/pulumi-provider-coolify/sdk/go/coolify/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Triggers a start, stop, or restart action on a Coolify application, database, or service. Changing the <span pulumi-lang-nodejs="`triggers`" pulumi-lang-dotnet="`Triggers`" pulumi-lang-go="`triggers`" pulumi-lang-python="`triggers`" pulumi-lang-yaml="`triggers`" pulumi-lang-java="`triggers`" pulumi-lang-hcl="`triggers`">`triggers`</span> map forces the action to run again.
//
// ## Example Usage
//
// <!--Start PulumiCodeChooser -->
// ```go
// package main
//
// import (
//
//	"github.com/mheers/pulumi-provider-coolify/sdk/go/coolify"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			// Start a database
//			_, err := coolify.NewResourceAction(ctx, "start_db", &coolify.ResourceActionArgs{
//				ResourceUuid: pulumi.Any(main.Uuid),
//				ResourceType: pulumi.String("database"),
//				Action:       pulumi.String("start"),
//			})
//			if err != nil {
//				return err
//			}
//			// Restart an application whenever the image tag changes
//			_, err = coolify.NewResourceAction(ctx, "restart_app", &coolify.ResourceActionArgs{
//				ResourceUuid: pulumi.Any(api.Uuid),
//				ResourceType: pulumi.String("application"),
//				Action:       pulumi.String("restart"),
//				Triggers: pulumi.StringMap{
//					"image_tag": pulumi.Any(imageTag),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			// Stop a service
//			_, err = coolify.NewResourceAction(ctx, "stop_svc", &coolify.ResourceActionArgs{
//				ResourceUuid: pulumi.Any(monitoring.Uuid),
//				ResourceType: pulumi.String("service"),
//				Action:       pulumi.String("stop"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
// <!--End PulumiCodeChooser -->
type ResourceAction struct {
	pulumi.CustomResourceState

	// The action to perform. Must be one of: <span pulumi-lang-nodejs="`start`" pulumi-lang-dotnet="`Start`" pulumi-lang-go="`start`" pulumi-lang-python="`start`" pulumi-lang-yaml="`start`" pulumi-lang-java="`start`" pulumi-lang-hcl="`start`">`start`</span>, <span pulumi-lang-nodejs="`stop`" pulumi-lang-dotnet="`Stop`" pulumi-lang-go="`stop`" pulumi-lang-python="`stop`" pulumi-lang-yaml="`stop`" pulumi-lang-java="`stop`" pulumi-lang-hcl="`stop`">`stop`</span>, <span pulumi-lang-nodejs="`restart`" pulumi-lang-dotnet="`Restart`" pulumi-lang-go="`restart`" pulumi-lang-python="`restart`" pulumi-lang-yaml="`restart`" pulumi-lang-java="`restart`" pulumi-lang-hcl="`restart`">`restart`</span>.
	Action pulumi.StringOutput `pulumi:"action"`
	// The type of the target resource. Must be one of: <span pulumi-lang-nodejs="`application`" pulumi-lang-dotnet="`Application`" pulumi-lang-go="`application`" pulumi-lang-python="`application`" pulumi-lang-yaml="`application`" pulumi-lang-java="`application`" pulumi-lang-hcl="`application`">`application`</span>, <span pulumi-lang-nodejs="`database`" pulumi-lang-dotnet="`Database`" pulumi-lang-go="`database`" pulumi-lang-python="`database`" pulumi-lang-yaml="`database`" pulumi-lang-java="`database`" pulumi-lang-hcl="`database`">`database`</span>, <span pulumi-lang-nodejs="`service`" pulumi-lang-dotnet="`Service`" pulumi-lang-go="`service`" pulumi-lang-python="`service`" pulumi-lang-yaml="`service`" pulumi-lang-java="`service`" pulumi-lang-hcl="`service`">`service`</span>.
	ResourceType pulumi.StringOutput `pulumi:"resourceType"`
	// The UUID of the target resource (application, database, or service).
	ResourceUuid pulumi.StringOutput `pulumi:"resourceUuid"`
	// An arbitrary map of values that, when changed, forces the action to run again.
	Triggers pulumi.StringMapOutput `pulumi:"triggers"`
}

// NewResourceAction registers a new resource with the given unique name, arguments, and options.
func NewResourceAction(ctx *pulumi.Context,
	name string, args *ResourceActionArgs, opts ...pulumi.ResourceOption) (*ResourceAction, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Action == nil {
		return nil, errors.New("invalid value for required argument 'Action'")
	}
	if args.ResourceType == nil {
		return nil, errors.New("invalid value for required argument 'ResourceType'")
	}
	if args.ResourceUuid == nil {
		return nil, errors.New("invalid value for required argument 'ResourceUuid'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ResourceAction
	err := ctx.RegisterResource("coolify:index/resourceAction:ResourceAction", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetResourceAction gets an existing ResourceAction resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetResourceAction(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ResourceActionState, opts ...pulumi.ResourceOption) (*ResourceAction, error) {
	var resource ResourceAction
	err := ctx.ReadResource("coolify:index/resourceAction:ResourceAction", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ResourceAction resources.
type resourceActionState struct {
	// The action to perform. Must be one of: <span pulumi-lang-nodejs="`start`" pulumi-lang-dotnet="`Start`" pulumi-lang-go="`start`" pulumi-lang-python="`start`" pulumi-lang-yaml="`start`" pulumi-lang-java="`start`" pulumi-lang-hcl="`start`">`start`</span>, <span pulumi-lang-nodejs="`stop`" pulumi-lang-dotnet="`Stop`" pulumi-lang-go="`stop`" pulumi-lang-python="`stop`" pulumi-lang-yaml="`stop`" pulumi-lang-java="`stop`" pulumi-lang-hcl="`stop`">`stop`</span>, <span pulumi-lang-nodejs="`restart`" pulumi-lang-dotnet="`Restart`" pulumi-lang-go="`restart`" pulumi-lang-python="`restart`" pulumi-lang-yaml="`restart`" pulumi-lang-java="`restart`" pulumi-lang-hcl="`restart`">`restart`</span>.
	Action *string `pulumi:"action"`
	// The type of the target resource. Must be one of: <span pulumi-lang-nodejs="`application`" pulumi-lang-dotnet="`Application`" pulumi-lang-go="`application`" pulumi-lang-python="`application`" pulumi-lang-yaml="`application`" pulumi-lang-java="`application`" pulumi-lang-hcl="`application`">`application`</span>, <span pulumi-lang-nodejs="`database`" pulumi-lang-dotnet="`Database`" pulumi-lang-go="`database`" pulumi-lang-python="`database`" pulumi-lang-yaml="`database`" pulumi-lang-java="`database`" pulumi-lang-hcl="`database`">`database`</span>, <span pulumi-lang-nodejs="`service`" pulumi-lang-dotnet="`Service`" pulumi-lang-go="`service`" pulumi-lang-python="`service`" pulumi-lang-yaml="`service`" pulumi-lang-java="`service`" pulumi-lang-hcl="`service`">`service`</span>.
	ResourceType *string `pulumi:"resourceType"`
	// The UUID of the target resource (application, database, or service).
	ResourceUuid *string `pulumi:"resourceUuid"`
	// An arbitrary map of values that, when changed, forces the action to run again.
	Triggers map[string]string `pulumi:"triggers"`
}

type ResourceActionState struct {
	// The action to perform. Must be one of: <span pulumi-lang-nodejs="`start`" pulumi-lang-dotnet="`Start`" pulumi-lang-go="`start`" pulumi-lang-python="`start`" pulumi-lang-yaml="`start`" pulumi-lang-java="`start`" pulumi-lang-hcl="`start`">`start`</span>, <span pulumi-lang-nodejs="`stop`" pulumi-lang-dotnet="`Stop`" pulumi-lang-go="`stop`" pulumi-lang-python="`stop`" pulumi-lang-yaml="`stop`" pulumi-lang-java="`stop`" pulumi-lang-hcl="`stop`">`stop`</span>, <span pulumi-lang-nodejs="`restart`" pulumi-lang-dotnet="`Restart`" pulumi-lang-go="`restart`" pulumi-lang-python="`restart`" pulumi-lang-yaml="`restart`" pulumi-lang-java="`restart`" pulumi-lang-hcl="`restart`">`restart`</span>.
	Action pulumi.StringPtrInput
	// The type of the target resource. Must be one of: <span pulumi-lang-nodejs="`application`" pulumi-lang-dotnet="`Application`" pulumi-lang-go="`application`" pulumi-lang-python="`application`" pulumi-lang-yaml="`application`" pulumi-lang-java="`application`" pulumi-lang-hcl="`application`">`application`</span>, <span pulumi-lang-nodejs="`database`" pulumi-lang-dotnet="`Database`" pulumi-lang-go="`database`" pulumi-lang-python="`database`" pulumi-lang-yaml="`database`" pulumi-lang-java="`database`" pulumi-lang-hcl="`database`">`database`</span>, <span pulumi-lang-nodejs="`service`" pulumi-lang-dotnet="`Service`" pulumi-lang-go="`service`" pulumi-lang-python="`service`" pulumi-lang-yaml="`service`" pulumi-lang-java="`service`" pulumi-lang-hcl="`service`">`service`</span>.
	ResourceType pulumi.StringPtrInput
	// The UUID of the target resource (application, database, or service).
	ResourceUuid pulumi.StringPtrInput
	// An arbitrary map of values that, when changed, forces the action to run again.
	Triggers pulumi.StringMapInput
}

func (ResourceActionState) ElementType() reflect.Type {
	return reflect.TypeOf((*resourceActionState)(nil)).Elem()
}

type resourceActionArgs struct {
	// The action to perform. Must be one of: <span pulumi-lang-nodejs="`start`" pulumi-lang-dotnet="`Start`" pulumi-lang-go="`start`" pulumi-lang-python="`start`" pulumi-lang-yaml="`start`" pulumi-lang-java="`start`" pulumi-lang-hcl="`start`">`start`</span>, <span pulumi-lang-nodejs="`stop`" pulumi-lang-dotnet="`Stop`" pulumi-lang-go="`stop`" pulumi-lang-python="`stop`" pulumi-lang-yaml="`stop`" pulumi-lang-java="`stop`" pulumi-lang-hcl="`stop`">`stop`</span>, <span pulumi-lang-nodejs="`restart`" pulumi-lang-dotnet="`Restart`" pulumi-lang-go="`restart`" pulumi-lang-python="`restart`" pulumi-lang-yaml="`restart`" pulumi-lang-java="`restart`" pulumi-lang-hcl="`restart`">`restart`</span>.
	Action string `pulumi:"action"`
	// The type of the target resource. Must be one of: <span pulumi-lang-nodejs="`application`" pulumi-lang-dotnet="`Application`" pulumi-lang-go="`application`" pulumi-lang-python="`application`" pulumi-lang-yaml="`application`" pulumi-lang-java="`application`" pulumi-lang-hcl="`application`">`application`</span>, <span pulumi-lang-nodejs="`database`" pulumi-lang-dotnet="`Database`" pulumi-lang-go="`database`" pulumi-lang-python="`database`" pulumi-lang-yaml="`database`" pulumi-lang-java="`database`" pulumi-lang-hcl="`database`">`database`</span>, <span pulumi-lang-nodejs="`service`" pulumi-lang-dotnet="`Service`" pulumi-lang-go="`service`" pulumi-lang-python="`service`" pulumi-lang-yaml="`service`" pulumi-lang-java="`service`" pulumi-lang-hcl="`service`">`service`</span>.
	ResourceType string `pulumi:"resourceType"`
	// The UUID of the target resource (application, database, or service).
	ResourceUuid string `pulumi:"resourceUuid"`
	// An arbitrary map of values that, when changed, forces the action to run again.
	Triggers map[string]string `pulumi:"triggers"`
}

// The set of arguments for constructing a ResourceAction resource.
type ResourceActionArgs struct {
	// The action to perform. Must be one of: <span pulumi-lang-nodejs="`start`" pulumi-lang-dotnet="`Start`" pulumi-lang-go="`start`" pulumi-lang-python="`start`" pulumi-lang-yaml="`start`" pulumi-lang-java="`start`" pulumi-lang-hcl="`start`">`start`</span>, <span pulumi-lang-nodejs="`stop`" pulumi-lang-dotnet="`Stop`" pulumi-lang-go="`stop`" pulumi-lang-python="`stop`" pulumi-lang-yaml="`stop`" pulumi-lang-java="`stop`" pulumi-lang-hcl="`stop`">`stop`</span>, <span pulumi-lang-nodejs="`restart`" pulumi-lang-dotnet="`Restart`" pulumi-lang-go="`restart`" pulumi-lang-python="`restart`" pulumi-lang-yaml="`restart`" pulumi-lang-java="`restart`" pulumi-lang-hcl="`restart`">`restart`</span>.
	Action pulumi.StringInput
	// The type of the target resource. Must be one of: <span pulumi-lang-nodejs="`application`" pulumi-lang-dotnet="`Application`" pulumi-lang-go="`application`" pulumi-lang-python="`application`" pulumi-lang-yaml="`application`" pulumi-lang-java="`application`" pulumi-lang-hcl="`application`">`application`</span>, <span pulumi-lang-nodejs="`database`" pulumi-lang-dotnet="`Database`" pulumi-lang-go="`database`" pulumi-lang-python="`database`" pulumi-lang-yaml="`database`" pulumi-lang-java="`database`" pulumi-lang-hcl="`database`">`database`</span>, <span pulumi-lang-nodejs="`service`" pulumi-lang-dotnet="`Service`" pulumi-lang-go="`service`" pulumi-lang-python="`service`" pulumi-lang-yaml="`service`" pulumi-lang-java="`service`" pulumi-lang-hcl="`service`">`service`</span>.
	ResourceType pulumi.StringInput
	// The UUID of the target resource (application, database, or service).
	ResourceUuid pulumi.StringInput
	// An arbitrary map of values that, when changed, forces the action to run again.
	Triggers pulumi.StringMapInput
}

func (ResourceActionArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*resourceActionArgs)(nil)).Elem()
}

type ResourceActionInput interface {
	pulumi.Input

	ToResourceActionOutput() ResourceActionOutput
	ToResourceActionOutputWithContext(ctx context.Context) ResourceActionOutput
}

func (*ResourceAction) ElementType() reflect.Type {
	return reflect.TypeOf((**ResourceAction)(nil)).Elem()
}

func (i *ResourceAction) ToResourceActionOutput() ResourceActionOutput {
	return i.ToResourceActionOutputWithContext(context.Background())
}

func (i *ResourceAction) ToResourceActionOutputWithContext(ctx context.Context) ResourceActionOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ResourceActionOutput)
}

// ResourceActionArrayInput is an input type that accepts ResourceActionArray and ResourceActionArrayOutput values.
// You can construct a concrete instance of `ResourceActionArrayInput` via:
//
//	ResourceActionArray{ ResourceActionArgs{...} }
type ResourceActionArrayInput interface {
	pulumi.Input

	ToResourceActionArrayOutput() ResourceActionArrayOutput
	ToResourceActionArrayOutputWithContext(context.Context) ResourceActionArrayOutput
}

type ResourceActionArray []ResourceActionInput

func (ResourceActionArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ResourceAction)(nil)).Elem()
}

func (i ResourceActionArray) ToResourceActionArrayOutput() ResourceActionArrayOutput {
	return i.ToResourceActionArrayOutputWithContext(context.Background())
}

func (i ResourceActionArray) ToResourceActionArrayOutputWithContext(ctx context.Context) ResourceActionArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ResourceActionArrayOutput)
}

// ResourceActionMapInput is an input type that accepts ResourceActionMap and ResourceActionMapOutput values.
// You can construct a concrete instance of `ResourceActionMapInput` via:
//
//	ResourceActionMap{ "key": ResourceActionArgs{...} }
type ResourceActionMapInput interface {
	pulumi.Input

	ToResourceActionMapOutput() ResourceActionMapOutput
	ToResourceActionMapOutputWithContext(context.Context) ResourceActionMapOutput
}

type ResourceActionMap map[string]ResourceActionInput

func (ResourceActionMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ResourceAction)(nil)).Elem()
}

func (i ResourceActionMap) ToResourceActionMapOutput() ResourceActionMapOutput {
	return i.ToResourceActionMapOutputWithContext(context.Background())
}

func (i ResourceActionMap) ToResourceActionMapOutputWithContext(ctx context.Context) ResourceActionMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ResourceActionMapOutput)
}

type ResourceActionOutput struct{ *pulumi.OutputState }

func (ResourceActionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ResourceAction)(nil)).Elem()
}

func (o ResourceActionOutput) ToResourceActionOutput() ResourceActionOutput {
	return o
}

func (o ResourceActionOutput) ToResourceActionOutputWithContext(ctx context.Context) ResourceActionOutput {
	return o
}

// The action to perform. Must be one of: <span pulumi-lang-nodejs="`start`" pulumi-lang-dotnet="`Start`" pulumi-lang-go="`start`" pulumi-lang-python="`start`" pulumi-lang-yaml="`start`" pulumi-lang-java="`start`" pulumi-lang-hcl="`start`">`start`</span>, <span pulumi-lang-nodejs="`stop`" pulumi-lang-dotnet="`Stop`" pulumi-lang-go="`stop`" pulumi-lang-python="`stop`" pulumi-lang-yaml="`stop`" pulumi-lang-java="`stop`" pulumi-lang-hcl="`stop`">`stop`</span>, <span pulumi-lang-nodejs="`restart`" pulumi-lang-dotnet="`Restart`" pulumi-lang-go="`restart`" pulumi-lang-python="`restart`" pulumi-lang-yaml="`restart`" pulumi-lang-java="`restart`" pulumi-lang-hcl="`restart`">`restart`</span>.
func (o ResourceActionOutput) Action() pulumi.StringOutput {
	return o.ApplyT(func(v *ResourceAction) pulumi.StringOutput { return v.Action }).(pulumi.StringOutput)
}

// The type of the target resource. Must be one of: <span pulumi-lang-nodejs="`application`" pulumi-lang-dotnet="`Application`" pulumi-lang-go="`application`" pulumi-lang-python="`application`" pulumi-lang-yaml="`application`" pulumi-lang-java="`application`" pulumi-lang-hcl="`application`">`application`</span>, <span pulumi-lang-nodejs="`database`" pulumi-lang-dotnet="`Database`" pulumi-lang-go="`database`" pulumi-lang-python="`database`" pulumi-lang-yaml="`database`" pulumi-lang-java="`database`" pulumi-lang-hcl="`database`">`database`</span>, <span pulumi-lang-nodejs="`service`" pulumi-lang-dotnet="`Service`" pulumi-lang-go="`service`" pulumi-lang-python="`service`" pulumi-lang-yaml="`service`" pulumi-lang-java="`service`" pulumi-lang-hcl="`service`">`service`</span>.
func (o ResourceActionOutput) ResourceType() pulumi.StringOutput {
	return o.ApplyT(func(v *ResourceAction) pulumi.StringOutput { return v.ResourceType }).(pulumi.StringOutput)
}

// The UUID of the target resource (application, database, or service).
func (o ResourceActionOutput) ResourceUuid() pulumi.StringOutput {
	return o.ApplyT(func(v *ResourceAction) pulumi.StringOutput { return v.ResourceUuid }).(pulumi.StringOutput)
}

// An arbitrary map of values that, when changed, forces the action to run again.
func (o ResourceActionOutput) Triggers() pulumi.StringMapOutput {
	return o.ApplyT(func(v *ResourceAction) pulumi.StringMapOutput { return v.Triggers }).(pulumi.StringMapOutput)
}

type ResourceActionArrayOutput struct{ *pulumi.OutputState }

func (ResourceActionArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ResourceAction)(nil)).Elem()
}

func (o ResourceActionArrayOutput) ToResourceActionArrayOutput() ResourceActionArrayOutput {
	return o
}

func (o ResourceActionArrayOutput) ToResourceActionArrayOutputWithContext(ctx context.Context) ResourceActionArrayOutput {
	return o
}

func (o ResourceActionArrayOutput) Index(i pulumi.IntInput) ResourceActionOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ResourceAction {
		return vs[0].([]*ResourceAction)[vs[1].(int)]
	}).(ResourceActionOutput)
}

type ResourceActionMapOutput struct{ *pulumi.OutputState }

func (ResourceActionMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ResourceAction)(nil)).Elem()
}

func (o ResourceActionMapOutput) ToResourceActionMapOutput() ResourceActionMapOutput {
	return o
}

func (o ResourceActionMapOutput) ToResourceActionMapOutputWithContext(ctx context.Context) ResourceActionMapOutput {
	return o
}

func (o ResourceActionMapOutput) MapIndex(k pulumi.StringInput) ResourceActionOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ResourceAction {
		return vs[0].(map[string]*ResourceAction)[vs[1].(string)]
	}).(ResourceActionOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ResourceActionInput)(nil)).Elem(), &ResourceAction{})
	pulumi.RegisterInputType(reflect.TypeOf((*ResourceActionArrayInput)(nil)).Elem(), ResourceActionArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ResourceActionMapInput)(nil)).Elem(), ResourceActionMap{})
	pulumi.RegisterOutputType(ResourceActionOutput{})
	pulumi.RegisterOutputType(ResourceActionArrayOutput{})
	pulumi.RegisterOutputType(ResourceActionMapOutput{})
}
