// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package coolify

import (
	"context"
	"reflect"

	"errors"
	"github.com/mheers/pulumi-provider-coolify/sdk/go/coolify/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Manages a scheduled task on a Coolify application or service.
//
// > **Note:** Each instance requires a List API call to read because the Coolify API does not provide a singular GET endpoint for scheduled tasks. Large numbers of these resources on a single parent resource may cause slower plan/apply times due to this API limitation.
//
// ## Example Usage
//
// <!--Start PulumiCodeChooser -->
// ```go
// package main
//
// import (
//
//	"github.com/mheers/pulumi-provider-coolify/sdk/go/coolify"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			// Create a scheduled task on an application
//			_, err := coolify.NewScheduledTask(ctx, "backup", &coolify.ScheduledTaskArgs{
//				ApplicationUuid: pulumi.Any(example.Uuid),
//				Name:            pulumi.String("backup-database"),
//				Command:         pulumi.String("pg_dump mydb > /backups/mydb.sql"),
//				Frequency:       pulumi.String("0 2 * * *"),
//				Enabled:         pulumi.Bool(true),
//			})
//			if err != nil {
//				return err
//			}
//			// Create a scheduled task on a service
//			_, err = coolify.NewScheduledTask(ctx, "health_check", &coolify.ScheduledTaskArgs{
//				ServiceUuid: pulumi.Any(exampleCoolifyService.Uuid),
//				Name:        pulumi.String("health-check"),
//				Command:     pulumi.String("curl -f http://localhost/health || exit 1"),
//				Frequency:   pulumi.String("*/5 * * * *"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
// <!--End PulumiCodeChooser -->
//
// ## Import
//
// The `pulumi import` command can be used, for example:
//
// Import a scheduled task on an application:
//
// ```sh
// $ pulumi import coolify:index/scheduledTask:ScheduledTask example application:<application-uuid>:<task-uuid>
// ```
//
// Import a scheduled task on a service:
//
// ```sh
// $ pulumi import coolify:index/scheduledTask:ScheduledTask example service:<service-uuid>:<task-uuid>
// ```
type ScheduledTask struct {
	pulumi.CustomResourceState

	// The UUID of the application to create the scheduled task on. Exactly one of <span pulumi-lang-nodejs="`applicationUuid`" pulumi-lang-dotnet="`ApplicationUuid`" pulumi-lang-go="`applicationUuid`" pulumi-lang-python="`application_uuid`" pulumi-lang-yaml="`applicationUuid`" pulumi-lang-java="`applicationUuid`" pulumi-lang-hcl="`application_uuid`">`applicationUuid`</span> or <span pulumi-lang-nodejs="`serviceUuid`" pulumi-lang-dotnet="`ServiceUuid`" pulumi-lang-go="`serviceUuid`" pulumi-lang-python="`service_uuid`" pulumi-lang-yaml="`serviceUuid`" pulumi-lang-java="`serviceUuid`" pulumi-lang-hcl="`service_uuid`">`serviceUuid`</span> must be provided. Changing this forces a new resource.
	ApplicationUuid pulumi.StringPtrOutput `pulumi:"applicationUuid"`
	// The command to execute.
	Command pulumi.StringOutput `pulumi:"command"`
	// Container name where the command runs (for multi-container applications or services). When omitted, Coolify uses its default container selection.
	Container pulumi.StringOutput `pulumi:"container"`
	// Whether the scheduled task is enabled (defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>).
	Enabled pulumi.BoolOutput `pulumi:"enabled"`
	// Cron or Coolify human schedule (e.g., `*/5 * * * *`, <span pulumi-lang-nodejs="`daily`" pulumi-lang-dotnet="`Daily`" pulumi-lang-go="`daily`" pulumi-lang-python="`daily`" pulumi-lang-yaml="`daily`" pulumi-lang-java="`daily`" pulumi-lang-hcl="`daily`">`daily`</span>, `@daily`). Six-field cron is allowed for tasks.
	Frequency pulumi.StringOutput `pulumi:"frequency"`
	// The name of the scheduled task.
	Name pulumi.StringOutput `pulumi:"name"`
	// The UUID of the service to create the scheduled task on. Exactly one of <span pulumi-lang-nodejs="`applicationUuid`" pulumi-lang-dotnet="`ApplicationUuid`" pulumi-lang-go="`applicationUuid`" pulumi-lang-python="`application_uuid`" pulumi-lang-yaml="`applicationUuid`" pulumi-lang-java="`applicationUuid`" pulumi-lang-hcl="`application_uuid`">`applicationUuid`</span> or <span pulumi-lang-nodejs="`serviceUuid`" pulumi-lang-dotnet="`ServiceUuid`" pulumi-lang-go="`serviceUuid`" pulumi-lang-python="`service_uuid`" pulumi-lang-yaml="`serviceUuid`" pulumi-lang-java="`serviceUuid`" pulumi-lang-hcl="`service_uuid`">`serviceUuid`</span> must be provided. Changing this forces a new resource.
	ServiceUuid pulumi.StringPtrOutput `pulumi:"serviceUuid"`
	// Maximum run time for the task in seconds. Coolify defaults to <span pulumi-lang-nodejs="`300`" pulumi-lang-dotnet="`300`" pulumi-lang-go="`300`" pulumi-lang-python="`300`" pulumi-lang-yaml="`300`" pulumi-lang-java="`300`" pulumi-lang-hcl="`300`">`300`</span> when omitted on create.
	Timeout pulumi.IntOutput `pulumi:"timeout"`
	// The unique identifier of the scheduled task.
	Uuid pulumi.StringOutput `pulumi:"uuid"`
}

// NewScheduledTask registers a new resource with the given unique name, arguments, and options.
func NewScheduledTask(ctx *pulumi.Context,
	name string, args *ScheduledTaskArgs, opts ...pulumi.ResourceOption) (*ScheduledTask, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Command == nil {
		return nil, errors.New("invalid value for required argument 'Command'")
	}
	if args.Frequency == nil {
		return nil, errors.New("invalid value for required argument 'Frequency'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ScheduledTask
	err := ctx.RegisterResource("coolify:index/scheduledTask:ScheduledTask", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetScheduledTask gets an existing ScheduledTask resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetScheduledTask(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ScheduledTaskState, opts ...pulumi.ResourceOption) (*ScheduledTask, error) {
	var resource ScheduledTask
	err := ctx.ReadResource("coolify:index/scheduledTask:ScheduledTask", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ScheduledTask resources.
type scheduledTaskState struct {
	// The UUID of the application to create the scheduled task on. Exactly one of <span pulumi-lang-nodejs="`applicationUuid`" pulumi-lang-dotnet="`ApplicationUuid`" pulumi-lang-go="`applicationUuid`" pulumi-lang-python="`application_uuid`" pulumi-lang-yaml="`applicationUuid`" pulumi-lang-java="`applicationUuid`" pulumi-lang-hcl="`application_uuid`">`applicationUuid`</span> or <span pulumi-lang-nodejs="`serviceUuid`" pulumi-lang-dotnet="`ServiceUuid`" pulumi-lang-go="`serviceUuid`" pulumi-lang-python="`service_uuid`" pulumi-lang-yaml="`serviceUuid`" pulumi-lang-java="`serviceUuid`" pulumi-lang-hcl="`service_uuid`">`serviceUuid`</span> must be provided. Changing this forces a new resource.
	ApplicationUuid *string `pulumi:"applicationUuid"`
	// The command to execute.
	Command *string `pulumi:"command"`
	// Container name where the command runs (for multi-container applications or services). When omitted, Coolify uses its default container selection.
	Container *string `pulumi:"container"`
	// Whether the scheduled task is enabled (defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>).
	Enabled *bool `pulumi:"enabled"`
	// Cron or Coolify human schedule (e.g., `*/5 * * * *`, <span pulumi-lang-nodejs="`daily`" pulumi-lang-dotnet="`Daily`" pulumi-lang-go="`daily`" pulumi-lang-python="`daily`" pulumi-lang-yaml="`daily`" pulumi-lang-java="`daily`" pulumi-lang-hcl="`daily`">`daily`</span>, `@daily`). Six-field cron is allowed for tasks.
	Frequency *string `pulumi:"frequency"`
	// The name of the scheduled task.
	Name *string `pulumi:"name"`
	// The UUID of the service to create the scheduled task on. Exactly one of <span pulumi-lang-nodejs="`applicationUuid`" pulumi-lang-dotnet="`ApplicationUuid`" pulumi-lang-go="`applicationUuid`" pulumi-lang-python="`application_uuid`" pulumi-lang-yaml="`applicationUuid`" pulumi-lang-java="`applicationUuid`" pulumi-lang-hcl="`application_uuid`">`applicationUuid`</span> or <span pulumi-lang-nodejs="`serviceUuid`" pulumi-lang-dotnet="`ServiceUuid`" pulumi-lang-go="`serviceUuid`" pulumi-lang-python="`service_uuid`" pulumi-lang-yaml="`serviceUuid`" pulumi-lang-java="`serviceUuid`" pulumi-lang-hcl="`service_uuid`">`serviceUuid`</span> must be provided. Changing this forces a new resource.
	ServiceUuid *string `pulumi:"serviceUuid"`
	// Maximum run time for the task in seconds. Coolify defaults to <span pulumi-lang-nodejs="`300`" pulumi-lang-dotnet="`300`" pulumi-lang-go="`300`" pulumi-lang-python="`300`" pulumi-lang-yaml="`300`" pulumi-lang-java="`300`" pulumi-lang-hcl="`300`">`300`</span> when omitted on create.
	Timeout *int `pulumi:"timeout"`
	// The unique identifier of the scheduled task.
	Uuid *string `pulumi:"uuid"`
}

type ScheduledTaskState struct {
	// The UUID of the application to create the scheduled task on. Exactly one of <span pulumi-lang-nodejs="`applicationUuid`" pulumi-lang-dotnet="`ApplicationUuid`" pulumi-lang-go="`applicationUuid`" pulumi-lang-python="`application_uuid`" pulumi-lang-yaml="`applicationUuid`" pulumi-lang-java="`applicationUuid`" pulumi-lang-hcl="`application_uuid`">`applicationUuid`</span> or <span pulumi-lang-nodejs="`serviceUuid`" pulumi-lang-dotnet="`ServiceUuid`" pulumi-lang-go="`serviceUuid`" pulumi-lang-python="`service_uuid`" pulumi-lang-yaml="`serviceUuid`" pulumi-lang-java="`serviceUuid`" pulumi-lang-hcl="`service_uuid`">`serviceUuid`</span> must be provided. Changing this forces a new resource.
	ApplicationUuid pulumi.StringPtrInput
	// The command to execute.
	Command pulumi.StringPtrInput
	// Container name where the command runs (for multi-container applications or services). When omitted, Coolify uses its default container selection.
	Container pulumi.StringPtrInput
	// Whether the scheduled task is enabled (defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>).
	Enabled pulumi.BoolPtrInput
	// Cron or Coolify human schedule (e.g., `*/5 * * * *`, <span pulumi-lang-nodejs="`daily`" pulumi-lang-dotnet="`Daily`" pulumi-lang-go="`daily`" pulumi-lang-python="`daily`" pulumi-lang-yaml="`daily`" pulumi-lang-java="`daily`" pulumi-lang-hcl="`daily`">`daily`</span>, `@daily`). Six-field cron is allowed for tasks.
	Frequency pulumi.StringPtrInput
	// The name of the scheduled task.
	Name pulumi.StringPtrInput
	// The UUID of the service to create the scheduled task on. Exactly one of <span pulumi-lang-nodejs="`applicationUuid`" pulumi-lang-dotnet="`ApplicationUuid`" pulumi-lang-go="`applicationUuid`" pulumi-lang-python="`application_uuid`" pulumi-lang-yaml="`applicationUuid`" pulumi-lang-java="`applicationUuid`" pulumi-lang-hcl="`application_uuid`">`applicationUuid`</span> or <span pulumi-lang-nodejs="`serviceUuid`" pulumi-lang-dotnet="`ServiceUuid`" pulumi-lang-go="`serviceUuid`" pulumi-lang-python="`service_uuid`" pulumi-lang-yaml="`serviceUuid`" pulumi-lang-java="`serviceUuid`" pulumi-lang-hcl="`service_uuid`">`serviceUuid`</span> must be provided. Changing this forces a new resource.
	ServiceUuid pulumi.StringPtrInput
	// Maximum run time for the task in seconds. Coolify defaults to <span pulumi-lang-nodejs="`300`" pulumi-lang-dotnet="`300`" pulumi-lang-go="`300`" pulumi-lang-python="`300`" pulumi-lang-yaml="`300`" pulumi-lang-java="`300`" pulumi-lang-hcl="`300`">`300`</span> when omitted on create.
	Timeout pulumi.IntPtrInput
	// The unique identifier of the scheduled task.
	Uuid pulumi.StringPtrInput
}

func (ScheduledTaskState) ElementType() reflect.Type {
	return reflect.TypeOf((*scheduledTaskState)(nil)).Elem()
}

type scheduledTaskArgs struct {
	// The UUID of the application to create the scheduled task on. Exactly one of <span pulumi-lang-nodejs="`applicationUuid`" pulumi-lang-dotnet="`ApplicationUuid`" pulumi-lang-go="`applicationUuid`" pulumi-lang-python="`application_uuid`" pulumi-lang-yaml="`applicationUuid`" pulumi-lang-java="`applicationUuid`" pulumi-lang-hcl="`application_uuid`">`applicationUuid`</span> or <span pulumi-lang-nodejs="`serviceUuid`" pulumi-lang-dotnet="`ServiceUuid`" pulumi-lang-go="`serviceUuid`" pulumi-lang-python="`service_uuid`" pulumi-lang-yaml="`serviceUuid`" pulumi-lang-java="`serviceUuid`" pulumi-lang-hcl="`service_uuid`">`serviceUuid`</span> must be provided. Changing this forces a new resource.
	ApplicationUuid *string `pulumi:"applicationUuid"`
	// The command to execute.
	Command string `pulumi:"command"`
	// Container name where the command runs (for multi-container applications or services). When omitted, Coolify uses its default container selection.
	Container *string `pulumi:"container"`
	// Whether the scheduled task is enabled (defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>).
	Enabled *bool `pulumi:"enabled"`
	// Cron or Coolify human schedule (e.g., `*/5 * * * *`, <span pulumi-lang-nodejs="`daily`" pulumi-lang-dotnet="`Daily`" pulumi-lang-go="`daily`" pulumi-lang-python="`daily`" pulumi-lang-yaml="`daily`" pulumi-lang-java="`daily`" pulumi-lang-hcl="`daily`">`daily`</span>, `@daily`). Six-field cron is allowed for tasks.
	Frequency string `pulumi:"frequency"`
	// The name of the scheduled task.
	Name *string `pulumi:"name"`
	// The UUID of the service to create the scheduled task on. Exactly one of <span pulumi-lang-nodejs="`applicationUuid`" pulumi-lang-dotnet="`ApplicationUuid`" pulumi-lang-go="`applicationUuid`" pulumi-lang-python="`application_uuid`" pulumi-lang-yaml="`applicationUuid`" pulumi-lang-java="`applicationUuid`" pulumi-lang-hcl="`application_uuid`">`applicationUuid`</span> or <span pulumi-lang-nodejs="`serviceUuid`" pulumi-lang-dotnet="`ServiceUuid`" pulumi-lang-go="`serviceUuid`" pulumi-lang-python="`service_uuid`" pulumi-lang-yaml="`serviceUuid`" pulumi-lang-java="`serviceUuid`" pulumi-lang-hcl="`service_uuid`">`serviceUuid`</span> must be provided. Changing this forces a new resource.
	ServiceUuid *string `pulumi:"serviceUuid"`
	// Maximum run time for the task in seconds. Coolify defaults to <span pulumi-lang-nodejs="`300`" pulumi-lang-dotnet="`300`" pulumi-lang-go="`300`" pulumi-lang-python="`300`" pulumi-lang-yaml="`300`" pulumi-lang-java="`300`" pulumi-lang-hcl="`300`">`300`</span> when omitted on create.
	Timeout *int `pulumi:"timeout"`
}

// The set of arguments for constructing a ScheduledTask resource.
type ScheduledTaskArgs struct {
	// The UUID of the application to create the scheduled task on. Exactly one of <span pulumi-lang-nodejs="`applicationUuid`" pulumi-lang-dotnet="`ApplicationUuid`" pulumi-lang-go="`applicationUuid`" pulumi-lang-python="`application_uuid`" pulumi-lang-yaml="`applicationUuid`" pulumi-lang-java="`applicationUuid`" pulumi-lang-hcl="`application_uuid`">`applicationUuid`</span> or <span pulumi-lang-nodejs="`serviceUuid`" pulumi-lang-dotnet="`ServiceUuid`" pulumi-lang-go="`serviceUuid`" pulumi-lang-python="`service_uuid`" pulumi-lang-yaml="`serviceUuid`" pulumi-lang-java="`serviceUuid`" pulumi-lang-hcl="`service_uuid`">`serviceUuid`</span> must be provided. Changing this forces a new resource.
	ApplicationUuid pulumi.StringPtrInput
	// The command to execute.
	Command pulumi.StringInput
	// Container name where the command runs (for multi-container applications or services). When omitted, Coolify uses its default container selection.
	Container pulumi.StringPtrInput
	// Whether the scheduled task is enabled (defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>).
	Enabled pulumi.BoolPtrInput
	// Cron or Coolify human schedule (e.g., `*/5 * * * *`, <span pulumi-lang-nodejs="`daily`" pulumi-lang-dotnet="`Daily`" pulumi-lang-go="`daily`" pulumi-lang-python="`daily`" pulumi-lang-yaml="`daily`" pulumi-lang-java="`daily`" pulumi-lang-hcl="`daily`">`daily`</span>, `@daily`). Six-field cron is allowed for tasks.
	Frequency pulumi.StringInput
	// The name of the scheduled task.
	Name pulumi.StringPtrInput
	// The UUID of the service to create the scheduled task on. Exactly one of <span pulumi-lang-nodejs="`applicationUuid`" pulumi-lang-dotnet="`ApplicationUuid`" pulumi-lang-go="`applicationUuid`" pulumi-lang-python="`application_uuid`" pulumi-lang-yaml="`applicationUuid`" pulumi-lang-java="`applicationUuid`" pulumi-lang-hcl="`application_uuid`">`applicationUuid`</span> or <span pulumi-lang-nodejs="`serviceUuid`" pulumi-lang-dotnet="`ServiceUuid`" pulumi-lang-go="`serviceUuid`" pulumi-lang-python="`service_uuid`" pulumi-lang-yaml="`serviceUuid`" pulumi-lang-java="`serviceUuid`" pulumi-lang-hcl="`service_uuid`">`serviceUuid`</span> must be provided. Changing this forces a new resource.
	ServiceUuid pulumi.StringPtrInput
	// Maximum run time for the task in seconds. Coolify defaults to <span pulumi-lang-nodejs="`300`" pulumi-lang-dotnet="`300`" pulumi-lang-go="`300`" pulumi-lang-python="`300`" pulumi-lang-yaml="`300`" pulumi-lang-java="`300`" pulumi-lang-hcl="`300`">`300`</span> when omitted on create.
	Timeout pulumi.IntPtrInput
}

func (ScheduledTaskArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*scheduledTaskArgs)(nil)).Elem()
}

type ScheduledTaskInput interface {
	pulumi.Input

	ToScheduledTaskOutput() ScheduledTaskOutput
	ToScheduledTaskOutputWithContext(ctx context.Context) ScheduledTaskOutput
}

func (*ScheduledTask) ElementType() reflect.Type {
	return reflect.TypeOf((**ScheduledTask)(nil)).Elem()
}

func (i *ScheduledTask) ToScheduledTaskOutput() ScheduledTaskOutput {
	return i.ToScheduledTaskOutputWithContext(context.Background())
}

func (i *ScheduledTask) ToScheduledTaskOutputWithContext(ctx context.Context) ScheduledTaskOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ScheduledTaskOutput)
}

// ScheduledTaskArrayInput is an input type that accepts ScheduledTaskArray and ScheduledTaskArrayOutput values.
// You can construct a concrete instance of `ScheduledTaskArrayInput` via:
//
//	ScheduledTaskArray{ ScheduledTaskArgs{...} }
type ScheduledTaskArrayInput interface {
	pulumi.Input

	ToScheduledTaskArrayOutput() ScheduledTaskArrayOutput
	ToScheduledTaskArrayOutputWithContext(context.Context) ScheduledTaskArrayOutput
}

type ScheduledTaskArray []ScheduledTaskInput

func (ScheduledTaskArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ScheduledTask)(nil)).Elem()
}

func (i ScheduledTaskArray) ToScheduledTaskArrayOutput() ScheduledTaskArrayOutput {
	return i.ToScheduledTaskArrayOutputWithContext(context.Background())
}

func (i ScheduledTaskArray) ToScheduledTaskArrayOutputWithContext(ctx context.Context) ScheduledTaskArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ScheduledTaskArrayOutput)
}

// ScheduledTaskMapInput is an input type that accepts ScheduledTaskMap and ScheduledTaskMapOutput values.
// You can construct a concrete instance of `ScheduledTaskMapInput` via:
//
//	ScheduledTaskMap{ "key": ScheduledTaskArgs{...} }
type ScheduledTaskMapInput interface {
	pulumi.Input

	ToScheduledTaskMapOutput() ScheduledTaskMapOutput
	ToScheduledTaskMapOutputWithContext(context.Context) ScheduledTaskMapOutput
}

type ScheduledTaskMap map[string]ScheduledTaskInput

func (ScheduledTaskMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ScheduledTask)(nil)).Elem()
}

func (i ScheduledTaskMap) ToScheduledTaskMapOutput() ScheduledTaskMapOutput {
	return i.ToScheduledTaskMapOutputWithContext(context.Background())
}

func (i ScheduledTaskMap) ToScheduledTaskMapOutputWithContext(ctx context.Context) ScheduledTaskMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ScheduledTaskMapOutput)
}

type ScheduledTaskOutput struct{ *pulumi.OutputState }

func (ScheduledTaskOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ScheduledTask)(nil)).Elem()
}

func (o ScheduledTaskOutput) ToScheduledTaskOutput() ScheduledTaskOutput {
	return o
}

func (o ScheduledTaskOutput) ToScheduledTaskOutputWithContext(ctx context.Context) ScheduledTaskOutput {
	return o
}

// The UUID of the application to create the scheduled task on. Exactly one of <span pulumi-lang-nodejs="`applicationUuid`" pulumi-lang-dotnet="`ApplicationUuid`" pulumi-lang-go="`applicationUuid`" pulumi-lang-python="`application_uuid`" pulumi-lang-yaml="`applicationUuid`" pulumi-lang-java="`applicationUuid`" pulumi-lang-hcl="`application_uuid`">`applicationUuid`</span> or <span pulumi-lang-nodejs="`serviceUuid`" pulumi-lang-dotnet="`ServiceUuid`" pulumi-lang-go="`serviceUuid`" pulumi-lang-python="`service_uuid`" pulumi-lang-yaml="`serviceUuid`" pulumi-lang-java="`serviceUuid`" pulumi-lang-hcl="`service_uuid`">`serviceUuid`</span> must be provided. Changing this forces a new resource.
func (o ScheduledTaskOutput) ApplicationUuid() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ScheduledTask) pulumi.StringPtrOutput { return v.ApplicationUuid }).(pulumi.StringPtrOutput)
}

// The command to execute.
func (o ScheduledTaskOutput) Command() pulumi.StringOutput {
	return o.ApplyT(func(v *ScheduledTask) pulumi.StringOutput { return v.Command }).(pulumi.StringOutput)
}

// Container name where the command runs (for multi-container applications or services). When omitted, Coolify uses its default container selection.
func (o ScheduledTaskOutput) Container() pulumi.StringOutput {
	return o.ApplyT(func(v *ScheduledTask) pulumi.StringOutput { return v.Container }).(pulumi.StringOutput)
}

// Whether the scheduled task is enabled (defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>).
func (o ScheduledTaskOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *ScheduledTask) pulumi.BoolOutput { return v.Enabled }).(pulumi.BoolOutput)
}

// Cron or Coolify human schedule (e.g., `*/5 * * * *`, <span pulumi-lang-nodejs="`daily`" pulumi-lang-dotnet="`Daily`" pulumi-lang-go="`daily`" pulumi-lang-python="`daily`" pulumi-lang-yaml="`daily`" pulumi-lang-java="`daily`" pulumi-lang-hcl="`daily`">`daily`</span>, `@daily`). Six-field cron is allowed for tasks.
func (o ScheduledTaskOutput) Frequency() pulumi.StringOutput {
	return o.ApplyT(func(v *ScheduledTask) pulumi.StringOutput { return v.Frequency }).(pulumi.StringOutput)
}

// The name of the scheduled task.
func (o ScheduledTaskOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *ScheduledTask) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The UUID of the service to create the scheduled task on. Exactly one of <span pulumi-lang-nodejs="`applicationUuid`" pulumi-lang-dotnet="`ApplicationUuid`" pulumi-lang-go="`applicationUuid`" pulumi-lang-python="`application_uuid`" pulumi-lang-yaml="`applicationUuid`" pulumi-lang-java="`applicationUuid`" pulumi-lang-hcl="`application_uuid`">`applicationUuid`</span> or <span pulumi-lang-nodejs="`serviceUuid`" pulumi-lang-dotnet="`ServiceUuid`" pulumi-lang-go="`serviceUuid`" pulumi-lang-python="`service_uuid`" pulumi-lang-yaml="`serviceUuid`" pulumi-lang-java="`serviceUuid`" pulumi-lang-hcl="`service_uuid`">`serviceUuid`</span> must be provided. Changing this forces a new resource.
func (o ScheduledTaskOutput) ServiceUuid() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ScheduledTask) pulumi.StringPtrOutput { return v.ServiceUuid }).(pulumi.StringPtrOutput)
}

// Maximum run time for the task in seconds. Coolify defaults to <span pulumi-lang-nodejs="`300`" pulumi-lang-dotnet="`300`" pulumi-lang-go="`300`" pulumi-lang-python="`300`" pulumi-lang-yaml="`300`" pulumi-lang-java="`300`" pulumi-lang-hcl="`300`">`300`</span> when omitted on create.
func (o ScheduledTaskOutput) Timeout() pulumi.IntOutput {
	return o.ApplyT(func(v *ScheduledTask) pulumi.IntOutput { return v.Timeout }).(pulumi.IntOutput)
}

// The unique identifier of the scheduled task.
func (o ScheduledTaskOutput) Uuid() pulumi.StringOutput {
	return o.ApplyT(func(v *ScheduledTask) pulumi.StringOutput { return v.Uuid }).(pulumi.StringOutput)
}

type ScheduledTaskArrayOutput struct{ *pulumi.OutputState }

func (ScheduledTaskArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ScheduledTask)(nil)).Elem()
}

func (o ScheduledTaskArrayOutput) ToScheduledTaskArrayOutput() ScheduledTaskArrayOutput {
	return o
}

func (o ScheduledTaskArrayOutput) ToScheduledTaskArrayOutputWithContext(ctx context.Context) ScheduledTaskArrayOutput {
	return o
}

func (o ScheduledTaskArrayOutput) Index(i pulumi.IntInput) ScheduledTaskOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ScheduledTask {
		return vs[0].([]*ScheduledTask)[vs[1].(int)]
	}).(ScheduledTaskOutput)
}

type ScheduledTaskMapOutput struct{ *pulumi.OutputState }

func (ScheduledTaskMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ScheduledTask)(nil)).Elem()
}

func (o ScheduledTaskMapOutput) ToScheduledTaskMapOutput() ScheduledTaskMapOutput {
	return o
}

func (o ScheduledTaskMapOutput) ToScheduledTaskMapOutputWithContext(ctx context.Context) ScheduledTaskMapOutput {
	return o
}

func (o ScheduledTaskMapOutput) MapIndex(k pulumi.StringInput) ScheduledTaskOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ScheduledTask {
		return vs[0].(map[string]*ScheduledTask)[vs[1].(string)]
	}).(ScheduledTaskOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ScheduledTaskInput)(nil)).Elem(), &ScheduledTask{})
	pulumi.RegisterInputType(reflect.TypeOf((*ScheduledTaskArrayInput)(nil)).Elem(), ScheduledTaskArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ScheduledTaskMapInput)(nil)).Elem(), ScheduledTaskMap{})
	pulumi.RegisterOutputType(ScheduledTaskOutput{})
	pulumi.RegisterOutputType(ScheduledTaskArrayOutput{})
	pulumi.RegisterOutputType(ScheduledTaskMapOutput{})
}
