// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package coolify

import (
	"context"
	"reflect"

	"errors"
	"github.com/mheers/pulumi-provider-coolify/sdk/go/coolify/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Provisions a Vultr instance and registers it with Coolify. Requires Coolify >= v4.2.0.
//
// > **Warning:** Deleting this resource will delete the server from Coolify and cascade-delete all applications, databases, and services deployed on it. The underlying Vultr server is not destroyed; manage its lifecycle separately.
//
// > **Import note:** Vultr-specific fields (<span pulumi-lang-nodejs="`cloudProviderTokenUuid`" pulumi-lang-dotnet="`CloudProviderTokenUuid`" pulumi-lang-go="`cloudProviderTokenUuid`" pulumi-lang-python="`cloud_provider_token_uuid`" pulumi-lang-yaml="`cloudProviderTokenUuid`" pulumi-lang-java="`cloudProviderTokenUuid`" pulumi-lang-hcl="`cloud_provider_token_uuid`">`cloudProviderTokenUuid`</span>, <span pulumi-lang-nodejs="`plan`" pulumi-lang-dotnet="`Plan`" pulumi-lang-go="`plan`" pulumi-lang-python="`plan`" pulumi-lang-yaml="`plan`" pulumi-lang-java="`plan`" pulumi-lang-hcl="`plan`">`plan`</span>, <span pulumi-lang-nodejs="`region`" pulumi-lang-dotnet="`Region`" pulumi-lang-go="`region`" pulumi-lang-python="`region`" pulumi-lang-yaml="`region`" pulumi-lang-java="`region`" pulumi-lang-hcl="`region`">`region`</span>, <span pulumi-lang-nodejs="`osId`" pulumi-lang-dotnet="`OsId`" pulumi-lang-go="`osId`" pulumi-lang-python="`os_id`" pulumi-lang-yaml="`osId`" pulumi-lang-java="`osId`" pulumi-lang-hcl="`os_id`">`osId`</span>, <span pulumi-lang-nodejs="`vultrSshKeyIds`" pulumi-lang-dotnet="`VultrSshKeyIds`" pulumi-lang-go="`vultrSshKeyIds`" pulumi-lang-python="`vultr_ssh_key_ids`" pulumi-lang-yaml="`vultrSshKeyIds`" pulumi-lang-java="`vultrSshKeyIds`" pulumi-lang-hcl="`vultr_ssh_key_ids`">`vultrSshKeyIds`</span>, <span pulumi-lang-nodejs="`cloudInitScript`" pulumi-lang-dotnet="`CloudInitScript`" pulumi-lang-go="`cloudInitScript`" pulumi-lang-python="`cloud_init_script`" pulumi-lang-yaml="`cloudInitScript`" pulumi-lang-java="`cloudInitScript`" pulumi-lang-hcl="`cloud_init_script`">`cloudInitScript`</span>) are only sent at creation time and are not returned by the Coolify API. After `pulumi import`, these fields will be empty in state. Set them in your configuration before running `pulumi preview` to avoid a forced replacement.
//
// ## Example Usage
//
// <!--Start PulumiCodeChooser -->
// ```go
// package main
//
// import (
//
//	"github.com/mheers/pulumi-provider-coolify/sdk/go/coolify"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			cfg := config.New(ctx, "")
//			vultrToken := cfg.Require("vultrToken")
//			vultr, err := coolify.NewCloudToken(ctx, "vultr", &coolify.CloudTokenArgs{
//				Name:          pulumi.String("vultr"),
//				CloudProvider: pulumi.String("vultr"),
//				Token:         pulumi.String(vultrToken),
//			})
//			if err != nil {
//				return err
//			}
//			_, err = coolify.NewServerVultr(ctx, "app", &coolify.ServerVultrArgs{
//				Name:                   pulumi.String("vultr-app-node"),
//				CloudProviderTokenUuid: vultr.Uuid,
//				Region:                 pulumi.String("ewr"),
//				Plan:                   pulumi.String("vc2-1c-1gb"),
//				OsId:                   pulumi.Int(1743),
//				PrivateKeyUuid:         pulumi.Any(main.Uuid),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
// <!--End PulumiCodeChooser -->
//
// ## Import
//
// The `pulumi import` command can be used, for example:
//
// !/bin/sh
//
// ```sh
// $ pulumi import coolify:index/serverVultr:ServerVultr app <server-uuid>
// ```
type ServerVultr struct {
	pulumi.CustomResourceState

	// CPU percentage Coolify uses when compressing volume backups. Read-only (not on public server PATCH). Present on Coolify >= v4.3.3; empty on older instances.
	BackupCompressionCpuPercentage pulumi.IntOutput `pulumi:"backupCompressionCpuPercentage"`
	// Cloud-init script to run on server creation. Changing this forces a new resource.
	CloudInitScript pulumi.StringPtrOutput `pulumi:"cloudInitScript"`
	// The UUID of the Vultr cloud provider token (from <span pulumi-lang-nodejs="`coolify.CloudToken`" pulumi-lang-dotnet="`coolify.CloudToken`" pulumi-lang-go="`CloudToken`" pulumi-lang-python="`CloudToken`" pulumi-lang-yaml="`coolify.CloudToken`" pulumi-lang-java="`coolify.CloudToken`" pulumi-lang-hcl="`coolify_cloud_token`">`coolify.CloudToken`</span>). Changing this forces a new resource.
	CloudProviderTokenUuid pulumi.StringOutput `pulumi:"cloudProviderTokenUuid"`
	// Docker Compose version reported by Coolify for this server (host probe). Read-only; Populated on Coolify >= v4.3.2 when the host has been probed. Empty on older instances.
	ComposeVersion pulumi.StringOutput `pulumi:"composeVersion"`
	// When Coolify last checked the Compose version on this server. Read-only.
	ComposeVersionCheckedAt pulumi.StringOutput `pulumi:"composeVersionCheckedAt"`
	// How many deployments can run in parallel on this server.
	ConcurrentBuilds pulumi.IntOutput `pulumi:"concurrentBuilds"`
	// SSH connection timeout in seconds.
	ConnectionTimeout pulumi.IntOutput `pulumi:"connectionTimeout"`
	// Whether to delete unused Docker networks during cleanup.
	DeleteUnusedNetworks pulumi.BoolOutput `pulumi:"deleteUnusedNetworks"`
	// Whether to delete unused Docker volumes during cleanup.
	DeleteUnusedVolumes pulumi.BoolOutput `pulumi:"deleteUnusedVolumes"`
	// Maximum number of queued deployments (default 25).
	DeploymentQueueLimit pulumi.IntOutput `pulumi:"deploymentQueueLimit"`
	// A description of the server.
	Description pulumi.StringOutput `pulumi:"description"`
	// Whether application image retention is disabled. Read-only (not on public server PATCH allow-list).
	DisableApplicationImageRetention pulumi.BoolOutput `pulumi:"disableApplicationImageRetention"`
	// Whether to disable public IPv4 on the Vultr instance.
	DisablePublicIpv4 pulumi.BoolOutput `pulumi:"disablePublicIpv4"`
	// Cron expression for Docker cleanup schedule.
	DockerCleanupFrequency pulumi.StringOutput `pulumi:"dockerCleanupFrequency"`
	// Disk usage percentage threshold for Docker cleanup.
	DockerCleanupThreshold pulumi.IntOutput `pulumi:"dockerCleanupThreshold"`
	// Docker engine version reported by Coolify for this server (host probe). Read-only; Populated on Coolify >= v4.3.2 when the host has been probed. Empty on older instances.
	DockerVersion pulumi.StringOutput `pulumi:"dockerVersion"`
	// When Coolify last checked the Docker version on this server. Read-only.
	DockerVersionCheckedAt pulumi.StringOutput `pulumi:"dockerVersionCheckedAt"`
	// Timeout in seconds for Docker operations (pull, build, health check) during deployment.
	DynamicTimeout pulumi.IntOutput `pulumi:"dynamicTimeout"`
	// Whether to enable IPv6 on the Vultr instance. Defaults to true to match Coolify.
	EnableIpv6 pulumi.BoolOutput `pulumi:"enableIpv6"`
	// Whether the server is force-disabled in Coolify. Read-only (not on public server PATCH allow-list).
	ForceDisabled pulumi.BoolOutput `pulumi:"forceDisabled"`
	// Whether to force Docker cleanup regardless of disk usage.
	ForceDockerCleanup pulumi.BoolOutput `pulumi:"forceDockerCleanup"`
	// Whether to generate exact Docker labels (removes extra labels from containers).
	GenerateExactLabels pulumi.BoolOutput `pulumi:"generateExactLabels"`
	// Whether to validate server connectivity immediately after creation. Defaults to false to match Coolify.
	InstantValidate pulumi.BoolOutput `pulumi:"instantValidate"`
	// The IP address assigned to the server by Vultr.
	Ip pulumi.StringOutput `pulumi:"ip"`
	// Whether this server is used for building applications.
	IsBuildServer pulumi.BoolOutput `pulumi:"isBuildServer"`
	// Whether this server uses a Cloudflare Tunnel.
	IsCloudflareTunnel pulumi.BoolOutput `pulumi:"isCloudflareTunnel"`
	// Whether this server is a jump host. Read-only (not on public server PATCH allow-list).
	IsJumpServer pulumi.BoolOutput `pulumi:"isJumpServer"`
	// Whether Axiom log drain is enabled. Read-only (not on public server PATCH allow-list).
	IsLogdrainAxiomEnabled pulumi.BoolOutput `pulumi:"isLogdrainAxiomEnabled"`
	// Whether custom log drain is enabled. Read-only.
	IsLogdrainCustomEnabled pulumi.BoolOutput `pulumi:"isLogdrainCustomEnabled"`
	// Whether Highlight log drain is enabled. Read-only.
	IsLogdrainHighlightEnabled pulumi.BoolOutput `pulumi:"isLogdrainHighlightEnabled"`
	// Whether New Relic log drain is enabled. Read-only.
	IsLogdrainNewrelicEnabled pulumi.BoolOutput `pulumi:"isLogdrainNewrelicEnabled"`
	// Whether metrics collection is enabled on this server.
	IsMetricsEnabled pulumi.BoolOutput `pulumi:"isMetricsEnabled"`
	// Whether the server is currently reachable.
	IsReachable pulumi.BoolOutput `pulumi:"isReachable"`
	// Whether Sentinel debug mode is enabled. Read-only (not on public server PATCH allow-list).
	IsSentinelDebugEnabled pulumi.BoolOutput `pulumi:"isSentinelDebugEnabled"`
	// Whether the Sentinel monitoring agent is enabled.
	IsSentinelEnabled pulumi.BoolOutput `pulumi:"isSentinelEnabled"`
	// Whether this server is a Docker Swarm manager. Read-only (not on public server PATCH allow-list).
	IsSwarmManager pulumi.BoolOutput `pulumi:"isSwarmManager"`
	// Whether this server is a Docker Swarm worker. Read-only (not on public server PATCH allow-list).
	IsSwarmWorker pulumi.BoolOutput `pulumi:"isSwarmWorker"`
	// Whether the web terminal is enabled for this server.
	IsTerminalEnabled pulumi.BoolOutput `pulumi:"isTerminalEnabled"`
	// Whether the server is currently usable for deployments.
	IsUsable pulumi.BoolOutput `pulumi:"isUsable"`
	// Axiom API key for log drain. Sensitive; read-only.
	LogdrainAxiomApiKey pulumi.StringOutput `pulumi:"logdrainAxiomApiKey"`
	// Axiom dataset name for log drain. Read-only.
	LogdrainAxiomDatasetName pulumi.StringOutput `pulumi:"logdrainAxiomDatasetName"`
	// Custom log drain configuration. Sensitive; read-only.
	LogdrainCustomConfig pulumi.StringOutput `pulumi:"logdrainCustomConfig"`
	// Custom log drain config parser. Read-only.
	LogdrainCustomConfigParser pulumi.StringOutput `pulumi:"logdrainCustomConfigParser"`
	// Highlight project ID for log drain. Read-only.
	LogdrainHighlightProjectId pulumi.StringOutput `pulumi:"logdrainHighlightProjectId"`
	// New Relic base URI for log drain. Read-only.
	LogdrainNewrelicBaseUri pulumi.StringOutput `pulumi:"logdrainNewrelicBaseUri"`
	// New Relic license key for log drain. Sensitive; read-only.
	LogdrainNewrelicLicenseKey pulumi.StringOutput `pulumi:"logdrainNewrelicLicenseKey"`
	// The name of the server.
	Name pulumi.StringOutput `pulumi:"name"`
	// The Vultr operating system ID. Use <span pulumi-lang-nodejs="`coolify.getVultrOs`" pulumi-lang-dotnet="`coolify.getVultrOs`" pulumi-lang-go="`getVultrOs`" pulumi-lang-python="`get_vultr_os`" pulumi-lang-yaml="`coolify.getVultrOs`" pulumi-lang-java="`coolify.getVultrOs`" pulumi-lang-hcl="`data.coolify_vultr_os`">`coolify.getVultrOs`</span> to list available operating systems. Changing this forces a new resource.
	OsId pulumi.IntOutput `pulumi:"osId"`
	// The Vultr server type (e.g., `s-1vcpu-1gb`). Use <span pulumi-lang-nodejs="`coolify.getVultrPlans`" pulumi-lang-dotnet="`coolify.getVultrPlans`" pulumi-lang-go="`getVultrPlans`" pulumi-lang-python="`get_vultr_plans`" pulumi-lang-yaml="`coolify.getVultrPlans`" pulumi-lang-java="`coolify.getVultrPlans`" pulumi-lang-hcl="`data.coolify_vultr_plans`">`coolify.getVultrPlans`</span> to list available plans. Changing this forces a new resource.
	Plan pulumi.StringOutput `pulumi:"plan"`
	// The SSH port of the server.
	Port pulumi.IntOutput `pulumi:"port"`
	// The UUID of the private key used for SSH authentication.
	PrivateKeyUuid pulumi.StringOutput `pulumi:"privateKeyUuid"`
	// The Vultr region slug (e.g., <span pulumi-lang-nodejs="`nyc1`" pulumi-lang-dotnet="`Nyc1`" pulumi-lang-go="`nyc1`" pulumi-lang-python="`nyc1`" pulumi-lang-yaml="`nyc1`" pulumi-lang-java="`nyc1`" pulumi-lang-hcl="`nyc1`">`nyc1`</span>). Use <span pulumi-lang-nodejs="`coolify.getVultrRegions`" pulumi-lang-dotnet="`coolify.getVultrRegions`" pulumi-lang-go="`getVultrRegions`" pulumi-lang-python="`get_vultr_regions`" pulumi-lang-yaml="`coolify.getVultrRegions`" pulumi-lang-java="`coolify.getVultrRegions`" pulumi-lang-hcl="`data.coolify_vultr_regions`">`coolify.getVultrRegions`</span> to list available regions. Changing this forces a new resource.
	Region pulumi.StringOutput `pulumi:"region"`
	// Custom Sentinel push URL. Read-only (not on public server PATCH allow-list).
	SentinelCustomUrl pulumi.StringOutput `pulumi:"sentinelCustomUrl"`
	// Number of days to retain Sentinel metrics.
	SentinelMetricsHistoryDays pulumi.IntOutput `pulumi:"sentinelMetricsHistoryDays"`
	// Sentinel metrics refresh rate in seconds.
	SentinelMetricsRefreshRateSeconds pulumi.IntOutput `pulumi:"sentinelMetricsRefreshRateSeconds"`
	// Interval in seconds between Sentinel metric pushes.
	SentinelPushIntervalSeconds pulumi.IntOutput `pulumi:"sentinelPushIntervalSeconds"`
	// Sentinel agent token. Sensitive; only returned when the API token can read secrets. Read-only.
	SentinelToken pulumi.StringOutput `pulumi:"sentinelToken"`
	// Cron or Coolify human schedule for how often disk usage is checked (e.g., `*/5 * * * *`, <span pulumi-lang-nodejs="`daily`" pulumi-lang-dotnet="`Daily`" pulumi-lang-go="`daily`" pulumi-lang-python="`daily`" pulumi-lang-yaml="`daily`" pulumi-lang-java="`daily`" pulumi-lang-hcl="`daily`">`daily`</span>, `@daily`).
	ServerDiskUsageCheckFrequency pulumi.StringOutput `pulumi:"serverDiskUsageCheckFrequency"`
	// Disk usage percentage at which a notification is sent.
	ServerDiskUsageNotificationThreshold pulumi.IntOutput `pulumi:"serverDiskUsageNotificationThreshold"`
	// Server timezone (e.g., `UTC`, `America/New_York`).
	ServerTimezone pulumi.StringOutput          `pulumi:"serverTimezone"`
	Timeouts       ServerVultrTimeoutsPtrOutput `pulumi:"timeouts"`
	// The SSH user for connecting to the server.
	User pulumi.StringOutput `pulumi:"user"`
	// The unique identifier of the server.
	Uuid pulumi.StringOutput `pulumi:"uuid"`
	// Comma-separated list of Vultr SSH key IDs (strings). Use <span pulumi-lang-nodejs="`coolify.getVultrSshKeys`" pulumi-lang-dotnet="`coolify.getVultrSshKeys`" pulumi-lang-go="`getVultrSshKeys`" pulumi-lang-python="`get_vultr_ssh_keys`" pulumi-lang-yaml="`coolify.getVultrSshKeys`" pulumi-lang-java="`coolify.getVultrSshKeys`" pulumi-lang-hcl="`data.coolify_vultr_ssh_keys`">`coolify.getVultrSshKeys`</span> to list available keys. Changing this forces a new resource.
	VultrSshKeyIds pulumi.StringPtrOutput `pulumi:"vultrSshKeyIds"`
	// Wildcard domain for applications on this server (e.g., `example.com`).
	WildcardDomain pulumi.StringOutput `pulumi:"wildcardDomain"`
}

// NewServerVultr registers a new resource with the given unique name, arguments, and options.
func NewServerVultr(ctx *pulumi.Context,
	name string, args *ServerVultrArgs, opts ...pulumi.ResourceOption) (*ServerVultr, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.CloudProviderTokenUuid == nil {
		return nil, errors.New("invalid value for required argument 'CloudProviderTokenUuid'")
	}
	if args.OsId == nil {
		return nil, errors.New("invalid value for required argument 'OsId'")
	}
	if args.Plan == nil {
		return nil, errors.New("invalid value for required argument 'Plan'")
	}
	if args.PrivateKeyUuid == nil {
		return nil, errors.New("invalid value for required argument 'PrivateKeyUuid'")
	}
	if args.Region == nil {
		return nil, errors.New("invalid value for required argument 'Region'")
	}
	if args.CloudInitScript != nil {
		args.CloudInitScript = pulumi.ToSecret(args.CloudInitScript).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"cloudInitScript",
		"logdrainAxiomApiKey",
		"logdrainCustomConfig",
		"logdrainNewrelicLicenseKey",
		"sentinelToken",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ServerVultr
	err := ctx.RegisterResource("coolify:index/serverVultr:ServerVultr", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetServerVultr gets an existing ServerVultr resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetServerVultr(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ServerVultrState, opts ...pulumi.ResourceOption) (*ServerVultr, error) {
	var resource ServerVultr
	err := ctx.ReadResource("coolify:index/serverVultr:ServerVultr", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ServerVultr resources.
type serverVultrState struct {
	// CPU percentage Coolify uses when compressing volume backups. Read-only (not on public server PATCH). Present on Coolify >= v4.3.3; empty on older instances.
	BackupCompressionCpuPercentage *int `pulumi:"backupCompressionCpuPercentage"`
	// Cloud-init script to run on server creation. Changing this forces a new resource.
	CloudInitScript *string `pulumi:"cloudInitScript"`
	// The UUID of the Vultr cloud provider token (from <span pulumi-lang-nodejs="`coolify.CloudToken`" pulumi-lang-dotnet="`coolify.CloudToken`" pulumi-lang-go="`CloudToken`" pulumi-lang-python="`CloudToken`" pulumi-lang-yaml="`coolify.CloudToken`" pulumi-lang-java="`coolify.CloudToken`" pulumi-lang-hcl="`coolify_cloud_token`">`coolify.CloudToken`</span>). Changing this forces a new resource.
	CloudProviderTokenUuid *string `pulumi:"cloudProviderTokenUuid"`
	// Docker Compose version reported by Coolify for this server (host probe). Read-only; Populated on Coolify >= v4.3.2 when the host has been probed. Empty on older instances.
	ComposeVersion *string `pulumi:"composeVersion"`
	// When Coolify last checked the Compose version on this server. Read-only.
	ComposeVersionCheckedAt *string `pulumi:"composeVersionCheckedAt"`
	// How many deployments can run in parallel on this server.
	ConcurrentBuilds *int `pulumi:"concurrentBuilds"`
	// SSH connection timeout in seconds.
	ConnectionTimeout *int `pulumi:"connectionTimeout"`
	// Whether to delete unused Docker networks during cleanup.
	DeleteUnusedNetworks *bool `pulumi:"deleteUnusedNetworks"`
	// Whether to delete unused Docker volumes during cleanup.
	DeleteUnusedVolumes *bool `pulumi:"deleteUnusedVolumes"`
	// Maximum number of queued deployments (default 25).
	DeploymentQueueLimit *int `pulumi:"deploymentQueueLimit"`
	// A description of the server.
	Description *string `pulumi:"description"`
	// Whether application image retention is disabled. Read-only (not on public server PATCH allow-list).
	DisableApplicationImageRetention *bool `pulumi:"disableApplicationImageRetention"`
	// Whether to disable public IPv4 on the Vultr instance.
	DisablePublicIpv4 *bool `pulumi:"disablePublicIpv4"`
	// Cron expression for Docker cleanup schedule.
	DockerCleanupFrequency *string `pulumi:"dockerCleanupFrequency"`
	// Disk usage percentage threshold for Docker cleanup.
	DockerCleanupThreshold *int `pulumi:"dockerCleanupThreshold"`
	// Docker engine version reported by Coolify for this server (host probe). Read-only; Populated on Coolify >= v4.3.2 when the host has been probed. Empty on older instances.
	DockerVersion *string `pulumi:"dockerVersion"`
	// When Coolify last checked the Docker version on this server. Read-only.
	DockerVersionCheckedAt *string `pulumi:"dockerVersionCheckedAt"`
	// Timeout in seconds for Docker operations (pull, build, health check) during deployment.
	DynamicTimeout *int `pulumi:"dynamicTimeout"`
	// Whether to enable IPv6 on the Vultr instance. Defaults to true to match Coolify.
	EnableIpv6 *bool `pulumi:"enableIpv6"`
	// Whether the server is force-disabled in Coolify. Read-only (not on public server PATCH allow-list).
	ForceDisabled *bool `pulumi:"forceDisabled"`
	// Whether to force Docker cleanup regardless of disk usage.
	ForceDockerCleanup *bool `pulumi:"forceDockerCleanup"`
	// Whether to generate exact Docker labels (removes extra labels from containers).
	GenerateExactLabels *bool `pulumi:"generateExactLabels"`
	// Whether to validate server connectivity immediately after creation. Defaults to false to match Coolify.
	InstantValidate *bool `pulumi:"instantValidate"`
	// The IP address assigned to the server by Vultr.
	Ip *string `pulumi:"ip"`
	// Whether this server is used for building applications.
	IsBuildServer *bool `pulumi:"isBuildServer"`
	// Whether this server uses a Cloudflare Tunnel.
	IsCloudflareTunnel *bool `pulumi:"isCloudflareTunnel"`
	// Whether this server is a jump host. Read-only (not on public server PATCH allow-list).
	IsJumpServer *bool `pulumi:"isJumpServer"`
	// Whether Axiom log drain is enabled. Read-only (not on public server PATCH allow-list).
	IsLogdrainAxiomEnabled *bool `pulumi:"isLogdrainAxiomEnabled"`
	// Whether custom log drain is enabled. Read-only.
	IsLogdrainCustomEnabled *bool `pulumi:"isLogdrainCustomEnabled"`
	// Whether Highlight log drain is enabled. Read-only.
	IsLogdrainHighlightEnabled *bool `pulumi:"isLogdrainHighlightEnabled"`
	// Whether New Relic log drain is enabled. Read-only.
	IsLogdrainNewrelicEnabled *bool `pulumi:"isLogdrainNewrelicEnabled"`
	// Whether metrics collection is enabled on this server.
	IsMetricsEnabled *bool `pulumi:"isMetricsEnabled"`
	// Whether the server is currently reachable.
	IsReachable *bool `pulumi:"isReachable"`
	// Whether Sentinel debug mode is enabled. Read-only (not on public server PATCH allow-list).
	IsSentinelDebugEnabled *bool `pulumi:"isSentinelDebugEnabled"`
	// Whether the Sentinel monitoring agent is enabled.
	IsSentinelEnabled *bool `pulumi:"isSentinelEnabled"`
	// Whether this server is a Docker Swarm manager. Read-only (not on public server PATCH allow-list).
	IsSwarmManager *bool `pulumi:"isSwarmManager"`
	// Whether this server is a Docker Swarm worker. Read-only (not on public server PATCH allow-list).
	IsSwarmWorker *bool `pulumi:"isSwarmWorker"`
	// Whether the web terminal is enabled for this server.
	IsTerminalEnabled *bool `pulumi:"isTerminalEnabled"`
	// Whether the server is currently usable for deployments.
	IsUsable *bool `pulumi:"isUsable"`
	// Axiom API key for log drain. Sensitive; read-only.
	LogdrainAxiomApiKey *string `pulumi:"logdrainAxiomApiKey"`
	// Axiom dataset name for log drain. Read-only.
	LogdrainAxiomDatasetName *string `pulumi:"logdrainAxiomDatasetName"`
	// Custom log drain configuration. Sensitive; read-only.
	LogdrainCustomConfig *string `pulumi:"logdrainCustomConfig"`
	// Custom log drain config parser. Read-only.
	LogdrainCustomConfigParser *string `pulumi:"logdrainCustomConfigParser"`
	// Highlight project ID for log drain. Read-only.
	LogdrainHighlightProjectId *string `pulumi:"logdrainHighlightProjectId"`
	// New Relic base URI for log drain. Read-only.
	LogdrainNewrelicBaseUri *string `pulumi:"logdrainNewrelicBaseUri"`
	// New Relic license key for log drain. Sensitive; read-only.
	LogdrainNewrelicLicenseKey *string `pulumi:"logdrainNewrelicLicenseKey"`
	// The name of the server.
	Name *string `pulumi:"name"`
	// The Vultr operating system ID. Use <span pulumi-lang-nodejs="`coolify.getVultrOs`" pulumi-lang-dotnet="`coolify.getVultrOs`" pulumi-lang-go="`getVultrOs`" pulumi-lang-python="`get_vultr_os`" pulumi-lang-yaml="`coolify.getVultrOs`" pulumi-lang-java="`coolify.getVultrOs`" pulumi-lang-hcl="`data.coolify_vultr_os`">`coolify.getVultrOs`</span> to list available operating systems. Changing this forces a new resource.
	OsId *int `pulumi:"osId"`
	// The Vultr server type (e.g., `s-1vcpu-1gb`). Use <span pulumi-lang-nodejs="`coolify.getVultrPlans`" pulumi-lang-dotnet="`coolify.getVultrPlans`" pulumi-lang-go="`getVultrPlans`" pulumi-lang-python="`get_vultr_plans`" pulumi-lang-yaml="`coolify.getVultrPlans`" pulumi-lang-java="`coolify.getVultrPlans`" pulumi-lang-hcl="`data.coolify_vultr_plans`">`coolify.getVultrPlans`</span> to list available plans. Changing this forces a new resource.
	Plan *string `pulumi:"plan"`
	// The SSH port of the server.
	Port *int `pulumi:"port"`
	// The UUID of the private key used for SSH authentication.
	PrivateKeyUuid *string `pulumi:"privateKeyUuid"`
	// The Vultr region slug (e.g., <span pulumi-lang-nodejs="`nyc1`" pulumi-lang-dotnet="`Nyc1`" pulumi-lang-go="`nyc1`" pulumi-lang-python="`nyc1`" pulumi-lang-yaml="`nyc1`" pulumi-lang-java="`nyc1`" pulumi-lang-hcl="`nyc1`">`nyc1`</span>). Use <span pulumi-lang-nodejs="`coolify.getVultrRegions`" pulumi-lang-dotnet="`coolify.getVultrRegions`" pulumi-lang-go="`getVultrRegions`" pulumi-lang-python="`get_vultr_regions`" pulumi-lang-yaml="`coolify.getVultrRegions`" pulumi-lang-java="`coolify.getVultrRegions`" pulumi-lang-hcl="`data.coolify_vultr_regions`">`coolify.getVultrRegions`</span> to list available regions. Changing this forces a new resource.
	Region *string `pulumi:"region"`
	// Custom Sentinel push URL. Read-only (not on public server PATCH allow-list).
	SentinelCustomUrl *string `pulumi:"sentinelCustomUrl"`
	// Number of days to retain Sentinel metrics.
	SentinelMetricsHistoryDays *int `pulumi:"sentinelMetricsHistoryDays"`
	// Sentinel metrics refresh rate in seconds.
	SentinelMetricsRefreshRateSeconds *int `pulumi:"sentinelMetricsRefreshRateSeconds"`
	// Interval in seconds between Sentinel metric pushes.
	SentinelPushIntervalSeconds *int `pulumi:"sentinelPushIntervalSeconds"`
	// Sentinel agent token. Sensitive; only returned when the API token can read secrets. Read-only.
	SentinelToken *string `pulumi:"sentinelToken"`
	// Cron or Coolify human schedule for how often disk usage is checked (e.g., `*/5 * * * *`, <span pulumi-lang-nodejs="`daily`" pulumi-lang-dotnet="`Daily`" pulumi-lang-go="`daily`" pulumi-lang-python="`daily`" pulumi-lang-yaml="`daily`" pulumi-lang-java="`daily`" pulumi-lang-hcl="`daily`">`daily`</span>, `@daily`).
	ServerDiskUsageCheckFrequency *string `pulumi:"serverDiskUsageCheckFrequency"`
	// Disk usage percentage at which a notification is sent.
	ServerDiskUsageNotificationThreshold *int `pulumi:"serverDiskUsageNotificationThreshold"`
	// Server timezone (e.g., `UTC`, `America/New_York`).
	ServerTimezone *string              `pulumi:"serverTimezone"`
	Timeouts       *ServerVultrTimeouts `pulumi:"timeouts"`
	// The SSH user for connecting to the server.
	User *string `pulumi:"user"`
	// The unique identifier of the server.
	Uuid *string `pulumi:"uuid"`
	// Comma-separated list of Vultr SSH key IDs (strings). Use <span pulumi-lang-nodejs="`coolify.getVultrSshKeys`" pulumi-lang-dotnet="`coolify.getVultrSshKeys`" pulumi-lang-go="`getVultrSshKeys`" pulumi-lang-python="`get_vultr_ssh_keys`" pulumi-lang-yaml="`coolify.getVultrSshKeys`" pulumi-lang-java="`coolify.getVultrSshKeys`" pulumi-lang-hcl="`data.coolify_vultr_ssh_keys`">`coolify.getVultrSshKeys`</span> to list available keys. Changing this forces a new resource.
	VultrSshKeyIds *string `pulumi:"vultrSshKeyIds"`
	// Wildcard domain for applications on this server (e.g., `example.com`).
	WildcardDomain *string `pulumi:"wildcardDomain"`
}

type ServerVultrState struct {
	// CPU percentage Coolify uses when compressing volume backups. Read-only (not on public server PATCH). Present on Coolify >= v4.3.3; empty on older instances.
	BackupCompressionCpuPercentage pulumi.IntPtrInput
	// Cloud-init script to run on server creation. Changing this forces a new resource.
	CloudInitScript pulumi.StringPtrInput
	// The UUID of the Vultr cloud provider token (from <span pulumi-lang-nodejs="`coolify.CloudToken`" pulumi-lang-dotnet="`coolify.CloudToken`" pulumi-lang-go="`CloudToken`" pulumi-lang-python="`CloudToken`" pulumi-lang-yaml="`coolify.CloudToken`" pulumi-lang-java="`coolify.CloudToken`" pulumi-lang-hcl="`coolify_cloud_token`">`coolify.CloudToken`</span>). Changing this forces a new resource.
	CloudProviderTokenUuid pulumi.StringPtrInput
	// Docker Compose version reported by Coolify for this server (host probe). Read-only; Populated on Coolify >= v4.3.2 when the host has been probed. Empty on older instances.
	ComposeVersion pulumi.StringPtrInput
	// When Coolify last checked the Compose version on this server. Read-only.
	ComposeVersionCheckedAt pulumi.StringPtrInput
	// How many deployments can run in parallel on this server.
	ConcurrentBuilds pulumi.IntPtrInput
	// SSH connection timeout in seconds.
	ConnectionTimeout pulumi.IntPtrInput
	// Whether to delete unused Docker networks during cleanup.
	DeleteUnusedNetworks pulumi.BoolPtrInput
	// Whether to delete unused Docker volumes during cleanup.
	DeleteUnusedVolumes pulumi.BoolPtrInput
	// Maximum number of queued deployments (default 25).
	DeploymentQueueLimit pulumi.IntPtrInput
	// A description of the server.
	Description pulumi.StringPtrInput
	// Whether application image retention is disabled. Read-only (not on public server PATCH allow-list).
	DisableApplicationImageRetention pulumi.BoolPtrInput
	// Whether to disable public IPv4 on the Vultr instance.
	DisablePublicIpv4 pulumi.BoolPtrInput
	// Cron expression for Docker cleanup schedule.
	DockerCleanupFrequency pulumi.StringPtrInput
	// Disk usage percentage threshold for Docker cleanup.
	DockerCleanupThreshold pulumi.IntPtrInput
	// Docker engine version reported by Coolify for this server (host probe). Read-only; Populated on Coolify >= v4.3.2 when the host has been probed. Empty on older instances.
	DockerVersion pulumi.StringPtrInput
	// When Coolify last checked the Docker version on this server. Read-only.
	DockerVersionCheckedAt pulumi.StringPtrInput
	// Timeout in seconds for Docker operations (pull, build, health check) during deployment.
	DynamicTimeout pulumi.IntPtrInput
	// Whether to enable IPv6 on the Vultr instance. Defaults to true to match Coolify.
	EnableIpv6 pulumi.BoolPtrInput
	// Whether the server is force-disabled in Coolify. Read-only (not on public server PATCH allow-list).
	ForceDisabled pulumi.BoolPtrInput
	// Whether to force Docker cleanup regardless of disk usage.
	ForceDockerCleanup pulumi.BoolPtrInput
	// Whether to generate exact Docker labels (removes extra labels from containers).
	GenerateExactLabels pulumi.BoolPtrInput
	// Whether to validate server connectivity immediately after creation. Defaults to false to match Coolify.
	InstantValidate pulumi.BoolPtrInput
	// The IP address assigned to the server by Vultr.
	Ip pulumi.StringPtrInput
	// Whether this server is used for building applications.
	IsBuildServer pulumi.BoolPtrInput
	// Whether this server uses a Cloudflare Tunnel.
	IsCloudflareTunnel pulumi.BoolPtrInput
	// Whether this server is a jump host. Read-only (not on public server PATCH allow-list).
	IsJumpServer pulumi.BoolPtrInput
	// Whether Axiom log drain is enabled. Read-only (not on public server PATCH allow-list).
	IsLogdrainAxiomEnabled pulumi.BoolPtrInput
	// Whether custom log drain is enabled. Read-only.
	IsLogdrainCustomEnabled pulumi.BoolPtrInput
	// Whether Highlight log drain is enabled. Read-only.
	IsLogdrainHighlightEnabled pulumi.BoolPtrInput
	// Whether New Relic log drain is enabled. Read-only.
	IsLogdrainNewrelicEnabled pulumi.BoolPtrInput
	// Whether metrics collection is enabled on this server.
	IsMetricsEnabled pulumi.BoolPtrInput
	// Whether the server is currently reachable.
	IsReachable pulumi.BoolPtrInput
	// Whether Sentinel debug mode is enabled. Read-only (not on public server PATCH allow-list).
	IsSentinelDebugEnabled pulumi.BoolPtrInput
	// Whether the Sentinel monitoring agent is enabled.
	IsSentinelEnabled pulumi.BoolPtrInput
	// Whether this server is a Docker Swarm manager. Read-only (not on public server PATCH allow-list).
	IsSwarmManager pulumi.BoolPtrInput
	// Whether this server is a Docker Swarm worker. Read-only (not on public server PATCH allow-list).
	IsSwarmWorker pulumi.BoolPtrInput
	// Whether the web terminal is enabled for this server.
	IsTerminalEnabled pulumi.BoolPtrInput
	// Whether the server is currently usable for deployments.
	IsUsable pulumi.BoolPtrInput
	// Axiom API key for log drain. Sensitive; read-only.
	LogdrainAxiomApiKey pulumi.StringPtrInput
	// Axiom dataset name for log drain. Read-only.
	LogdrainAxiomDatasetName pulumi.StringPtrInput
	// Custom log drain configuration. Sensitive; read-only.
	LogdrainCustomConfig pulumi.StringPtrInput
	// Custom log drain config parser. Read-only.
	LogdrainCustomConfigParser pulumi.StringPtrInput
	// Highlight project ID for log drain. Read-only.
	LogdrainHighlightProjectId pulumi.StringPtrInput
	// New Relic base URI for log drain. Read-only.
	LogdrainNewrelicBaseUri pulumi.StringPtrInput
	// New Relic license key for log drain. Sensitive; read-only.
	LogdrainNewrelicLicenseKey pulumi.StringPtrInput
	// The name of the server.
	Name pulumi.StringPtrInput
	// The Vultr operating system ID. Use <span pulumi-lang-nodejs="`coolify.getVultrOs`" pulumi-lang-dotnet="`coolify.getVultrOs`" pulumi-lang-go="`getVultrOs`" pulumi-lang-python="`get_vultr_os`" pulumi-lang-yaml="`coolify.getVultrOs`" pulumi-lang-java="`coolify.getVultrOs`" pulumi-lang-hcl="`data.coolify_vultr_os`">`coolify.getVultrOs`</span> to list available operating systems. Changing this forces a new resource.
	OsId pulumi.IntPtrInput
	// The Vultr server type (e.g., `s-1vcpu-1gb`). Use <span pulumi-lang-nodejs="`coolify.getVultrPlans`" pulumi-lang-dotnet="`coolify.getVultrPlans`" pulumi-lang-go="`getVultrPlans`" pulumi-lang-python="`get_vultr_plans`" pulumi-lang-yaml="`coolify.getVultrPlans`" pulumi-lang-java="`coolify.getVultrPlans`" pulumi-lang-hcl="`data.coolify_vultr_plans`">`coolify.getVultrPlans`</span> to list available plans. Changing this forces a new resource.
	Plan pulumi.StringPtrInput
	// The SSH port of the server.
	Port pulumi.IntPtrInput
	// The UUID of the private key used for SSH authentication.
	PrivateKeyUuid pulumi.StringPtrInput
	// The Vultr region slug (e.g., <span pulumi-lang-nodejs="`nyc1`" pulumi-lang-dotnet="`Nyc1`" pulumi-lang-go="`nyc1`" pulumi-lang-python="`nyc1`" pulumi-lang-yaml="`nyc1`" pulumi-lang-java="`nyc1`" pulumi-lang-hcl="`nyc1`">`nyc1`</span>). Use <span pulumi-lang-nodejs="`coolify.getVultrRegions`" pulumi-lang-dotnet="`coolify.getVultrRegions`" pulumi-lang-go="`getVultrRegions`" pulumi-lang-python="`get_vultr_regions`" pulumi-lang-yaml="`coolify.getVultrRegions`" pulumi-lang-java="`coolify.getVultrRegions`" pulumi-lang-hcl="`data.coolify_vultr_regions`">`coolify.getVultrRegions`</span> to list available regions. Changing this forces a new resource.
	Region pulumi.StringPtrInput
	// Custom Sentinel push URL. Read-only (not on public server PATCH allow-list).
	SentinelCustomUrl pulumi.StringPtrInput
	// Number of days to retain Sentinel metrics.
	SentinelMetricsHistoryDays pulumi.IntPtrInput
	// Sentinel metrics refresh rate in seconds.
	SentinelMetricsRefreshRateSeconds pulumi.IntPtrInput
	// Interval in seconds between Sentinel metric pushes.
	SentinelPushIntervalSeconds pulumi.IntPtrInput
	// Sentinel agent token. Sensitive; only returned when the API token can read secrets. Read-only.
	SentinelToken pulumi.StringPtrInput
	// Cron or Coolify human schedule for how often disk usage is checked (e.g., `*/5 * * * *`, <span pulumi-lang-nodejs="`daily`" pulumi-lang-dotnet="`Daily`" pulumi-lang-go="`daily`" pulumi-lang-python="`daily`" pulumi-lang-yaml="`daily`" pulumi-lang-java="`daily`" pulumi-lang-hcl="`daily`">`daily`</span>, `@daily`).
	ServerDiskUsageCheckFrequency pulumi.StringPtrInput
	// Disk usage percentage at which a notification is sent.
	ServerDiskUsageNotificationThreshold pulumi.IntPtrInput
	// Server timezone (e.g., `UTC`, `America/New_York`).
	ServerTimezone pulumi.StringPtrInput
	Timeouts       ServerVultrTimeoutsPtrInput
	// The SSH user for connecting to the server.
	User pulumi.StringPtrInput
	// The unique identifier of the server.
	Uuid pulumi.StringPtrInput
	// Comma-separated list of Vultr SSH key IDs (strings). Use <span pulumi-lang-nodejs="`coolify.getVultrSshKeys`" pulumi-lang-dotnet="`coolify.getVultrSshKeys`" pulumi-lang-go="`getVultrSshKeys`" pulumi-lang-python="`get_vultr_ssh_keys`" pulumi-lang-yaml="`coolify.getVultrSshKeys`" pulumi-lang-java="`coolify.getVultrSshKeys`" pulumi-lang-hcl="`data.coolify_vultr_ssh_keys`">`coolify.getVultrSshKeys`</span> to list available keys. Changing this forces a new resource.
	VultrSshKeyIds pulumi.StringPtrInput
	// Wildcard domain for applications on this server (e.g., `example.com`).
	WildcardDomain pulumi.StringPtrInput
}

func (ServerVultrState) ElementType() reflect.Type {
	return reflect.TypeOf((*serverVultrState)(nil)).Elem()
}

type serverVultrArgs struct {
	// Cloud-init script to run on server creation. Changing this forces a new resource.
	CloudInitScript *string `pulumi:"cloudInitScript"`
	// The UUID of the Vultr cloud provider token (from <span pulumi-lang-nodejs="`coolify.CloudToken`" pulumi-lang-dotnet="`coolify.CloudToken`" pulumi-lang-go="`CloudToken`" pulumi-lang-python="`CloudToken`" pulumi-lang-yaml="`coolify.CloudToken`" pulumi-lang-java="`coolify.CloudToken`" pulumi-lang-hcl="`coolify_cloud_token`">`coolify.CloudToken`</span>). Changing this forces a new resource.
	CloudProviderTokenUuid string `pulumi:"cloudProviderTokenUuid"`
	// How many deployments can run in parallel on this server.
	ConcurrentBuilds *int `pulumi:"concurrentBuilds"`
	// SSH connection timeout in seconds.
	ConnectionTimeout *int `pulumi:"connectionTimeout"`
	// Maximum number of queued deployments (default 25).
	DeploymentQueueLimit *int `pulumi:"deploymentQueueLimit"`
	// A description of the server.
	Description *string `pulumi:"description"`
	// Whether to disable public IPv4 on the Vultr instance.
	DisablePublicIpv4 *bool `pulumi:"disablePublicIpv4"`
	// Timeout in seconds for Docker operations (pull, build, health check) during deployment.
	DynamicTimeout *int `pulumi:"dynamicTimeout"`
	// Whether to enable IPv6 on the Vultr instance. Defaults to true to match Coolify.
	EnableIpv6 *bool `pulumi:"enableIpv6"`
	// Whether to validate server connectivity immediately after creation. Defaults to false to match Coolify.
	InstantValidate *bool `pulumi:"instantValidate"`
	// Whether this server is used for building applications.
	IsBuildServer *bool `pulumi:"isBuildServer"`
	// The name of the server.
	Name *string `pulumi:"name"`
	// The Vultr operating system ID. Use <span pulumi-lang-nodejs="`coolify.getVultrOs`" pulumi-lang-dotnet="`coolify.getVultrOs`" pulumi-lang-go="`getVultrOs`" pulumi-lang-python="`get_vultr_os`" pulumi-lang-yaml="`coolify.getVultrOs`" pulumi-lang-java="`coolify.getVultrOs`" pulumi-lang-hcl="`data.coolify_vultr_os`">`coolify.getVultrOs`</span> to list available operating systems. Changing this forces a new resource.
	OsId int `pulumi:"osId"`
	// The Vultr server type (e.g., `s-1vcpu-1gb`). Use <span pulumi-lang-nodejs="`coolify.getVultrPlans`" pulumi-lang-dotnet="`coolify.getVultrPlans`" pulumi-lang-go="`getVultrPlans`" pulumi-lang-python="`get_vultr_plans`" pulumi-lang-yaml="`coolify.getVultrPlans`" pulumi-lang-java="`coolify.getVultrPlans`" pulumi-lang-hcl="`data.coolify_vultr_plans`">`coolify.getVultrPlans`</span> to list available plans. Changing this forces a new resource.
	Plan string `pulumi:"plan"`
	// The SSH port of the server.
	Port *int `pulumi:"port"`
	// The UUID of the private key used for SSH authentication.
	PrivateKeyUuid string `pulumi:"privateKeyUuid"`
	// The Vultr region slug (e.g., <span pulumi-lang-nodejs="`nyc1`" pulumi-lang-dotnet="`Nyc1`" pulumi-lang-go="`nyc1`" pulumi-lang-python="`nyc1`" pulumi-lang-yaml="`nyc1`" pulumi-lang-java="`nyc1`" pulumi-lang-hcl="`nyc1`">`nyc1`</span>). Use <span pulumi-lang-nodejs="`coolify.getVultrRegions`" pulumi-lang-dotnet="`coolify.getVultrRegions`" pulumi-lang-go="`getVultrRegions`" pulumi-lang-python="`get_vultr_regions`" pulumi-lang-yaml="`coolify.getVultrRegions`" pulumi-lang-java="`coolify.getVultrRegions`" pulumi-lang-hcl="`data.coolify_vultr_regions`">`coolify.getVultrRegions`</span> to list available regions. Changing this forces a new resource.
	Region string `pulumi:"region"`
	// Cron or Coolify human schedule for how often disk usage is checked (e.g., `*/5 * * * *`, <span pulumi-lang-nodejs="`daily`" pulumi-lang-dotnet="`Daily`" pulumi-lang-go="`daily`" pulumi-lang-python="`daily`" pulumi-lang-yaml="`daily`" pulumi-lang-java="`daily`" pulumi-lang-hcl="`daily`">`daily`</span>, `@daily`).
	ServerDiskUsageCheckFrequency *string `pulumi:"serverDiskUsageCheckFrequency"`
	// Disk usage percentage at which a notification is sent.
	ServerDiskUsageNotificationThreshold *int                 `pulumi:"serverDiskUsageNotificationThreshold"`
	Timeouts                             *ServerVultrTimeouts `pulumi:"timeouts"`
	// The SSH user for connecting to the server.
	User *string `pulumi:"user"`
	// Comma-separated list of Vultr SSH key IDs (strings). Use <span pulumi-lang-nodejs="`coolify.getVultrSshKeys`" pulumi-lang-dotnet="`coolify.getVultrSshKeys`" pulumi-lang-go="`getVultrSshKeys`" pulumi-lang-python="`get_vultr_ssh_keys`" pulumi-lang-yaml="`coolify.getVultrSshKeys`" pulumi-lang-java="`coolify.getVultrSshKeys`" pulumi-lang-hcl="`data.coolify_vultr_ssh_keys`">`coolify.getVultrSshKeys`</span> to list available keys. Changing this forces a new resource.
	VultrSshKeyIds *string `pulumi:"vultrSshKeyIds"`
}

// The set of arguments for constructing a ServerVultr resource.
type ServerVultrArgs struct {
	// Cloud-init script to run on server creation. Changing this forces a new resource.
	CloudInitScript pulumi.StringPtrInput
	// The UUID of the Vultr cloud provider token (from <span pulumi-lang-nodejs="`coolify.CloudToken`" pulumi-lang-dotnet="`coolify.CloudToken`" pulumi-lang-go="`CloudToken`" pulumi-lang-python="`CloudToken`" pulumi-lang-yaml="`coolify.CloudToken`" pulumi-lang-java="`coolify.CloudToken`" pulumi-lang-hcl="`coolify_cloud_token`">`coolify.CloudToken`</span>). Changing this forces a new resource.
	CloudProviderTokenUuid pulumi.StringInput
	// How many deployments can run in parallel on this server.
	ConcurrentBuilds pulumi.IntPtrInput
	// SSH connection timeout in seconds.
	ConnectionTimeout pulumi.IntPtrInput
	// Maximum number of queued deployments (default 25).
	DeploymentQueueLimit pulumi.IntPtrInput
	// A description of the server.
	Description pulumi.StringPtrInput
	// Whether to disable public IPv4 on the Vultr instance.
	DisablePublicIpv4 pulumi.BoolPtrInput
	// Timeout in seconds for Docker operations (pull, build, health check) during deployment.
	DynamicTimeout pulumi.IntPtrInput
	// Whether to enable IPv6 on the Vultr instance. Defaults to true to match Coolify.
	EnableIpv6 pulumi.BoolPtrInput
	// Whether to validate server connectivity immediately after creation. Defaults to false to match Coolify.
	InstantValidate pulumi.BoolPtrInput
	// Whether this server is used for building applications.
	IsBuildServer pulumi.BoolPtrInput
	// The name of the server.
	Name pulumi.StringPtrInput
	// The Vultr operating system ID. Use <span pulumi-lang-nodejs="`coolify.getVultrOs`" pulumi-lang-dotnet="`coolify.getVultrOs`" pulumi-lang-go="`getVultrOs`" pulumi-lang-python="`get_vultr_os`" pulumi-lang-yaml="`coolify.getVultrOs`" pulumi-lang-java="`coolify.getVultrOs`" pulumi-lang-hcl="`data.coolify_vultr_os`">`coolify.getVultrOs`</span> to list available operating systems. Changing this forces a new resource.
	OsId pulumi.IntInput
	// The Vultr server type (e.g., `s-1vcpu-1gb`). Use <span pulumi-lang-nodejs="`coolify.getVultrPlans`" pulumi-lang-dotnet="`coolify.getVultrPlans`" pulumi-lang-go="`getVultrPlans`" pulumi-lang-python="`get_vultr_plans`" pulumi-lang-yaml="`coolify.getVultrPlans`" pulumi-lang-java="`coolify.getVultrPlans`" pulumi-lang-hcl="`data.coolify_vultr_plans`">`coolify.getVultrPlans`</span> to list available plans. Changing this forces a new resource.
	Plan pulumi.StringInput
	// The SSH port of the server.
	Port pulumi.IntPtrInput
	// The UUID of the private key used for SSH authentication.
	PrivateKeyUuid pulumi.StringInput
	// The Vultr region slug (e.g., <span pulumi-lang-nodejs="`nyc1`" pulumi-lang-dotnet="`Nyc1`" pulumi-lang-go="`nyc1`" pulumi-lang-python="`nyc1`" pulumi-lang-yaml="`nyc1`" pulumi-lang-java="`nyc1`" pulumi-lang-hcl="`nyc1`">`nyc1`</span>). Use <span pulumi-lang-nodejs="`coolify.getVultrRegions`" pulumi-lang-dotnet="`coolify.getVultrRegions`" pulumi-lang-go="`getVultrRegions`" pulumi-lang-python="`get_vultr_regions`" pulumi-lang-yaml="`coolify.getVultrRegions`" pulumi-lang-java="`coolify.getVultrRegions`" pulumi-lang-hcl="`data.coolify_vultr_regions`">`coolify.getVultrRegions`</span> to list available regions. Changing this forces a new resource.
	Region pulumi.StringInput
	// Cron or Coolify human schedule for how often disk usage is checked (e.g., `*/5 * * * *`, <span pulumi-lang-nodejs="`daily`" pulumi-lang-dotnet="`Daily`" pulumi-lang-go="`daily`" pulumi-lang-python="`daily`" pulumi-lang-yaml="`daily`" pulumi-lang-java="`daily`" pulumi-lang-hcl="`daily`">`daily`</span>, `@daily`).
	ServerDiskUsageCheckFrequency pulumi.StringPtrInput
	// Disk usage percentage at which a notification is sent.
	ServerDiskUsageNotificationThreshold pulumi.IntPtrInput
	Timeouts                             ServerVultrTimeoutsPtrInput
	// The SSH user for connecting to the server.
	User pulumi.StringPtrInput
	// Comma-separated list of Vultr SSH key IDs (strings). Use <span pulumi-lang-nodejs="`coolify.getVultrSshKeys`" pulumi-lang-dotnet="`coolify.getVultrSshKeys`" pulumi-lang-go="`getVultrSshKeys`" pulumi-lang-python="`get_vultr_ssh_keys`" pulumi-lang-yaml="`coolify.getVultrSshKeys`" pulumi-lang-java="`coolify.getVultrSshKeys`" pulumi-lang-hcl="`data.coolify_vultr_ssh_keys`">`coolify.getVultrSshKeys`</span> to list available keys. Changing this forces a new resource.
	VultrSshKeyIds pulumi.StringPtrInput
}

func (ServerVultrArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*serverVultrArgs)(nil)).Elem()
}

type ServerVultrInput interface {
	pulumi.Input

	ToServerVultrOutput() ServerVultrOutput
	ToServerVultrOutputWithContext(ctx context.Context) ServerVultrOutput
}

func (*ServerVultr) ElementType() reflect.Type {
	return reflect.TypeOf((**ServerVultr)(nil)).Elem()
}

func (i *ServerVultr) ToServerVultrOutput() ServerVultrOutput {
	return i.ToServerVultrOutputWithContext(context.Background())
}

func (i *ServerVultr) ToServerVultrOutputWithContext(ctx context.Context) ServerVultrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServerVultrOutput)
}

// ServerVultrArrayInput is an input type that accepts ServerVultrArray and ServerVultrArrayOutput values.
// You can construct a concrete instance of `ServerVultrArrayInput` via:
//
//	ServerVultrArray{ ServerVultrArgs{...} }
type ServerVultrArrayInput interface {
	pulumi.Input

	ToServerVultrArrayOutput() ServerVultrArrayOutput
	ToServerVultrArrayOutputWithContext(context.Context) ServerVultrArrayOutput
}

type ServerVultrArray []ServerVultrInput

func (ServerVultrArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ServerVultr)(nil)).Elem()
}

func (i ServerVultrArray) ToServerVultrArrayOutput() ServerVultrArrayOutput {
	return i.ToServerVultrArrayOutputWithContext(context.Background())
}

func (i ServerVultrArray) ToServerVultrArrayOutputWithContext(ctx context.Context) ServerVultrArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServerVultrArrayOutput)
}

// ServerVultrMapInput is an input type that accepts ServerVultrMap and ServerVultrMapOutput values.
// You can construct a concrete instance of `ServerVultrMapInput` via:
//
//	ServerVultrMap{ "key": ServerVultrArgs{...} }
type ServerVultrMapInput interface {
	pulumi.Input

	ToServerVultrMapOutput() ServerVultrMapOutput
	ToServerVultrMapOutputWithContext(context.Context) ServerVultrMapOutput
}

type ServerVultrMap map[string]ServerVultrInput

func (ServerVultrMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ServerVultr)(nil)).Elem()
}

func (i ServerVultrMap) ToServerVultrMapOutput() ServerVultrMapOutput {
	return i.ToServerVultrMapOutputWithContext(context.Background())
}

func (i ServerVultrMap) ToServerVultrMapOutputWithContext(ctx context.Context) ServerVultrMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServerVultrMapOutput)
}

type ServerVultrOutput struct{ *pulumi.OutputState }

func (ServerVultrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ServerVultr)(nil)).Elem()
}

func (o ServerVultrOutput) ToServerVultrOutput() ServerVultrOutput {
	return o
}

func (o ServerVultrOutput) ToServerVultrOutputWithContext(ctx context.Context) ServerVultrOutput {
	return o
}

// CPU percentage Coolify uses when compressing volume backups. Read-only (not on public server PATCH). Present on Coolify >= v4.3.3; empty on older instances.
func (o ServerVultrOutput) BackupCompressionCpuPercentage() pulumi.IntOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.IntOutput { return v.BackupCompressionCpuPercentage }).(pulumi.IntOutput)
}

// Cloud-init script to run on server creation. Changing this forces a new resource.
func (o ServerVultrOutput) CloudInitScript() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.StringPtrOutput { return v.CloudInitScript }).(pulumi.StringPtrOutput)
}

// The UUID of the Vultr cloud provider token (from <span pulumi-lang-nodejs="`coolify.CloudToken`" pulumi-lang-dotnet="`coolify.CloudToken`" pulumi-lang-go="`CloudToken`" pulumi-lang-python="`CloudToken`" pulumi-lang-yaml="`coolify.CloudToken`" pulumi-lang-java="`coolify.CloudToken`" pulumi-lang-hcl="`coolify_cloud_token`">`coolify.CloudToken`</span>). Changing this forces a new resource.
func (o ServerVultrOutput) CloudProviderTokenUuid() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.StringOutput { return v.CloudProviderTokenUuid }).(pulumi.StringOutput)
}

// Docker Compose version reported by Coolify for this server (host probe). Read-only; Populated on Coolify >= v4.3.2 when the host has been probed. Empty on older instances.
func (o ServerVultrOutput) ComposeVersion() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.StringOutput { return v.ComposeVersion }).(pulumi.StringOutput)
}

// When Coolify last checked the Compose version on this server. Read-only.
func (o ServerVultrOutput) ComposeVersionCheckedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.StringOutput { return v.ComposeVersionCheckedAt }).(pulumi.StringOutput)
}

// How many deployments can run in parallel on this server.
func (o ServerVultrOutput) ConcurrentBuilds() pulumi.IntOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.IntOutput { return v.ConcurrentBuilds }).(pulumi.IntOutput)
}

// SSH connection timeout in seconds.
func (o ServerVultrOutput) ConnectionTimeout() pulumi.IntOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.IntOutput { return v.ConnectionTimeout }).(pulumi.IntOutput)
}

// Whether to delete unused Docker networks during cleanup.
func (o ServerVultrOutput) DeleteUnusedNetworks() pulumi.BoolOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.BoolOutput { return v.DeleteUnusedNetworks }).(pulumi.BoolOutput)
}

// Whether to delete unused Docker volumes during cleanup.
func (o ServerVultrOutput) DeleteUnusedVolumes() pulumi.BoolOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.BoolOutput { return v.DeleteUnusedVolumes }).(pulumi.BoolOutput)
}

// Maximum number of queued deployments (default 25).
func (o ServerVultrOutput) DeploymentQueueLimit() pulumi.IntOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.IntOutput { return v.DeploymentQueueLimit }).(pulumi.IntOutput)
}

// A description of the server.
func (o ServerVultrOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.StringOutput { return v.Description }).(pulumi.StringOutput)
}

// Whether application image retention is disabled. Read-only (not on public server PATCH allow-list).
func (o ServerVultrOutput) DisableApplicationImageRetention() pulumi.BoolOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.BoolOutput { return v.DisableApplicationImageRetention }).(pulumi.BoolOutput)
}

// Whether to disable public IPv4 on the Vultr instance.
func (o ServerVultrOutput) DisablePublicIpv4() pulumi.BoolOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.BoolOutput { return v.DisablePublicIpv4 }).(pulumi.BoolOutput)
}

// Cron expression for Docker cleanup schedule.
func (o ServerVultrOutput) DockerCleanupFrequency() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.StringOutput { return v.DockerCleanupFrequency }).(pulumi.StringOutput)
}

// Disk usage percentage threshold for Docker cleanup.
func (o ServerVultrOutput) DockerCleanupThreshold() pulumi.IntOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.IntOutput { return v.DockerCleanupThreshold }).(pulumi.IntOutput)
}

// Docker engine version reported by Coolify for this server (host probe). Read-only; Populated on Coolify >= v4.3.2 when the host has been probed. Empty on older instances.
func (o ServerVultrOutput) DockerVersion() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.StringOutput { return v.DockerVersion }).(pulumi.StringOutput)
}

// When Coolify last checked the Docker version on this server. Read-only.
func (o ServerVultrOutput) DockerVersionCheckedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.StringOutput { return v.DockerVersionCheckedAt }).(pulumi.StringOutput)
}

// Timeout in seconds for Docker operations (pull, build, health check) during deployment.
func (o ServerVultrOutput) DynamicTimeout() pulumi.IntOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.IntOutput { return v.DynamicTimeout }).(pulumi.IntOutput)
}

// Whether to enable IPv6 on the Vultr instance. Defaults to true to match Coolify.
func (o ServerVultrOutput) EnableIpv6() pulumi.BoolOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.BoolOutput { return v.EnableIpv6 }).(pulumi.BoolOutput)
}

// Whether the server is force-disabled in Coolify. Read-only (not on public server PATCH allow-list).
func (o ServerVultrOutput) ForceDisabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.BoolOutput { return v.ForceDisabled }).(pulumi.BoolOutput)
}

// Whether to force Docker cleanup regardless of disk usage.
func (o ServerVultrOutput) ForceDockerCleanup() pulumi.BoolOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.BoolOutput { return v.ForceDockerCleanup }).(pulumi.BoolOutput)
}

// Whether to generate exact Docker labels (removes extra labels from containers).
func (o ServerVultrOutput) GenerateExactLabels() pulumi.BoolOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.BoolOutput { return v.GenerateExactLabels }).(pulumi.BoolOutput)
}

// Whether to validate server connectivity immediately after creation. Defaults to false to match Coolify.
func (o ServerVultrOutput) InstantValidate() pulumi.BoolOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.BoolOutput { return v.InstantValidate }).(pulumi.BoolOutput)
}

// The IP address assigned to the server by Vultr.
func (o ServerVultrOutput) Ip() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.StringOutput { return v.Ip }).(pulumi.StringOutput)
}

// Whether this server is used for building applications.
func (o ServerVultrOutput) IsBuildServer() pulumi.BoolOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.BoolOutput { return v.IsBuildServer }).(pulumi.BoolOutput)
}

// Whether this server uses a Cloudflare Tunnel.
func (o ServerVultrOutput) IsCloudflareTunnel() pulumi.BoolOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.BoolOutput { return v.IsCloudflareTunnel }).(pulumi.BoolOutput)
}

// Whether this server is a jump host. Read-only (not on public server PATCH allow-list).
func (o ServerVultrOutput) IsJumpServer() pulumi.BoolOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.BoolOutput { return v.IsJumpServer }).(pulumi.BoolOutput)
}

// Whether Axiom log drain is enabled. Read-only (not on public server PATCH allow-list).
func (o ServerVultrOutput) IsLogdrainAxiomEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.BoolOutput { return v.IsLogdrainAxiomEnabled }).(pulumi.BoolOutput)
}

// Whether custom log drain is enabled. Read-only.
func (o ServerVultrOutput) IsLogdrainCustomEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.BoolOutput { return v.IsLogdrainCustomEnabled }).(pulumi.BoolOutput)
}

// Whether Highlight log drain is enabled. Read-only.
func (o ServerVultrOutput) IsLogdrainHighlightEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.BoolOutput { return v.IsLogdrainHighlightEnabled }).(pulumi.BoolOutput)
}

// Whether New Relic log drain is enabled. Read-only.
func (o ServerVultrOutput) IsLogdrainNewrelicEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.BoolOutput { return v.IsLogdrainNewrelicEnabled }).(pulumi.BoolOutput)
}

// Whether metrics collection is enabled on this server.
func (o ServerVultrOutput) IsMetricsEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.BoolOutput { return v.IsMetricsEnabled }).(pulumi.BoolOutput)
}

// Whether the server is currently reachable.
func (o ServerVultrOutput) IsReachable() pulumi.BoolOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.BoolOutput { return v.IsReachable }).(pulumi.BoolOutput)
}

// Whether Sentinel debug mode is enabled. Read-only (not on public server PATCH allow-list).
func (o ServerVultrOutput) IsSentinelDebugEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.BoolOutput { return v.IsSentinelDebugEnabled }).(pulumi.BoolOutput)
}

// Whether the Sentinel monitoring agent is enabled.
func (o ServerVultrOutput) IsSentinelEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.BoolOutput { return v.IsSentinelEnabled }).(pulumi.BoolOutput)
}

// Whether this server is a Docker Swarm manager. Read-only (not on public server PATCH allow-list).
func (o ServerVultrOutput) IsSwarmManager() pulumi.BoolOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.BoolOutput { return v.IsSwarmManager }).(pulumi.BoolOutput)
}

// Whether this server is a Docker Swarm worker. Read-only (not on public server PATCH allow-list).
func (o ServerVultrOutput) IsSwarmWorker() pulumi.BoolOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.BoolOutput { return v.IsSwarmWorker }).(pulumi.BoolOutput)
}

// Whether the web terminal is enabled for this server.
func (o ServerVultrOutput) IsTerminalEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.BoolOutput { return v.IsTerminalEnabled }).(pulumi.BoolOutput)
}

// Whether the server is currently usable for deployments.
func (o ServerVultrOutput) IsUsable() pulumi.BoolOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.BoolOutput { return v.IsUsable }).(pulumi.BoolOutput)
}

// Axiom API key for log drain. Sensitive; read-only.
func (o ServerVultrOutput) LogdrainAxiomApiKey() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.StringOutput { return v.LogdrainAxiomApiKey }).(pulumi.StringOutput)
}

// Axiom dataset name for log drain. Read-only.
func (o ServerVultrOutput) LogdrainAxiomDatasetName() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.StringOutput { return v.LogdrainAxiomDatasetName }).(pulumi.StringOutput)
}

// Custom log drain configuration. Sensitive; read-only.
func (o ServerVultrOutput) LogdrainCustomConfig() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.StringOutput { return v.LogdrainCustomConfig }).(pulumi.StringOutput)
}

// Custom log drain config parser. Read-only.
func (o ServerVultrOutput) LogdrainCustomConfigParser() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.StringOutput { return v.LogdrainCustomConfigParser }).(pulumi.StringOutput)
}

// Highlight project ID for log drain. Read-only.
func (o ServerVultrOutput) LogdrainHighlightProjectId() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.StringOutput { return v.LogdrainHighlightProjectId }).(pulumi.StringOutput)
}

// New Relic base URI for log drain. Read-only.
func (o ServerVultrOutput) LogdrainNewrelicBaseUri() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.StringOutput { return v.LogdrainNewrelicBaseUri }).(pulumi.StringOutput)
}

// New Relic license key for log drain. Sensitive; read-only.
func (o ServerVultrOutput) LogdrainNewrelicLicenseKey() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.StringOutput { return v.LogdrainNewrelicLicenseKey }).(pulumi.StringOutput)
}

// The name of the server.
func (o ServerVultrOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The Vultr operating system ID. Use <span pulumi-lang-nodejs="`coolify.getVultrOs`" pulumi-lang-dotnet="`coolify.getVultrOs`" pulumi-lang-go="`getVultrOs`" pulumi-lang-python="`get_vultr_os`" pulumi-lang-yaml="`coolify.getVultrOs`" pulumi-lang-java="`coolify.getVultrOs`" pulumi-lang-hcl="`data.coolify_vultr_os`">`coolify.getVultrOs`</span> to list available operating systems. Changing this forces a new resource.
func (o ServerVultrOutput) OsId() pulumi.IntOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.IntOutput { return v.OsId }).(pulumi.IntOutput)
}

// The Vultr server type (e.g., `s-1vcpu-1gb`). Use <span pulumi-lang-nodejs="`coolify.getVultrPlans`" pulumi-lang-dotnet="`coolify.getVultrPlans`" pulumi-lang-go="`getVultrPlans`" pulumi-lang-python="`get_vultr_plans`" pulumi-lang-yaml="`coolify.getVultrPlans`" pulumi-lang-java="`coolify.getVultrPlans`" pulumi-lang-hcl="`data.coolify_vultr_plans`">`coolify.getVultrPlans`</span> to list available plans. Changing this forces a new resource.
func (o ServerVultrOutput) Plan() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.StringOutput { return v.Plan }).(pulumi.StringOutput)
}

// The SSH port of the server.
func (o ServerVultrOutput) Port() pulumi.IntOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.IntOutput { return v.Port }).(pulumi.IntOutput)
}

// The UUID of the private key used for SSH authentication.
func (o ServerVultrOutput) PrivateKeyUuid() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.StringOutput { return v.PrivateKeyUuid }).(pulumi.StringOutput)
}

// The Vultr region slug (e.g., <span pulumi-lang-nodejs="`nyc1`" pulumi-lang-dotnet="`Nyc1`" pulumi-lang-go="`nyc1`" pulumi-lang-python="`nyc1`" pulumi-lang-yaml="`nyc1`" pulumi-lang-java="`nyc1`" pulumi-lang-hcl="`nyc1`">`nyc1`</span>). Use <span pulumi-lang-nodejs="`coolify.getVultrRegions`" pulumi-lang-dotnet="`coolify.getVultrRegions`" pulumi-lang-go="`getVultrRegions`" pulumi-lang-python="`get_vultr_regions`" pulumi-lang-yaml="`coolify.getVultrRegions`" pulumi-lang-java="`coolify.getVultrRegions`" pulumi-lang-hcl="`data.coolify_vultr_regions`">`coolify.getVultrRegions`</span> to list available regions. Changing this forces a new resource.
func (o ServerVultrOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.StringOutput { return v.Region }).(pulumi.StringOutput)
}

// Custom Sentinel push URL. Read-only (not on public server PATCH allow-list).
func (o ServerVultrOutput) SentinelCustomUrl() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.StringOutput { return v.SentinelCustomUrl }).(pulumi.StringOutput)
}

// Number of days to retain Sentinel metrics.
func (o ServerVultrOutput) SentinelMetricsHistoryDays() pulumi.IntOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.IntOutput { return v.SentinelMetricsHistoryDays }).(pulumi.IntOutput)
}

// Sentinel metrics refresh rate in seconds.
func (o ServerVultrOutput) SentinelMetricsRefreshRateSeconds() pulumi.IntOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.IntOutput { return v.SentinelMetricsRefreshRateSeconds }).(pulumi.IntOutput)
}

// Interval in seconds between Sentinel metric pushes.
func (o ServerVultrOutput) SentinelPushIntervalSeconds() pulumi.IntOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.IntOutput { return v.SentinelPushIntervalSeconds }).(pulumi.IntOutput)
}

// Sentinel agent token. Sensitive; only returned when the API token can read secrets. Read-only.
func (o ServerVultrOutput) SentinelToken() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.StringOutput { return v.SentinelToken }).(pulumi.StringOutput)
}

// Cron or Coolify human schedule for how often disk usage is checked (e.g., `*/5 * * * *`, <span pulumi-lang-nodejs="`daily`" pulumi-lang-dotnet="`Daily`" pulumi-lang-go="`daily`" pulumi-lang-python="`daily`" pulumi-lang-yaml="`daily`" pulumi-lang-java="`daily`" pulumi-lang-hcl="`daily`">`daily`</span>, `@daily`).
func (o ServerVultrOutput) ServerDiskUsageCheckFrequency() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.StringOutput { return v.ServerDiskUsageCheckFrequency }).(pulumi.StringOutput)
}

// Disk usage percentage at which a notification is sent.
func (o ServerVultrOutput) ServerDiskUsageNotificationThreshold() pulumi.IntOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.IntOutput { return v.ServerDiskUsageNotificationThreshold }).(pulumi.IntOutput)
}

// Server timezone (e.g., `UTC`, `America/New_York`).
func (o ServerVultrOutput) ServerTimezone() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.StringOutput { return v.ServerTimezone }).(pulumi.StringOutput)
}

func (o ServerVultrOutput) Timeouts() ServerVultrTimeoutsPtrOutput {
	return o.ApplyT(func(v *ServerVultr) ServerVultrTimeoutsPtrOutput { return v.Timeouts }).(ServerVultrTimeoutsPtrOutput)
}

// The SSH user for connecting to the server.
func (o ServerVultrOutput) User() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.StringOutput { return v.User }).(pulumi.StringOutput)
}

// The unique identifier of the server.
func (o ServerVultrOutput) Uuid() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.StringOutput { return v.Uuid }).(pulumi.StringOutput)
}

// Comma-separated list of Vultr SSH key IDs (strings). Use <span pulumi-lang-nodejs="`coolify.getVultrSshKeys`" pulumi-lang-dotnet="`coolify.getVultrSshKeys`" pulumi-lang-go="`getVultrSshKeys`" pulumi-lang-python="`get_vultr_ssh_keys`" pulumi-lang-yaml="`coolify.getVultrSshKeys`" pulumi-lang-java="`coolify.getVultrSshKeys`" pulumi-lang-hcl="`data.coolify_vultr_ssh_keys`">`coolify.getVultrSshKeys`</span> to list available keys. Changing this forces a new resource.
func (o ServerVultrOutput) VultrSshKeyIds() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.StringPtrOutput { return v.VultrSshKeyIds }).(pulumi.StringPtrOutput)
}

// Wildcard domain for applications on this server (e.g., `example.com`).
func (o ServerVultrOutput) WildcardDomain() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerVultr) pulumi.StringOutput { return v.WildcardDomain }).(pulumi.StringOutput)
}

type ServerVultrArrayOutput struct{ *pulumi.OutputState }

func (ServerVultrArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ServerVultr)(nil)).Elem()
}

func (o ServerVultrArrayOutput) ToServerVultrArrayOutput() ServerVultrArrayOutput {
	return o
}

func (o ServerVultrArrayOutput) ToServerVultrArrayOutputWithContext(ctx context.Context) ServerVultrArrayOutput {
	return o
}

func (o ServerVultrArrayOutput) Index(i pulumi.IntInput) ServerVultrOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ServerVultr {
		return vs[0].([]*ServerVultr)[vs[1].(int)]
	}).(ServerVultrOutput)
}

type ServerVultrMapOutput struct{ *pulumi.OutputState }

func (ServerVultrMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ServerVultr)(nil)).Elem()
}

func (o ServerVultrMapOutput) ToServerVultrMapOutput() ServerVultrMapOutput {
	return o
}

func (o ServerVultrMapOutput) ToServerVultrMapOutputWithContext(ctx context.Context) ServerVultrMapOutput {
	return o
}

func (o ServerVultrMapOutput) MapIndex(k pulumi.StringInput) ServerVultrOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ServerVultr {
		return vs[0].(map[string]*ServerVultr)[vs[1].(string)]
	}).(ServerVultrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ServerVultrInput)(nil)).Elem(), &ServerVultr{})
	pulumi.RegisterInputType(reflect.TypeOf((*ServerVultrArrayInput)(nil)).Elem(), ServerVultrArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ServerVultrMapInput)(nil)).Elem(), ServerVultrMap{})
	pulumi.RegisterOutputType(ServerVultrOutput{})
	pulumi.RegisterOutputType(ServerVultrArrayOutput{})
	pulumi.RegisterOutputType(ServerVultrMapOutput{})
}
