// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package coolify

import (
	"context"
	"reflect"

	"errors"
	"github.com/mheers/pulumi-provider-coolify/sdk/go/coolify/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Manages whether a Coolify server uses a Cloudflare tunnel. Requires Coolify >= v4.3.0. Destroy sets<span pulumi-lang-nodejs=" isCloudflareTunnel " pulumi-lang-dotnet=" IsCloudflareTunnel " pulumi-lang-go=" isCloudflareTunnel " pulumi-lang-python=" is_cloudflare_tunnel " pulumi-lang-yaml=" isCloudflareTunnel " pulumi-lang-java=" isCloudflareTunnel " pulumi-lang-hcl=" is_cloudflare_tunnel "> isCloudflareTunnel </span>to false.
//
// ## Example Usage
//
// <!--Start PulumiCodeChooser -->
// ```go
// package main
//
// import (
//
//	"github.com/mheers/pulumi-provider-coolify/sdk/go/coolify"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := coolify.NewServerCloudflareTunnel(ctx, "example", &coolify.ServerCloudflareTunnelArgs{
//				ServerUuid:         pulumi.Any(exampleCoolifyServer.Uuid),
//				IsCloudflareTunnel: pulumi.Bool(true),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
// <!--End PulumiCodeChooser -->
//
// ## Import
//
// The `pulumi import` command can be used, for example:
//
// ```sh
// $ pulumi import coolify:index/serverCloudflareTunnel:ServerCloudflareTunnel example <server-uuid>
// ```
type ServerCloudflareTunnel struct {
	pulumi.CustomResourceState

	// Whether Cloudflare tunnel is enabled on the server.
	IsCloudflareTunnel pulumi.BoolOutput   `pulumi:"isCloudflareTunnel"`
	ServerUuid         pulumi.StringOutput `pulumi:"serverUuid"`
}

// NewServerCloudflareTunnel registers a new resource with the given unique name, arguments, and options.
func NewServerCloudflareTunnel(ctx *pulumi.Context,
	name string, args *ServerCloudflareTunnelArgs, opts ...pulumi.ResourceOption) (*ServerCloudflareTunnel, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.IsCloudflareTunnel == nil {
		return nil, errors.New("invalid value for required argument 'IsCloudflareTunnel'")
	}
	if args.ServerUuid == nil {
		return nil, errors.New("invalid value for required argument 'ServerUuid'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ServerCloudflareTunnel
	err := ctx.RegisterResource("coolify:index/serverCloudflareTunnel:ServerCloudflareTunnel", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetServerCloudflareTunnel gets an existing ServerCloudflareTunnel resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetServerCloudflareTunnel(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ServerCloudflareTunnelState, opts ...pulumi.ResourceOption) (*ServerCloudflareTunnel, error) {
	var resource ServerCloudflareTunnel
	err := ctx.ReadResource("coolify:index/serverCloudflareTunnel:ServerCloudflareTunnel", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ServerCloudflareTunnel resources.
type serverCloudflareTunnelState struct {
	// Whether Cloudflare tunnel is enabled on the server.
	IsCloudflareTunnel *bool   `pulumi:"isCloudflareTunnel"`
	ServerUuid         *string `pulumi:"serverUuid"`
}

type ServerCloudflareTunnelState struct {
	// Whether Cloudflare tunnel is enabled on the server.
	IsCloudflareTunnel pulumi.BoolPtrInput
	ServerUuid         pulumi.StringPtrInput
}

func (ServerCloudflareTunnelState) ElementType() reflect.Type {
	return reflect.TypeOf((*serverCloudflareTunnelState)(nil)).Elem()
}

type serverCloudflareTunnelArgs struct {
	// Whether Cloudflare tunnel is enabled on the server.
	IsCloudflareTunnel bool   `pulumi:"isCloudflareTunnel"`
	ServerUuid         string `pulumi:"serverUuid"`
}

// The set of arguments for constructing a ServerCloudflareTunnel resource.
type ServerCloudflareTunnelArgs struct {
	// Whether Cloudflare tunnel is enabled on the server.
	IsCloudflareTunnel pulumi.BoolInput
	ServerUuid         pulumi.StringInput
}

func (ServerCloudflareTunnelArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*serverCloudflareTunnelArgs)(nil)).Elem()
}

type ServerCloudflareTunnelInput interface {
	pulumi.Input

	ToServerCloudflareTunnelOutput() ServerCloudflareTunnelOutput
	ToServerCloudflareTunnelOutputWithContext(ctx context.Context) ServerCloudflareTunnelOutput
}

func (*ServerCloudflareTunnel) ElementType() reflect.Type {
	return reflect.TypeOf((**ServerCloudflareTunnel)(nil)).Elem()
}

func (i *ServerCloudflareTunnel) ToServerCloudflareTunnelOutput() ServerCloudflareTunnelOutput {
	return i.ToServerCloudflareTunnelOutputWithContext(context.Background())
}

func (i *ServerCloudflareTunnel) ToServerCloudflareTunnelOutputWithContext(ctx context.Context) ServerCloudflareTunnelOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServerCloudflareTunnelOutput)
}

// ServerCloudflareTunnelArrayInput is an input type that accepts ServerCloudflareTunnelArray and ServerCloudflareTunnelArrayOutput values.
// You can construct a concrete instance of `ServerCloudflareTunnelArrayInput` via:
//
//	ServerCloudflareTunnelArray{ ServerCloudflareTunnelArgs{...} }
type ServerCloudflareTunnelArrayInput interface {
	pulumi.Input

	ToServerCloudflareTunnelArrayOutput() ServerCloudflareTunnelArrayOutput
	ToServerCloudflareTunnelArrayOutputWithContext(context.Context) ServerCloudflareTunnelArrayOutput
}

type ServerCloudflareTunnelArray []ServerCloudflareTunnelInput

func (ServerCloudflareTunnelArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ServerCloudflareTunnel)(nil)).Elem()
}

func (i ServerCloudflareTunnelArray) ToServerCloudflareTunnelArrayOutput() ServerCloudflareTunnelArrayOutput {
	return i.ToServerCloudflareTunnelArrayOutputWithContext(context.Background())
}

func (i ServerCloudflareTunnelArray) ToServerCloudflareTunnelArrayOutputWithContext(ctx context.Context) ServerCloudflareTunnelArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServerCloudflareTunnelArrayOutput)
}

// ServerCloudflareTunnelMapInput is an input type that accepts ServerCloudflareTunnelMap and ServerCloudflareTunnelMapOutput values.
// You can construct a concrete instance of `ServerCloudflareTunnelMapInput` via:
//
//	ServerCloudflareTunnelMap{ "key": ServerCloudflareTunnelArgs{...} }
type ServerCloudflareTunnelMapInput interface {
	pulumi.Input

	ToServerCloudflareTunnelMapOutput() ServerCloudflareTunnelMapOutput
	ToServerCloudflareTunnelMapOutputWithContext(context.Context) ServerCloudflareTunnelMapOutput
}

type ServerCloudflareTunnelMap map[string]ServerCloudflareTunnelInput

func (ServerCloudflareTunnelMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ServerCloudflareTunnel)(nil)).Elem()
}

func (i ServerCloudflareTunnelMap) ToServerCloudflareTunnelMapOutput() ServerCloudflareTunnelMapOutput {
	return i.ToServerCloudflareTunnelMapOutputWithContext(context.Background())
}

func (i ServerCloudflareTunnelMap) ToServerCloudflareTunnelMapOutputWithContext(ctx context.Context) ServerCloudflareTunnelMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServerCloudflareTunnelMapOutput)
}

type ServerCloudflareTunnelOutput struct{ *pulumi.OutputState }

func (ServerCloudflareTunnelOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ServerCloudflareTunnel)(nil)).Elem()
}

func (o ServerCloudflareTunnelOutput) ToServerCloudflareTunnelOutput() ServerCloudflareTunnelOutput {
	return o
}

func (o ServerCloudflareTunnelOutput) ToServerCloudflareTunnelOutputWithContext(ctx context.Context) ServerCloudflareTunnelOutput {
	return o
}

// Whether Cloudflare tunnel is enabled on the server.
func (o ServerCloudflareTunnelOutput) IsCloudflareTunnel() pulumi.BoolOutput {
	return o.ApplyT(func(v *ServerCloudflareTunnel) pulumi.BoolOutput { return v.IsCloudflareTunnel }).(pulumi.BoolOutput)
}

func (o ServerCloudflareTunnelOutput) ServerUuid() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerCloudflareTunnel) pulumi.StringOutput { return v.ServerUuid }).(pulumi.StringOutput)
}

type ServerCloudflareTunnelArrayOutput struct{ *pulumi.OutputState }

func (ServerCloudflareTunnelArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ServerCloudflareTunnel)(nil)).Elem()
}

func (o ServerCloudflareTunnelArrayOutput) ToServerCloudflareTunnelArrayOutput() ServerCloudflareTunnelArrayOutput {
	return o
}

func (o ServerCloudflareTunnelArrayOutput) ToServerCloudflareTunnelArrayOutputWithContext(ctx context.Context) ServerCloudflareTunnelArrayOutput {
	return o
}

func (o ServerCloudflareTunnelArrayOutput) Index(i pulumi.IntInput) ServerCloudflareTunnelOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ServerCloudflareTunnel {
		return vs[0].([]*ServerCloudflareTunnel)[vs[1].(int)]
	}).(ServerCloudflareTunnelOutput)
}

type ServerCloudflareTunnelMapOutput struct{ *pulumi.OutputState }

func (ServerCloudflareTunnelMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ServerCloudflareTunnel)(nil)).Elem()
}

func (o ServerCloudflareTunnelMapOutput) ToServerCloudflareTunnelMapOutput() ServerCloudflareTunnelMapOutput {
	return o
}

func (o ServerCloudflareTunnelMapOutput) ToServerCloudflareTunnelMapOutputWithContext(ctx context.Context) ServerCloudflareTunnelMapOutput {
	return o
}

func (o ServerCloudflareTunnelMapOutput) MapIndex(k pulumi.StringInput) ServerCloudflareTunnelOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ServerCloudflareTunnel {
		return vs[0].(map[string]*ServerCloudflareTunnel)[vs[1].(string)]
	}).(ServerCloudflareTunnelOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ServerCloudflareTunnelInput)(nil)).Elem(), &ServerCloudflareTunnel{})
	pulumi.RegisterInputType(reflect.TypeOf((*ServerCloudflareTunnelArrayInput)(nil)).Elem(), ServerCloudflareTunnelArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ServerCloudflareTunnelMapInput)(nil)).Elem(), ServerCloudflareTunnelMap{})
	pulumi.RegisterOutputType(ServerCloudflareTunnelOutput{})
	pulumi.RegisterOutputType(ServerCloudflareTunnelArrayOutput{})
	pulumi.RegisterOutputType(ServerCloudflareTunnelMapOutput{})
}
