// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package coolify

import (
	"context"
	"reflect"

	"errors"
	"github.com/mheers/pulumi-provider-coolify/sdk/go/coolify/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Provisions a DigitalOcean droplet and registers it with Coolify. Requires Coolify >= v4.2.0.
//
// > **Warning:** Deleting this resource will delete the server from Coolify and cascade-delete all applications, databases, and services deployed on it. The underlying DigitalOcean server is not destroyed; manage its lifecycle separately.
//
// > **Import note:** DigitalOcean-specific fields (<span pulumi-lang-nodejs="`cloudProviderTokenUuid`" pulumi-lang-dotnet="`CloudProviderTokenUuid`" pulumi-lang-go="`cloudProviderTokenUuid`" pulumi-lang-python="`cloud_provider_token_uuid`" pulumi-lang-yaml="`cloudProviderTokenUuid`" pulumi-lang-java="`cloudProviderTokenUuid`" pulumi-lang-hcl="`cloud_provider_token_uuid`">`cloudProviderTokenUuid`</span>, <span pulumi-lang-nodejs="`size`" pulumi-lang-dotnet="`Size`" pulumi-lang-go="`size`" pulumi-lang-python="`size`" pulumi-lang-yaml="`size`" pulumi-lang-java="`size`" pulumi-lang-hcl="`size`">`size`</span>, <span pulumi-lang-nodejs="`region`" pulumi-lang-dotnet="`Region`" pulumi-lang-go="`region`" pulumi-lang-python="`region`" pulumi-lang-yaml="`region`" pulumi-lang-java="`region`" pulumi-lang-hcl="`region`">`region`</span>, <span pulumi-lang-nodejs="`image`" pulumi-lang-dotnet="`Image`" pulumi-lang-go="`image`" pulumi-lang-python="`image`" pulumi-lang-yaml="`image`" pulumi-lang-java="`image`" pulumi-lang-hcl="`image`">`image`</span>, <span pulumi-lang-nodejs="`digitaloceanSshKeyIds`" pulumi-lang-dotnet="`DigitaloceanSshKeyIds`" pulumi-lang-go="`digitaloceanSshKeyIds`" pulumi-lang-python="`digitalocean_ssh_key_ids`" pulumi-lang-yaml="`digitaloceanSshKeyIds`" pulumi-lang-java="`digitaloceanSshKeyIds`" pulumi-lang-hcl="`digitalocean_ssh_key_ids`">`digitaloceanSshKeyIds`</span>, <span pulumi-lang-nodejs="`cloudInitScript`" pulumi-lang-dotnet="`CloudInitScript`" pulumi-lang-go="`cloudInitScript`" pulumi-lang-python="`cloud_init_script`" pulumi-lang-yaml="`cloudInitScript`" pulumi-lang-java="`cloudInitScript`" pulumi-lang-hcl="`cloud_init_script`">`cloudInitScript`</span>) are only sent at creation time and are not returned by the Coolify API. After `pulumi import`, these fields will be empty in state. Set them in your configuration before running `pulumi preview` to avoid a forced replacement.
//
// ## Example Usage
//
// <!--Start PulumiCodeChooser -->
// ```go
// package main
//
// import (
//
//	"github.com/mheers/pulumi-provider-coolify/sdk/go/coolify"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			cfg := config.New(ctx, "")
//			digitaloceanToken := cfg.Require("digitaloceanToken")
//			do, err := coolify.NewCloudToken(ctx, "do", &coolify.CloudTokenArgs{
//				Name:          pulumi.String("digitalocean"),
//				CloudProvider: pulumi.String("digitalocean"),
//				Token:         pulumi.String(digitaloceanToken),
//			})
//			if err != nil {
//				return err
//			}
//			_, err = coolify.NewServerDigitalocean(ctx, "app", &coolify.ServerDigitaloceanArgs{
//				Name:                   pulumi.String("do-app-node"),
//				CloudProviderTokenUuid: do.Uuid,
//				Region:                 pulumi.String("nyc1"),
//				Size:                   pulumi.String("s-1vcpu-1gb"),
//				Image:                  pulumi.String("ubuntu-24-04-x64"),
//				PrivateKeyUuid:         pulumi.Any(main.Uuid),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
// <!--End PulumiCodeChooser -->
//
// ## Import
//
// The `pulumi import` command can be used, for example:
//
// !/bin/sh
// Import requires Coolify >= v4.2.0. DigitalOcean create-only fields are empty after import.
//
// ```sh
// $ pulumi import coolify:index/serverDigitalocean:ServerDigitalocean app <server-uuid>
// ```
type ServerDigitalocean struct {
	pulumi.CustomResourceState

	// CPU percentage Coolify uses when compressing volume backups. Read-only (not on public server PATCH). Present on Coolify >= v4.3.3; empty on older instances.
	BackupCompressionCpuPercentage pulumi.IntOutput `pulumi:"backupCompressionCpuPercentage"`
	// Cloud-init script to run on server creation. Changing this forces a new resource.
	CloudInitScript pulumi.StringPtrOutput `pulumi:"cloudInitScript"`
	// The UUID of the DigitalOcean cloud provider token (from <span pulumi-lang-nodejs="`coolify.CloudToken`" pulumi-lang-dotnet="`coolify.CloudToken`" pulumi-lang-go="`CloudToken`" pulumi-lang-python="`CloudToken`" pulumi-lang-yaml="`coolify.CloudToken`" pulumi-lang-java="`coolify.CloudToken`" pulumi-lang-hcl="`coolify_cloud_token`">`coolify.CloudToken`</span>). Changing this forces a new resource.
	CloudProviderTokenUuid pulumi.StringOutput `pulumi:"cloudProviderTokenUuid"`
	// Docker Compose version reported by Coolify for this server (host probe). Read-only; Populated on Coolify >= v4.3.2 when the host has been probed. Empty on older instances.
	ComposeVersion pulumi.StringOutput `pulumi:"composeVersion"`
	// When Coolify last checked the Compose version on this server. Read-only.
	ComposeVersionCheckedAt pulumi.StringOutput `pulumi:"composeVersionCheckedAt"`
	// How many deployments can run in parallel on this server.
	ConcurrentBuilds pulumi.IntOutput `pulumi:"concurrentBuilds"`
	// SSH connection timeout in seconds.
	ConnectionTimeout pulumi.IntOutput `pulumi:"connectionTimeout"`
	// Whether to delete unused Docker networks during cleanup.
	DeleteUnusedNetworks pulumi.BoolOutput `pulumi:"deleteUnusedNetworks"`
	// Whether to delete unused Docker volumes during cleanup.
	DeleteUnusedVolumes pulumi.BoolOutput `pulumi:"deleteUnusedVolumes"`
	// Maximum number of queued deployments (default 25).
	DeploymentQueueLimit pulumi.IntOutput `pulumi:"deploymentQueueLimit"`
	// A description of the server.
	Description pulumi.StringOutput `pulumi:"description"`
	// Comma-separated list of DigitalOcean SSH key numeric IDs. Use <span pulumi-lang-nodejs="`coolify.getDigitaloceanSshKeys`" pulumi-lang-dotnet="`coolify.getDigitaloceanSshKeys`" pulumi-lang-go="`getDigitaloceanSshKeys`" pulumi-lang-python="`get_digitalocean_ssh_keys`" pulumi-lang-yaml="`coolify.getDigitaloceanSshKeys`" pulumi-lang-java="`coolify.getDigitaloceanSshKeys`" pulumi-lang-hcl="`data.coolify_digitalocean_ssh_keys`">`coolify.getDigitaloceanSshKeys`</span> to list available keys. Changing this forces a new resource.
	DigitaloceanSshKeyIds pulumi.StringPtrOutput `pulumi:"digitaloceanSshKeyIds"`
	// Whether application image retention is disabled. Read-only (not on public server PATCH allow-list).
	DisableApplicationImageRetention pulumi.BoolOutput `pulumi:"disableApplicationImageRetention"`
	// Cron expression for Docker cleanup schedule.
	DockerCleanupFrequency pulumi.StringOutput `pulumi:"dockerCleanupFrequency"`
	// Disk usage percentage threshold for Docker cleanup.
	DockerCleanupThreshold pulumi.IntOutput `pulumi:"dockerCleanupThreshold"`
	// Docker engine version reported by Coolify for this server (host probe). Read-only; Populated on Coolify >= v4.3.2 when the host has been probed. Empty on older instances.
	DockerVersion pulumi.StringOutput `pulumi:"dockerVersion"`
	// When Coolify last checked the Docker version on this server. Read-only.
	DockerVersionCheckedAt pulumi.StringOutput `pulumi:"dockerVersionCheckedAt"`
	// Timeout in seconds for Docker operations (pull, build, health check) during deployment.
	DynamicTimeout pulumi.IntOutput `pulumi:"dynamicTimeout"`
	// Whether to enable IPv6 on the droplet. Defaults to true to match Coolify.
	EnableIpv6 pulumi.BoolOutput `pulumi:"enableIpv6"`
	// Whether the server is force-disabled in Coolify. Read-only (not on public server PATCH allow-list).
	ForceDisabled pulumi.BoolOutput `pulumi:"forceDisabled"`
	// Whether to force Docker cleanup regardless of disk usage.
	ForceDockerCleanup pulumi.BoolOutput `pulumi:"forceDockerCleanup"`
	// Whether to generate exact Docker labels (removes extra labels from containers).
	GenerateExactLabels pulumi.BoolOutput `pulumi:"generateExactLabels"`
	// The OS image to use (e.g., `ubuntu-24.04`). Use <span pulumi-lang-nodejs="`coolify.getDigitaloceanImages`" pulumi-lang-dotnet="`coolify.getDigitaloceanImages`" pulumi-lang-go="`getDigitaloceanImages`" pulumi-lang-python="`get_digitalocean_images`" pulumi-lang-yaml="`coolify.getDigitaloceanImages`" pulumi-lang-java="`coolify.getDigitaloceanImages`" pulumi-lang-hcl="`data.coolify_digitalocean_images`">`coolify.getDigitaloceanImages`</span> data source to list available images. Changing this forces a new resource.
	Image pulumi.StringOutput `pulumi:"image"`
	// Whether to validate server connectivity immediately after creation. Defaults to false to match Coolify.
	InstantValidate pulumi.BoolOutput `pulumi:"instantValidate"`
	// The IP address assigned to the server by DigitalOcean.
	Ip pulumi.StringOutput `pulumi:"ip"`
	// Whether this server is used for building applications.
	IsBuildServer pulumi.BoolOutput `pulumi:"isBuildServer"`
	// Whether this server uses a Cloudflare Tunnel.
	IsCloudflareTunnel pulumi.BoolOutput `pulumi:"isCloudflareTunnel"`
	// Whether this server is a jump host. Read-only (not on public server PATCH allow-list).
	IsJumpServer pulumi.BoolOutput `pulumi:"isJumpServer"`
	// Whether Axiom log drain is enabled. Read-only (not on public server PATCH allow-list).
	IsLogdrainAxiomEnabled pulumi.BoolOutput `pulumi:"isLogdrainAxiomEnabled"`
	// Whether custom log drain is enabled. Read-only.
	IsLogdrainCustomEnabled pulumi.BoolOutput `pulumi:"isLogdrainCustomEnabled"`
	// Whether Highlight log drain is enabled. Read-only.
	IsLogdrainHighlightEnabled pulumi.BoolOutput `pulumi:"isLogdrainHighlightEnabled"`
	// Whether New Relic log drain is enabled. Read-only.
	IsLogdrainNewrelicEnabled pulumi.BoolOutput `pulumi:"isLogdrainNewrelicEnabled"`
	// Whether metrics collection is enabled on this server.
	IsMetricsEnabled pulumi.BoolOutput `pulumi:"isMetricsEnabled"`
	// Whether the server is currently reachable.
	IsReachable pulumi.BoolOutput `pulumi:"isReachable"`
	// Whether Sentinel debug mode is enabled. Read-only (not on public server PATCH allow-list).
	IsSentinelDebugEnabled pulumi.BoolOutput `pulumi:"isSentinelDebugEnabled"`
	// Whether the Sentinel monitoring agent is enabled.
	IsSentinelEnabled pulumi.BoolOutput `pulumi:"isSentinelEnabled"`
	// Whether this server is a Docker Swarm manager. Read-only (not on public server PATCH allow-list).
	IsSwarmManager pulumi.BoolOutput `pulumi:"isSwarmManager"`
	// Whether this server is a Docker Swarm worker. Read-only (not on public server PATCH allow-list).
	IsSwarmWorker pulumi.BoolOutput `pulumi:"isSwarmWorker"`
	// Whether the web terminal is enabled for this server.
	IsTerminalEnabled pulumi.BoolOutput `pulumi:"isTerminalEnabled"`
	// Whether the server is currently usable for deployments.
	IsUsable pulumi.BoolOutput `pulumi:"isUsable"`
	// Axiom API key for log drain. Sensitive; read-only.
	LogdrainAxiomApiKey pulumi.StringOutput `pulumi:"logdrainAxiomApiKey"`
	// Axiom dataset name for log drain. Read-only.
	LogdrainAxiomDatasetName pulumi.StringOutput `pulumi:"logdrainAxiomDatasetName"`
	// Custom log drain configuration. Sensitive; read-only.
	LogdrainCustomConfig pulumi.StringOutput `pulumi:"logdrainCustomConfig"`
	// Custom log drain config parser. Read-only.
	LogdrainCustomConfigParser pulumi.StringOutput `pulumi:"logdrainCustomConfigParser"`
	// Highlight project ID for log drain. Read-only.
	LogdrainHighlightProjectId pulumi.StringOutput `pulumi:"logdrainHighlightProjectId"`
	// New Relic base URI for log drain. Read-only.
	LogdrainNewrelicBaseUri pulumi.StringOutput `pulumi:"logdrainNewrelicBaseUri"`
	// New Relic license key for log drain. Sensitive; read-only.
	LogdrainNewrelicLicenseKey pulumi.StringOutput `pulumi:"logdrainNewrelicLicenseKey"`
	// Whether to enable DigitalOcean monitoring on the droplet. Defaults to true to match Coolify.
	Monitoring pulumi.BoolOutput `pulumi:"monitoring"`
	// The name of the server.
	Name pulumi.StringOutput `pulumi:"name"`
	// The SSH port of the server.
	Port pulumi.IntOutput `pulumi:"port"`
	// The UUID of the private key used for SSH authentication.
	PrivateKeyUuid pulumi.StringOutput `pulumi:"privateKeyUuid"`
	// The DigitalOcean region slug (e.g., <span pulumi-lang-nodejs="`nyc1`" pulumi-lang-dotnet="`Nyc1`" pulumi-lang-go="`nyc1`" pulumi-lang-python="`nyc1`" pulumi-lang-yaml="`nyc1`" pulumi-lang-java="`nyc1`" pulumi-lang-hcl="`nyc1`">`nyc1`</span>). Use <span pulumi-lang-nodejs="`coolify.getDigitaloceanRegions`" pulumi-lang-dotnet="`coolify.getDigitaloceanRegions`" pulumi-lang-go="`getDigitaloceanRegions`" pulumi-lang-python="`get_digitalocean_regions`" pulumi-lang-yaml="`coolify.getDigitaloceanRegions`" pulumi-lang-java="`coolify.getDigitaloceanRegions`" pulumi-lang-hcl="`data.coolify_digitalocean_regions`">`coolify.getDigitaloceanRegions`</span> to list available regions. Changing this forces a new resource.
	Region pulumi.StringOutput `pulumi:"region"`
	// Custom Sentinel push URL. Read-only (not on public server PATCH allow-list).
	SentinelCustomUrl pulumi.StringOutput `pulumi:"sentinelCustomUrl"`
	// Number of days to retain Sentinel metrics.
	SentinelMetricsHistoryDays pulumi.IntOutput `pulumi:"sentinelMetricsHistoryDays"`
	// Sentinel metrics refresh rate in seconds.
	SentinelMetricsRefreshRateSeconds pulumi.IntOutput `pulumi:"sentinelMetricsRefreshRateSeconds"`
	// Interval in seconds between Sentinel metric pushes.
	SentinelPushIntervalSeconds pulumi.IntOutput `pulumi:"sentinelPushIntervalSeconds"`
	// Sentinel agent token. Sensitive; only returned when the API token can read secrets. Read-only.
	SentinelToken pulumi.StringOutput `pulumi:"sentinelToken"`
	// Cron or Coolify human schedule for how often disk usage is checked (e.g., `*/5 * * * *`, <span pulumi-lang-nodejs="`daily`" pulumi-lang-dotnet="`Daily`" pulumi-lang-go="`daily`" pulumi-lang-python="`daily`" pulumi-lang-yaml="`daily`" pulumi-lang-java="`daily`" pulumi-lang-hcl="`daily`">`daily`</span>, `@daily`).
	ServerDiskUsageCheckFrequency pulumi.StringOutput `pulumi:"serverDiskUsageCheckFrequency"`
	// Disk usage percentage at which a notification is sent.
	ServerDiskUsageNotificationThreshold pulumi.IntOutput `pulumi:"serverDiskUsageNotificationThreshold"`
	// Server timezone (e.g., `UTC`, `America/New_York`).
	ServerTimezone pulumi.StringOutput `pulumi:"serverTimezone"`
	// The DigitalOcean server type (e.g., `s-1vcpu-1gb`). Use <span pulumi-lang-nodejs="`coolify.getDigitaloceanSizes`" pulumi-lang-dotnet="`coolify.getDigitaloceanSizes`" pulumi-lang-go="`getDigitaloceanSizes`" pulumi-lang-python="`get_digitalocean_sizes`" pulumi-lang-yaml="`coolify.getDigitaloceanSizes`" pulumi-lang-java="`coolify.getDigitaloceanSizes`" pulumi-lang-hcl="`data.coolify_digitalocean_sizes`">`coolify.getDigitaloceanSizes`</span> data source to list available types. Changing this forces a new resource.
	Size     pulumi.StringOutput                 `pulumi:"size"`
	Timeouts ServerDigitaloceanTimeoutsPtrOutput `pulumi:"timeouts"`
	// The SSH user for connecting to the server.
	User pulumi.StringOutput `pulumi:"user"`
	// The unique identifier of the server.
	Uuid pulumi.StringOutput `pulumi:"uuid"`
	// Wildcard domain for applications on this server (e.g., `example.com`).
	WildcardDomain pulumi.StringOutput `pulumi:"wildcardDomain"`
}

// NewServerDigitalocean registers a new resource with the given unique name, arguments, and options.
func NewServerDigitalocean(ctx *pulumi.Context,
	name string, args *ServerDigitaloceanArgs, opts ...pulumi.ResourceOption) (*ServerDigitalocean, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.CloudProviderTokenUuid == nil {
		return nil, errors.New("invalid value for required argument 'CloudProviderTokenUuid'")
	}
	if args.Image == nil {
		return nil, errors.New("invalid value for required argument 'Image'")
	}
	if args.PrivateKeyUuid == nil {
		return nil, errors.New("invalid value for required argument 'PrivateKeyUuid'")
	}
	if args.Region == nil {
		return nil, errors.New("invalid value for required argument 'Region'")
	}
	if args.Size == nil {
		return nil, errors.New("invalid value for required argument 'Size'")
	}
	if args.CloudInitScript != nil {
		args.CloudInitScript = pulumi.ToSecret(args.CloudInitScript).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"cloudInitScript",
		"logdrainAxiomApiKey",
		"logdrainCustomConfig",
		"logdrainNewrelicLicenseKey",
		"sentinelToken",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ServerDigitalocean
	err := ctx.RegisterResource("coolify:index/serverDigitalocean:ServerDigitalocean", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetServerDigitalocean gets an existing ServerDigitalocean resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetServerDigitalocean(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ServerDigitaloceanState, opts ...pulumi.ResourceOption) (*ServerDigitalocean, error) {
	var resource ServerDigitalocean
	err := ctx.ReadResource("coolify:index/serverDigitalocean:ServerDigitalocean", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ServerDigitalocean resources.
type serverDigitaloceanState struct {
	// CPU percentage Coolify uses when compressing volume backups. Read-only (not on public server PATCH). Present on Coolify >= v4.3.3; empty on older instances.
	BackupCompressionCpuPercentage *int `pulumi:"backupCompressionCpuPercentage"`
	// Cloud-init script to run on server creation. Changing this forces a new resource.
	CloudInitScript *string `pulumi:"cloudInitScript"`
	// The UUID of the DigitalOcean cloud provider token (from <span pulumi-lang-nodejs="`coolify.CloudToken`" pulumi-lang-dotnet="`coolify.CloudToken`" pulumi-lang-go="`CloudToken`" pulumi-lang-python="`CloudToken`" pulumi-lang-yaml="`coolify.CloudToken`" pulumi-lang-java="`coolify.CloudToken`" pulumi-lang-hcl="`coolify_cloud_token`">`coolify.CloudToken`</span>). Changing this forces a new resource.
	CloudProviderTokenUuid *string `pulumi:"cloudProviderTokenUuid"`
	// Docker Compose version reported by Coolify for this server (host probe). Read-only; Populated on Coolify >= v4.3.2 when the host has been probed. Empty on older instances.
	ComposeVersion *string `pulumi:"composeVersion"`
	// When Coolify last checked the Compose version on this server. Read-only.
	ComposeVersionCheckedAt *string `pulumi:"composeVersionCheckedAt"`
	// How many deployments can run in parallel on this server.
	ConcurrentBuilds *int `pulumi:"concurrentBuilds"`
	// SSH connection timeout in seconds.
	ConnectionTimeout *int `pulumi:"connectionTimeout"`
	// Whether to delete unused Docker networks during cleanup.
	DeleteUnusedNetworks *bool `pulumi:"deleteUnusedNetworks"`
	// Whether to delete unused Docker volumes during cleanup.
	DeleteUnusedVolumes *bool `pulumi:"deleteUnusedVolumes"`
	// Maximum number of queued deployments (default 25).
	DeploymentQueueLimit *int `pulumi:"deploymentQueueLimit"`
	// A description of the server.
	Description *string `pulumi:"description"`
	// Comma-separated list of DigitalOcean SSH key numeric IDs. Use <span pulumi-lang-nodejs="`coolify.getDigitaloceanSshKeys`" pulumi-lang-dotnet="`coolify.getDigitaloceanSshKeys`" pulumi-lang-go="`getDigitaloceanSshKeys`" pulumi-lang-python="`get_digitalocean_ssh_keys`" pulumi-lang-yaml="`coolify.getDigitaloceanSshKeys`" pulumi-lang-java="`coolify.getDigitaloceanSshKeys`" pulumi-lang-hcl="`data.coolify_digitalocean_ssh_keys`">`coolify.getDigitaloceanSshKeys`</span> to list available keys. Changing this forces a new resource.
	DigitaloceanSshKeyIds *string `pulumi:"digitaloceanSshKeyIds"`
	// Whether application image retention is disabled. Read-only (not on public server PATCH allow-list).
	DisableApplicationImageRetention *bool `pulumi:"disableApplicationImageRetention"`
	// Cron expression for Docker cleanup schedule.
	DockerCleanupFrequency *string `pulumi:"dockerCleanupFrequency"`
	// Disk usage percentage threshold for Docker cleanup.
	DockerCleanupThreshold *int `pulumi:"dockerCleanupThreshold"`
	// Docker engine version reported by Coolify for this server (host probe). Read-only; Populated on Coolify >= v4.3.2 when the host has been probed. Empty on older instances.
	DockerVersion *string `pulumi:"dockerVersion"`
	// When Coolify last checked the Docker version on this server. Read-only.
	DockerVersionCheckedAt *string `pulumi:"dockerVersionCheckedAt"`
	// Timeout in seconds for Docker operations (pull, build, health check) during deployment.
	DynamicTimeout *int `pulumi:"dynamicTimeout"`
	// Whether to enable IPv6 on the droplet. Defaults to true to match Coolify.
	EnableIpv6 *bool `pulumi:"enableIpv6"`
	// Whether the server is force-disabled in Coolify. Read-only (not on public server PATCH allow-list).
	ForceDisabled *bool `pulumi:"forceDisabled"`
	// Whether to force Docker cleanup regardless of disk usage.
	ForceDockerCleanup *bool `pulumi:"forceDockerCleanup"`
	// Whether to generate exact Docker labels (removes extra labels from containers).
	GenerateExactLabels *bool `pulumi:"generateExactLabels"`
	// The OS image to use (e.g., `ubuntu-24.04`). Use <span pulumi-lang-nodejs="`coolify.getDigitaloceanImages`" pulumi-lang-dotnet="`coolify.getDigitaloceanImages`" pulumi-lang-go="`getDigitaloceanImages`" pulumi-lang-python="`get_digitalocean_images`" pulumi-lang-yaml="`coolify.getDigitaloceanImages`" pulumi-lang-java="`coolify.getDigitaloceanImages`" pulumi-lang-hcl="`data.coolify_digitalocean_images`">`coolify.getDigitaloceanImages`</span> data source to list available images. Changing this forces a new resource.
	Image *string `pulumi:"image"`
	// Whether to validate server connectivity immediately after creation. Defaults to false to match Coolify.
	InstantValidate *bool `pulumi:"instantValidate"`
	// The IP address assigned to the server by DigitalOcean.
	Ip *string `pulumi:"ip"`
	// Whether this server is used for building applications.
	IsBuildServer *bool `pulumi:"isBuildServer"`
	// Whether this server uses a Cloudflare Tunnel.
	IsCloudflareTunnel *bool `pulumi:"isCloudflareTunnel"`
	// Whether this server is a jump host. Read-only (not on public server PATCH allow-list).
	IsJumpServer *bool `pulumi:"isJumpServer"`
	// Whether Axiom log drain is enabled. Read-only (not on public server PATCH allow-list).
	IsLogdrainAxiomEnabled *bool `pulumi:"isLogdrainAxiomEnabled"`
	// Whether custom log drain is enabled. Read-only.
	IsLogdrainCustomEnabled *bool `pulumi:"isLogdrainCustomEnabled"`
	// Whether Highlight log drain is enabled. Read-only.
	IsLogdrainHighlightEnabled *bool `pulumi:"isLogdrainHighlightEnabled"`
	// Whether New Relic log drain is enabled. Read-only.
	IsLogdrainNewrelicEnabled *bool `pulumi:"isLogdrainNewrelicEnabled"`
	// Whether metrics collection is enabled on this server.
	IsMetricsEnabled *bool `pulumi:"isMetricsEnabled"`
	// Whether the server is currently reachable.
	IsReachable *bool `pulumi:"isReachable"`
	// Whether Sentinel debug mode is enabled. Read-only (not on public server PATCH allow-list).
	IsSentinelDebugEnabled *bool `pulumi:"isSentinelDebugEnabled"`
	// Whether the Sentinel monitoring agent is enabled.
	IsSentinelEnabled *bool `pulumi:"isSentinelEnabled"`
	// Whether this server is a Docker Swarm manager. Read-only (not on public server PATCH allow-list).
	IsSwarmManager *bool `pulumi:"isSwarmManager"`
	// Whether this server is a Docker Swarm worker. Read-only (not on public server PATCH allow-list).
	IsSwarmWorker *bool `pulumi:"isSwarmWorker"`
	// Whether the web terminal is enabled for this server.
	IsTerminalEnabled *bool `pulumi:"isTerminalEnabled"`
	// Whether the server is currently usable for deployments.
	IsUsable *bool `pulumi:"isUsable"`
	// Axiom API key for log drain. Sensitive; read-only.
	LogdrainAxiomApiKey *string `pulumi:"logdrainAxiomApiKey"`
	// Axiom dataset name for log drain. Read-only.
	LogdrainAxiomDatasetName *string `pulumi:"logdrainAxiomDatasetName"`
	// Custom log drain configuration. Sensitive; read-only.
	LogdrainCustomConfig *string `pulumi:"logdrainCustomConfig"`
	// Custom log drain config parser. Read-only.
	LogdrainCustomConfigParser *string `pulumi:"logdrainCustomConfigParser"`
	// Highlight project ID for log drain. Read-only.
	LogdrainHighlightProjectId *string `pulumi:"logdrainHighlightProjectId"`
	// New Relic base URI for log drain. Read-only.
	LogdrainNewrelicBaseUri *string `pulumi:"logdrainNewrelicBaseUri"`
	// New Relic license key for log drain. Sensitive; read-only.
	LogdrainNewrelicLicenseKey *string `pulumi:"logdrainNewrelicLicenseKey"`
	// Whether to enable DigitalOcean monitoring on the droplet. Defaults to true to match Coolify.
	Monitoring *bool `pulumi:"monitoring"`
	// The name of the server.
	Name *string `pulumi:"name"`
	// The SSH port of the server.
	Port *int `pulumi:"port"`
	// The UUID of the private key used for SSH authentication.
	PrivateKeyUuid *string `pulumi:"privateKeyUuid"`
	// The DigitalOcean region slug (e.g., <span pulumi-lang-nodejs="`nyc1`" pulumi-lang-dotnet="`Nyc1`" pulumi-lang-go="`nyc1`" pulumi-lang-python="`nyc1`" pulumi-lang-yaml="`nyc1`" pulumi-lang-java="`nyc1`" pulumi-lang-hcl="`nyc1`">`nyc1`</span>). Use <span pulumi-lang-nodejs="`coolify.getDigitaloceanRegions`" pulumi-lang-dotnet="`coolify.getDigitaloceanRegions`" pulumi-lang-go="`getDigitaloceanRegions`" pulumi-lang-python="`get_digitalocean_regions`" pulumi-lang-yaml="`coolify.getDigitaloceanRegions`" pulumi-lang-java="`coolify.getDigitaloceanRegions`" pulumi-lang-hcl="`data.coolify_digitalocean_regions`">`coolify.getDigitaloceanRegions`</span> to list available regions. Changing this forces a new resource.
	Region *string `pulumi:"region"`
	// Custom Sentinel push URL. Read-only (not on public server PATCH allow-list).
	SentinelCustomUrl *string `pulumi:"sentinelCustomUrl"`
	// Number of days to retain Sentinel metrics.
	SentinelMetricsHistoryDays *int `pulumi:"sentinelMetricsHistoryDays"`
	// Sentinel metrics refresh rate in seconds.
	SentinelMetricsRefreshRateSeconds *int `pulumi:"sentinelMetricsRefreshRateSeconds"`
	// Interval in seconds between Sentinel metric pushes.
	SentinelPushIntervalSeconds *int `pulumi:"sentinelPushIntervalSeconds"`
	// Sentinel agent token. Sensitive; only returned when the API token can read secrets. Read-only.
	SentinelToken *string `pulumi:"sentinelToken"`
	// Cron or Coolify human schedule for how often disk usage is checked (e.g., `*/5 * * * *`, <span pulumi-lang-nodejs="`daily`" pulumi-lang-dotnet="`Daily`" pulumi-lang-go="`daily`" pulumi-lang-python="`daily`" pulumi-lang-yaml="`daily`" pulumi-lang-java="`daily`" pulumi-lang-hcl="`daily`">`daily`</span>, `@daily`).
	ServerDiskUsageCheckFrequency *string `pulumi:"serverDiskUsageCheckFrequency"`
	// Disk usage percentage at which a notification is sent.
	ServerDiskUsageNotificationThreshold *int `pulumi:"serverDiskUsageNotificationThreshold"`
	// Server timezone (e.g., `UTC`, `America/New_York`).
	ServerTimezone *string `pulumi:"serverTimezone"`
	// The DigitalOcean server type (e.g., `s-1vcpu-1gb`). Use <span pulumi-lang-nodejs="`coolify.getDigitaloceanSizes`" pulumi-lang-dotnet="`coolify.getDigitaloceanSizes`" pulumi-lang-go="`getDigitaloceanSizes`" pulumi-lang-python="`get_digitalocean_sizes`" pulumi-lang-yaml="`coolify.getDigitaloceanSizes`" pulumi-lang-java="`coolify.getDigitaloceanSizes`" pulumi-lang-hcl="`data.coolify_digitalocean_sizes`">`coolify.getDigitaloceanSizes`</span> data source to list available types. Changing this forces a new resource.
	Size     *string                     `pulumi:"size"`
	Timeouts *ServerDigitaloceanTimeouts `pulumi:"timeouts"`
	// The SSH user for connecting to the server.
	User *string `pulumi:"user"`
	// The unique identifier of the server.
	Uuid *string `pulumi:"uuid"`
	// Wildcard domain for applications on this server (e.g., `example.com`).
	WildcardDomain *string `pulumi:"wildcardDomain"`
}

type ServerDigitaloceanState struct {
	// CPU percentage Coolify uses when compressing volume backups. Read-only (not on public server PATCH). Present on Coolify >= v4.3.3; empty on older instances.
	BackupCompressionCpuPercentage pulumi.IntPtrInput
	// Cloud-init script to run on server creation. Changing this forces a new resource.
	CloudInitScript pulumi.StringPtrInput
	// The UUID of the DigitalOcean cloud provider token (from <span pulumi-lang-nodejs="`coolify.CloudToken`" pulumi-lang-dotnet="`coolify.CloudToken`" pulumi-lang-go="`CloudToken`" pulumi-lang-python="`CloudToken`" pulumi-lang-yaml="`coolify.CloudToken`" pulumi-lang-java="`coolify.CloudToken`" pulumi-lang-hcl="`coolify_cloud_token`">`coolify.CloudToken`</span>). Changing this forces a new resource.
	CloudProviderTokenUuid pulumi.StringPtrInput
	// Docker Compose version reported by Coolify for this server (host probe). Read-only; Populated on Coolify >= v4.3.2 when the host has been probed. Empty on older instances.
	ComposeVersion pulumi.StringPtrInput
	// When Coolify last checked the Compose version on this server. Read-only.
	ComposeVersionCheckedAt pulumi.StringPtrInput
	// How many deployments can run in parallel on this server.
	ConcurrentBuilds pulumi.IntPtrInput
	// SSH connection timeout in seconds.
	ConnectionTimeout pulumi.IntPtrInput
	// Whether to delete unused Docker networks during cleanup.
	DeleteUnusedNetworks pulumi.BoolPtrInput
	// Whether to delete unused Docker volumes during cleanup.
	DeleteUnusedVolumes pulumi.BoolPtrInput
	// Maximum number of queued deployments (default 25).
	DeploymentQueueLimit pulumi.IntPtrInput
	// A description of the server.
	Description pulumi.StringPtrInput
	// Comma-separated list of DigitalOcean SSH key numeric IDs. Use <span pulumi-lang-nodejs="`coolify.getDigitaloceanSshKeys`" pulumi-lang-dotnet="`coolify.getDigitaloceanSshKeys`" pulumi-lang-go="`getDigitaloceanSshKeys`" pulumi-lang-python="`get_digitalocean_ssh_keys`" pulumi-lang-yaml="`coolify.getDigitaloceanSshKeys`" pulumi-lang-java="`coolify.getDigitaloceanSshKeys`" pulumi-lang-hcl="`data.coolify_digitalocean_ssh_keys`">`coolify.getDigitaloceanSshKeys`</span> to list available keys. Changing this forces a new resource.
	DigitaloceanSshKeyIds pulumi.StringPtrInput
	// Whether application image retention is disabled. Read-only (not on public server PATCH allow-list).
	DisableApplicationImageRetention pulumi.BoolPtrInput
	// Cron expression for Docker cleanup schedule.
	DockerCleanupFrequency pulumi.StringPtrInput
	// Disk usage percentage threshold for Docker cleanup.
	DockerCleanupThreshold pulumi.IntPtrInput
	// Docker engine version reported by Coolify for this server (host probe). Read-only; Populated on Coolify >= v4.3.2 when the host has been probed. Empty on older instances.
	DockerVersion pulumi.StringPtrInput
	// When Coolify last checked the Docker version on this server. Read-only.
	DockerVersionCheckedAt pulumi.StringPtrInput
	// Timeout in seconds for Docker operations (pull, build, health check) during deployment.
	DynamicTimeout pulumi.IntPtrInput
	// Whether to enable IPv6 on the droplet. Defaults to true to match Coolify.
	EnableIpv6 pulumi.BoolPtrInput
	// Whether the server is force-disabled in Coolify. Read-only (not on public server PATCH allow-list).
	ForceDisabled pulumi.BoolPtrInput
	// Whether to force Docker cleanup regardless of disk usage.
	ForceDockerCleanup pulumi.BoolPtrInput
	// Whether to generate exact Docker labels (removes extra labels from containers).
	GenerateExactLabels pulumi.BoolPtrInput
	// The OS image to use (e.g., `ubuntu-24.04`). Use <span pulumi-lang-nodejs="`coolify.getDigitaloceanImages`" pulumi-lang-dotnet="`coolify.getDigitaloceanImages`" pulumi-lang-go="`getDigitaloceanImages`" pulumi-lang-python="`get_digitalocean_images`" pulumi-lang-yaml="`coolify.getDigitaloceanImages`" pulumi-lang-java="`coolify.getDigitaloceanImages`" pulumi-lang-hcl="`data.coolify_digitalocean_images`">`coolify.getDigitaloceanImages`</span> data source to list available images. Changing this forces a new resource.
	Image pulumi.StringPtrInput
	// Whether to validate server connectivity immediately after creation. Defaults to false to match Coolify.
	InstantValidate pulumi.BoolPtrInput
	// The IP address assigned to the server by DigitalOcean.
	Ip pulumi.StringPtrInput
	// Whether this server is used for building applications.
	IsBuildServer pulumi.BoolPtrInput
	// Whether this server uses a Cloudflare Tunnel.
	IsCloudflareTunnel pulumi.BoolPtrInput
	// Whether this server is a jump host. Read-only (not on public server PATCH allow-list).
	IsJumpServer pulumi.BoolPtrInput
	// Whether Axiom log drain is enabled. Read-only (not on public server PATCH allow-list).
	IsLogdrainAxiomEnabled pulumi.BoolPtrInput
	// Whether custom log drain is enabled. Read-only.
	IsLogdrainCustomEnabled pulumi.BoolPtrInput
	// Whether Highlight log drain is enabled. Read-only.
	IsLogdrainHighlightEnabled pulumi.BoolPtrInput
	// Whether New Relic log drain is enabled. Read-only.
	IsLogdrainNewrelicEnabled pulumi.BoolPtrInput
	// Whether metrics collection is enabled on this server.
	IsMetricsEnabled pulumi.BoolPtrInput
	// Whether the server is currently reachable.
	IsReachable pulumi.BoolPtrInput
	// Whether Sentinel debug mode is enabled. Read-only (not on public server PATCH allow-list).
	IsSentinelDebugEnabled pulumi.BoolPtrInput
	// Whether the Sentinel monitoring agent is enabled.
	IsSentinelEnabled pulumi.BoolPtrInput
	// Whether this server is a Docker Swarm manager. Read-only (not on public server PATCH allow-list).
	IsSwarmManager pulumi.BoolPtrInput
	// Whether this server is a Docker Swarm worker. Read-only (not on public server PATCH allow-list).
	IsSwarmWorker pulumi.BoolPtrInput
	// Whether the web terminal is enabled for this server.
	IsTerminalEnabled pulumi.BoolPtrInput
	// Whether the server is currently usable for deployments.
	IsUsable pulumi.BoolPtrInput
	// Axiom API key for log drain. Sensitive; read-only.
	LogdrainAxiomApiKey pulumi.StringPtrInput
	// Axiom dataset name for log drain. Read-only.
	LogdrainAxiomDatasetName pulumi.StringPtrInput
	// Custom log drain configuration. Sensitive; read-only.
	LogdrainCustomConfig pulumi.StringPtrInput
	// Custom log drain config parser. Read-only.
	LogdrainCustomConfigParser pulumi.StringPtrInput
	// Highlight project ID for log drain. Read-only.
	LogdrainHighlightProjectId pulumi.StringPtrInput
	// New Relic base URI for log drain. Read-only.
	LogdrainNewrelicBaseUri pulumi.StringPtrInput
	// New Relic license key for log drain. Sensitive; read-only.
	LogdrainNewrelicLicenseKey pulumi.StringPtrInput
	// Whether to enable DigitalOcean monitoring on the droplet. Defaults to true to match Coolify.
	Monitoring pulumi.BoolPtrInput
	// The name of the server.
	Name pulumi.StringPtrInput
	// The SSH port of the server.
	Port pulumi.IntPtrInput
	// The UUID of the private key used for SSH authentication.
	PrivateKeyUuid pulumi.StringPtrInput
	// The DigitalOcean region slug (e.g., <span pulumi-lang-nodejs="`nyc1`" pulumi-lang-dotnet="`Nyc1`" pulumi-lang-go="`nyc1`" pulumi-lang-python="`nyc1`" pulumi-lang-yaml="`nyc1`" pulumi-lang-java="`nyc1`" pulumi-lang-hcl="`nyc1`">`nyc1`</span>). Use <span pulumi-lang-nodejs="`coolify.getDigitaloceanRegions`" pulumi-lang-dotnet="`coolify.getDigitaloceanRegions`" pulumi-lang-go="`getDigitaloceanRegions`" pulumi-lang-python="`get_digitalocean_regions`" pulumi-lang-yaml="`coolify.getDigitaloceanRegions`" pulumi-lang-java="`coolify.getDigitaloceanRegions`" pulumi-lang-hcl="`data.coolify_digitalocean_regions`">`coolify.getDigitaloceanRegions`</span> to list available regions. Changing this forces a new resource.
	Region pulumi.StringPtrInput
	// Custom Sentinel push URL. Read-only (not on public server PATCH allow-list).
	SentinelCustomUrl pulumi.StringPtrInput
	// Number of days to retain Sentinel metrics.
	SentinelMetricsHistoryDays pulumi.IntPtrInput
	// Sentinel metrics refresh rate in seconds.
	SentinelMetricsRefreshRateSeconds pulumi.IntPtrInput
	// Interval in seconds between Sentinel metric pushes.
	SentinelPushIntervalSeconds pulumi.IntPtrInput
	// Sentinel agent token. Sensitive; only returned when the API token can read secrets. Read-only.
	SentinelToken pulumi.StringPtrInput
	// Cron or Coolify human schedule for how often disk usage is checked (e.g., `*/5 * * * *`, <span pulumi-lang-nodejs="`daily`" pulumi-lang-dotnet="`Daily`" pulumi-lang-go="`daily`" pulumi-lang-python="`daily`" pulumi-lang-yaml="`daily`" pulumi-lang-java="`daily`" pulumi-lang-hcl="`daily`">`daily`</span>, `@daily`).
	ServerDiskUsageCheckFrequency pulumi.StringPtrInput
	// Disk usage percentage at which a notification is sent.
	ServerDiskUsageNotificationThreshold pulumi.IntPtrInput
	// Server timezone (e.g., `UTC`, `America/New_York`).
	ServerTimezone pulumi.StringPtrInput
	// The DigitalOcean server type (e.g., `s-1vcpu-1gb`). Use <span pulumi-lang-nodejs="`coolify.getDigitaloceanSizes`" pulumi-lang-dotnet="`coolify.getDigitaloceanSizes`" pulumi-lang-go="`getDigitaloceanSizes`" pulumi-lang-python="`get_digitalocean_sizes`" pulumi-lang-yaml="`coolify.getDigitaloceanSizes`" pulumi-lang-java="`coolify.getDigitaloceanSizes`" pulumi-lang-hcl="`data.coolify_digitalocean_sizes`">`coolify.getDigitaloceanSizes`</span> data source to list available types. Changing this forces a new resource.
	Size     pulumi.StringPtrInput
	Timeouts ServerDigitaloceanTimeoutsPtrInput
	// The SSH user for connecting to the server.
	User pulumi.StringPtrInput
	// The unique identifier of the server.
	Uuid pulumi.StringPtrInput
	// Wildcard domain for applications on this server (e.g., `example.com`).
	WildcardDomain pulumi.StringPtrInput
}

func (ServerDigitaloceanState) ElementType() reflect.Type {
	return reflect.TypeOf((*serverDigitaloceanState)(nil)).Elem()
}

type serverDigitaloceanArgs struct {
	// Cloud-init script to run on server creation. Changing this forces a new resource.
	CloudInitScript *string `pulumi:"cloudInitScript"`
	// The UUID of the DigitalOcean cloud provider token (from <span pulumi-lang-nodejs="`coolify.CloudToken`" pulumi-lang-dotnet="`coolify.CloudToken`" pulumi-lang-go="`CloudToken`" pulumi-lang-python="`CloudToken`" pulumi-lang-yaml="`coolify.CloudToken`" pulumi-lang-java="`coolify.CloudToken`" pulumi-lang-hcl="`coolify_cloud_token`">`coolify.CloudToken`</span>). Changing this forces a new resource.
	CloudProviderTokenUuid string `pulumi:"cloudProviderTokenUuid"`
	// How many deployments can run in parallel on this server.
	ConcurrentBuilds *int `pulumi:"concurrentBuilds"`
	// SSH connection timeout in seconds.
	ConnectionTimeout *int `pulumi:"connectionTimeout"`
	// Maximum number of queued deployments (default 25).
	DeploymentQueueLimit *int `pulumi:"deploymentQueueLimit"`
	// A description of the server.
	Description *string `pulumi:"description"`
	// Comma-separated list of DigitalOcean SSH key numeric IDs. Use <span pulumi-lang-nodejs="`coolify.getDigitaloceanSshKeys`" pulumi-lang-dotnet="`coolify.getDigitaloceanSshKeys`" pulumi-lang-go="`getDigitaloceanSshKeys`" pulumi-lang-python="`get_digitalocean_ssh_keys`" pulumi-lang-yaml="`coolify.getDigitaloceanSshKeys`" pulumi-lang-java="`coolify.getDigitaloceanSshKeys`" pulumi-lang-hcl="`data.coolify_digitalocean_ssh_keys`">`coolify.getDigitaloceanSshKeys`</span> to list available keys. Changing this forces a new resource.
	DigitaloceanSshKeyIds *string `pulumi:"digitaloceanSshKeyIds"`
	// Timeout in seconds for Docker operations (pull, build, health check) during deployment.
	DynamicTimeout *int `pulumi:"dynamicTimeout"`
	// Whether to enable IPv6 on the droplet. Defaults to true to match Coolify.
	EnableIpv6 *bool `pulumi:"enableIpv6"`
	// The OS image to use (e.g., `ubuntu-24.04`). Use <span pulumi-lang-nodejs="`coolify.getDigitaloceanImages`" pulumi-lang-dotnet="`coolify.getDigitaloceanImages`" pulumi-lang-go="`getDigitaloceanImages`" pulumi-lang-python="`get_digitalocean_images`" pulumi-lang-yaml="`coolify.getDigitaloceanImages`" pulumi-lang-java="`coolify.getDigitaloceanImages`" pulumi-lang-hcl="`data.coolify_digitalocean_images`">`coolify.getDigitaloceanImages`</span> data source to list available images. Changing this forces a new resource.
	Image string `pulumi:"image"`
	// Whether to validate server connectivity immediately after creation. Defaults to false to match Coolify.
	InstantValidate *bool `pulumi:"instantValidate"`
	// Whether this server is used for building applications.
	IsBuildServer *bool `pulumi:"isBuildServer"`
	// Whether to enable DigitalOcean monitoring on the droplet. Defaults to true to match Coolify.
	Monitoring *bool `pulumi:"monitoring"`
	// The name of the server.
	Name *string `pulumi:"name"`
	// The SSH port of the server.
	Port *int `pulumi:"port"`
	// The UUID of the private key used for SSH authentication.
	PrivateKeyUuid string `pulumi:"privateKeyUuid"`
	// The DigitalOcean region slug (e.g., <span pulumi-lang-nodejs="`nyc1`" pulumi-lang-dotnet="`Nyc1`" pulumi-lang-go="`nyc1`" pulumi-lang-python="`nyc1`" pulumi-lang-yaml="`nyc1`" pulumi-lang-java="`nyc1`" pulumi-lang-hcl="`nyc1`">`nyc1`</span>). Use <span pulumi-lang-nodejs="`coolify.getDigitaloceanRegions`" pulumi-lang-dotnet="`coolify.getDigitaloceanRegions`" pulumi-lang-go="`getDigitaloceanRegions`" pulumi-lang-python="`get_digitalocean_regions`" pulumi-lang-yaml="`coolify.getDigitaloceanRegions`" pulumi-lang-java="`coolify.getDigitaloceanRegions`" pulumi-lang-hcl="`data.coolify_digitalocean_regions`">`coolify.getDigitaloceanRegions`</span> to list available regions. Changing this forces a new resource.
	Region string `pulumi:"region"`
	// Cron or Coolify human schedule for how often disk usage is checked (e.g., `*/5 * * * *`, <span pulumi-lang-nodejs="`daily`" pulumi-lang-dotnet="`Daily`" pulumi-lang-go="`daily`" pulumi-lang-python="`daily`" pulumi-lang-yaml="`daily`" pulumi-lang-java="`daily`" pulumi-lang-hcl="`daily`">`daily`</span>, `@daily`).
	ServerDiskUsageCheckFrequency *string `pulumi:"serverDiskUsageCheckFrequency"`
	// Disk usage percentage at which a notification is sent.
	ServerDiskUsageNotificationThreshold *int `pulumi:"serverDiskUsageNotificationThreshold"`
	// The DigitalOcean server type (e.g., `s-1vcpu-1gb`). Use <span pulumi-lang-nodejs="`coolify.getDigitaloceanSizes`" pulumi-lang-dotnet="`coolify.getDigitaloceanSizes`" pulumi-lang-go="`getDigitaloceanSizes`" pulumi-lang-python="`get_digitalocean_sizes`" pulumi-lang-yaml="`coolify.getDigitaloceanSizes`" pulumi-lang-java="`coolify.getDigitaloceanSizes`" pulumi-lang-hcl="`data.coolify_digitalocean_sizes`">`coolify.getDigitaloceanSizes`</span> data source to list available types. Changing this forces a new resource.
	Size     string                      `pulumi:"size"`
	Timeouts *ServerDigitaloceanTimeouts `pulumi:"timeouts"`
	// The SSH user for connecting to the server.
	User *string `pulumi:"user"`
}

// The set of arguments for constructing a ServerDigitalocean resource.
type ServerDigitaloceanArgs struct {
	// Cloud-init script to run on server creation. Changing this forces a new resource.
	CloudInitScript pulumi.StringPtrInput
	// The UUID of the DigitalOcean cloud provider token (from <span pulumi-lang-nodejs="`coolify.CloudToken`" pulumi-lang-dotnet="`coolify.CloudToken`" pulumi-lang-go="`CloudToken`" pulumi-lang-python="`CloudToken`" pulumi-lang-yaml="`coolify.CloudToken`" pulumi-lang-java="`coolify.CloudToken`" pulumi-lang-hcl="`coolify_cloud_token`">`coolify.CloudToken`</span>). Changing this forces a new resource.
	CloudProviderTokenUuid pulumi.StringInput
	// How many deployments can run in parallel on this server.
	ConcurrentBuilds pulumi.IntPtrInput
	// SSH connection timeout in seconds.
	ConnectionTimeout pulumi.IntPtrInput
	// Maximum number of queued deployments (default 25).
	DeploymentQueueLimit pulumi.IntPtrInput
	// A description of the server.
	Description pulumi.StringPtrInput
	// Comma-separated list of DigitalOcean SSH key numeric IDs. Use <span pulumi-lang-nodejs="`coolify.getDigitaloceanSshKeys`" pulumi-lang-dotnet="`coolify.getDigitaloceanSshKeys`" pulumi-lang-go="`getDigitaloceanSshKeys`" pulumi-lang-python="`get_digitalocean_ssh_keys`" pulumi-lang-yaml="`coolify.getDigitaloceanSshKeys`" pulumi-lang-java="`coolify.getDigitaloceanSshKeys`" pulumi-lang-hcl="`data.coolify_digitalocean_ssh_keys`">`coolify.getDigitaloceanSshKeys`</span> to list available keys. Changing this forces a new resource.
	DigitaloceanSshKeyIds pulumi.StringPtrInput
	// Timeout in seconds for Docker operations (pull, build, health check) during deployment.
	DynamicTimeout pulumi.IntPtrInput
	// Whether to enable IPv6 on the droplet. Defaults to true to match Coolify.
	EnableIpv6 pulumi.BoolPtrInput
	// The OS image to use (e.g., `ubuntu-24.04`). Use <span pulumi-lang-nodejs="`coolify.getDigitaloceanImages`" pulumi-lang-dotnet="`coolify.getDigitaloceanImages`" pulumi-lang-go="`getDigitaloceanImages`" pulumi-lang-python="`get_digitalocean_images`" pulumi-lang-yaml="`coolify.getDigitaloceanImages`" pulumi-lang-java="`coolify.getDigitaloceanImages`" pulumi-lang-hcl="`data.coolify_digitalocean_images`">`coolify.getDigitaloceanImages`</span> data source to list available images. Changing this forces a new resource.
	Image pulumi.StringInput
	// Whether to validate server connectivity immediately after creation. Defaults to false to match Coolify.
	InstantValidate pulumi.BoolPtrInput
	// Whether this server is used for building applications.
	IsBuildServer pulumi.BoolPtrInput
	// Whether to enable DigitalOcean monitoring on the droplet. Defaults to true to match Coolify.
	Monitoring pulumi.BoolPtrInput
	// The name of the server.
	Name pulumi.StringPtrInput
	// The SSH port of the server.
	Port pulumi.IntPtrInput
	// The UUID of the private key used for SSH authentication.
	PrivateKeyUuid pulumi.StringInput
	// The DigitalOcean region slug (e.g., <span pulumi-lang-nodejs="`nyc1`" pulumi-lang-dotnet="`Nyc1`" pulumi-lang-go="`nyc1`" pulumi-lang-python="`nyc1`" pulumi-lang-yaml="`nyc1`" pulumi-lang-java="`nyc1`" pulumi-lang-hcl="`nyc1`">`nyc1`</span>). Use <span pulumi-lang-nodejs="`coolify.getDigitaloceanRegions`" pulumi-lang-dotnet="`coolify.getDigitaloceanRegions`" pulumi-lang-go="`getDigitaloceanRegions`" pulumi-lang-python="`get_digitalocean_regions`" pulumi-lang-yaml="`coolify.getDigitaloceanRegions`" pulumi-lang-java="`coolify.getDigitaloceanRegions`" pulumi-lang-hcl="`data.coolify_digitalocean_regions`">`coolify.getDigitaloceanRegions`</span> to list available regions. Changing this forces a new resource.
	Region pulumi.StringInput
	// Cron or Coolify human schedule for how often disk usage is checked (e.g., `*/5 * * * *`, <span pulumi-lang-nodejs="`daily`" pulumi-lang-dotnet="`Daily`" pulumi-lang-go="`daily`" pulumi-lang-python="`daily`" pulumi-lang-yaml="`daily`" pulumi-lang-java="`daily`" pulumi-lang-hcl="`daily`">`daily`</span>, `@daily`).
	ServerDiskUsageCheckFrequency pulumi.StringPtrInput
	// Disk usage percentage at which a notification is sent.
	ServerDiskUsageNotificationThreshold pulumi.IntPtrInput
	// The DigitalOcean server type (e.g., `s-1vcpu-1gb`). Use <span pulumi-lang-nodejs="`coolify.getDigitaloceanSizes`" pulumi-lang-dotnet="`coolify.getDigitaloceanSizes`" pulumi-lang-go="`getDigitaloceanSizes`" pulumi-lang-python="`get_digitalocean_sizes`" pulumi-lang-yaml="`coolify.getDigitaloceanSizes`" pulumi-lang-java="`coolify.getDigitaloceanSizes`" pulumi-lang-hcl="`data.coolify_digitalocean_sizes`">`coolify.getDigitaloceanSizes`</span> data source to list available types. Changing this forces a new resource.
	Size     pulumi.StringInput
	Timeouts ServerDigitaloceanTimeoutsPtrInput
	// The SSH user for connecting to the server.
	User pulumi.StringPtrInput
}

func (ServerDigitaloceanArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*serverDigitaloceanArgs)(nil)).Elem()
}

type ServerDigitaloceanInput interface {
	pulumi.Input

	ToServerDigitaloceanOutput() ServerDigitaloceanOutput
	ToServerDigitaloceanOutputWithContext(ctx context.Context) ServerDigitaloceanOutput
}

func (*ServerDigitalocean) ElementType() reflect.Type {
	return reflect.TypeOf((**ServerDigitalocean)(nil)).Elem()
}

func (i *ServerDigitalocean) ToServerDigitaloceanOutput() ServerDigitaloceanOutput {
	return i.ToServerDigitaloceanOutputWithContext(context.Background())
}

func (i *ServerDigitalocean) ToServerDigitaloceanOutputWithContext(ctx context.Context) ServerDigitaloceanOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServerDigitaloceanOutput)
}

// ServerDigitaloceanArrayInput is an input type that accepts ServerDigitaloceanArray and ServerDigitaloceanArrayOutput values.
// You can construct a concrete instance of `ServerDigitaloceanArrayInput` via:
//
//	ServerDigitaloceanArray{ ServerDigitaloceanArgs{...} }
type ServerDigitaloceanArrayInput interface {
	pulumi.Input

	ToServerDigitaloceanArrayOutput() ServerDigitaloceanArrayOutput
	ToServerDigitaloceanArrayOutputWithContext(context.Context) ServerDigitaloceanArrayOutput
}

type ServerDigitaloceanArray []ServerDigitaloceanInput

func (ServerDigitaloceanArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ServerDigitalocean)(nil)).Elem()
}

func (i ServerDigitaloceanArray) ToServerDigitaloceanArrayOutput() ServerDigitaloceanArrayOutput {
	return i.ToServerDigitaloceanArrayOutputWithContext(context.Background())
}

func (i ServerDigitaloceanArray) ToServerDigitaloceanArrayOutputWithContext(ctx context.Context) ServerDigitaloceanArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServerDigitaloceanArrayOutput)
}

// ServerDigitaloceanMapInput is an input type that accepts ServerDigitaloceanMap and ServerDigitaloceanMapOutput values.
// You can construct a concrete instance of `ServerDigitaloceanMapInput` via:
//
//	ServerDigitaloceanMap{ "key": ServerDigitaloceanArgs{...} }
type ServerDigitaloceanMapInput interface {
	pulumi.Input

	ToServerDigitaloceanMapOutput() ServerDigitaloceanMapOutput
	ToServerDigitaloceanMapOutputWithContext(context.Context) ServerDigitaloceanMapOutput
}

type ServerDigitaloceanMap map[string]ServerDigitaloceanInput

func (ServerDigitaloceanMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ServerDigitalocean)(nil)).Elem()
}

func (i ServerDigitaloceanMap) ToServerDigitaloceanMapOutput() ServerDigitaloceanMapOutput {
	return i.ToServerDigitaloceanMapOutputWithContext(context.Background())
}

func (i ServerDigitaloceanMap) ToServerDigitaloceanMapOutputWithContext(ctx context.Context) ServerDigitaloceanMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServerDigitaloceanMapOutput)
}

type ServerDigitaloceanOutput struct{ *pulumi.OutputState }

func (ServerDigitaloceanOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ServerDigitalocean)(nil)).Elem()
}

func (o ServerDigitaloceanOutput) ToServerDigitaloceanOutput() ServerDigitaloceanOutput {
	return o
}

func (o ServerDigitaloceanOutput) ToServerDigitaloceanOutputWithContext(ctx context.Context) ServerDigitaloceanOutput {
	return o
}

// CPU percentage Coolify uses when compressing volume backups. Read-only (not on public server PATCH). Present on Coolify >= v4.3.3; empty on older instances.
func (o ServerDigitaloceanOutput) BackupCompressionCpuPercentage() pulumi.IntOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.IntOutput { return v.BackupCompressionCpuPercentage }).(pulumi.IntOutput)
}

// Cloud-init script to run on server creation. Changing this forces a new resource.
func (o ServerDigitaloceanOutput) CloudInitScript() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.StringPtrOutput { return v.CloudInitScript }).(pulumi.StringPtrOutput)
}

// The UUID of the DigitalOcean cloud provider token (from <span pulumi-lang-nodejs="`coolify.CloudToken`" pulumi-lang-dotnet="`coolify.CloudToken`" pulumi-lang-go="`CloudToken`" pulumi-lang-python="`CloudToken`" pulumi-lang-yaml="`coolify.CloudToken`" pulumi-lang-java="`coolify.CloudToken`" pulumi-lang-hcl="`coolify_cloud_token`">`coolify.CloudToken`</span>). Changing this forces a new resource.
func (o ServerDigitaloceanOutput) CloudProviderTokenUuid() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.StringOutput { return v.CloudProviderTokenUuid }).(pulumi.StringOutput)
}

// Docker Compose version reported by Coolify for this server (host probe). Read-only; Populated on Coolify >= v4.3.2 when the host has been probed. Empty on older instances.
func (o ServerDigitaloceanOutput) ComposeVersion() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.StringOutput { return v.ComposeVersion }).(pulumi.StringOutput)
}

// When Coolify last checked the Compose version on this server. Read-only.
func (o ServerDigitaloceanOutput) ComposeVersionCheckedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.StringOutput { return v.ComposeVersionCheckedAt }).(pulumi.StringOutput)
}

// How many deployments can run in parallel on this server.
func (o ServerDigitaloceanOutput) ConcurrentBuilds() pulumi.IntOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.IntOutput { return v.ConcurrentBuilds }).(pulumi.IntOutput)
}

// SSH connection timeout in seconds.
func (o ServerDigitaloceanOutput) ConnectionTimeout() pulumi.IntOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.IntOutput { return v.ConnectionTimeout }).(pulumi.IntOutput)
}

// Whether to delete unused Docker networks during cleanup.
func (o ServerDigitaloceanOutput) DeleteUnusedNetworks() pulumi.BoolOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.BoolOutput { return v.DeleteUnusedNetworks }).(pulumi.BoolOutput)
}

// Whether to delete unused Docker volumes during cleanup.
func (o ServerDigitaloceanOutput) DeleteUnusedVolumes() pulumi.BoolOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.BoolOutput { return v.DeleteUnusedVolumes }).(pulumi.BoolOutput)
}

// Maximum number of queued deployments (default 25).
func (o ServerDigitaloceanOutput) DeploymentQueueLimit() pulumi.IntOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.IntOutput { return v.DeploymentQueueLimit }).(pulumi.IntOutput)
}

// A description of the server.
func (o ServerDigitaloceanOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.StringOutput { return v.Description }).(pulumi.StringOutput)
}

// Comma-separated list of DigitalOcean SSH key numeric IDs. Use <span pulumi-lang-nodejs="`coolify.getDigitaloceanSshKeys`" pulumi-lang-dotnet="`coolify.getDigitaloceanSshKeys`" pulumi-lang-go="`getDigitaloceanSshKeys`" pulumi-lang-python="`get_digitalocean_ssh_keys`" pulumi-lang-yaml="`coolify.getDigitaloceanSshKeys`" pulumi-lang-java="`coolify.getDigitaloceanSshKeys`" pulumi-lang-hcl="`data.coolify_digitalocean_ssh_keys`">`coolify.getDigitaloceanSshKeys`</span> to list available keys. Changing this forces a new resource.
func (o ServerDigitaloceanOutput) DigitaloceanSshKeyIds() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.StringPtrOutput { return v.DigitaloceanSshKeyIds }).(pulumi.StringPtrOutput)
}

// Whether application image retention is disabled. Read-only (not on public server PATCH allow-list).
func (o ServerDigitaloceanOutput) DisableApplicationImageRetention() pulumi.BoolOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.BoolOutput { return v.DisableApplicationImageRetention }).(pulumi.BoolOutput)
}

// Cron expression for Docker cleanup schedule.
func (o ServerDigitaloceanOutput) DockerCleanupFrequency() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.StringOutput { return v.DockerCleanupFrequency }).(pulumi.StringOutput)
}

// Disk usage percentage threshold for Docker cleanup.
func (o ServerDigitaloceanOutput) DockerCleanupThreshold() pulumi.IntOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.IntOutput { return v.DockerCleanupThreshold }).(pulumi.IntOutput)
}

// Docker engine version reported by Coolify for this server (host probe). Read-only; Populated on Coolify >= v4.3.2 when the host has been probed. Empty on older instances.
func (o ServerDigitaloceanOutput) DockerVersion() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.StringOutput { return v.DockerVersion }).(pulumi.StringOutput)
}

// When Coolify last checked the Docker version on this server. Read-only.
func (o ServerDigitaloceanOutput) DockerVersionCheckedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.StringOutput { return v.DockerVersionCheckedAt }).(pulumi.StringOutput)
}

// Timeout in seconds for Docker operations (pull, build, health check) during deployment.
func (o ServerDigitaloceanOutput) DynamicTimeout() pulumi.IntOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.IntOutput { return v.DynamicTimeout }).(pulumi.IntOutput)
}

// Whether to enable IPv6 on the droplet. Defaults to true to match Coolify.
func (o ServerDigitaloceanOutput) EnableIpv6() pulumi.BoolOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.BoolOutput { return v.EnableIpv6 }).(pulumi.BoolOutput)
}

// Whether the server is force-disabled in Coolify. Read-only (not on public server PATCH allow-list).
func (o ServerDigitaloceanOutput) ForceDisabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.BoolOutput { return v.ForceDisabled }).(pulumi.BoolOutput)
}

// Whether to force Docker cleanup regardless of disk usage.
func (o ServerDigitaloceanOutput) ForceDockerCleanup() pulumi.BoolOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.BoolOutput { return v.ForceDockerCleanup }).(pulumi.BoolOutput)
}

// Whether to generate exact Docker labels (removes extra labels from containers).
func (o ServerDigitaloceanOutput) GenerateExactLabels() pulumi.BoolOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.BoolOutput { return v.GenerateExactLabels }).(pulumi.BoolOutput)
}

// The OS image to use (e.g., `ubuntu-24.04`). Use <span pulumi-lang-nodejs="`coolify.getDigitaloceanImages`" pulumi-lang-dotnet="`coolify.getDigitaloceanImages`" pulumi-lang-go="`getDigitaloceanImages`" pulumi-lang-python="`get_digitalocean_images`" pulumi-lang-yaml="`coolify.getDigitaloceanImages`" pulumi-lang-java="`coolify.getDigitaloceanImages`" pulumi-lang-hcl="`data.coolify_digitalocean_images`">`coolify.getDigitaloceanImages`</span> data source to list available images. Changing this forces a new resource.
func (o ServerDigitaloceanOutput) Image() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.StringOutput { return v.Image }).(pulumi.StringOutput)
}

// Whether to validate server connectivity immediately after creation. Defaults to false to match Coolify.
func (o ServerDigitaloceanOutput) InstantValidate() pulumi.BoolOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.BoolOutput { return v.InstantValidate }).(pulumi.BoolOutput)
}

// The IP address assigned to the server by DigitalOcean.
func (o ServerDigitaloceanOutput) Ip() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.StringOutput { return v.Ip }).(pulumi.StringOutput)
}

// Whether this server is used for building applications.
func (o ServerDigitaloceanOutput) IsBuildServer() pulumi.BoolOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.BoolOutput { return v.IsBuildServer }).(pulumi.BoolOutput)
}

// Whether this server uses a Cloudflare Tunnel.
func (o ServerDigitaloceanOutput) IsCloudflareTunnel() pulumi.BoolOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.BoolOutput { return v.IsCloudflareTunnel }).(pulumi.BoolOutput)
}

// Whether this server is a jump host. Read-only (not on public server PATCH allow-list).
func (o ServerDigitaloceanOutput) IsJumpServer() pulumi.BoolOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.BoolOutput { return v.IsJumpServer }).(pulumi.BoolOutput)
}

// Whether Axiom log drain is enabled. Read-only (not on public server PATCH allow-list).
func (o ServerDigitaloceanOutput) IsLogdrainAxiomEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.BoolOutput { return v.IsLogdrainAxiomEnabled }).(pulumi.BoolOutput)
}

// Whether custom log drain is enabled. Read-only.
func (o ServerDigitaloceanOutput) IsLogdrainCustomEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.BoolOutput { return v.IsLogdrainCustomEnabled }).(pulumi.BoolOutput)
}

// Whether Highlight log drain is enabled. Read-only.
func (o ServerDigitaloceanOutput) IsLogdrainHighlightEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.BoolOutput { return v.IsLogdrainHighlightEnabled }).(pulumi.BoolOutput)
}

// Whether New Relic log drain is enabled. Read-only.
func (o ServerDigitaloceanOutput) IsLogdrainNewrelicEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.BoolOutput { return v.IsLogdrainNewrelicEnabled }).(pulumi.BoolOutput)
}

// Whether metrics collection is enabled on this server.
func (o ServerDigitaloceanOutput) IsMetricsEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.BoolOutput { return v.IsMetricsEnabled }).(pulumi.BoolOutput)
}

// Whether the server is currently reachable.
func (o ServerDigitaloceanOutput) IsReachable() pulumi.BoolOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.BoolOutput { return v.IsReachable }).(pulumi.BoolOutput)
}

// Whether Sentinel debug mode is enabled. Read-only (not on public server PATCH allow-list).
func (o ServerDigitaloceanOutput) IsSentinelDebugEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.BoolOutput { return v.IsSentinelDebugEnabled }).(pulumi.BoolOutput)
}

// Whether the Sentinel monitoring agent is enabled.
func (o ServerDigitaloceanOutput) IsSentinelEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.BoolOutput { return v.IsSentinelEnabled }).(pulumi.BoolOutput)
}

// Whether this server is a Docker Swarm manager. Read-only (not on public server PATCH allow-list).
func (o ServerDigitaloceanOutput) IsSwarmManager() pulumi.BoolOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.BoolOutput { return v.IsSwarmManager }).(pulumi.BoolOutput)
}

// Whether this server is a Docker Swarm worker. Read-only (not on public server PATCH allow-list).
func (o ServerDigitaloceanOutput) IsSwarmWorker() pulumi.BoolOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.BoolOutput { return v.IsSwarmWorker }).(pulumi.BoolOutput)
}

// Whether the web terminal is enabled for this server.
func (o ServerDigitaloceanOutput) IsTerminalEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.BoolOutput { return v.IsTerminalEnabled }).(pulumi.BoolOutput)
}

// Whether the server is currently usable for deployments.
func (o ServerDigitaloceanOutput) IsUsable() pulumi.BoolOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.BoolOutput { return v.IsUsable }).(pulumi.BoolOutput)
}

// Axiom API key for log drain. Sensitive; read-only.
func (o ServerDigitaloceanOutput) LogdrainAxiomApiKey() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.StringOutput { return v.LogdrainAxiomApiKey }).(pulumi.StringOutput)
}

// Axiom dataset name for log drain. Read-only.
func (o ServerDigitaloceanOutput) LogdrainAxiomDatasetName() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.StringOutput { return v.LogdrainAxiomDatasetName }).(pulumi.StringOutput)
}

// Custom log drain configuration. Sensitive; read-only.
func (o ServerDigitaloceanOutput) LogdrainCustomConfig() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.StringOutput { return v.LogdrainCustomConfig }).(pulumi.StringOutput)
}

// Custom log drain config parser. Read-only.
func (o ServerDigitaloceanOutput) LogdrainCustomConfigParser() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.StringOutput { return v.LogdrainCustomConfigParser }).(pulumi.StringOutput)
}

// Highlight project ID for log drain. Read-only.
func (o ServerDigitaloceanOutput) LogdrainHighlightProjectId() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.StringOutput { return v.LogdrainHighlightProjectId }).(pulumi.StringOutput)
}

// New Relic base URI for log drain. Read-only.
func (o ServerDigitaloceanOutput) LogdrainNewrelicBaseUri() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.StringOutput { return v.LogdrainNewrelicBaseUri }).(pulumi.StringOutput)
}

// New Relic license key for log drain. Sensitive; read-only.
func (o ServerDigitaloceanOutput) LogdrainNewrelicLicenseKey() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.StringOutput { return v.LogdrainNewrelicLicenseKey }).(pulumi.StringOutput)
}

// Whether to enable DigitalOcean monitoring on the droplet. Defaults to true to match Coolify.
func (o ServerDigitaloceanOutput) Monitoring() pulumi.BoolOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.BoolOutput { return v.Monitoring }).(pulumi.BoolOutput)
}

// The name of the server.
func (o ServerDigitaloceanOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The SSH port of the server.
func (o ServerDigitaloceanOutput) Port() pulumi.IntOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.IntOutput { return v.Port }).(pulumi.IntOutput)
}

// The UUID of the private key used for SSH authentication.
func (o ServerDigitaloceanOutput) PrivateKeyUuid() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.StringOutput { return v.PrivateKeyUuid }).(pulumi.StringOutput)
}

// The DigitalOcean region slug (e.g., <span pulumi-lang-nodejs="`nyc1`" pulumi-lang-dotnet="`Nyc1`" pulumi-lang-go="`nyc1`" pulumi-lang-python="`nyc1`" pulumi-lang-yaml="`nyc1`" pulumi-lang-java="`nyc1`" pulumi-lang-hcl="`nyc1`">`nyc1`</span>). Use <span pulumi-lang-nodejs="`coolify.getDigitaloceanRegions`" pulumi-lang-dotnet="`coolify.getDigitaloceanRegions`" pulumi-lang-go="`getDigitaloceanRegions`" pulumi-lang-python="`get_digitalocean_regions`" pulumi-lang-yaml="`coolify.getDigitaloceanRegions`" pulumi-lang-java="`coolify.getDigitaloceanRegions`" pulumi-lang-hcl="`data.coolify_digitalocean_regions`">`coolify.getDigitaloceanRegions`</span> to list available regions. Changing this forces a new resource.
func (o ServerDigitaloceanOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.StringOutput { return v.Region }).(pulumi.StringOutput)
}

// Custom Sentinel push URL. Read-only (not on public server PATCH allow-list).
func (o ServerDigitaloceanOutput) SentinelCustomUrl() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.StringOutput { return v.SentinelCustomUrl }).(pulumi.StringOutput)
}

// Number of days to retain Sentinel metrics.
func (o ServerDigitaloceanOutput) SentinelMetricsHistoryDays() pulumi.IntOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.IntOutput { return v.SentinelMetricsHistoryDays }).(pulumi.IntOutput)
}

// Sentinel metrics refresh rate in seconds.
func (o ServerDigitaloceanOutput) SentinelMetricsRefreshRateSeconds() pulumi.IntOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.IntOutput { return v.SentinelMetricsRefreshRateSeconds }).(pulumi.IntOutput)
}

// Interval in seconds between Sentinel metric pushes.
func (o ServerDigitaloceanOutput) SentinelPushIntervalSeconds() pulumi.IntOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.IntOutput { return v.SentinelPushIntervalSeconds }).(pulumi.IntOutput)
}

// Sentinel agent token. Sensitive; only returned when the API token can read secrets. Read-only.
func (o ServerDigitaloceanOutput) SentinelToken() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.StringOutput { return v.SentinelToken }).(pulumi.StringOutput)
}

// Cron or Coolify human schedule for how often disk usage is checked (e.g., `*/5 * * * *`, <span pulumi-lang-nodejs="`daily`" pulumi-lang-dotnet="`Daily`" pulumi-lang-go="`daily`" pulumi-lang-python="`daily`" pulumi-lang-yaml="`daily`" pulumi-lang-java="`daily`" pulumi-lang-hcl="`daily`">`daily`</span>, `@daily`).
func (o ServerDigitaloceanOutput) ServerDiskUsageCheckFrequency() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.StringOutput { return v.ServerDiskUsageCheckFrequency }).(pulumi.StringOutput)
}

// Disk usage percentage at which a notification is sent.
func (o ServerDigitaloceanOutput) ServerDiskUsageNotificationThreshold() pulumi.IntOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.IntOutput { return v.ServerDiskUsageNotificationThreshold }).(pulumi.IntOutput)
}

// Server timezone (e.g., `UTC`, `America/New_York`).
func (o ServerDigitaloceanOutput) ServerTimezone() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.StringOutput { return v.ServerTimezone }).(pulumi.StringOutput)
}

// The DigitalOcean server type (e.g., `s-1vcpu-1gb`). Use <span pulumi-lang-nodejs="`coolify.getDigitaloceanSizes`" pulumi-lang-dotnet="`coolify.getDigitaloceanSizes`" pulumi-lang-go="`getDigitaloceanSizes`" pulumi-lang-python="`get_digitalocean_sizes`" pulumi-lang-yaml="`coolify.getDigitaloceanSizes`" pulumi-lang-java="`coolify.getDigitaloceanSizes`" pulumi-lang-hcl="`data.coolify_digitalocean_sizes`">`coolify.getDigitaloceanSizes`</span> data source to list available types. Changing this forces a new resource.
func (o ServerDigitaloceanOutput) Size() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.StringOutput { return v.Size }).(pulumi.StringOutput)
}

func (o ServerDigitaloceanOutput) Timeouts() ServerDigitaloceanTimeoutsPtrOutput {
	return o.ApplyT(func(v *ServerDigitalocean) ServerDigitaloceanTimeoutsPtrOutput { return v.Timeouts }).(ServerDigitaloceanTimeoutsPtrOutput)
}

// The SSH user for connecting to the server.
func (o ServerDigitaloceanOutput) User() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.StringOutput { return v.User }).(pulumi.StringOutput)
}

// The unique identifier of the server.
func (o ServerDigitaloceanOutput) Uuid() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.StringOutput { return v.Uuid }).(pulumi.StringOutput)
}

// Wildcard domain for applications on this server (e.g., `example.com`).
func (o ServerDigitaloceanOutput) WildcardDomain() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerDigitalocean) pulumi.StringOutput { return v.WildcardDomain }).(pulumi.StringOutput)
}

type ServerDigitaloceanArrayOutput struct{ *pulumi.OutputState }

func (ServerDigitaloceanArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ServerDigitalocean)(nil)).Elem()
}

func (o ServerDigitaloceanArrayOutput) ToServerDigitaloceanArrayOutput() ServerDigitaloceanArrayOutput {
	return o
}

func (o ServerDigitaloceanArrayOutput) ToServerDigitaloceanArrayOutputWithContext(ctx context.Context) ServerDigitaloceanArrayOutput {
	return o
}

func (o ServerDigitaloceanArrayOutput) Index(i pulumi.IntInput) ServerDigitaloceanOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ServerDigitalocean {
		return vs[0].([]*ServerDigitalocean)[vs[1].(int)]
	}).(ServerDigitaloceanOutput)
}

type ServerDigitaloceanMapOutput struct{ *pulumi.OutputState }

func (ServerDigitaloceanMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ServerDigitalocean)(nil)).Elem()
}

func (o ServerDigitaloceanMapOutput) ToServerDigitaloceanMapOutput() ServerDigitaloceanMapOutput {
	return o
}

func (o ServerDigitaloceanMapOutput) ToServerDigitaloceanMapOutputWithContext(ctx context.Context) ServerDigitaloceanMapOutput {
	return o
}

func (o ServerDigitaloceanMapOutput) MapIndex(k pulumi.StringInput) ServerDigitaloceanOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ServerDigitalocean {
		return vs[0].(map[string]*ServerDigitalocean)[vs[1].(string)]
	}).(ServerDigitaloceanOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ServerDigitaloceanInput)(nil)).Elem(), &ServerDigitalocean{})
	pulumi.RegisterInputType(reflect.TypeOf((*ServerDigitaloceanArrayInput)(nil)).Elem(), ServerDigitaloceanArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ServerDigitaloceanMapInput)(nil)).Elem(), ServerDigitaloceanMap{})
	pulumi.RegisterOutputType(ServerDigitaloceanOutput{})
	pulumi.RegisterOutputType(ServerDigitaloceanArrayOutput{})
	pulumi.RegisterOutputType(ServerDigitaloceanMapOutput{})
}
