package main

import (
	"fmt"
	"strings"

	coolify "github.com/mheers/pulumi-provider-coolify/sdk/go/coolify"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		cfg := config.New(ctx, "nginx")
		var endpoint pulumi.StringPtrInput
		var token pulumi.StringPtrInput
		if hostStackName := cfg.Get("hostStack"); hostStackName != "" {
			hostStack, err := pulumi.NewStackReference(ctx, "showboat-host", &pulumi.StackReferenceArgs{
				Name: pulumi.String(hostStackName),
			})
			if err != nil {
				return fmt.Errorf("create host stack reference: %w", err)
			}

			endpoint = hostStack.GetStringOutput(pulumi.String("showboat:coolify:dashboard")).ToStringPtrOutput()
			token = hostStack.GetOutput(pulumi.String("showboat:coolify:apiToken")).ApplyT(func(value any) *string {
				valueString, ok := value.(string)
				if !ok {
					return nil
				}
				return &valueString
			}).(pulumi.StringPtrOutput)
		} else {
			endpoint = pulumi.StringPtr(cfg.Require("endpoint"))
			token = cfg.RequireSecret("token").ToStringPtrOutput()
		}

		provider, err := coolify.NewProvider(ctx, "coolify", &coolify.ProviderArgs{
			Endpoint: endpoint,
			Token:    token,
		})
		if err != nil {
			return fmt.Errorf("configure Coolify provider: %w", err)
		}
		providerOption := pulumi.Provider(provider)

		project, err := coolify.GetProject(ctx, "showboat-project", pulumi.ID(cfg.Require("projectUuid")), nil, providerOption)
		if err != nil {
			return fmt.Errorf("look up Coolify project: %w", err)
		}
		server, err := coolify.GetServer(ctx, "showboat-server", pulumi.ID(cfg.Require("serverUuid")), nil, providerOption)
		if err != nil {
			return fmt.Errorf("look up Coolify server: %w", err)
		}

		app, err := coolify.NewApplicationDockerImage(ctx, "nginx", &coolify.ApplicationDockerImageArgs{
			Name:                pulumi.StringPtr("nginx-hello"),
			Description:         pulumi.StringPtr("Pulumi Coolify provider example"),
			ProjectUuid:         project.Uuid,
			ServerUuid:          server.Uuid,
			DockerImage:         pulumi.String("nginx:latest"),
			PortsExposes:        pulumi.String("80"),
			Domains:             pulumi.StringPtr(cfg.Require("appDomain")),
			AutogenerateDomain:  pulumi.BoolPtr(false),
			InstantDeploy:       pulumi.BoolPtr(false),
			IsForceHttpsEnabled: pulumi.BoolPtr(false),
		}, providerOption)
		if err != nil {
			return fmt.Errorf("create nginx application: %w", err)
		}

		deployment, err := coolify.NewDeployment(ctx, "nginx", &coolify.DeploymentArgs{
			ApplicationUuid: app.Uuid,
			Triggers: pulumi.StringMap{
				"image":      pulumi.String("nginx:latest"),
				"forceHttps": pulumi.String("false"),
				"domain":     pulumi.String(cfg.Require("appDomain")),
			},
			WaitForCompletion: pulumi.BoolPtr(true),
		}, providerOption, pulumi.Parent(app))
		if err != nil {
			return fmt.Errorf("create nginx deployment: %w", err)
		}

		ctx.Export("url", pulumi.String(publicURL(cfg.Require("appDomain"))))
		ctx.Export("applicationUuid", app.Uuid)
		ctx.Export("deploymentStatus", deployment.Status)
		return nil
	})
}

func publicURL(domain string) string {
	return "https://" + strings.TrimPrefix(strings.TrimPrefix(domain, "https://"), "http://")
}
